// Fiches de l'atlas qui ont une structure 3D (chantiers A.3 et C.3).
// clé = id de la fiche (MINERAUX ou ESPECES) → fichier structures/<fichier>.js + réglages d'affichage.
// Réglages possibles : mode ("billes" | "polyedres" | "compact"), polyedres (éléments centres),
// ligandsHors (false = seulement les atomes de la maille), decalage [fx, fy, fz] (origine déplacée), repetition [na, nb, nc],
// vue { axe: "a" | "b" | "c", inclinaison: [degrés autour de l'horizontale, de la verticale] }, note (texte affiché).
(function () {
  const KAOLINITE_H = "Affinement à 1,5 K : seule structure de la COD qui place les hydrogènes ; la maille à température ambiante ne diffère que de 0,04 % (Bish et Von Dreele 1989).";
  const PLAGIO_MOYEN = "Structure moyenne : sodium et calcium se partagent le même site, aluminium et silicium les sites tétraédriques. Le long de la série, Ca²⁺ + Al³⁺ remplacent Na⁺ + Si⁴⁺, de l'albite (NaAlSi₃O₈) à l'anorthite (CaAl₂Si₂O₈).";
  Structure3D.index({
    // ── silice ──
    quartz: { fichier: "quartz" },
    calcedoine: { fichier: "quartz",
      note: "La calcédoine est du quartz en fibres microscopiques, mêlé d'un peu de moganite : la structure est celle du quartz." },
    coesite: { fichier: "coesite" },

    // ── carbonates, sulfates, halogénures, phosphates ──
    calcite: { fichier: "calcite", polyedres: ["C", "Ca"] },
    aragonite: { fichier: "aragonite", polyedres: ["C"] },
    dolomite: { fichier: "dolomite", polyedres: ["C", "Ca", "Mg"] },
    siderite: { fichier: "siderite", polyedres: ["C", "Fe"] },
    halite_m: { fichier: "halite", ligandsHors: false, polyedres: ["Na"], decalage: [0.5, 0, 0] },
    sylvite: { fichier: "sylvite", ligandsHors: false },
    fluorine: { fichier: "fluorine" },
    chlorargyrite: { fichier: "chlorargyrite", ligandsHors: false,
      note: "Même structure que le sel de cuisine : chaque argent entouré de six chlores, en cube. La liaison Ag–Cl, en partie covalente, rend le cristal souple : il se coupe au couteau." },
    carnallite: { fichier: "carnallite", polyedres: ["Mg"],
      note: "Chaque magnésium est enfermé dans un octaèdre de six molécules d'eau, Mg(H₂O)₆ ; potassium et chlore remplissent les vides entre ces octaèdres. Cette eau, tenue par des liaisons hydrogène fragiles, explique que la carnallite fonde dans l'humidité de l'air." },
    cryolite: { fichier: "cryolite", polyedres: ["Al"],
      note: "Octaèdres AlF₆ isolés, à peine basculés les uns par rapport aux autres, et sodium entre eux : un arrangement de type pérovskite, presque cubique. Au-dessus de 885 °C, les octaèdres se redressent et la maille devient cubique." },
    atacamite: { fichier: "atacamite",
      note: "Le cuivre est au centre d'octaèdres allongés (4 OH proches, 2 Cl plus loin, ou 5 OH et 1 Cl) qui partagent leurs arêtes en une charpente. Mêmes positions que les cations d'un spinelle (Parise et Hyde 1986)." },
    gypse_m: { fichier: "gypse", polyedres: ["S"] },
    anhydrite: { fichier: "anhydrite", polyedres: ["S"] },
    apatite: { fichier: "apatite", polyedres: ["P"],
      note: "Structure de la fluorapatite, Ca₅(PO₄)₃F : dans l'apatite des roches, OH⁻ et Cl⁻ remplacent une partie du fluor." },

    // ── feldspaths et feldspathoïdes ──
    orthose: { fichier: "orthose" },
    sanidine: { fichier: "sanidine" },
    microcline: { fichier: "microcline" },
    albite: { fichier: "albite" },
    anorthite: { fichier: "anorthite" },
    plagioclases: { fichier: "plagioclase_an48",
      note: "Structure d'un plagioclase An48 (48 % d'anorthite), au milieu de la série. " + PLAGIO_MOYEN },
    andesine: { fichier: "plagioclase_an48", note: "Plagioclase An48 (andésine). " + PLAGIO_MOYEN },
    labradorite: { fichier: "labradorite", note: "Plagioclase An62–66 (labradorite). " + PLAGIO_MOYEN },
    nepheline: { fichier: "nepheline" },
    leucite: { fichier: "leucite" },

    // ── olivine, grenats, silicates d'alumine ──
    forsterite: { fichier: "forsterite" },
    olivine: { fichier: "forsterite",
      note: "Structure de la forstérite (Mg₂SiO₄), pôle magnésien de la série : dans l'olivine courante, le fer (Fe²⁺) occupe une partie des sites du magnésium." },
    grenat: { fichier: "almandin", mode: "polyedres", polyedres: ["Si", "Al"],
      note: "Structure de l'almandin, Fe₃Al₂(SiO₄)₃, le grenat des micaschistes et des gneiss. Les autres grenats ont la même charpente : Mg, Ca ou Mn à la place du fer, Fe³⁺ ou Cr³⁺ à la place de l'aluminium." },
    almandin: { fichier: "almandin", mode: "polyedres", polyedres: ["Si", "Al"] },
    pyrope: { fichier: "pyrope", mode: "polyedres", polyedres: ["Si", "Al"] },
    grossulaire: { fichier: "grossulaire", mode: "polyedres", polyedres: ["Si", "Al"] },
    andradite: { fichier: "andradite", mode: "polyedres", polyedres: ["Si", "Fe"] },
    zircon: { fichier: "zircon", polyedres: ["Si"] },
    titanite: { fichier: "titanite", mode: "polyedres", polyedres: ["Si", "Ti"] },
    andalousite: { fichier: "andalousite", mode: "polyedres", polyedres: ["Si", "Al"] },
    sillimanite: { fichier: "sillimanite", mode: "polyedres", polyedres: ["Si", "Al"] },
    disthene: { fichier: "disthene", mode: "polyedres", polyedres: ["Si", "Al"] },
    topaze: { fichier: "topaze", mode: "polyedres", polyedres: ["Si", "Al"] },
    epidote: { fichier: "epidote", mode: "polyedres", polyedres: ["Si", "Al", "Fe"] },
    zoisite: { fichier: "zoisite", mode: "polyedres", polyedres: ["Si", "Al"] },
    clinozoisite: { fichier: "clinozoisite", mode: "polyedres", polyedres: ["Si", "Al"] },
    lawsonite: { fichier: "lawsonite", mode: "polyedres", polyedres: ["Si", "Al"] },
    beryl: { fichier: "beryl", mode: "polyedres", polyedres: ["Si", "Be"] },
    cordierite: { fichier: "cordierite", mode: "polyedres", polyedres: ["Si", "Al"] },
    tourmaline: { fichier: "tourmaline", mode: "polyedres", polyedres: ["Si", "B"] },

    // ── pyroxènes, amphiboles, pyroxénoïdes ──
    augite: { fichier: "augite", mode: "polyedres", polyedres: ["Si", "Mg"] },
    pyroxenes: { fichier: "augite", mode: "polyedres", polyedres: ["Si", "Mg"],
      note: "Structure de l'augite, le pyroxène le plus courant des basaltes et des gabbros : des chaînes simples de tétraèdres SiO₄ liées par des rubans d'octaèdres de magnésium et de fer." },
    diopside: { fichier: "diopside", mode: "polyedres", polyedres: ["Si", "Mg"] },
    enstatite: { fichier: "enstatite", mode: "polyedres", polyedres: ["Si", "Mg"],
      note: "Structure de l'orthoenstatite pure (MgSiO₃) : dans l'orthopyroxène des roches, le fer remplace une partie du magnésium." },
    omphacite: { fichier: "omphacite", mode: "polyedres", polyedres: ["Si", "Al", "Mg"] },
    aegyrine: { fichier: "aegyrine", mode: "polyedres", polyedres: ["Si", "Fe"] },
    jadeite: { fichier: "jadeite", mode: "polyedres", polyedres: ["Si", "Al"] },
    wollastonite: { fichier: "wollastonite", mode: "polyedres", polyedres: ["Si"] },
    hornblende: { fichier: "hornblende", mode: "polyedres", polyedres: ["Si", "Mg"] },
    amphiboles: { fichier: "hornblende", mode: "polyedres", polyedres: ["Si", "Mg"],
      note: "Structure d'une hornblende magnésienne : des chaînes doubles de tétraèdres SiO₄ liées par des rubans d'octaèdres, avec des groupes OH." },
    pargasite: { fichier: "pargasite", mode: "polyedres", polyedres: ["Si", "Mg"] },
    tremolite: { fichier: "tremolite", mode: "polyedres", polyedres: ["Si", "Mg"] },
    actinote: { fichier: "actinote", mode: "polyedres", polyedres: ["Si", "Mg"] },
    glaucophane: { fichier: "glaucophane", mode: "polyedres", polyedres: ["Si", "Mg", "Al"] },
    arfvedsonite: { fichier: "arfvedsonite", mode: "polyedres", polyedres: ["Si", "Fe"] },

    // ── micas, chlorites, serpentines ──
    muscovite: { fichier: "muscovite", mode: "polyedres" },
    illite_m: { fichier: "muscovite", mode: "polyedres",
      note: "L'illite n'a pas de structure affinée : ses feuillets de mica dioctaédrique, moins riches en potassium, s'empilent en désordre. Structure montrée : la muscovite, dont elle est proche." },
    biotite: { fichier: "biotite", mode: "polyedres" },
    phlogopite: { fichier: "phlogopite", mode: "polyedres" },
    clinochlore: { fichier: "clinochlore", mode: "polyedres" },
    chlorite_m: { fichier: "clinochlore", mode: "polyedres",
      note: "Structure du clinochlore, la chlorite magnésienne la plus courante : un feuillet de mica sans potassium, alterné avec une couche d'hydroxyde de magnésium." },
    lizardite: { fichier: "lizardite", mode: "polyedres" },
    serpentine: { fichier: "lizardite", mode: "polyedres",
      note: "Structure de la lizardite, serpentine à feuillets plans. L'antigorite (feuillets ondulés) et le chrysotile (feuillets enroulés en fibres) ne se réduisent pas à une petite maille." },

    // ── argiles ──
    kaolinite_m: { fichier: "kaolinite", mode: "polyedres", note: KAOLINITE_H },
    kaolinite_e: { fichier: "kaolinite", mode: "polyedres", note: KAOLINITE_H },
    dickite: { fichier: "dickite", mode: "polyedres" },
    gibbsite: { fichier: "gibbsite", mode: "polyedres", polyedres: ["Al"] },

    // ── oxydes, sulfures, éléments natifs ──
    magnetite: { fichier: "magnetite", mode: "polyedres", polyedres: ["Fe"] },
    chromite: { fichier: "chromite", mode: "polyedres", polyedres: ["Cr", "Fe"] },
    hematite: { fichier: "hematite", mode: "polyedres", polyedres: ["Fe"] },
    ilmenite: { fichier: "ilmenite", mode: "polyedres", polyedres: ["Fe", "Ti"] },
    goethite: { fichier: "goethite", mode: "polyedres", polyedres: ["Fe"] },
    rutile: { fichier: "rutile", mode: "polyedres", polyedres: ["Ti"], repetition: [2, 2, 2] },
    cassiterite: { fichier: "cassiterite", mode: "polyedres", polyedres: ["Sn"], repetition: [2, 2, 2] },
    pyrite: { fichier: "pyrite",
      note: "Chaque fer est au centre d'un octaèdre de soufres, mais les soufres vont par paires (S₂, 2,16 Å) : c'est la structure du sel de cuisine, avec des paires de soufre à la place du chlore, chaque paire couchée le long d'une diagonale du cube." },
    // ── inosilicates et phyllosilicates (F.4 classes IX.D, IX.E, 01/10/2026) ──
    ferrosilite: { fichier: "ferrosilite", polyedres: ["Si","Fe"],
      note: "Orthopyroxène : chaînes simples de tétraèdres SiO₄ le long de c, reliées par des rubans d'octaèdres (sites M1) et de grands sites M2. Pôle ferreux, maille orthorhombique (deux fois plus longue selon a)." },
    hedenbergite: { fichier: "hedenbergite", polyedres: ["Si","Fe"],
      note: "Pyroxène : chaînes simples de tétraèdres SiO₄ le long de c, reliées par des rubans d'octaèdres (sites M1) et de grands sites M2. Calcium en M2, fer ferreux en M1." },
    pigeonite: { fichier: "pigeonite", polyedres: ["Si","Fe","Mg"],
      note: "Pyroxène : chaînes simples de tétraèdres SiO₄ le long de c, reliées par des rubans d'octaèdres (sites M1) et de grands sites M2. Pauvre en calcium : une partie des sites M2 est occupée par Fe et Mg, ce qui abaisse la symétrie (P2₁/c)." },
    johannsenite: { fichier: "johannsenite", polyedres: ["Si","Mn"],
      note: "Pyroxène : chaînes simples de tétraèdres SiO₄ le long de c, reliées par des rubans d'octaèdres (sites M1) et de grands sites M2. Calcium en M2, manganèse en M1." },
    kosmochlor: { fichier: "kosmochlor", polyedres: ["Si","Cr"],
      note: "Pyroxène : chaînes simples de tétraèdres SiO₄ le long de c, reliées par des rubans d'octaèdres (sites M1) et de grands sites M2. Sodium en M2, chrome en M1 ; synthétique." },
    spodumene: { fichier: "spodumene", polyedres: ["Si","Al"],
      note: "Pyroxène : chaînes simples de tétraèdres SiO₄ le long de c, reliées par des rubans d'octaèdres (sites M1) et de grands sites M2. Lithium en M2, aluminium en M1. Affinement aux neutrons." },
    rhodonite: { fichier: "rhodonite", polyedres: ["Si","Mn"],
      note: "Pyroxénoïde : chaînes simples de tétraèdres qui se répètent tous les cinq tétraèdres, octaèdres de manganèse (avec calcium, magnésium et fer)." },
    pectolite: { fichier: "pectolite", polyedres: ["Si"],
      note: "Pyroxénoïde : chaînes simples de tétraèdres qui se répètent tous les trois tétraèdres, calcium et sodium entre elles ; une liaison hydrogène très courte relie deux chaînes." },
    bustamite: { fichier: "bustamite", polyedres: ["Si","Mn"],
      note: "Pyroxénoïde : chaînes simples de tétraèdres qui se répètent tous les trois tétraèdres (comme la wollastonite), calcium et manganèse." },
    anthophyllite: { fichier: "anthophyllite", polyedres: ["Si"],
      note: "Orthoamphibole :  chaînes doubles de tétraèdres le long de c (rubans Si₈O₂₂), reliées par des rubans d'octaèdres, avec un OH au centre de chaque anneau et un site A souvent vide. Maille orthorhombique." },
    cummingtonite: { fichier: "cummingtonite", polyedres: ["Si"],
      note: "Amphibole : chaînes doubles de tétraèdres le long de c (rubans Si₈O₂₂), reliées par des rubans d'octaèdres, avec un OH au centre de chaque anneau et un site A souvent vide. Magnésium et fer partout, site A vide." },
    grunerite: { fichier: "grunerite", polyedres: ["Si","Fe"],
      note: "Amphibole : chaînes doubles de tétraèdres le long de c (rubans Si₈O₂₂), reliées par des rubans d'octaèdres, avec un OH au centre de chaque anneau et un site A souvent vide. Pôle ferreux de la cummingtonite." },
    kaersutite: { fichier: "kaersutite", polyedres: ["Si"],
      note: "Amphibole : chaînes doubles de tétraèdres le long de c (rubans Si₈O₂₂), reliées par des rubans d'octaèdres, avec un OH au centre de chaque anneau et un site A souvent vide. Titane dans un octaèdre et oxygène à la place d'une partie des OH ; site A occupé." },
    richterite: { fichier: "richterite", polyedres: ["Si","Mg"],
      note: "Amphibole : chaînes doubles de tétraèdres le long de c (rubans Si₈O₂₂), reliées par des rubans d'octaèdres, avec un OH au centre de chaque anneau et un site A souvent vide. Sodium en M4 et dans le site A ; ici une richtérite potassique de synthèse." },
    riebeckite: { fichier: "riebeckite", polyedres: ["Si","Fe"],
      note: "Amphibole : chaînes doubles de tétraèdres le long de c (rubans Si₈O₂₂), reliées par des rubans d'octaèdres, avec un OH au centre de chaque anneau et un site A souvent vide. Sodium en M4, fer ferreux et ferrique dans les octaèdres ; cristal naturel avec un peu de potassium et de fluor." },
    apophyllite: { fichier: "apophyllite", polyedres: ["Si"],
      note: "Feuillets de tétraèdres en anneaux de quatre et de huit, reliés par le calcium et le potassium ; eau entre les feuillets. Fluorapophyllite partiellement déshydratée, aux neutrons." },
    prehnite: { fichier: "prehnite", polyedres: ["Si","Al"],
      note: "Feuillets de tétraèdres (Si et Al) reliés par des octaèdres d'aluminium et du calcium : un phyllosilicate à feuillets reliés, d'où un clivage seulement bon." },
    paragonite: { fichier: "paragonite", polyedres: ["Si"],
      note: "Mica dioctaédrique sodique : feuillets 2:1 d'aluminium, sodium entre les feuillets (d(001) ≈ 9,6 Å)." },
    glauconie: { fichier: "glauconite", polyedres: ["Si"],
      note: "Mica dioctaédrique ferrifère et potassique (modèle de Drits et al. 2010 ; octaèdres notés Al)." },
    lepidolite: { fichier: "lepidolite", polyedres: ["Si"],
      note: "Mica trioctaédrique au lithium et à l'aluminium, potassium entre les feuillets." },
    zinnwaldite: { fichier: "zinnwaldite", polyedres: ["Si"],
      note: "Mica trioctaédrique au lithium, au fer et à l'aluminium." },
    margarite: { fichier: "margarite", polyedres: ["Si"],
      note: "Mica « cassant » : calcium entre les feuillets, deux fois plus chargé que le potassium, qui les tient plus fort. Neutrons." },
    clintonite: { fichier: "clintonite", polyedres: ["Si"],
      note: "Mica cassant trioctaédrique : calcium entre les feuillets, aluminium jusque dans les tétraèdres." },
    talc: { fichier: "talc", polyedres: ["Si"],
      note: "Feuillets 2:1 de magnésium électriquement neutres : rien entre les feuillets, qui ne se tiennent que par des forces de van der Waals." },
    pyrophyllite: { fichier: "pyrophyllite", polyedres: ["Si"],
      note: "Feuillets 2:1 d'aluminium électriquement neutres, sans rien entre eux : le talc de l'aluminium." },
    antigorite: { fichier: "antigorite", polyedres: ["Si"],
      note: "Serpentine à feuillets ondulés : la couche de magnésium, plus large que celle de silice, la force à s'incurver puis à changer de côté toutes les 21,75 Å (Capitani et Mellini 2004)." },
    chrysotile: { fichier: "lizardite", polyedres: ["Si"],
      note: "Pas de maille plane pour le chrysotile, dont les feuillets s'enroulent en tubes : structure montrée, la lizardite, même feuillet à plat." },
    chamosite: { fichier: "chamosite", polyedres: ["Si"],
      note: "Chlorite ferreuse : feuillets 2:1 et feuillet d'hydroxyde intercalé, fer à la place du magnésium." },
    // ── sorosilicates et cyclosilicates (F.4 classes IX.B, IX.C, 01/10/2026) ──
    piemontite: { fichier: "piemontite", polyedres: ["Si"],
      note: "Groupe de l'épidote : chaînes d'octaèdres le long de b, reliées par des tétraèdres SiO₄ isolés et des paires Si₂O₇, calciums dans les grandes cavités. Manganèse trivalent dans un site octaédrique : d'où la couleur rouge." },
    allanite: { fichier: "allanite", polyedres: ["Si"],
      note: "Groupe de l'épidote : chaînes d'octaèdres le long de b, reliées par des tétraèdres SiO₄ isolés et des paires Si₂O₇, calciums dans les grandes cavités. Terres rares (cérium) à la place d'un calcium, fer à la place de l'aluminium." },
    vesuvianite: { fichier: "vesuvianite", polyedres: ["Si"],
      note: "Tétraèdres SiO₄ et Si₂O₇, colonnes de calcium et de fer le long de c, sites à cinq oxygènes en pyramide ; hydrogènes placés (Lager et al. 1999)." },
    pumpellyite: { fichier: "pumpellyite", polyedres: ["Si"],
      note: "Chaînes d'octaèdres le long de b, reliées par des tétraèdres SiO₄ et Si₂O₇ : une parente de l'épidote, plus hydratée." },
    akermanite: { fichier: "akermanite", polyedres: ["Si","Mg"],
      note: "Groupe de la mélilite : couches de tétraèdres (Si₂O₇ et un tétraèdre de Mg, Al ou Zn) perpendiculaires à c, calciums entre les couches. Pôle magnésien." },
    gehlenite: { fichier: "gehlenite", polyedres: ["Al"],
      note: "Groupe de la mélilite : couches de tétraèdres (Si₂O₇ et un tétraèdre de Mg, Al ou Zn) perpendiculaires à c, calciums entre les couches. Pôle alumineux : Al et Si se partagent les tétraèdres (sites partagés)." },
    hardystonite: { fichier: "hardystonite", polyedres: ["Si","Zn"],
      note: "Groupe de la mélilite : couches de tétraèdres (Si₂O₇ et un tétraèdre de Mg, Al ou Zn) perpendiculaires à c, calciums entre les couches. Zinc dans les tétraèdres de liaison." },
    hemimorphite: { fichier: "hemimorphite", polyedres: ["Si","Zn"],
      note: "Tétraèdres ZnO₃(OH) et paires Si₂O₇ tous pointés dans le même sens le long de c : le cristal est polaire, ses deux bouts sont différents (d'où son nom). Hydrogènes placés (neutrons)." },
    bertrandite: { fichier: "bertrandite", polyedres: ["Si","Be"],
      note: "Tétraèdres BeO₃(OH) et paires Si₂O₇ reliés en charpente, tous pointés le long de c. Hydrogènes placés (neutrons)." },
    ilvaite: { fichier: "ilvaite", polyedres: ["Si"],
      note: "Doubles chaînes d'octaèdres de fer (Fe²⁺ et Fe³⁺) le long de c, reliées par des paires Si₂O₇ ; calcium et manganèse dans les cavités. Hydrogène placé." },
    thortveitite: { fichier: "thortveitite", polyedres: ["Si","Sc"],
      note: "Octaèdres de scandium en feuillets, reliés par des paires Si₂O₇ dont l'oxygène central est sur un centre de symétrie (angle Si–O–Si de 180°)." },
    cuspidine: { fichier: "cuspidine", polyedres: ["Si"],
      note: "Chaînes de polyèdres de calcium, reliées par des paires Si₂O₇ ; le fluor est lié au calcium seul." },
    tilleyite: { fichier: "tilleyite", polyedres: ["Si","C"],
      note: "Paires Si₂O₇ et triangles CO₃ reliés par des calciums." },
    rankinite: { fichier: "rankinite", polyedres: ["Si"],
      note: "Paires Si₂O₇ isolées, reliées par des calciums." },
    axinite: { fichier: "axinite", polyedres: ["Si","B"],
      note: "Groupes Si₂O₇ reliés deux à deux par des triangles de bore, octaèdres d'aluminium et de fer, calciums : une charpente triclinique, sans plan de symétrie. Ferroaxinite du Mexique." },
    benitoite: { fichier: "benitoite", polyedres: ["Si","Ti"],
      note: "Anneaux de trois tétraèdres (Si₃O₉) reliés par des octaèdres TiO₆, baryum dans les cavités : la seule espèce minérale de la classe 6̄m2." },
    wadeite: { fichier: "wadeite", polyedres: ["Si","Zr"],
      note: "Anneaux de trois tétraèdres (Si₃O₉) reliés par des octaèdres ZrO₆, potassium dans les cavités ; synthétique." },
    catapleiite: { fichier: "catapleiite", polyedres: ["Si","Zr"],
      note: "Anneaux de trois tétraèdres reliés par des octaèdres ZrO₆, sodium et eau dans les cavités (eau non affichée)." },
    joaquinite: { fichier: "joaquinite", polyedres: ["Si"],
      note: "Anneaux de quatre tétraèdres (Si₄O₁₂) en couches, reliés par des octaèdres de titane, baryum et terres rares entre les couches." },
    baotite: { fichier: "baotite", polyedres: ["Si","Ti"],
      note: "Anneaux de quatre tétraèdres (Si₄O₁₂) et colonnes d'octaèdres de titane et de niobium ; baryum et chlore dans les canaux." },
    bazzite: { fichier: "bazzite", polyedres: ["Si","Be"],
      note: "Structure du béryl, scandium à la place de l'aluminium : anneaux Si₆O₁₈ empilés en canaux le long de c." },
    sekaninaite: { fichier: "sekaninaite", polyedres: ["Si","Al"],
      note: "Structure de la cordiérite, fer à la place du magnésium : anneaux de six tétraèdres (Si et Al ordonnés) empilés en canaux." },
    indialite: { fichier: "indialite", polyedres: ["Si","Al"],
      note: "Forme hexagonale de la cordiérite : Si et Al y sont désordonnés dans les anneaux ; cristal d'une enclave du Vésuve." },
    dravite: { fichier: "dravite", polyedres: ["Si","B"],
      note: "Groupe de la tourmaline : anneaux de six tétraèdres SiO₄ tous pointés dans le même sens le long de c (cristal polaire), triangles BO₃, octaèdres ; magnésium dans les sites Y : le pôle magnésien." },
    elbaite: { fichier: "elbaite", polyedres: ["Si","B"],
      note: "Groupe de la tourmaline : anneaux de six tétraèdres SiO₄ tous pointés dans le même sens le long de c (cristal polaire), triangles BO₃, octaèdres ; lithium et aluminium dans les sites Y (sites partagés). Hydrogènes placés (neutrons)." },
    uvite: { fichier: "uvite", polyedres: ["Si","B"],
      note: "Groupe de la tourmaline : anneaux de six tétraèdres SiO₄ tous pointés dans le même sens le long de c (cristal polaire), triangles BO₃, octaèdres ; calcium dans le site X, magnésium dans les sites Y." },
    liddicoatite: { fichier: "liddicoatite", polyedres: ["Si","B"],
      note: "Groupe de la tourmaline : anneaux de six tétraèdres SiO₄ tous pointés dans le même sens le long de c (cristal polaire), triangles BO₃, octaèdres ; calcium dans le site X, lithium et aluminium dans les sites Y ; cristal de Madagascar." },
    dioptase: { fichier: "dioptase", polyedres: ["Si"],
      note: "Anneaux de six tétraèdres (Si₆O₁₈) reliés par des cuivres en carré, molécules d'eau en anneaux dans les canaux. Hydrogènes placés." },
    milarite: { fichier: "milarite", polyedres: ["Si"],
      note: "Groupe de la milarite : doubles anneaux de douze tétraèdres (Si₁₂O₃₀) empilés le long de c, reliés par des octaèdres et de gros cations ; béryllium dans les tétraèdres de liaison." },
    osumilite: { fichier: "osumilite", polyedres: ["Si"],
      note: "Groupe de la milarite : doubles anneaux de douze tétraèdres (Si₁₂O₃₀) empilés le long de c, reliés par des octaèdres et de gros cations ; magnésium, fer et aluminium dans les sites de liaison." },
    sugilite: { fichier: "sugilite", polyedres: ["Si"],
      note: "Groupe de la milarite : doubles anneaux de douze tétraèdres (Si₁₂O₃₀) empilés le long de c, reliés par des octaèdres et de gros cations ; lithium et fer ; le manganèse des sugilites gemmes leur donne le violet." },
    roedderite: { fichier: "roedderite", polyedres: ["Si"],
      note: "Groupe de la milarite : doubles anneaux de douze tétraèdres (Si₁₂O₃₀) empilés le long de c, reliés par des octaèdres et de gros cations ; magnésium dans les sites de liaison ; cristal d'une lamproïte espagnole." },
    eudialyte: { fichier: "eudialyte", polyedres: ["Si","Zr"],
      note: "Anneaux de trois et de neuf tétraèdres, octaèdres de zirconium et anneaux de six octaèdres de calcium ; sodium partout (558 atomes par maille)." },
    // ── nésosilicates (F.4 classe IX.A, 01/10/2026) ──
    phenacite: { fichier: "phenacite", polyedres: ["Si","Be"],
      note: "Tétraèdres SiO₄ et BeO₄ reliés par leurs sommets en une charpente percée de canaux le long de c (structure de la willémite)." },
    willemite: { fichier: "willemite", polyedres: ["Si","Zn"],
      note: "Tétraèdres SiO₄ et ZnO₄ reliés par leurs sommets en une charpente percée de canaux le long de c." },
    eucryptite: { fichier: "eucryptite", polyedres: ["Si"],
      note: "Structure de la phénacite, Li et Al à la place du béryllium : charpente de tétraèdres ; Al et Si se partagent ici les mêmes sites (structure moyenne)." },
    fayalite: { fichier: "fayalite", polyedres: ["Si","Fe"],
      note: "Structure de l'olivine : tétraèdres SiO₄ isolés et deux sites octaédriques en chaînes le long de c. Pôle ferreux (Fe₂SiO₄)." },
    tephroite: { fichier: "tephroite", polyedres: ["Si","Mn"],
      note: "Structure de l'olivine : tétraèdres SiO₄ isolés et deux sites octaédriques en chaînes le long de c. Pôle manganésifère (Mn₂SiO₄)." },
    liebenbergite: { fichier: "liebenbergite", polyedres: ["Si","Ni"],
      note: "Structure de l'olivine : tétraèdres SiO₄ isolés et deux sites octaédriques en chaînes le long de c. Pôle nickélifère (Ni₂SiO₄), de synthèse." },
    monticellite: { fichier: "monticellite", polyedres: ["Si","Mg"],
      note: "Structure de l'olivine : tétraèdres SiO₄ isolés et deux sites octaédriques en chaînes le long de c. Le calcium, plus gros, occupe un site sur deux, le magnésium l'autre." },
    kirschsteinite: { fichier: "kirschsteinite", polyedres: ["Si","Fe"],
      note: "Structure de l'olivine : tétraèdres SiO₄ isolés et deux sites octaédriques en chaînes le long de c. Calcium et fer se partagent les deux sites ; cristal d'une météorite (angrite)." },
    glaucochroite: { fichier: "glaucochroite", polyedres: ["Si","Mn"],
      note: "Structure de l'olivine : tétraèdres SiO₄ isolés et deux sites octaédriques en chaînes le long de c. Calcium et manganèse se partagent les deux sites." },
    larsenite: { fichier: "larsenite", polyedres: ["Si","Zn"],
      note: "Tétraèdres SiO₄ et ZnO₄, plombs entourés d'oxygènes d'un seul côté (doublet libre du plomb)." },
    wadsleyite: { fichier: "wadsleyite", polyedres: ["Si","Mg"],
      note: "Forme de haute pression de l'olivine (410–525 km) : les tétraèdres SiO₄ vont par paires (Si₂O₇) ; un oxygène sur huit n'est lié à aucun silicium, ce qui permet d'accueillir de l'eau." },
    ringwoodite: { fichier: "ringwoodite", polyedres: ["Si","Mg"],
      note: "Forme de très haute pression de l'olivine (525–660 km) : structure du spinelle, silicium en tétraèdres, magnésium en octaèdres, oxygènes en empilement cubique compact." },
    spessartine: { fichier: "spessartine", polyedres: ["Si","Al"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Manganèse dans les sites à huit oxygènes." },
    knorringite: { fichier: "knorringite", polyedres: ["Si","Cr"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Chrome dans les octaèdres, magnésium dans les sites à huit oxygènes ; synthétique." },
    uvarovite: { fichier: "uvarovite", polyedres: ["Si","Cr"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Chrome dans les octaèdres, calcium dans les sites à huit oxygènes ; cristal naturel." },
    goldmanite: { fichier: "goldmanite", polyedres: ["Si","V"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Vanadium dans les octaèdres ; synthétique." },
    schorlomite: { fichier: "schorlomite", polyedres: ["Si","Ti"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Titane dans les octaèdres (et du fer jusque dans les tétraèdres)." },
    hydrogrossulaire: { fichier: "hydrogrossulaire", polyedres: ["Si","Al"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Structure de la katoïte : une partie des tétraèdres SiO₄ est remplacée par quatre OH (sites en partie vides ; hydrogènes non placés)." },
    majorite: { fichier: "majorite", polyedres: ["Si","Al"],
      note: "Grenat : tétraèdres SiO₄ isolés, reliés par des octaèdres (Al, Cr, Fe³⁺, V, Ti) et des sites à huit oxygènes en cube déformé (Ca, Mg, Fe²⁺, Mn). Grenat du manteau profond où le silicium entre aussi dans les octaèdres ; ici un terme de la série majorite–pyrope, de synthèse." },
    hafnon: { fichier: "hafnon", polyedres: ["Si"],
      note: "Structure du zircon : tétraèdres SiO₄ isolés et gros cations entourés de huit oxygènes, en chaînes le long de c. Hafnium à la place du zirconium ; synthétique." },
    thorite: { fichier: "thorite", polyedres: ["Si"],
      note: "Structure du zircon : tétraèdres SiO₄ isolés et gros cations entourés de huit oxygènes, en chaînes le long de c. Thorium à la place du zirconium ; synthétique." },
    huttonite: { fichier: "huttonite", polyedres: ["Si"],
      note: "Même formule que la thorite, structure de la monazite : thoriums entourés de neuf oxygènes." },
    coffinite: { fichier: "coffinite", polyedres: ["Si"],
      note: "Structure du zircon : tétraèdres SiO₄ isolés et gros cations entourés de huit oxygènes, en chaînes le long de c. Uranium à la place du zirconium ; synthétique (1958)." },
    mullite: { fichier: "mullite", polyedres: ["Al","Si"],
      note: "Chaînes d'octaèdres AlO₆ le long de c, reliées par des tétraèdres où se mêlent Al et Si ; une partie des oxygènes manque (sites en partie occupés)." },
    euclase: { fichier: "euclase", polyedres: ["Si","Al","Be"],
      note: "Tétraèdres SiO₄ et BeO₃(OH) en couches, octaèdres d'aluminium : clivage parfait {010} entre les couches." },
    staurotide: { fichier: "staurotide", polyedres: ["Si","Al"],
      note: "Alternance de couches de type disthène (Al₂SiO₅) et de couches d'hydroxyde de fer et d'aluminium, perpendiculaires à a : la staurotide est presque un disthène feuilleté." },
    norbergite: { fichier: "norbergite", polyedres: ["Si","Mg"],
      note: "Groupe de la humite : tranches de structure d'olivine séparées par des couches de brucite où F et OH remplacent l'oxygène. Norbergite : une tranche d'olivine pour une de brucite. Hydrogènes placés." },
    chondrodite: { fichier: "chondrodite", polyedres: ["Si","Mg"],
      note: "Groupe de la humite : deux tranches d'olivine pour une couche Mg(F,OH)₂. Hydrogènes placés (neutrons)." },
    humite: { fichier: "humite", polyedres: ["Si","Mg"],
      note: "Groupe de la humite : trois tranches d'olivine pour une couche Mg(F,OH)₂." },
    clinohumite: { fichier: "clinohumite", polyedres: ["Si","Mg"],
      note: "Groupe de la humite : quatre tranches d'olivine pour une couche Mg(F,OH)₂. Hydrogènes placés (neutrons)." },
    alleghanyite: { fichier: "alleghanyite", polyedres: ["Si"],
      note: "Structure de la chondrodite, manganèse à la place du magnésium (avec un peu de magnésium)." },
    malayaite: { fichier: "malayaite", polyedres: ["Si","Sn"],
      note: "Structure de la titanite : chaînes d'octaèdres SnO₆ reliées par des tétraèdres SiO₄, calciums dans les cavités." },
    chloritoide: { fichier: "chloritoide", polyedres: ["Si","Al"],
      note: "Couches d'octaèdres d'aluminium alternant avec des couches d'octaèdres de fer, de magnésium et d'aluminium, reliées par des tétraèdres SiO₄ isolés : un faux mica cassant." },
    datolite: { fichier: "datolite", polyedres: ["Si","B"],
      note: "Couches de tétraèdres SiO₄ et BO₃(OH) alternés, reliées par des calciums. Hydrogènes placés." },
    dumortierite: { fichier: "dumortierite", polyedres: ["Si","Al"],
      note: "Chaînes d'octaèdres d'aluminium le long de a, tétraèdres SiO₄ et triangles BO₃ ; cristal riche en antimoine et en arsenic (sites partagés)." },
    kornerupine: { fichier: "kornerupine", polyedres: ["Si","Al"],
      note: "Chaînes d'octaèdres d'aluminium et de magnésium le long de c, reliées par des groupes Si₂O₇ et SiO₄ (une partie du silicium peut être remplacée par du bore)." },
    grandidierite: { fichier: "grandidierite", polyedres: ["Si","Al","B"],
      note: "Chaînes d'octaèdres d'aluminium le long de c, tétraèdres SiO₄, triangles BO₃ et magnésiums en bipyramides." },
    gadolinite: { fichier: "gadolinite", polyedres: ["Si","Be"],
      note: "Couches de tétraèdres SiO₄ et BeO₄ reliées par des octaèdres de fer, terres rares (ici l'yttrium) entre les couches." },
    britholite: { fichier: "britholite", polyedres: ["Si"],
      note: "Structure de l'apatite où les tétraèdres SiO₄ remplacent les PO₄ et les terres rares (cérium) le calcium ; symétrie abaissée en monoclinique." },
    ottrelite: { fichier: "chloritoide", polyedres: ["Si", "Al"],
      note: "Pas de structure affinée de l'ottrélite : structure du chloritoïde, dont elle est le pôle manganésifère." },
    // ── oxydes et hydroxydes (F.4 classe IV, 01/10/2026) ──
    ferrihydrite: { fichier: "ferrihydrite", polyedres: ["Fe"],
      note: "Modèle de Michel et al. (2007) : nanocristaux de 2 à 6 nm, fers surtout en octaèdres et un sur cinq en tétraèdre, sites en partie vides. Une maille ne décrit qu'imparfaitement un cristal si petit." },
    lepidocrocite: { fichier: "lepidocrocite", polyedres: ["Fe"],
      note: "Feuillets ondulés d'octaèdres FeO₆ partageant leurs arêtes, ⊥ b, tenus entre eux par des liaisons hydrogène : d'où les écailles. Hydrogènes placés (diffraction d'électrons)." },
    maghemite: { fichier: "maghemite", polyedres: ["Fe"],
      note: "Structure de la magnétite (spinelle) où un site octaédrique sur six est vide : tout le fer est ferrique. Les lacunes s'ordonnent et abaissent la symétrie (P4₃32)." },
    akaganeite: { fichier: "akaganeite", polyedres: ["Fe"],
      note: "Doubles chaînes d'octaèdres FeO₆ qui délimitent des tunnels carrés (2 × 2) ; les chlores logent dans les tunnels et en tiennent la charpente. Akaganéite d'une météorite (Post et Buchwald 1991)." },
    wustite: { fichier: "wustite", polyedres: ["Fe"],
      note: "Structure du sel : chaque fer au centre d'un octaèdre d'oxygènes. La wüstite naturelle manque toujours un peu de fer (Fe₀,₉₅O) ; ici un échantillon presque stœchiométrique." },
    birnessite: { fichier: "birnessite", polyedres: ["Mn"],
      note: "Feuillets d'octaèdres MnO₆ (avec des sites vides et du Mn³⁺), séparés de ≈ 7 Å par un plan d'eau et de sodium (site partagé Na/eau dans la légende). Birnessite sodique de synthèse (Post et Veblen 1990)." },
    lithiophorite: { fichier: "lithiophorite", polyedres: ["Mn","Al"],
      note: "Alternance de feuillets d'octaèdres de manganèse et de feuillets d'octaèdres d'aluminium et de lithium (type gibbsite), reliés par des liaisons hydrogène." },
    todorokite: { fichier: "todorokite", polyedres: ["Mn"],
      note: "Charpente d'octaèdres MnO₆ en murs de trois octaèdres : tunnels de 3 × 3 octaèdres, remplis d'eau et de cations (non placés ici)." },
    cryptomelane: { fichier: "cryptomelane", polyedres: ["Mn"],
      note: "Structure de la hollandite : doubles chaînes d'octaèdres MnO₆ formant des tunnels de 2 × 2 octaèdres, où loge le potassium (avec un peu de sodium et de strontium)." },
    romanechite: { fichier: "romanechite", polyedres: ["Mn"],
      note: "Tunnels de 2 × 3 octaèdres MnO₆, où logent le baryum et l'eau (eau non affichée ; site du baryum occupé au tiers)." },
    pyrolusite: { fichier: "pyrolusite", polyedres: ["Mn"],
      note: "Structure du rutile : chaînes d'octaèdres MnO₆ partageant leurs arêtes le long de c — tunnels de 1 × 1, trop étroits pour un cation. Affinement aux neutrons (Bolzan et al. 1993)." },
    manganite: { fichier: "manganite", polyedres: ["Mn"],
      note: "Octaèdres de Mn³⁺ très déformés (effet Jahn-Teller : deux liaisons longues), en chaînes ; hydrogènes placés (Kohler et al. 1997)." },
    hausmannite: { fichier: "hausmannite", polyedres: ["Mn"],
      note: "Spinelle déformé : Mn²⁺ en tétraèdres, Mn³⁺ en octaèdres allongés (effet Jahn-Teller), d'où la maille quadratique." },
    braunite: { fichier: "braunite", polyedres: ["Mn","Si"],
      note: "Structure dérivée de la bixbyite : octaèdres de Mn³⁺, polyèdres de Mn²⁺ et un tétraèdre SiO₄ pour huit manganèses." },
    bixbyite: { fichier: "bixbyite", polyedres: ["Fe"],
      note: "Structure de la fluorine à laquelle on a retiré un oxygène sur quatre : chaque métal entouré de six oxygènes. Fer et manganèse se partagent les sites (Fe₁,₂₆Mn₀,₇₄O₃)." },
    manganosite: { fichier: "manganosite", polyedres: ["Mn"],
      note: "Structure du sel : chaque manganèse au centre d'un octaèdre d'oxygènes." },
    fougerite: { fichier: "fougerite", polyedres: ["Fe"],
      note: "Seul le feuillet de type brucite est affiché (fer en octaèdres d'OH, Fe²⁺ et Fe³⁺ mêlés) : l'eau et les anions entre les feuillets, très désordonnés, ne sont occupés qu'à 8 % dans ce modèle (Trolard et al. 2007)." },
    bayerite: { fichier: "bayerite", polyedres: ["Al"],
      note: "Même feuillet d'octaèdres Al(OH)₆ que la gibbsite, empilé autrement : les OH d'un feuillet se logent dans les creux du suivant. Hydrogènes placés." },
    nordstrandite: { fichier: "nordstrandite", polyedres: ["Al"],
      note: "Troisième façon d'empiler les feuillets de gibbsite, alternant les deux empilements de la gibbsite et de la bayérite (hydrogènes non placés)." },
    boehmite: { fichier: "boehmite", polyedres: ["Al"],
      note: "Doubles couches d'octaèdres AlO₄(OH)₂ ondulées, ⊥ b, tenues par des liaisons hydrogène (hydrogènes non placés par cet affinement)." },
    diaspore: { fichier: "diaspore", polyedres: ["Al"],
      note: "Structure de la goethite : doubles chaînes d'octaèdres Al(O,OH)₆ le long de c, plus denses que dans la boehmite. Hydrogènes placés." },
    corindon: { fichier: "corindon", polyedres: ["Al"],
      note: "Oxygènes en empilement hexagonal compact ; les aluminiums occupent deux vides octaédriques sur trois. Ces liaisons courtes et serrées en font le minéral le plus dur après le diamant." },
    anatase: { fichier: "anatase", polyedres: ["Ti"],
      note: "Octaèdres TiO₆ qui partagent quatre arêtes chacun, en zigzag : une maille quadratique très allongée (c ≈ 2,5 a)." },
    brookite: { fichier: "brookite", polyedres: ["Ti"],
      note: "Octaèdres TiO₆ partageant trois arêtes : troisième arrangement du TiO₂, orthorhombique." },
    perovskite: { fichier: "perovskite", polyedres: ["Ti"],
      note: "Octaèdres TiO₆ reliés par leurs sommets dans les trois directions, calcium dans les grandes cavités ; les octaèdres basculent légèrement, d'où la maille orthorhombique presque cubique." },
    geikielite: { fichier: "geikielite", polyedres: ["Ti","Mg"],
      note: "Structure de l'ilménite : le corindon où les cations alternent par plans, magnésium et titane." },
    cuprite: { fichier: "cuprite",
      note: "Oxygènes en réseau cubique centré, chaque cuivre relié à deux oxygènes en ligne : deux réseaux de ce type s'interpénètrent sans se toucher." },
    tenorite: { fichier: "tenorite",
      note: "Cuivres entourés de quatre oxygènes en carré presque plan (Cu²⁺), chaînes en zigzag." },
    zincite: { fichier: "zincite", polyedres: ["Zn"],
      note: "Structure de la würtzite : chaque zinc dans un tétraèdre d'oxygènes, tous pointés dans le même sens le long de c (cristal polaire)." },
    gahnite: { fichier: "gahnite", polyedres: ["Zn","Al"],
      note: "Spinelle : zinc en tétraèdres, aluminium en octaèdres." },
    franklinite: { fichier: "franklinite", polyedres: ["Zn","Fe"],
      note: "Spinelle : zinc en tétraèdres, fer ferrique en octaèdres. Ferrite de zinc de synthèse ; la franklinite naturelle contient aussi du manganèse." },
    eskolaite: { fichier: "eskolaite", polyedres: ["Cr"],
      note: "Structure du corindon, chrome à la place de l'aluminium." },
    periclase: { fichier: "periclase", polyedres: ["Mg"],
      note: "Structure du sel : chaque magnésium au centre d'un octaèdre d'oxygènes." },
    brucite: { fichier: "brucite", polyedres: ["Mg"],
      note: "Feuillets d'octaèdres Mg(OH)₆ (type CdI₂), tenus entre eux par des forces faibles : clivage basal parfait. Hydrogènes placés." },
    spinelle: { fichier: "spinelle", polyedres: ["Mg","Al"],
      note: "Le type de toute la famille : oxygènes en empilement cubique compact, magnésium dans un huitième des vides tétraédriques, aluminium dans la moitié des vides octaédriques." },
    baddeleyite: { fichier: "baddeleyite", polyedres: ["Zr"],
      note: "Chaque zirconium entouré de sept oxygènes : une fluorine déformée, monoclinique." },
    uraninite: { fichier: "uraninite",
      note: "Structure de la fluorine : uraniums en réseau cubique à faces centrées, oxygènes dans tous les vides tétraédriques. La pechblende naturelle est en partie oxydée et désordonnée." },
    thorianite: { fichier: "thorianite",
      note: "Structure de la fluorine, thorium à la place de l'uranium : les deux minéraux forment une série." },
    columbite: { fichier: "columbite", polyedres: ["Nb","Fe"],
      note: "Octaèdres de niobium et de fer en chaînes en zigzag le long de c, dans un ordre fer–niobium–niobium : la structure de la wolframite, dédoublée." },
    pyrochlore: { fichier: "pyrochlore", polyedres: ["Nb"],
      note: "Charpente d'octaèdres NbO₆ reliés par leurs sommets, calcium, sodium et fluor dans ses cavités." },
    // ── phosphates, arséniates, vanadates (F.4 classe VIII, 01/10/2026) ──
    monazite: { fichier: "monazite", polyedres: ["P"],
      note: "Tétraèdres PO₄ isolés et gros ions de terres rares (ici le cérium) entourés de neuf oxygènes. Monazite-(Ce) naturelle (Ni et al. 1995)." },
    xenotime: { fichier: "xenotime", polyedres: ["P"],
      note: "Structure du zircon : tétraèdres PO₄ et yttriums entourés de huit oxygènes, en chaînes le long de c." },
    amblygonite: { fichier: "amblygonite", polyedres: ["P", "Al"],
      note: "Chaînes d'octaèdres d'aluminium reliées par des tétraèdres PO₄, lithium entre elles. Montebrasite (pôle à OH) mesurée à 22 °C, hydrogène placé." },
    vivianite: { fichier: "vivianite", polyedres: ["P", "Fe"],
      note: "Octaèdres de fer seuls ou en paires, reliés par des tétraèdres PO₄ en feuillets ⊥ b ; eau et liaisons hydrogène entre les feuillets. Maille I2/m (Bartl 1989), hydrogènes placés." },
    turquoise: { fichier: "turquoise", polyedres: ["P", "Al"],
      note: "Octaèdres d'aluminium, tétraèdres PO₄ et cuivres liés à des OH et à de l'eau. Turquoise naturelle, site du cuivre occupé à 90 % (Kolitsch et Giester 2000)." },
    wavellite: { fichier: "wavellite", polyedres: ["P", "Al"],
      note: "Chaînes d'octaèdres d'aluminium (OH et fluor) reliées par des tétraèdres PO₄, eau dans les canaux. Wavellite de Zbirov (Bohême)." },
    autunite: { fichier: "autunite", polyedres: ["P", "U"],
      note: "Feuillets d'uranyle (UO₂²⁺, deux oxygènes à 1,8 Å de l'uranium) et de tétraèdres PO₄, perpendiculaires à b ; calcium et eau entre les feuillets. Autunite de synthèse (Locock et Burns 2003)." },
    torbernite: { fichier: "torbernite", polyedres: ["P", "U"],
      note: "Mêmes feuillets d'uranyle-phosphate que l'autunite, ⊥ c ; cuivre et eau entre les feuillets." },
    pyromorphite: { fichier: "pyromorphite", polyedres: ["P"],
      note: "Structure de l'apatite : plombs autour de canaux hexagonaux où s'alignent les chlores, tétraèdres PO₄." },
    mimetite: { fichier: "mimetite", polyedres: ["As"],
      note: "Structure de l'apatite, tétraèdres AsO₄ à la place des PO₄." },
    vanadinite: { fichier: "vanadinite", polyedres: ["V"],
      note: "Structure de l'apatite, tétraèdres VO₄ à la place des PO₄." },
    erythrite: { fichier: "erythrite", polyedres: ["As", "Co"],
      note: "Structure de la vivianite : octaèdres de cobalt reliés par des tétraèdres AsO₄ en feuillets, eau entre les feuillets." },
    // ── borates (F.4 classe VI, 01/10/2026) ──
    borax: { fichier: "borax", polyedres: ["B", "Na"],
      note: "Ions borate [B₄O₅(OH)₄]²⁻ (deux triangles BO₃ et deux tétraèdres BO₄ en anneau double) et chaînes d'octaèdres Na(H₂O)₆. Affinement aux neutrons : hydrogènes placés." },
    kernite: { fichier: "kernite", polyedres: ["B"],
      note: "Triangles BO₃ et tétraèdres BO₄ reliés en longues chaînes selon b, sodiums et eau entre elles (hydrogènes non placés par cet affinement)." },
    ulexite: { fichier: "ulexite", polyedres: ["B"],
      note: "Ions borate isolés (trois tétraèdres et deux triangles) et chaînes d'octaèdres de sodium et de calcium, toutes allongées selon c : d'où les fibres." },
    colemanite: { fichier: "colemanite", polyedres: ["B"],
      note: "Chaînes infinies de triangles BO₃ et de tétraèdres BO₄ le long de a, reliées par des calciums ; hydrogènes placés (Burns et Hawthorne 1993)." },
    boracite: { fichier: "boracite", polyedres: ["B"],
      note: "Charpente de tétraèdres BO₄ et de triangles BO₃ ; magnésium et chlore dans ses cages. Forme orthorhombique de basse température ; au-dessus de 265 °C, la boracite est cubique." },
    // ── sulfates, chromates, molybdates, tungstates (F.4 classe VII, 01/10/2026) ──
    barytine: { fichier: "barytine", polyedres: ["S"],
      note: "Tétraèdres SO₄ isolés et baryums entourés de douze oxygènes. Maille en Pnma, comme les ouvrages." },
    celestine: { fichier: "celestine", polyedres: ["S"],
      note: "Structure de la barytine, strontium à la place du baryum." },
    anglesite: { fichier: "anglesite", polyedres: ["S"],
      note: "Structure de la barytine, plomb à la place du baryum. Maille en Pbnm (a et c des ouvrages échangés)." },
    epsomite: { fichier: "epsomite", polyedres: ["S", "Mg"],
      note: "Octaèdres Mg(H₂O)₆, tétraèdres SO₄ et une septième molécule d'eau libre, le tout tenu par des liaisons hydrogène." },
    mirabilite: { fichier: "mirabilite", polyedres: ["S", "Na"],
      note: "Chaînes d'octaèdres Na(H₂O)₆, ions sulfate et molécules d'eau, tenus par des liaisons hydrogène. Affinement aux neutrons." },
    chalcanthite: { fichier: "chalcanthite", polyedres: ["S"],
      note: "Cuivres entourés de quatre molécules d'eau en carré et de deux oxygènes de sulfate plus loin ; une cinquième eau est libre. Affinement aux neutrons." },
    alunite: { fichier: "alunite", polyedres: ["S", "Al"],
      note: "Feuillets d'octaèdres AlO₂(OH)₄ reliés par des tétraèdres SO₄, potassium entre les feuillets." },
    jarosite: { fichier: "jarosite", polyedres: ["S", "Fe"],
      note: "Structure de l'alunite, fer ferrique à la place de l'aluminium." },
    crocoite: { fichier: "crocoite", polyedres: ["Cr"],
      note: "Tétraèdres CrO₄ isolés et plombs entourés de neuf oxygènes : la structure de la monazite." },
    wulfenite: { fichier: "wulfenite", polyedres: ["Mo"],
      note: "Tétraèdres MoO₄ isolés et plombs entourés de huit oxygènes : la structure de la scheelite." },
    scheelite: { fichier: "scheelite", polyedres: ["W"],
      note: "Tétraèdres WO₄ isolés et calciums entourés de huit oxygènes, dans une maille quadratique (c ≈ 2,2 a)." },
    wolframite: { fichier: "wolframite", polyedres: ["W", "Fe"],
      note: "Chaînes en zigzag d'octaèdres WO₆ et FeO₆ allongées selon c. Structure d'une wolframite ferrifère (Escobar et al. 1971) ; le manganèse peut remplacer le fer en toutes proportions." },
    // ── carbonates et nitrates (F.4 classe V, 01/10/2026) ──
    magnesite: { fichier: "magnesite", polyedres: ["C", "Mg"],
      note: "Structure de la calcite, magnésium à la place du calcium : plans de cations et plans de triangles CO₃ alternés, chaque magnésium au centre d'un octaèdre d'oxygènes." },
    rhodochrosite: { fichier: "rhodochrosite", polyedres: ["C", "Mn"],
      note: "Structure de la calcite, manganèse à la place du calcium." },
    smithsonite: { fichier: "smithsonite", polyedres: ["C", "Zn"],
      note: "Structure de la calcite, zinc à la place du calcium : la plus petite maille du groupe après la magnésite." },
    ankerite: { fichier: "ankerite", polyedres: ["C", "Ca", "Fe"],
      note: "Structure de la dolomite : plans de calcium et plans de fer et de magnésium (sites partagés) alternés. Ankérite de composition Ca(Fe₀,₅₄Mg₀,₄₅)(CO₃)₂." },
    cerusite: { fichier: "cerusite", polyedres: ["C"],
      note: "Structure de l'aragonite : chaque plomb entouré de neuf oxygènes, triangles CO₃ empilés en colonnes." },
    strontianite: { fichier: "strontianite", polyedres: ["C"],
      note: "Structure de l'aragonite, strontium à la place du calcium." },
    witherite: { fichier: "witherite", polyedres: ["C"],
      note: "Structure de l'aragonite, baryum à la place du calcium ; la maille est presque hexagonale (b ≈ a√3)." },
    malachite: { fichier: "malachite", polyedres: ["C"],
      note: "Chaînes d'octaèdres de cuivre allongés (deux liaisons longues, effet Jahn-Teller) le long de c, reliées par les triangles CO₃ et les OH. Affinement aux neutrons : hydrogènes placés." },
    azurite: { fichier: "azurite", polyedres: ["C"],
      note: "Cuivres entourés de quatre oxygènes en carré (plus un ou deux plus loin), reliés par les triangles CO₃ et les OH en une charpente." },
    nitratine: { fichier: "nitratine", polyedres: ["N", "Na"],
      note: "Structure de la calcite : sodium à la place du calcium, triangles NO₃ à la place des CO₃." },
    nitre: { fichier: "nitre", polyedres: ["N"],
      note: "Structure de l'aragonite : potassium à la place du calcium, triangles NO₃ à la place des CO₃. Affinement aux neutrons à 25 °C." },
    // ── sulfures (F.4 classe II, 01/10/2026) ──
    chalcocite: { fichier: "chalcocite",
      note: "Les soufres forment un empilement hexagonal compact presque parfait ; les 96 cuivres de la maille se répartissent dans ses vides triangulaires, de façon si complexe que la maille est géante (chalcocite « basse », stable sous 103 °C). Au-dessus, les cuivres deviennent mobiles : c'est presque un liquide de cuivre dans une charpente de soufre." },
    bornite: { fichier: "bornite",
      note: "Les soufres forment un réseau cubique à faces centrées ; cuivre et fer occupent une partie des vides tétraédriques, et les vides restés vides s'ordonnent en une surstructure (bornite « basse », orthorhombique). L'affinement ne distingue pas le fer du cuivre : tous les métaux sont notés Cu." },
    acanthite: { fichier: "acanthite",
      note: "Forme de basse température du sulfure d'argent : au-dessus de 173 °C, les argents se déplacent librement dans un réseau cubique de soufres (argentite) ; en refroidissant, ils se figent sur des sites précis et le réseau se déforme en monoclinique." },
    pentlandite: { fichier: "pentlandite", polyedres: ["Fe"],
      note: "Les soufres forment un réseau cubique à faces centrées ; les métaux occupent huit vides tétraédriques sur seize, groupés par huit en petits cubes de métal (Fe,Ni)₈ liés entre eux, plus un vide octaédrique. Fer et nickel se partagent les mêmes sites : la légende indique les proportions." },
    galene: { fichier: "galene", polyedres: ["Pb"], ligandsHors: false,
      note: "Même structure que le sel de cuisine : chaque plomb au centre d'un octaèdre de six soufres. Les plans {100} sont électriquement neutres, d'où le clivage cubique parfait." },
    blende: { fichier: "blende", polyedres: ["Zn"],
      note: "Chaque zinc au centre d'un tétraèdre de quatre soufres, et inversement : c'est la structure du diamant, un atome sur deux remplacé. Les plans {110}, où zinc et soufre alternent, sont ceux du clivage dodécaédrique." },
    chalcopyrite: { fichier: "chalcopyrite", polyedres: ["Cu", "Fe"],
      note: "Structure de la blende avec cuivre et fer à la place du zinc, rangés en alternance : la maille cubique devient quadratique, deux fois plus haute (c ≈ 2 a). Chaque métal est dans un tétraèdre de soufres." },
    pyrrhotite: { fichier: "pyrrhotite", polyedres: ["Fe"],
      note: "Structure de la nickéline (fers dans des octaèdres de soufres empilés en colonnes), à laquelle il manque un fer sur huit : Fe₇S₈. Les sites vides s'ordonnent et font une maille monoclinique (pyrrhotite 4C), magnétique." },
    cinabre: { fichier: "cinabre",
      note: "Des chaînes hélicoïdales –Hg–S–Hg–S– (2,37 Å) qui tournent autour de l'axe c : trois atomes de mercure par tour. Le sens de l'hélice est celui d'un pas de vis, comme dans le quartz, d'où des cristaux droits et gauches." },
    covellite: { fichier: "covellite",
      note: "Un empilement de feuillets : couches de cuivres en triangles CuS₃, couches de tétraèdres CuS₄, et entre deux, des paires de soufre (S₂, 2,07 Å). Le clivage basal parfait passe par ces paires." },
    nickeline: { fichier: "nickeline", polyedres: ["Ni"],
      note: "Le modèle de toute une famille (« type NiAs ») : arsenics en empilement hexagonal compact, nickels dans les vides octaédriques. Les octaèdres partagent leurs faces le long de l'axe c, si bien que deux nickels voisins ne sont qu'à 2,5 Å : la liaison est en partie métallique. Affinement de 1988, qui a montré une légère distorsion (maille orthorhombique)." },
    marcassite: { fichier: "marcassite", polyedres: ["Fe"],
      note: "Même formule que la pyrite, autre arrangement : les octaèdres FeS₆ partagent des arêtes en colonnes le long de c, et les soufres vont encore par paires (2,21 Å)." },
    arsenopyrite: { fichier: "arsenopyrite", polyedres: ["Fe"],
      note: "Structure de la marcassite où chaque paire de soufres devient une paire arsenic–soufre ; les fers se rapprochent deux à deux (2,73 Å), ce qui fait basculer la maille en monoclinique. Cristal de La Roche-Balue (Loire-Atlantique), de composition FeAsS exacte." },
    stibine: { fichier: "stibine",
      note: "Des rubans (Sb₄S₆)ₙ allongés selon b, faits de pyramides SbS₃ ; entre les rubans, seulement des liaisons faibles. D'où les longs prismes striés selon b et le clivage parfait parallèle aux rubans." },
    orpiment: { fichier: "orpiment",
      note: "Des feuillets plissés de pyramides AsS₃ partageant leurs sommets ; entre les feuillets, seulement des forces de van der Waals : clivage parfait, lamelles souples comme du mica." },
    realgar: { fichier: "realgar",
      note: "Un cristal de molécules As₄S₄ : quatre arsenics et quatre soufres en cage, comme un tétraèdre d'arsenics coiffé d'un carré de soufres. Les molécules ne se tiennent que par de faibles forces ; la lumière casse la cage et transforme lentement le réalgar en poudre jaune (pararéalgar)." },
    molybdenite: { fichier: "molybdenite", polyedres: ["Mo"],
      note: "Des feuillets S–Mo–S : chaque molybdène au centre d'un prisme triangulaire de six soufres. Entre les feuillets, rien que des forces de van der Waals : clivage parfait, toucher gras, et le même usage que le graphite comme lubrifiant." },
    tetraedrite: { fichier: "tetraedrite",
      note: "Une charpente de type blende, ouverte : cuivres en tétraèdres et en triangles, antimoines en pyramides SbS₃, et un soufre au centre d'un octaèdre de cuivres. Le cuivre est remplacé en partie par du fer, du zinc ou de l'argent (sites partagés)." },
    bournonite: { fichier: "bournonite",
      note: "Pyramides SbS₃, cuivres en tétraèdres et plombs entourés de sept à huit soufres. La maille est presque carrée (a ≈ b), ce qui explique les macles répétées à 90° en « roue dentée »." },
    boulangerite: { fichier: "boulangerite",
      note: "Des rubans de plomb, d'antimoine et de soufre allongés selon c (8,1 Å), plusieurs sites partagés entre plomb et antimoine. Ces rubans font les fibres et les « cheveux » de la boulangérite." },
    proustite: { fichier: "proustite",
      note: "Des pyramides AsS₃ toutes tournées dans le même sens selon c, reliées par des argents liés à deux soufres : le cristal est polaire (le haut et le bas des prismes diffèrent)." },
    pyrargyrite: { fichier: "pyrargyrite",
      note: "Même structure que la proustite, avec l'antimoine à la place de l'arsenic : les deux « argents rouges » forment une série." },
    graphite: { fichier: "graphite", repetition: [2, 2, 1] },
    diamant: { fichier: "diamant" },

    // ── éléments natifs (classe I, F.4, 01/10/2026) : pas de polyèdres ; vue compacte = rayons MÉTALLIQUES
    //    (rayon atomique en coordinence 12, Teatum, Gschneidner et Waber 1968), pas ioniques ──
    or_natif: { fichier: "or", polyedres: [], rayonsCompacts: { Au: 1.44 },
      note: "Cubique à faces centrées : un atome à chaque coin et au centre de chaque face. Chaque atome touche 12 voisins à 2,88 Å : c'est l'empilement le plus serré possible de sphères égales (74 % de l'espace)." },
    argent_natif: { fichier: "argent", polyedres: [], rayonsCompacts: { Ag: 1.44 },
      note: "Même empilement que l'or (cubique à faces centrées, 12 voisins à 2,89 Å) : les deux métaux se mêlent en toutes proportions, d'où l'électrum naturel." },
    cuivre_natif: { fichier: "cuivre", polyedres: [], rayonsCompacts: { Cu: 1.28 },
      note: "Cubique à faces centrées, 12 voisins à 2,56 Å. Les plans les plus denses {111} glissent facilement les uns sur les autres : c'est l'origine de la malléabilité de l'or, de l'argent et du cuivre." },
    platine_natif: { fichier: "platine", polyedres: [], rayonsCompacts: { Pt: 1.39 },
      note: "Cubique à faces centrées, 12 voisins à 2,77 Å. Le platine naturel contient presque toujours du fer (souvent quelques %, parfois plus de 10 %) et d'autres platinoïdes." },
    fer_natif: { fichier: "fer", polyedres: [], rayonsCompacts: { Fe: 1.26 },
      note: "Cubique centré (fer α, la kamacite des météorites) : un atome à chaque coin et un au centre, 8 voisins à 2,48 Å. Moins serré (68 %) que l'or ou le cuivre. Au-dessus de 912 °C, le fer passe à l'empilement cubique à faces centrées (fer γ, la taénite des météorites)." },
    mercure_natif: { fichier: "mercure", mode: "compact", polyedres: [], rotation: true, rayonsCompacts: { Hg: 1.4 },
      note: "Liquide : les atomes sont serrés comme dans un solide (10 voisins vers 3 Å), mais sans aucun ordre et ils bougent sans cesse — l'agitation dessinée est schématique. Le mercure ne cristallise qu'à −38,8 °C (maille rhomboédrique)." },
    arsenic_natif: { fichier: "arsenic", polyedres: [], repetition: [2, 2, 1], vue: { axe: "a" }, rayonsCompacts: { As: 1.21 },
      note: "Couches plissées : chaque atome est lié à 3 voisins de sa couche (2,52 Å) ; les couches ne se touchent qu'à 3,12 Å, sans liaison forte. C'est ce qui donne le clivage parfait {0001}, parallèle aux couches." },
    antimoine_natif: { fichier: "antimoine", polyedres: [], repetition: [2, 2, 1], vue: { axe: "a" }, rayonsCompacts: { Sb: 1.41 },
      note: "Même structure en couches plissées que l'arsenic : 3 voisins dans la couche (2,91 Å), couches à 3,36 Å l'une de l'autre. Clivage parfait {0001} entre les couches." },
    bismuth_natif: { fichier: "bismuth", polyedres: [], repetition: [2, 2, 1], vue: { axe: "a" }, rayonsCompacts: { Bi: 1.55 },
      note: "Même structure en couches plissées que l'arsenic et l'antimoine : 3 voisins dans la couche (3,07 Å), couches à 3,53 Å. Clivage parfait {0001}." },
    soufre_natif: { fichier: "soufre", polyedres: [], molecules: true, rayonsCompacts: { S: 1.04 },
      note: "Le soufre α est un cristal MOLÉCULAIRE : des anneaux de 8 atomes (S₈) en couronne, liés entre eux par de simples forces de van der Waals (3,3 Å entre anneaux). D'où sa faible dureté (2) et sa fusion dès 115 °C. 16 anneaux par maille." },

    // ── composés organiques (classe X, F.6) : billes et liaisons ; polyèdres autour des seuls métaux ;
    //    molecules: true = molécules et ions organiques complétés au bord du bloc ──
    whewellite: { fichier: "whewellite", molecules: true, polyedres: ["Ca"],
      note: "Deux molécules d'eau de la maille occupent chacune deux positions voisines ; seule la plus fréquente (85 %) est montrée. Certains hydrogènes ne sont pas localisés dans l'affinement." },
    weddellite: { fichier: "weddellite", molecules: true, polyedres: ["Ca"],
      note: "Les molécules d'eau au centre des canaux (eau « zéolitique ») ne sont présentes que dans environ six cas sur dix : c'est ce surplus d'eau variable qui s'échappe quand la weddellite se change en whewellite." },
    caoxite: { fichier: "caoxite", molecules: true, polyedres: ["Ca"] },
    humboldtine: { fichier: "humboldtine", molecules: true, polyedres: ["Fe"], note: "Affinement sur l'oxalate ferreux synthétique." },
    lindbergite: { fichier: "lindbergite", molecules: true, polyedres: ["Mn"],
      note: "Affinement sur le composé synthétique : même structure que la humboldtine, le manganèse à la place du fer." },
    natroxalate: { fichier: "natroxalate", molecules: true, polyedres: ["Na"], note: "Affinement sur l'oxalate de sodium synthétique." },
    oxammite: { fichier: "oxammite", molecules: true, polyedres: [] },
    minguzzite: { fichier: "minguzzite", molecules: true, polyedres: ["Fe"], note: "Affinement sur le ferrioxalate de potassium synthétique (Herpin 1958) ; les hydrogènes ne sont pas placés." },
    wheatleyite: { fichier: "wheatleyite", molecules: true, polyedres: ["Cu"], note: "Affinement sur le composé synthétique ; les hydrogènes ne sont pas placés." },
    novgorodovaite: { fichier: "novgorodovaite", molecules: true, polyedres: ["Ca"] },
    coskrenite_ce: { fichier: "coskrenite_ce", molecules: true, polyedres: ["S"],
      note: "Les terres rares (cérium, néodyme, lanthane…) se partagent le même site : la bille montre l'élément dominant." },
    levinsonite_y: { fichier: "levinsonite_y", molecules: true, polyedres: ["Al", "S"],
      note: "Yttrium et terres rares se partagent le même site : la bille montre l'élément dominant." },
    zugshunstite_ce: { fichier: "zugshunstite_ce", molecules: true, polyedres: ["Al", "S"] },
    deveroite_ce: { fichier: "deveroite_ce", molecules: true, polyedres: [],
      note: "Affinement sur l'oxalate de cérium synthétique (Ollendorff et Weigel 1969) ; les hydrogènes des molécules d'eau ne sont pas placés." },
    dashkovaite: { fichier: "dashkovaite", molecules: true, polyedres: ["Mg"],
      note: "Affinement sur le formiate de magnésium synthétique ; les hydrogènes ne sont pas placés." },
    calclacite: { fichier: "calclacite", molecules: true, polyedres: [], note: "Affinement sur le composé synthétique ; les hydrogènes ne sont pas placés." },
    hoganite: { fichier: "hoganite", molecules: true, polyedres: [],
      note: "Affinement sur l'acétate de cuivre synthétique. Les atomes de cuivre vont par paires, reliés par quatre ions acétate : la « roue à aubes », motif classique de la chimie de coordination." },
    paceite: { fichier: "paceite", molecules: true, polyedres: ["Cu"],
      note: "Les hydrogènes des groupes méthyle occupent deux orientations ; une seule est montrée." },
    ernstburkeite: { fichier: "ernstburkeite", molecules: true, polyedres: ["Mg"],
      note: "Affinement sur le composé synthétique Mg(CH₃SO₃)₂·12H₂O." },
    mellite: { fichier: "mellite", molecules: true, polyedres: ["Al"],
      note: "Diffraction de neutrons à 15 K sur un cristal de Tatabánya (Robl et Kuhs 1991) : tous les hydrogènes sont placés. Les ions mellitate, cycles plats à six groupes acide, alternent avec des octaèdres Al(H₂O)₆ ; la cohésion tient aux liaisons hydrogène." },
    julienite: { fichier: "julienite", molecules: true, polyedres: ["Co"], note: "Affinement sur le composé synthétique ; les hydrogènes ne sont pas placés. Chaque cobalt est entouré de quatre ions thiocyanate liés par leur azote : c'est cet environnement à quatre voisins qui le rend bleu." },
    fichtelite: { fichier: "fichtelite", molecules: true, polyedres: [] },
    branchite: { fichier: "branchite", molecules: true, polyedres: [], note: "Les hydrogènes ne sont pas placés dans cet affinement (Bouška et al. 1998, sous le nom de hartite)." },
    simonellite: { fichier: "simonellite", molecules: true, polyedres: [], note: "Affinement sur le composé synthétique ; les hydrogènes ne sont pas placés." },
    kratochvilite: { fichier: "kratochvilite", molecules: true, polyedres: [], note: "Affinement sur le fluorène synthétique." },
    ravatite: { fichier: "ravatite", molecules: true, polyedres: [], note: "Affinement sur le phénanthrène synthétique ; les hydrogènes ne sont pas placés." },
    carpathite: { fichier: "carpathite", molecules: true, polyedres: [],
      note: "Molécules plates de coronène empilées en colonnes inclinées, à 3,46 Å les unes des autres." },
    hoelite: { fichier: "hoelite", molecules: true, polyedres: [], note: "Structure de l'anthraquinone (affinement de 1967)." },
    kladnoite: { fichier: "kladnoite", molecules: true, polyedres: [], note: "Structure du phtalimide (Matzat 1972)." },
    flagstaffite: { fichier: "flagstaffite", molecules: true, polyedres: [], note: "Structure de l'hydrate de terpine (Marsh et Herbstein 1988)." },
    abelsonite: { fichier: "abelsonite", molecules: true, polyedres: [],
      note: "La molécule, non symétrique, se place au hasard dans deux orientations autour du nickel : la structure affichée superpose les positions les plus occupées de ses groupes latéraux (Hummer et al. 2017). Le cycle central, lui, est ordonné." },
    urea: { fichier: "urea", molecules: true, polyedres: [], note: "Affinement sur l'urée synthétique (diffraction de neutrons)." },
    uricite: { fichier: "uricite", molecules: true, polyedres: [], note: "Affinement sur l'acide urique synthétique." },
    allantoin: { fichier: "allantoin", molecules: true, polyedres: [], note: "Affinement sur de l'allantoïne extraite d'un lichen comestible (Xu et al. 2011)." },
    // ── tectosilicates et zéolithes (F.4 classes IX.F–IX.G, 01/10/2026) : charpentes de tétraèdres ; l'eau des zéolithes = « Ow » ──
    tridymite: { fichier: "tridymite", polyedres: ["Si"],
      note: "Tridymite MC (monoclinique, la forme stable à la température ambiante) : feuillets de tétraèdres SiO₄ en anneaux de six, pointes alternativement en haut et en bas, empilés à deux couches (le quartz et la cristobalite ont d'autres empilements)." },
    cristobalite: { fichier: "cristobalite", polyedres: ["Si"],
      note: "α-cristobalite (quadratique) : feuillets de tétraèdres en anneaux de six empilés à trois couches, légèrement inclinés ; au-dessus de ≈ 250 °C ils se redressent et la maille devient cubique." },
    moganite: { fichier: "moganite", polyedres: ["Si"],
      note: "Tranches de quartz droit et de quartz gauche alternées le long de a : un « quartz maclé à l'échelle de la maille »." },
    stishovite: { fichier: "stishovite", polyedres: ["Si"],
      note: "Structure du rutile : le silicium est entouré de SIX oxygènes (octaèdres en chaînes le long de c), seul cas courant à la surface ; d'où une densité de 4,3." },
    seifertite: { fichier: "seifertite", polyedres: ["Si"],
      note: "Octaèdres SiO₆ en chaînes en zigzag (structure de α-PbO₂), encore plus compacts que ceux de la stishovite." },
    melanophlogite: { fichier: "melanophlogite", polyedres: ["Si"],
      note: "Clathrate de silice : charpente de tétraèdres en cages (dodécaèdres et tétrakaidécaèdres), comme la glace des hydrates de gaz ; les cages contiennent du méthane et du CO₂ (C au centre, H non placés)." },
    anorthose: { fichier: "anorthose", polyedres: ["Si","Al"],
      note: "Feldspath sodi-potassique triclinique : charpente de l'albite, Na et K mêlés sur le même site (désordre Al/Si : structure moyenne)." },
    celsiane: { fichier: "celsiane", polyedres: ["Si","Al"],
      note: "Charpente feldspathique où l'aluminium et le silicium alternent strictement (Al₂Si₂) : la maille c est doublée (14,4 Å). Baryum dans les cavités." },
    hyalophane: { fichier: "hyalophane", polyedres: ["Si","Al"],
      note: "Feldspath de la sanidine au celsiane : baryum, potassium et sodium se partagent le site des cavités." },
    oligoclase: { fichier: "oligoclase", polyedres: ["Si","Al"],
      note: "Plagioclase An≈18 : charpente de l'albite, Na et un peu de Ca sur le même site." },
    bytownite: { fichier: "bytownite", polyedres: ["Si","Al"],
      note: "Plagioclase An85 : maille c doublée (14,2 Å) comme l'anorthite, Al et Si presque ordonnés." },
    kalsilite: { fichier: "kalsilite", polyedres: ["Si","Al"],
      note: "Charpente de la tridymite où Al et Si alternent, potassium dans les canaux : feldspathoïde très pauvre en silice." },
    sodalite: { fichier: "sodalite", polyedres: ["Si","Al"],
      note: "Cages de 24 tétraèdres (cuboctaèdres tronqués) empilées en cube ; au centre de chaque cage, un Cl⁻ entouré de quatre Na⁺." },
    hauyne: { fichier: "hauyne", polyedres: ["Si","Al","S"],
      note: "Cages de la sodalite ; un sulfate SO₄²⁻ par cage environ, avec Na, Ca et K (positions moyennes, désordonnées)." },
    noseane: { fichier: "noseane", polyedres: ["Si","Al","S"],
      note: "Cages de la sodalite remplies de sulfate et de sodium ; l'eau (moins d'une molécule par cage) n'est pas placée." },
    lazurite: { fichier: "lazurite", polyedres: ["Si","Al","S"],
      note: "Structure MOYENNE (la vraie est modulée) : cages de la sodalite avec sulfate et sodium ; les ions polysulfure S₃⁻ qui font le bleu sont trop désordonnés pour être dessinés." },
    cancrinite: { fichier: "cancrinite", polyedres: ["Si","Al"],
      note: "Anneaux de six tétraèdres empilés à deux couches : de larges canaux le long de c, garnis de Na, de Ca et de carbonates (orientations moyennes)." },
    davyne: { fichier: "davyne", polyedres: ["Si","Al"],
      note: "Charpente de la cancrinite ; les canaux contiennent des chaînes Ca–Cl et des sulfates, les cavités K et Na." },
    vishnevite: { fichier: "vishnevite", polyedres: ["Si","Al","S"],
      note: "Charpente de la cancrinite où les carbonates sont remplacés par des sulfates et de l'eau." },
    afghanite: { fichier: "afghanite", polyedres: ["Si","Al","S"],
      note: "Empilement à HUIT couches d'anneaux de six (c = 21,4 Å) : cages de sodalite et de cancrinite alternées, avec sulfates et chlore." },
    tugtupite: { fichier: "tugtupite", polyedres: ["Si","Al","Be"],
      note: "Charpente de la sodalite où le béryllium et l'aluminium remplacent une partie du silicium, de façon ordonnée ; Cl⁻ au centre des cages." },
    marialite: { fichier: "marialite", polyedres: ["Si","Al"],
      note: "Scapolite : anneaux de quatre tétraèdres reliés en colonnes le long de c ; dans les grandes cavités, un Cl⁻ entouré de Na⁺." },
    meionite: { fichier: "meionite", polyedres: ["Si","Al"],
      note: "Scapolite calcique (Me80) : même charpente que la marialite, carbonate CO₃²⁻ au centre des cavités et calcium autour (désordre d'orientation)." },
    silvialite: { fichier: "silvialite", polyedres: ["Si","Al","S"],
      note: "Scapolite à sulfate : charpente de la méionite, SO₄²⁻ (et un peu de CO₃²⁻) au centre des cavités." },
    danburite: { fichier: "danburite", polyedres: ["Si","B"],
      note: "Charpente de paires Si₂O₇ et B₂O₇ (tétraèdres de bore), calcium dans les cavités : même plan que le feldspath anorthite." },
    petalite: { fichier: "petalite", polyedres: ["Si","Al","Li"],
      note: "Feuillets de tétraèdres SiO₄ plissés reliés par des tétraèdres AlO₄ et LiO₄ : une charpente qui se clive selon les feuillets." },
    leifite: { fichier: "leifite", polyedres: ["Si","Al","Be"],
      note: "Charpente de tétraèdres (Si, Al, Be) percée de canaux le long de c, où logent Na, K et l'eau (non placée)." },
    natrolite: { fichier: "natrolite", polyedres: ["Si","Al"],
      note: "Zéolithe fibreuse : chaînes de tétraèdres le long de c (unités de cinq tétraèdres), reliées latéralement ; canaux en zigzag avec Na⁺ et eau." },
    mesolite: { fichier: "mesolite", polyedres: ["Si","Al"],
      note: "Charpente de la natrolite ; les canaux contiennent alternativement Na (comme la natrolite) et Ca (comme la scolécite), d'où une maille triplée selon b. Eau avec ses hydrogènes (neutrons)." },
    scolecite: { fichier: "scolecite", polyedres: ["Si","Al"],
      note: "Charpente de la natrolite, Ca²⁺ à la place de 2 Na⁺ et une molécule d'eau de plus ; symétrie abaissée (monoclinique)." },
    thomsonite: { fichier: "thomsonite", polyedres: ["Si","Al"],
      note: "Chaînes de la natrolite reliées autrement ; Al et Si alternent strictement. Eau avec ses hydrogènes." },
    gonnardite: { fichier: "gonnardite", polyedres: ["Si","Al"],
      note: "Charpente de la natrolite où Al et Si sont désordonnés : maille quadratique (« tétranatrolite »)." },
    edingtonite: { fichier: "edingtonite", polyedres: ["Si","Al"],
      note: "Chaînes de la natrolite reliées en charpente quadratique ; baryum et eau dans les canaux." },
    chabazite: { fichier: "chabazite", polyedres: ["Si","Al"],
      note: "Doubles anneaux de six tétraèdres empilés en rhomboèdre : de grandes cages (6,7 × 10 Å) ouvertes par des fenêtres de huit tétraèdres ; Ca, Na et eau dedans." },
    levyne: { fichier: "levyne", polyedres: ["Si","Al"],
      note: "Anneaux de six simples et doubles empilés autrement que dans la chabazite : cages aplaties ; cations et eau en positions partielles." },
    erionite: { fichier: "erionite", polyedres: ["Si","Al"],
      note: "Cages de cancrinite et doubles anneaux de six empilés le long de c : de grandes cavités ; la forme fibreuse de l'érionite est celle qui rend ses poussières dangereuses (mésothéliome)." },
    faujasite: { fichier: "faujasite", polyedres: ["Si","Al"],
      note: "Cages de sodalite reliées par des doubles anneaux de six comme les atomes de carbone du diamant : des « supercages » de 13 Å, les plus grandes des zéolithes naturelles (modèle de Baur 1964)." },
    heulandite: { fichier: "heulandite", polyedres: ["Si","Al"],
      note: "Couches denses de tétraèdres parallèles à (010), reliées par peu de liaisons : canaux de dix et huit tétraèdres dans le plan, d'où le clivage {010} parfait." },
    clinoptilolite: { fichier: "clinoptilolite", polyedres: ["Si","Al"],
      note: "Charpente de la heulandite, plus riche en silicium (Si/Al > 4) : plus stable à la chaleur. Ca, Na, K, Mg et eau dans les canaux (positions partielles)." },
    stilbite: { fichier: "stilbite", polyedres: ["Si","Al"],
      note: "Couches de tétraèdres parallèles à (010) reliées en charpente ; grands canaux de dix tétraèdres le long de a, avec Ca, Na et eau (affinement de Slaughter 1970)." },
    stellerite: { fichier: "stellerite", polyedres: ["Si","Al"],
      note: "Charpente de la stilbite, sans sodium : symétrie orthorhombique." },
    barrerite: { fichier: "barrerite", polyedres: ["Si","Al"],
      note: "Charpente de la stilbite, sodique : symétrie orthorhombique (Amma)." },
    brewsterite: { fichier: "brewsterite", polyedres: ["Si","Al"],
      note: "Charpente à canaux de huit tétraèdres ; chaque strontium est entouré d'oxygènes de la charpente et de cinq molécules d'eau. Secteur triclinique d'un cristal à secteurs (Akizuki 1996)." },
    epistilbite: { fichier: "epistilbite", polyedres: ["Si","Al"],
      note: "Charpente à canaux de dix et huit tétraèdres ; calcium et eau dedans (affinement de Perrotta 1967)." },
    analcime: { fichier: "analcime", polyedres: ["Si","Al"],
      note: "Anneaux de quatre et de six tétraèdres en une charpente cubique ; un Na⁺ et une molécule d'eau dans chaque canal. Même charpente que la leucite et la pollucite." },
    laumontite: { fichier: "laumontite", polyedres: ["Si","Al"],
      note: "Canaux de dix tétraèdres le long de c, calcium et eau dedans ; à l'air sec, elle perd une partie de son eau et s'effrite (« léonhardite »)." },
    phillipsite: { fichier: "phillipsite", polyedres: ["Si","Al"],
      note: "Doubles chaînes en « vilebrequin » reliées en charpente ; K, Na et Ca dans des canaux qui se croisent." },
    harmotome: { fichier: "harmotome", polyedres: ["Si","Al"],
      note: "Charpente de la phillipsite ; le baryum remplace le potassium." },
    amicite: { fichier: "amicite", polyedres: ["Si","Al"],
      note: "Charpente de la gismondine où Al et Si alternent strictement ; K et Na ordonnés dans les canaux." },
    pollucite: { fichier: "pollucite", polyedres: ["Si","Al"],
      note: "Charpente de l'analcime ; le gros césium occupe la place de la molécule d'eau (site partagé Cs/eau)." },
    hsianghualite: { fichier: "hsianghualite", polyedres: ["Si","Be","Li"],
      note: "Charpente cubique de tétraèdres SiO₄, BeO₄ et LiO₃F, à la manière de l'analcime ; calcium et fluor dans les cavités." },
  });
})();
