// ============================================================
// CLASSIFICATION SYSTÉMATIQUE DES MINÉRAUX ARGILEUX
// Groupe des silicates → sous-classe des phyllosilicates →
// familles (par type de feuillet) → groupes → espèces.
// Chargé après mineraux.js : enrichit ARGILES et ROCHE_EXTRAS.
// ============================================================

// ---------- Toutes les espèces ----------
// octa : caractère di- ou trioctaédrique du feuillet O
const ESPECES = {
  // — groupe du kaolin (1:1, Al) —
  kaolinite_e: { nom: "Kaolinite", formule: "Al₂Si₂O₅(OH)₄", octa: "dioctaédrique (Al)", fiche: "kaolinite",
    note: "L'espèce de très loin la plus répandue du groupe : celle des sols tropicaux (≥ 22 °C), des kaolins de Bretagne et du Limousin, de la porcelaine." },
  dickite: { nom: "Dickite", formule: "Al₂Si₂O₅(OH)₄", octa: "dioctaédrique (Al)",
    note: "Polymorphe de la kaolinite (même formule, empilement des feuillets différent), plus ordonné. Typique des altérations hydrothermales et des grès profonds — pas des sols." },
  nacrite: { nom: "Nacrite", formule: "Al₂Si₂O₅(OH)₄", octa: "dioctaédrique (Al)",
    note: "Le plus rare des polymorphes du kaolin, formé à plus haute température (filons hydrothermaux). Éclat nacré caractéristique." },
  halloysite: { nom: "Halloysite", formule: "Al₂Si₂O₅(OH)₄ · nH₂O", octa: "dioctaédrique (Al)",
    note: "Même chimie que la kaolinite, mais les feuillets s'enroulent en nanotubes. Fraîche, elle garde une couche d'eau entre ses feuillets (10 Å) ; dès qu'elle sèche, cette eau part pour toujours (7 Å). Les deux formes étaient deux espèces (halloysite et hydrohalloysite, ou endellite) : depuis 2026, l'IMA n'en reconnaît plus qu'une. Fréquente dans l'altération rapide des roches volcaniques (andosols)." },
  odinite: { nom: "Odinite", formule: "(Fe³⁺,Mg,Al,Fe²⁺,Ti,Mn)₂,₅(Si,Al)₂O₅(OH)₄", octa: "di-trioctaédrique (Fe)",
    note: "Argile verte ferrifère qui se néoforme aujourd'hui dans les sédiments marins tropicaux peu profonds ; précurseur probable de la berthiérine. Décrite en 1988 et nommée en l'honneur du géologue français Gilles S. Odin." },
  // — groupe des serpentines (1:1, Mg-Fe) —
  chrysotile: { nom: "Chrysotile", formule: "Mg₃Si₂O₅(OH)₄", octa: "trioctaédrique (Mg)", fiche: "serpentines",
    note: "Les feuillets s'enroulent en fibres creuses : c'est l'amiante blanc, interdit en France depuis 1997. Veines soyeuses vert clair dans les serpentinites." },
  antigorite: { nom: "Antigorite", formule: "(Mg,Fe)₃Si₂O₅(OH)₄", octa: "trioctaédrique (Mg)", fiche: "serpentines",
    note: "Feuillets ondulés en vagues, structure massive : la serpentine des zones de subduction et du métamorphisme alpin (schistes lustrés du Queyras)." },
  lizardite: { nom: "Lizardite", formule: "Mg₃Si₂O₅(OH)₄", octa: "trioctaédrique (Mg)", fiche: "serpentines",
    note: "Feuillets plans, cristaux minuscules : la plus abondante des serpentines, celle qui donne leur fond vert sombre aux serpentinites. Nommée d'après la péninsule du Lizard (Cornouailles)." },
  berthierine: { nom: "Berthiérine", formule: "(Fe²⁺,Fe³⁺,Al)₃(Si,Al)₂O₅(OH)₄", octa: "trioctaédrique (Fe)",
    note: "Serpentine ferrifère des oolithes : c'est elle (avec la chamosite) qui fait le minerai de fer lorrain, la « minette ». Nommée d'après le minéralogiste français Pierre Berthier." },
  greenalite: { nom: "Greenalite", formule: "(Fe²⁺,Fe³⁺)₂₋₃Si₂O₅(OH)₄", octa: "trioctaédrique (Fe)",
    note: "Serpentine ferreuse des « fers rubanés » précambriens (BIF), les plus vieilles roches ferrifères de la Terre." },
  amesite: { nom: "Amésite", formule: "Mg₂Al(AlSiO₅)(OH)₄", octa: "trioctaédrique (Mg-Al)",
    note: "Serpentine alumineuse rare, des roches métamorphiques riches en Mg et Al." },
  cronstedtite: { nom: "Cronstedtite", formule: "Fe²⁺₂Fe³⁺(SiFe³⁺O₅)(OH)₄", octa: "trioctaédrique (Fe)",
    note: "Serpentine ferrique noire des filons hydrothermaux de basse température. Célèbre ailleurs que sur Terre : c'est un produit majeur de l'altération aqueuse des astéroïdes, abondant dans les météorites carbonées." },
  nepouite: { nom: "Népouite", formule: "Ni₃Si₂O₅(OH)₄", octa: "trioctaédrique (Ni)",
    note: "Serpentine nickélifère vert pomme, nommée d'après Népoui (Nouvelle-Calédonie). Avec ses cousines, elle compose les « garniérites », le grand minerai de nickel des latérites calédoniennes." },
  // — groupe talc-pyrophyllite (2:1 neutres) —
  pyrophyllite: { nom: "Pyrophyllite", formule: "Al₂Si₄O₁₀(OH)₂", octa: "dioctaédrique (Al)",
    note: "L'équivalent alumineux du talc : feuillet 2:1 parfaitement neutre. Métamorphisme de bas degré des roches alumineuses ; toucher gras, tendre comme lui." },
  talc_e: { nom: "Talc", formule: "Mg₃Si₄O₁₀(OH)₂", octa: "trioctaédrique (Mg)", fiche: "talc",
    note: "Feuillets neutres qui glissent les uns sur les autres : le minéral le plus tendre de l'échelle de Mohs (dureté 1). Trimouns, au-dessus de Luzenac (Ariège), est la plus grande carrière de talc du monde." },
  willemseite: { nom: "Willemséite", formule: "(Ni,Mg)₃Si₄O₁₀(OH)₂", octa: "trioctaédrique (Ni)",
    note: "Talc nickélifère, très rare, des massifs ultrabasiques altérés." },
  minnesotaite: { nom: "Minnesotaïte", formule: "(Fe²⁺,Mg)₃Si₄O₁₀(OH)₂", octa: "trioctaédrique (Fe)",
    note: "Le « talc ferreux » : même feuillet neutre, mais rempli de fer. Typique des formations de fer rubanées (BIF) précambriennes faiblement métamorphisées." },
  ferripyrophyllite: { nom: "Ferripyrophyllite", formule: "Fe³⁺₂Si₄O₁₀(OH)₂", octa: "dioctaédrique (Fe³⁺)",
    note: "L'équivalent ferrique de la pyrophyllite, très rare : feuillet 2:1 neutre dont l'aluminium est remplacé par du fer ferrique." },
  // — groupe des smectites —
  montmorillonite: { nom: "Montmorillonite", formule: "(Na,Ca)₀,₃(Al,Mg)₂Si₄O₁₀(OH)₂ · nH₂O", octa: "dioctaédrique (Al-Mg)", fiche: "smectites",
    note: "LA smectite type, décrite en 1847 à Montmorillon (Vienne). Charge issue de substitutions dans le feuillet octaédrique. Constituant principal des bentonites." },
  beidellite: { nom: "Beidellite", formule: "(Na,Ca)₀,₃Al₂(Si,Al)₄O₁₀(OH)₂ · nH₂O", octa: "dioctaédrique (Al)",
    note: "Smectite alumineuse dont la charge vient du feuillet tétraédrique. Fréquente dans les sols argileux tempérés, 8–15 °C (vertisols, sols de Limagne)." },
  nontronite: { nom: "Nontronite", formule: "Na₀,₃Fe³⁺₂(Si,Al)₄O₁₀(OH)₂ · nH₂O", octa: "dioctaédrique (Fe³⁺)",
    note: "Smectite ferrique, jaune-vert, décrite à… Nontron, en Dordogne ! Produit d'altération des basaltes et gabbros ; détectée en abondance sur Mars." },
  saponite: { nom: "Saponite", formule: "Ca₀,₂₅(Mg,Fe)₃(Si,Al)₄O₁₀(OH)₂ · nH₂O", octa: "trioctaédrique (Mg)",
    note: "Smectite magnésienne (« argile à savon ») : altération des basaltes, gabbros, serpentinites et péridotites — celle des sols de l'étang de Lers." },
  hectorite: { nom: "Hectorite", formule: "Na₀,₃(Mg,Li)₃Si₄O₁₀(OH,F)₂ · nH₂O", octa: "trioctaédrique (Mg-Li)",
    note: "Smectite à lithium, rare, gonflement spectaculaire : prisée en cosmétique et pour les boues de forage haut de gamme." },
  stevensite: { nom: "Stevensite", formule: "Ca₀,₁₅Mg₃Si₄O₁₀(OH)₂ · nH₂O", octa: "trioctaédrique (Mg, lacunaire)",
    note: "Smectite magnésienne des lacs alcalins et milieux évaporitiques (charge créée par des lacunes, pas des substitutions)." },
  sauconite: { nom: "Sauconite", formule: "Na₀,₃Zn₃(Si,Al)₄O₁₀(OH)₂ · nH₂O", octa: "trioctaédrique (Zn)",
    note: "Smectite zincifère des chapeaux d'oxydation des gisements de zinc." },
  volkonskoite: { nom: "Volkonskoïte", formule: "Ca₀,₃(Cr³⁺,Mg,Fe³⁺)₂(Si,Al)₄O₁₀(OH)₂ · 4H₂O", octa: "dioctaédrique (Cr³⁺)",
    note: "Smectite chromifère d'un vert émeraude profond, décrite dans l'Oural. Broyée, elle a servi de pigment vert aux peintres russes — et la légende veut que Picasso en ait réclamé." },
  swinefordite: { nom: "Swinefordite", formule: "(Ca,Na)₀,₃(Li,Al,Mg)₂₋₃(Si,Al)₄O₁₀(OH,F)₂ · nH₂O", octa: "di-trioctaédrique (Li)",
    note: "Smectite lithinifère très rare, née de l'altération des pegmatites à spodumène." },
  // — groupe des vermiculites —
  vermiculite_e: { nom: "Vermiculite", formule: "(Mg,Fe)₃(Si,Al)₄O₁₀(OH)₂ · 4 H₂O", octa: "trioctaédrique (Mg-Fe)", fiche: "vermiculite",
    note: "Espèce unique de son groupe (avec ses variantes dioctaédriques de sols) : charge élevée héritée des micas dont elle provient." },
  // — groupe des micas et illites —
  illite_e: { nom: "Illite", formule: "K₀,₆₋₀,₈(Al,Mg,Fe)₂(Si,Al)₄O₁₀(OH)₂", octa: "dioctaédrique (Al)", fiche: "illite",
    note: "Le « mica argileux » : un peu moins de charge et de K que la muscovite, cristaux minuscules. L'argile la plus commune des sols français." },
  glauconite_e: { nom: "Glauconite", formule: "(K,Na)(Fe³⁺,Al,Mg)₂(Si,Al)₄O₁₀(OH)₂", octa: "dioctaédrique (Fe³⁺)", fiche: "glauconite",
    note: "Mica ferrifère marin néoformé en granules verts — voir sa fiche complète." },
  celadonite: { nom: "Céladonite", formule: "K(Mg,Fe²⁺)(Fe³⁺,Al)Si₄O₁₀(OH)₂", octa: "dioctaédrique (Fe-Mg)",
    note: "Cousine volcanique de la glauconite : tapisse les vésicules des basaltes altérés. C'est la « terre verte de Vérone » des peintres." },
  sericite: { nom: "Séricite", formule: "≈ muscovite microcristalline", octa: "dioctaédrique (Al)",
    note: "Pas une espèce officielle : nom de terrain de la muscovite/illite en très fins cristaux soyeux qui lustrent ardoises et phyllades." },
  muscovite_e: { nom: "Muscovite", formule: "KAl₂(AlSi₃O₁₀)(OH)₂", octa: "dioctaédrique (Al)",
    note: "Mica vrai (charge ≈ 1) : à la frontière supérieure des minéraux argileux, dont il est le parent direct par héritage." },
  biotite_e: { nom: "Biotite (série)", formule: "K(Mg,Fe)₃(AlSi₃O₁₀)(OH)₂", octa: "trioctaédrique (Mg-Fe)",
    note: "Mica vrai trioctaédrique (série phlogopite-annite). Mère de la vermiculite dans les sols." },
  phlogopite: { nom: "Phlogopite", formule: "KMg₃(AlSi₃O₁₀)(OH)₂", octa: "trioctaédrique (Mg)",
    note: "Pôle magnésien pur des micas sombres : marbres dolomitiques, roches ultrabasiques potassiques." },
  paragonite: { nom: "Paragonite", formule: "NaAl₂(AlSi₃O₁₀)(OH)₂", octa: "dioctaédrique (Al)",
    note: "Mica blanc sodique des schistes métamorphiques, sosie de la muscovite (seule la diffraction les distingue)." },
  lepidolite: { nom: "Lépidolite", formule: "K(Li,Al)₃(Si,Al)₄O₁₀(F,OH)₂", octa: "trioctaédrique (Li-Al)",
    note: "Mica lithinifère rose-lilas des pegmatites (Montebras, Creuse) — minerai historique de lithium." },
  margarite: { nom: "Margarite", formule: "CaAl₂(Al₂Si₂O₁₀)(OH)₂", octa: "dioctaédrique (Al)",
    note: "« Mica dur » calcique : charge 2, feuillets si fortement liés qu'il perd la souplesse des micas." },
  brammallite: { nom: "Brammallite", formule: "Na₀,₇(Al,Mg)₂(Si,Al)₄O₁₀(OH)₂", octa: "dioctaédrique (Al)",
    note: "L'« illite sodique » : même structure déficitaire en cations interfoliaires, mais avec du sodium à la place du potassium. Rare, décrite dans des schistes houillers gallois." },
  annite: { nom: "Annite", formule: "KFe²⁺₃(AlSi₃O₁₀)(OH)₂", octa: "trioctaédrique (Fe²⁺)",
    note: "Le pôle purement ferreux des micas noirs : la « biotite » des géologues est une solution solide entre annite (Fe) et phlogopite (Mg)." },
  zinnwaldite: { nom: "Zinnwaldite", formule: "KLiFe²⁺Al(AlSi₃O₁₀)(F,OH)₂", octa: "trioctaédrique (Li-Fe-Al)",
    note: "Mica lithinifère gris-brun des greisens à étain (Zinnwald, monts Métallifères). En France : greisens de Montebras et d'Échassières, riches en lithium." },
  clintonite: { nom: "Clintonite", formule: "Ca(Mg,Al)₃(Al₃SiO₁₀)(OH)₂", octa: "trioctaédrique (Mg-Al)",
    note: "Le « mica dur » trioctaédrique, pendant magnésien de la margarite : charge 2, feuillets cassants. Skarns et marbres métamorphiques." },
  // — groupe des chlorites —
  clinochlore: { nom: "Clinochlore", formule: "(Mg₅Al)(AlSi₃O₁₀)(OH)₈", octa: "trioctaédrique (Mg)", fiche: "chlorite",
    note: "La chlorite commune, magnésienne, des schistes verts et des sols jeunes de montagne." },
  chamosite: { nom: "Chamosite", formule: "(Fe²⁺₅Al)(AlSi₃O₁₀)(OH)₈", octa: "trioctaédrique (Fe)",
    note: "Chlorite ferrifère : avec la berthiérine, elle constitue les oolithes du minerai de fer lorrain. Nommée d'après Chamoson (Valais)." },
  pennantite: { nom: "Pennantite", formule: "(Mn₅Al)(AlSi₃O₁₀)(OH)₈", octa: "trioctaédrique (Mn)",
    note: "Chlorite manganésifère orangée, rare, des gisements de manganèse." },
  nimite: { nom: "Nimite", formule: "(Ni₅Al)(AlSi₃O₁₀)(OH)₈", octa: "trioctaédrique (Ni)",
    note: "Chlorite nickélifère verte des massifs ultrabasiques altérés." },
  sudoite: { nom: "Sudoïte", formule: "Mg₂Al₃(AlSi₃O₁₀)(OH)₈", octa: "di-trioctaédrique",
    note: "Chlorite « mixte » di-trioctaédrique, marqueur du métamorphisme de très bas degré et des altérations hydrothermales." },
  cookeite: { nom: "Cookéite", formule: "LiAl₄(AlSi₃O₁₀)(OH)₈", octa: "di-trioctaédrique (Li-Al)",
    note: "Chlorite à lithium des pegmatites et des quartz à cristaux ; connue des cristalliers alpins." },
  donbassite: { nom: "Donbassite", formule: "Al₂[Al₂,₃₃(Si₃Al)O₁₀](OH)₈", octa: "dioctaédrique (Al)",
    note: "La seule chlorite entièrement dioctaédrique : tout aluminium, feuillet interfoliaire compris. Altérations hydrothermales acides (Donbass, Ukraine)." },
  franklinfurnaceite: { nom: "Franklinfurnacéite", formule: "Ca₂Fe³⁺Mn²⁺₃Mn³⁺(Zn₂Si₂O₁₀)(OH)₈", octa: "trioctaédrique / interfoliaire dioctaédrique",
    note: "Le cas rarissime inverse : feuillet T-O-T trioctaédrique mais feuillet brucitique dioctaédrique. Connue presque uniquement du gisement de Franklin (New Jersey), célèbre pour ses minéraux fluorescents au zinc et au manganèse." },
  baileychlore: { nom: "Baileychlore", formule: "(Zn,Fe²⁺,Al,Mg)₆(Si,Al)₄O₁₀(OH)₈", octa: "trioctaédrique (Zn)",
    note: "Chlorite zincifère rare des zones d'oxydation des gisements de zinc ; nommée en l'honneur du minéralogiste S. W. Bailey, grand classificateur des phyllosilicates." },
  // — interstratifiés —
  rectorite: { nom: "Rectorite", formule: "mica/smectite régulier (1:1)", octa: "dioctaédrique",
    note: "L'interstratifié régulier parfait : un feuillet de mica, un feuillet de smectite, en alternance stricte. Marqueur de diagenèse avancée." },
  corrensite: { nom: "Corrensite", formule: "chlorite/smectite régulier (1:1)", octa: "trioctaédrique",
    note: "Alternance stricte chlorite-smectite : typique des évaporites et dolomies du Trias — les sondages du Keuper français en regorgent. Nommée d'après le minéralogiste C. W. Correns." },
  hydrobiotite: { nom: "Hydrobiotite", formule: "biotite/vermiculite régulier", octa: "trioctaédrique",
    note: "Étape intermédiaire figée de la transformation biotite → vermiculite, fréquente dans les arènes granitiques." },
  tosudite: { nom: "Tosudite", formule: "chlorite/smectite dioct. régulier (Li)", octa: "dioctaédrique",
    note: "Interstratifié régulier rare à lithium, des altérations hydrothermales acides." },
  aliettite: { nom: "Aliettite", formule: "talc/saponite régulier (1:1)", octa: "trioctaédrique",
    note: "Alternance stricte talc-saponite, rare, dans les serpentinites et ophiolites altérées." },
  kaolinite_smectite: { nom: "Kaolinite/smectite (K/S)", formule: "interstratifié irrégulier", octa: "dioctaédrique",
    note: "Mélange feuillet à feuillet kaolinite-smectite : l'instantané des sols tropicaux (≥ 22 °C) en cours de « kaolinisation »." },
  // — fibreuses —
  sepiolite_e: { nom: "Sépiolite", formule: "Mg₄Si₆O₁₅(OH)₂ · 6 H₂O", octa: "trioctaédrique (Mg)", fiche: "sepiolite",
    note: "L'« écume de mer » : si légère et poreuse qu'elle flotte. Sculptée en pipes au XIXᵉ siècle ; absorbant industriel aujourd'hui." },
  palygorskite: { nom: "Palygorskite (attapulgite)", formule: "(Mg,Al)₂Si₄O₁₀(OH) · 4 H₂O", octa: "di-trioctaédrique (Mg-Al)", fiche: "sepiolite",
    note: "Sœur de la sépiolite, un peu plus alumineuse. Le gisement de Mormoiron (Vaucluse) a fourni la France en « terre à foulon ». Ingrédient du bleu maya des fresques précolombiennes !" },
  // — para-cristallins —
  allophane_e: { nom: "Allophane", formule: "Al₂O₃ · (SiO₂)₁,₃₋₂ · (2,5–3) H₂O", octa: "—", fiche: "allophane",
    note: "Sphérules creuses de ~4 nm, sans ordre cristallin à longue distance : le premier produit de l'altération ultra-rapide des verres volcaniques." },
  imogolite: { nom: "Imogolite", formule: "Al₂SiO₃(OH)₄", octa: "—", fiche: "allophane",
    note: "Nanotubes parfaits de ~2 nm de diamètre, découverts dans les sols volcaniques japonais (« imogo »). Présente dans les andosols du Massif central." },
  hisingerite: { nom: "Hisingérite", formule: "Fe³⁺₂Si₂O₅(OH)₄ · 2H₂O", octa: "— (para-cristallin, Fe³⁺)",
    note: "Le pendant ferrique de l'allophane : gel silico-ferrique noir-brun, produit d'altération rapide des sulfures et silicates de fer." },
};

// ---------- L'arbre de classification ----------
// Structure FIDÈLE au tableau récapitulatif de Wikipédia : chaque « groupe » ci-dessous
// correspond à UNE COLONNE du tableau, définie par ses critères structuraux
//   octa    : caractère di- ou trioctaédrique du feuillet O
//   teSi    : substitution dans le feuillet TÉTRAÉDRIQUE (Te/Si = 4 ou 8 → aucune)
//   oc      : substitution dans le feuillet OCTAÉDRIQUE (Oc = 12/12 → aucune)
//   espace  : espacement basal stable ou variable (= gonflant)
const CLASSIF = [
  {
    famille: "Argiles 1:1 (T-O) — espacement ≈ 7 Å",
    desc: "Un feuillet tétraédrique + un feuillet octaédrique, soudés par liaisons hydrogène : pas d'espace interfoliaire utile, argiles « sages ». Quatre cas selon le remplissage du feuillet O et la présence de substitutions.",
    groupes: [
      { nom: "1:1 dioctaédrique — espacement stable", octa: "dioctaédrique (Al)", teSi: "Te/Si = 4", oc: "Oc = 12/12", espace: "stable (7,2 Å)", charge: "≈ 0", fiche: "kaolinite",
        note: "Le groupe du kaolin : aucune substitution, feuillets neutres soudés par liaisons hydrogène. Trois polymorphes de même formule, qui ne diffèrent que par l'empilement.",
        especes: ["kaolinite_e", "dickite", "nacrite"] },
      { nom: "1:1 dioctaédrique — espacement variable", octa: "dioctaédrique (Al)", teSi: "Te/Si = 4", oc: "Oc = 12/12", espace: "variable (7,2 ↔ 10 Å ; séchée, 7,2 Å pour toujours)", charge: "≈ 0", fiche: "kaolinite",
        note: "L'halloysite : même chimie que la kaolinite, mais une couche d'eau peut s'insérer entre les feuillets (10 Å hydratée, 7 Å sèche) et les feuillets s'enroulent en nanotubes. Une seule espèce depuis 2026 : la forme hydratée (endellite) n'en est plus une à part.",
        especes: ["halloysite"] },
      { nom: "1:1 trioctaédrique — espacement stable", octa: "trioctaédrique (Mg)", teSi: "Te/Si = 4", oc: "Oc = 12/12", espace: "stable (7,3 Å)", charge: "≈ 0", fiche: "serpentines",
        note: "Les serpentines magnésiennes : équivalent trioctaédrique du kaolin. Le désaccord de taille entre les deux feuillets les force à se courber (plans, ondulés ou enroulés).",
        especes: ["chrysotile", "antigorite", "lizardite"] },
      { nom: "1:1 trioctaédrique — substitutions tétraédriques", octa: "trioctaédrique (Fe, Al, Ni)", teSi: "Te/Si < 4", oc: "Oc > 12/12", espace: "stable", charge: "≈ 0", fiche: "serpentines",
        note: "Les serpentines ferrifères, alumineuses et nickélifères : de l'aluminium ou du fer remplace du silicium dans le feuillet T. Ce sont les argiles des minerais de fer oolithiques et des latérites à nickel.",
        especes: ["cronstedtite", "berthierine", "amesite", "greenalite", "nepouite", "odinite"] },
    ],
  },
  {
    famille: "Argiles 2:1 (T-O-T) dioctaédriques — espacement 9,3 à 18 Å",
    desc: "Sandwich T-O-T dont le feuillet octaédrique est rempli d'Al³⁺ (2 sites sur 3). Cinq cas selon l'endroit où se produit la substitution (feuillet tétraédrique ou octaédrique), qui décide de la charge — et donc du gonflement.",
    groupes: [
      { nom: "2:1 dioct. — feuillet neutre", octa: "dioctaédrique (Al)", teSi: "Te/Si = 8", oc: "Oc = 12/12", espace: "stable (9,2 Å)", charge: "0", fiche: "talc",
        note: "La pyrophyllite : aucune substitution nulle part, donc aucune charge et rien entre les feuillets. Le degré zéro de l'argile 2:1.",
        especes: ["pyrophyllite", "ferripyrophyllite"] },
      { nom: "2:1 dioct. — charge octaédrique (smectites)", octa: "dioctaédrique (Al, Cr)", teSi: "Te/Si = 8", oc: "Oc < 12/12", espace: "variable (9,7 → 15,6 Å ; dans l'eau 19 à 40 Å et plus)", charge: "0,2 – 0,6", fiche: "smectites",
        note: "La substitution a lieu dans le feuillet OCTAÉDRIQUE (Mg²⁺ remplace Al³⁺) : la charge, née loin de la surface, est faible et diffuse → l'eau s'engouffre, l'argile gonfle. C'est la montmorillonite.",
        especes: ["montmorillonite", "volkonskoite"] },
      { nom: "2:1 dioct. — charge tétraédrique (smectites)", octa: "dioctaédrique (Al, Fe³⁺)", teSi: "Te/Si < 8", oc: "Oc = 12/12", espace: "variable", charge: "0,2 – 0,6", fiche: "smectites",
        note: "Ici la substitution se fait dans le feuillet TÉTRAÉDRIQUE (Al³⁺ remplace Si⁴⁺) : la charge est plus proche de la surface, donc mieux ancrée — gonflement un peu moins libre qu'avec la montmorillonite.",
        especes: ["beidellite", "nontronite"] },
      { nom: "2:1 dioct. — vermiculite", octa: "dioctaédrique (Al)", teSi: "Te/Si < 8", oc: "Oc < 12/12", espace: "variable, bridé (14,4 Å à l'air, 14,8 Å dans l'eau)", charge: "0,6 – 0,9", fiche: "vermiculite",
        note: "Substitutions dans LES DEUX feuillets : la charge devient forte, l'attraction entre feuillets aussi → le gonflement se bride (deux couches d'eau maximum) mais la CEC explose.",
        especes: ["vermiculite_e"] },
      { nom: "2:1 dioct. — micas et illites", octa: "dioctaédrique (Al, Fe³⁺)", teSi: "Te/Si < 8", oc: "Oc = 12/12", espace: "stable (10 Å, verrouillé au K⁺)", charge: "0,6 – 2", fiche: "illite",
        note: "Charge si forte qu'elle est compensée par des K⁺ non hydratés qui rivettent les feuillets comme des clous : plus d'eau, plus de gonflement. Des illites des sols aux micas vrais, jusqu'aux micas « durs » calciques.",
        especes: ["illite_e", "brammallite", "sericite", "glauconite_e", "celadonite", "muscovite_e", "paragonite", "margarite"] },
    ],
  },
  {
    famille: "Argiles 2:1 (T-O-T) trioctaédriques — espacement 9,3 à 18 Å",
    desc: "Même architecture, mais le feuillet octaédrique est rempli de Mg²⁺ ou Fe²⁺ (3 sites sur 3). Les mêmes cinq cas se rejouent — c'est la symétrie parfaite du tableau : chaque groupe dioctaédrique a son jumeau trioctaédrique.",
    groupes: [
      { nom: "2:1 trioct. — feuillet neutre", octa: "trioctaédrique (Mg, Fe, Ni)", teSi: "Te/Si = 8", oc: "Oc = 12/12", espace: "stable (9,35 Å)", charge: "0", fiche: "talc",
        note: "Le talc : le jumeau magnésien de la pyrophyllite. Feuillets neutres qui glissent les uns sur les autres — dureté 1, le minéral le plus tendre de l'échelle de Mohs.",
        especes: ["talc_e", "minnesotaite", "willemseite"] },
      { nom: "2:1 trioct. — charge octaédrique (smectites)", octa: "trioctaédrique (Mg, Li)", teSi: "Te/Si = 8", oc: "Oc < 12/12", espace: "variable (9,7 → 15,6 Å ; dans l'eau 19 à 40 Å et plus)", charge: "0,2 – 0,6", fiche: "smectites",
        note: "La charge naît de lacunes ou de substitutions dans le feuillet octaédrique magnésien. Gonflement spectaculaire : l'hectorite au lithium est très utilisée en cosmétique.",
        especes: ["stevensite", "hectorite"] },
      { nom: "2:1 trioct. — charge tétraédrique (smectites)", octa: "trioctaédrique (Mg, Zn)", teSi: "Te/Si < 8", oc: "Oc = 12/12", espace: "variable", charge: "0,2 – 0,6", fiche: "smectites",
        note: "L'aluminium remplace le silicium dans le feuillet tétraédrique. La saponite (« argile à savon ») est LA smectite des basaltes, gabbros et serpentinites altérés.",
        especes: ["saponite", "sauconite", "swinefordite"] },
      { nom: "2:1 trioct. — vermiculite", octa: "trioctaédrique (Mg, Fe, Ni)", teSi: "Te/Si < 8", oc: "Oc < 12/12", espace: "variable, bridé (14,4 Å à l'air, 14,8 Å dans l'eau)", charge: "0,6 – 0,9", fiche: "vermiculite",
        note: "La forme la plus courante de la vermiculite : née de la biotite qui perd son potassium. C'est elle qu'on exfolie à 900 °C en accordéons dorés pour l'horticulture.",
        especes: ["vermiculite_e"] },
      { nom: "2:1 trioct. — micas", octa: "trioctaédrique (Mg, Fe, Li)", teSi: "Te/Si < 8", oc: "Oc = 12/12", espace: "stable (10 Å, verrouillé au K⁺)", charge: "0,6 – 2", fiche: "illite",
        note: "Les micas sombres : la série biotite (phlogopite magnésien ↔ annite ferreux), les micas au lithium, et le mica « dur » calcique. Ce sont les parents directs des vermiculites.",
        especes: ["phlogopite", "biotite_e", "annite", "lepidolite", "zinnwaldite", "clintonite"] },
    ],
  },
  {
    famille: "Argiles 2:1:1 (T-O-T-O) — chlorites, espacement 14 Å",
    desc: "Un sandwich T-O-T dont l'espace interfoliaire est occupé par un feuillet continu d'hydroxydes (type brucite) : tout est verrouillé. Quatre cas selon que le feuillet T-O-T ET le feuillet brucitique sont di- ou trioctaédriques.",
    groupes: [
      { nom: "2:1:1 — T-O-T dioct. / brucitique dioct.", octa: "dioctaédrique / dioctaédrique", teSi: "Te/Si < 8", oc: "Al dominant", espace: "stable (14 Å)", charge: "neutralisée", fiche: "chlorite",
        note: "La seule chlorite entièrement dioctaédrique : tout aluminium, des deux côtés. Altérations hydrothermales acides.",
        especes: ["donbassite"] },
      { nom: "2:1:1 — T-O-T dioct. / brucitique trioct.", octa: "dioctaédrique / trioctaédrique", teSi: "Te/Si < 8", oc: "Al + (Mg, Li)", espace: "stable (14 Å)", charge: "neutralisée", fiche: "chlorite",
        note: "Les chlorites « mixtes » (di-trioctaédriques) : marqueurs du métamorphisme de très bas degré et des pegmatites au lithium.",
        especes: ["cookeite", "sudoite"] },
      { nom: "2:1:1 — T-O-T trioct. / brucitique dioct.", octa: "trioctaédrique / dioctaédrique", teSi: "Te/Si < 8", oc: "Mn, Zn", espace: "stable (14 Å)", charge: "neutralisée", fiche: "chlorite",
        note: "Le cas inverse, rarissime : une seule espèce le représente, connue presque uniquement du gisement de Franklin (New Jersey).",
        especes: ["franklinfurnaceite"] },
      { nom: "2:1:1 — T-O-T trioct. / brucitique trioct.", octa: "trioctaédrique / trioctaédrique", teSi: "Te/Si < 8", oc: "Mg, Fe, Mn, Ni, Zn", espace: "stable (14 Å)", charge: "neutralisée", fiche: "chlorite",
        note: "Les vraies chlorites, de loin les plus courantes : celles qui verdissent schistes, ardoises et « pierres vertes » alpines. Elles se déclinent selon le cation dominant.",
        especes: ["clinochlore", "chamosite", "pennantite", "nimite", "baileychlore"] },
    ],
  },
  {
    famille: "Interstratifiés — empilements mixtes",
    desc: "Deux types de feuillets alternent dans un même cristal, régulièrement (R1 : ABAB) ou au hasard (R0). Les instantanés des transformations en cours.",
    groupes: [
      { nom: "Interstratifiés réguliers et irréguliers", octa: "selon les termes mélangés", charge: "mixte", fiche: "interstratifies",
        note: "Les plus courants : illite/smectite (I/S). Quelques alternances régulières ont reçu un nom d'espèce.",
        especes: ["rectorite", "corrensite", "hydrobiotite", "aliettite", "tosudite", "kaolinite_smectite"] },
    ],
  },
  {
    famille: "Argiles fibreuses — rubans 2:1 à canaux",
    desc: "Les feuillets 2:1 sont découpés en rubans alternés, ménageant des canaux remplis d'eau : structure en « tôle ondulée » et pouvoir absorbant énorme.",
    groupes: [
      { nom: "Groupe sépiolite-palygorskite", octa: "trioctaédrique (Mg) à mixte", charge: "faible", fiche: "sepiolite",
        note: "Néoformées en milieux évaporitiques et lacustres alcalins riches en Mg et Si.",
        especes: ["sepiolite_e", "palygorskite"] },
    ],
  },
  {
    famille: "Para-cristallins — nano-argiles sans feuillets",
    desc: "À la frontière des argiles : pas de vrai empilement, mais des sphérules et nanotubes alumino-silicatés. Les premiers-nés de l'altération des verres volcaniques.",
    groupes: [
      { nom: "Allophane et imogolite", octa: "—", charge: "variable selon le pH", fiche: "allophane",
        note: "Constituants clés des andosols (sols volcaniques jeunes) : surfaces colossales, charges dépendantes du pH.",
        especes: ["allophane_e", "imogolite", "hisingerite"] },
    ],
  },
];

// ---------- 4 nouvelles fiches complètes ----------
ARGILES.push(
  {
    id: "serpentines", nom: "Serpentines (chrysotile, antigorite…)", swatch: "#4f7057",
    formule: "Mg₃Si₂O₅(OH)₄",
    type: "1:1 (T-O) trioctaédrique", espacement: "7,3 Å — fixe", chargeFoliaire: "≈ 0",
    cecMin: 2, cecMax: 10, surfMin: 10, surfMax: 40, eauMin: 10, eauMax: 30,
    gonflement: "Nul", gonflementNiveau: 0,
    description: "Les cousines magnésiennes de la kaolinite : même architecture 1:1, mais le feuillet octaédrique est rempli de magnésium (trioctaédrique). Le léger désaccord de taille entre les deux feuillets les force à se courber — d'où trois espèces selon la solution adoptée : feuillets plans (lizardite), ondulés (antigorite) ou enroulés en fibres (chrysotile, l'amiante blanc).",
    origine: "Transformation (hydratation)",
    origineDetail: "Nées de l'hydratation de l'olivine et des pyroxènes par l'eau de mer dans le plancher océanique (serpentinisation) ou par les fluides métamorphiques — une transformation qui dégage de l'hydrogène et fait gonfler la roche. Dans les sols, elles sont héritées des serpentinites, puis se transforment lentement en smectites magnésiennes.",
    contexte: "Serpentinites du Queyras, du Chenaillet, du Cap Corse et du Limousin ; auréoles des péridotites ariégeoises. Signature d'un ancien manteau hydraté, le plus souvent par l'eau de mer.",
    pedologie: "CEC très faible, pas de gonflement. Les sols sur serpentine sont chimiquement hostiles : trop de Mg et de Ni, pas assez de Ca — d'où une flore « serpentinicole » endémique et clairsemée, d'intérêt pour les botanistes.",
    rochesSources: ["peridotite", "serpentinite"],
    usages: "Chrysotile = amiante (usage interdit en France depuis 1997) ; pierre ollaire pour poêles et sculptures ; granulats.",
    wikipedia: "https://fr.wikipedia.org/wiki/Serpentine_(min%C3%A9ral)",
    interfoliaire: "liaisons hydrogène",
    famille: "Famille 1:1 (T-O)", groupe: "Groupe des serpentines",
  },
  {
    id: "talc", nom: "Talc & pyrophyllite", swatch: "#cfd6cd",
    formule: "Mg₃Si₄O₁₀(OH)₂ (talc) · Al₂Si₄O₁₀(OH)₂ (pyrophyllite)",
    type: "2:1 (T-O-T) neutre", espacement: "9,2 Å (pyrophyllite) à 9,35 Å (talc) — fixe", chargeFoliaire: "0",
    cecMin: 1, cecMax: 5, surfMin: 3, surfMax: 20, eauMin: 5, eauMax: 15,
    gonflement: "Nul", gonflementNiveau: 0,
    description: "Le degré zéro de l'argile 2:1 : des feuillets parfaitement neutres, sans cation interfoliaire, qui ne tiennent ensemble que par de faibles forces de van der Waals. Résultat : les feuillets glissent les uns sur les autres — le talc est le minéral le plus tendre de l'échelle de Mohs (dureté 1) et laisse ce toucher savonneux caractéristique.",
    origine: "Transformation (métasomatose)",
    origineDetail: "Le talc naît de la transformation hydrothermale de roches magnésiennes : serpentinites, ou dolomies traversées par des fluides siliceux. Le gisement de Trimouns, au-dessus de Luzenac (Ariège), où des fluides ont « talcifié » dolomies et micaschistes, est la plus grande carrière de talc du monde (~8 % de la production mondiale).",
    contexte: "Zones de cisaillement des massifs métamorphiques (Pyrénées, Alpes) ; auréoles des serpentinites.",
    pedologie: "Marginal dans les sols (il y est hérité et s'y comporte comme un limon inerte) : CEC quasi nulle, aucune rétention utile.",
    rochesSources: ["serpentinite", "dolomie", "micaschiste"],
    usages: "Poudres cosmétiques, charge du papier et des peintures, céramiques, lubrifiant solide — le crayon du soudeur est en talc (« craie de Briançon »).",
    wikipedia: "https://fr.wikipedia.org/wiki/Talc",
    interfoliaire: "rien — forces de van der Waals",
    famille: "Famille 2:1 (T-O-T)", groupe: "Groupe talc-pyrophyllite",
  },
  {
    id: "sepiolite", nom: "Sépiolite & palygorskite", swatch: "#d9cdb4",
    formule: "Mg₄Si₆O₁₅(OH)₂·6H₂O · (Mg,Al)₂Si₄O₁₀(OH)·4H₂O",
    type: "2:1 en rubans (fibreuse)", espacement: "canaux de ≈ 4 × 10 Å", chargeFoliaire: "faible",
    cecMin: 10, cecMax: 40, surfMin: 150, surfMax: 320, eauMin: 80, eauMax: 250,
    gonflement: "Nul (mais absorption énorme dans les canaux)", gonflementNiveau: 0,
    description: "Les argiles « tôle ondulée » : les feuillets 2:1 sont découpés en rubans qui s'inversent périodiquement, ménageant des canaux ouverts remplis d'eau. Pas de gonflement, mais une capacité d'absorption spectaculaire dans les canaux et entre les fibres — la sépiolite sèche est si poreuse qu'elle flotte (« écume de mer »).",
    origine: "Néoformation",
    origineDetail: "Néoformées dans les milieux où silice et magnésium abondent sans aluminium : lacs alcalins, croûtes calcaires, bassins évaporitiques. La palygorskite (= attapulgite) de Mormoiron (Vaucluse) a été exploitée comme « terre à foulon » pour dégraisser la laine ; les terres absorbantes du Midi en contiennent.",
    contexte: "Rares en France métropolitaine actuelle (climat trop humide : pluie > 65 % de l'ETP presque partout) : paléosols et bassins tertiaires du Midi, croûtes calcaires. Abondantes en Espagne (Vallecas) et au Sénégal.",
    pedologie: "Argiles des sols steppiques et des croûtes calcaires ; leur présence dans un paléosol = signal d'aridité. CEC modeste mais surfaces énormes.",
    rochesSources: ["calcaire", "marne", "dolomie"],
    usages: "Litières pour chats, absorbants industriels (sols d'ateliers), terres décolorantes des huiles, boues de forage en eau salée, pipes d'écume de mer — et le fameux Bleu Maya (indigo + palygorskite).",
    wikipedia: "https://fr.wikipedia.org/wiki/S%C3%A9piolite",
    interfoliaire: "canaux remplis d'eau",
    famille: "Argiles fibreuses", groupe: "Groupe sépiolite-palygorskite",
  },
  {
    id: "allophane", nom: "Allophane & imogolite", swatch: "#b3927a",
    formule: "Al₂O₃·(SiO₂)₁,₃₋₂·(2,5–3)H₂O · Al₂SiO₃(OH)₄",
    type: "Para-cristallin (sphérules & nanotubes)", espacement: "— (pas d'empilement)", chargeFoliaire: "variable selon le pH",
    cecMin: 10, cecMax: 50, surfMin: 700, surfMax: 1100, eauMin: 100, eauMax: 300,
    gonflement: "Nul (mais rétention d'eau colossale)", gonflementNiveau: 0,
    description: "Les « bébés argiles » des sols volcaniques : des sphérules creuses de 4 nanomètres (allophane) et des nanotubes de 2 nm (imogolite), sans ordre cristallin à longue distance. Leur surface développée — jusqu'à plus de 1 000 m² par gramme ! — dépasse tout ce que font les vraies argiles. Leur charge électrique change avec le pH (charges « variables ») — un comportement unique.",
    origine: "Néoformation (ultra-rapide)",
    origineDetail: "Premiers produits de l'hydrolyse des verres volcaniques : quelques siècles à quelques millénaires suffisent. Ils évoluent ensuite, en quelques dizaines de milliers d'années, vers halloysite puis kaolinite (climat drainé) ou smectites (climat confiné). Les sols de la chaîne des Puys, jeunes de moins de 100 000 ans, en sont truffés.",
    contexte: "Andosols du Massif central (chaîne des Puys, Cantal, Aubrac), sols sur pouzzolanes et cendres.",
    pedologie: "Rétention d'eau énorme (les andosols restent humides et légers, toucher « savonneux »), forte rétention du phosphore (jusqu'à le rendre indisponible pour les plantes — le revers de la médaille), stabilisation spectaculaire de la matière organique : les andosols sont parmi les sols les plus riches en carbone de France.",
    rochesSources: ["basalte", "pouzzolane", "trachyandesite", "trachyte"],
    usages: "Pas d'usage industriel direct ; étudiés pour la dépollution (leur surface piège métaux et phosphates).",
    wikipedia: "https://fr.wikipedia.org/wiki/Allophane",
    interfoliaire: "— (pas d'empilement)",
    famille: "Para-cristallins", groupe: "Allophane et imogolite",
  }
);

// ---------- rattachement des fiches à la classification ----------
// Chaque fiche porte les CRITÈRES STRUCTURAUX qui caractérisent son groupe
// (octa, Te/Si, Oc, espacement) — ceux-là mêmes qui découpent le tableau de Wikipédia.
const ARGILE_EXTRAS = {
  kaolinite: { famille: "Argiles 1:1 (T-O)", groupe: "1:1 dioctaédrique",
    octa: "dioctaédrique (Al)", teSi: "Te/Si = 4 (aucune substitution)", oc: "Oc = 12/12 (aucune substitution)",
    especes: ["kaolinite_e", "dickite", "nacrite", "halloysite"] },
  serpentines: { famille: "Argiles 1:1 (T-O)", groupe: "1:1 trioctaédrique",
    octa: "trioctaédrique (Mg, Fe, Ni)", teSi: "Te/Si = 4 à < 4", oc: "Oc = 12/12 à > 12/12",
    especes: ["chrysotile", "antigorite", "lizardite", "berthierine", "greenalite", "cronstedtite", "amesite", "nepouite", "odinite"] },
  talc: { famille: "Argiles 2:1 (T-O-T)", groupe: "2:1 à feuillet neutre",
    octa: "trioctaédrique (talc) / dioctaédrique (pyrophyllite)", teSi: "Te/Si = 8 (aucune substitution)", oc: "Oc = 12/12 (aucune substitution)",
    especes: ["talc_e", "minnesotaite", "willemseite", "pyrophyllite", "ferripyrophyllite"] },
  smectites: { famille: "Argiles 2:1 (T-O-T)", groupe: "2:1 à charge faible (gonflantes)",
    octa: "di- et trioctaédriques", teSi: "Te/Si = 8 (charge octa.) ou < 8 (charge tétra.)", oc: "Oc < 12/12 ou = 12/12 selon le cas",
    especes: ["montmorillonite", "volkonskoite", "beidellite", "nontronite", "stevensite", "hectorite", "saponite", "sauconite", "swinefordite"] },
  vermiculite: { famille: "Argiles 2:1 (T-O-T)", groupe: "2:1 à charge forte",
    octa: "trioctaédrique surtout (formes dioct. dans les sols)", teSi: "Te/Si < 8", oc: "Oc < 12/12",
    especes: ["vermiculite_e"] },
  illite: { famille: "Argiles 2:1 (T-O-T)", groupe: "2:1 micas et illites",
    octa: "di- et trioctaédriques", teSi: "Te/Si < 8", oc: "Oc = 12/12",
    especes: ["illite_e", "brammallite", "sericite", "glauconite_e", "celadonite", "muscovite_e", "paragonite", "margarite",
              "phlogopite", "biotite_e", "annite", "lepidolite", "zinnwaldite", "clintonite"] },
  chlorite: { famille: "Argiles 2:1:1 (T-O-T-O)", groupe: "2:1:1 chlorites",
    octa: "trioctaédrique surtout (donbassite : dioct.)", teSi: "Te/Si < 8", oc: "variable selon le cation",
    especes: ["clinochlore", "chamosite", "pennantite", "nimite", "baileychlore", "sudoite", "cookeite", "donbassite", "franklinfurnaceite"] },
  interstratifies: { famille: "Interstratifiés", groupe: "Empilements mixtes",
    octa: "selon les termes mélangés", teSi: "mixte", oc: "mixte",
    especes: ["rectorite", "corrensite", "hydrobiotite", "aliettite", "tosudite", "kaolinite_smectite"] },
  // La glauconite est une ESPÈCE du groupe des micas/illites (pas un groupe à part).
  glauconite: { famille: "Argiles 2:1 (T-O-T)", groupe: "2:1 micas et illites",
    espece: "glauconite_e",
    octa: "dioctaédrique (Fe³⁺)", teSi: "Te/Si < 8", oc: "Oc = 12/12",
    especes: ["illite_e", "brammallite", "celadonite", "sericite"] },
  sepiolite: { famille: "Argiles fibreuses", groupe: "Rubans 2:1 à canaux",
    octa: "trioctaédrique (Mg) à mixte", teSi: "—", oc: "—",
    especes: ["sepiolite_e", "palygorskite"] },
  allophane: { famille: "Para-cristallins", groupe: "Sphérules et nanotubes",
    octa: "—", teSi: "—", oc: "—",
    especes: ["allophane_e", "imogolite", "hisingerite"] },
};
ARGILES.forEach((a) => { if (ARGILE_EXTRAS[a.id]) Object.assign(a, ARGILE_EXTRAS[a.id]); });

// ---------- les roches volcaniques et ultrabasiques produisent aussi ces argiles ----------
ROCHE_EXTRAS.basalte.argiles.push("allophane");
ROCHE_EXTRAS.pouzzolane.argiles.push("allophane");
ROCHE_EXTRAS.trachyandesite.argiles.push("allophane");
ROCHE_EXTRAS.peridotite.argiles.push("serpentines");
ROCHE_EXTRAS.serpentinite.argiles.unshift("serpentines");
ROCHE_EXTRAS.serpentinite.argiles.push("talc");
ROCHE_EXTRAS.dolomie.argiles.push("sepiolite");
