// ============================================================
// CLASSIFICATION GÉNÉRALE DES MINÉRAUX — extension de l'atlas
// Nouveaux minéraux (silicates par sous-classes + les autres
// classes chimiques) et arbre MIN_CLASSIF pour la page dédiée.
// Chargé après mineraux.js (complète MINERAUX) et avant app.js.
// ============================================================

Object.assign(MINERAUX, {
  // ---------- Nésosilicates (tétraèdres isolés) ----------
  zircon: {
    nom: "Zircon", formule: "ZrSiO₄", famille: "Nésosilicate (groupe du zircon)", durete: 7.5, densite: 4.65,
    systeme: "quadratique", clivage: "imparfait", eclat: "adamantin à gras",
    couleurs: "brun-rouge, incolore, jaune, bleu (chauffé)",
    contexte: "Accessoire de presque tous les granites et gneiss ; se concentre dans les placers et sables lourds.",
    stabilite: 10, swatch: "#c8a878",
    devient: "Rien : il traverse l'altération, l'érosion et même la fusion des roches. Se concentre dans les placers.",
    note: "Le grand survivant de la minéralogie : les plus vieux objets terrestres connus sont des zircons australiens de 4,4 milliards d'années. Son réseau piège l'uranium à sa formation — c'est LE chronomètre de la géologie (datation U-Pb).",
  },
  disthene: {
    nom: "Disthène (cyanite)", formule: "Al₂SiO₅", famille: "Nésosubsilicate (silicate d'alumine)", durete: 5.5, densite: 3.6,
    systeme: "triclinique", clivage: "parfait", eclat: "vitreux à nacré",
    couleurs: "bleu acier, bleu-gris, parfois vert",
    contexte: "Micaschistes et éclogites : c'est le polymorphe de HAUTE PRESSION de Al₂SiO₅.",
    stabilite: 8, swatch: "#6f8fc9",
    devient: "Résiduel, puis très lentement argiles alumineuses.",
    note: "Lames bleu acier des micaschistes : le polymorphe haute pression de Al₂SiO₅. Sa curiosité : une dureté double selon la direction où on le raye (4-5 le long du cristal, 6-7 en travers) — d'où son nom (« double force »).",
  },
  andalousite: {
    nom: "Andalousite", formule: "Al₂SiO₅", famille: "Nésosubsilicate (silicate d'alumine)", durete: 6.75, densite: 3.15,
    systeme: "orthorhombique", clivage: "bon", eclat: "vitreux",
    couleurs: "rose-brun, gris-vert ; la chiastolite dessine une croix noire",
    contexte: "Métamorphisme de CONTACT (basse pression) : cornéennes. Mine de Glomel (Côtes-d'Armor).",
    stabilite: 8, swatch: "#b06a5a",
    devient: "Résiduelle, puis argiles (séricite en profondeur).",
    note: "Le polymorphe basse pression de Al₂SiO₅, typique du métamorphisme de contact. Sa variété chiastolite dessine une croix noire dans le cristal. La mine de Glomel (Côtes-d'Armor) est le premier producteur mondial — pour les céramiques réfractaires.",
  },
  sillimanite: {
    nom: "Sillimanite", formule: "Al₂SiO₅", famille: "Nésosubsilicate (silicate d'alumine)", durete: 7, densite: 3.24,
    systeme: "orthorhombique", clivage: "parfait", eclat: "soyeux (en fibres) à vitreux",
    couleurs: "blanc, gris, brun pâle",
    contexte: "Gneiss et migmatites : c'est le polymorphe de HAUTE TEMPÉRATURE de Al₂SiO₅.",
    stabilite: 8, swatch: "#cbb8a0",
    devient: "Résiduelle, puis très lentement argiles.",
    note: "Le polymorphe haute température de Al₂SiO₅, en aiguilles soyeuses dans les gneiss les plus cuits. Le trio disthène-andalousite-sillimanite est le baromètre-thermomètre favori des métamorphistes.",
  },
  staurotide: {
    nom: "Staurotide (staurolite)", formule: "Fe²⁺₂Al₉Si₄O₂₃(OH)", famille: "Nésosubsilicate", durete: 7.25, densite: 3.75,
    systeme: "monoclinique (pseudo-orthorhombique)", clivage: "médiocre", eclat: "vitreux à résineux",
    couleurs: "brun-rouge sombre, brun-noir",
    contexte: "Micaschistes de degré moyen. Croisettes de Coadry et Baud (Bretagne).",
    stabilite: 8, swatch: "#7a4a3a",
    devient: "Résiduelle (sables), puis oxydes de fer + argiles.",
    note: "Ses macles en croix — les « croisettes de Bretagne » de Coadry et Baud — ont servi d'amulettes et de bénitiers de poche. Minéral index du métamorphisme moyen des micaschistes.",
  },
  topaze: {
    nom: "Topaze", formule: "Al₂SiO₄(F,OH)₂", famille: "Nésosubsilicate fluoré", durete: 8, densite: 3.55,
    systeme: "orthorhombique", clivage: "parfait (basal)", eclat: "vitreux",
    couleurs: "incolore, jaune miel, bleu, rose (chauffée)",
    contexte: "Greisens et pegmatites : là où les vapeurs fluorées ont « cuit » le granite (Échassières, Allier).",
    stabilite: 9, swatch: "#e8d8b0",
    devient: "Résiduelle ; très lentement argiles fluorées.",
    note: "L'étalon de dureté 8 de l'échelle de Mohs. Cristallise dans les greisens et pegmatites, quand les vapeurs fluorées « cuisent » le granite (Échassières, Allier).",
  },
  titanite: {
    nom: "Titanite (sphène)", formule: "CaTiSiO₅", famille: "Nésosubsilicate (groupe de la titanite)", durete: 5.25, densite: 3.5,
    systeme: "monoclinique", clivage: "net", eclat: "adamantin à résineux",
    couleurs: "brun-miel, vert, jaune — fort éclat, forte dispersion",
    contexte: "Accessoire des granites, syénites et gneiss. Source principale du titane des sols.",
    stabilite: 6, swatch: "#b8a04a",
    devient: "→ anatase + leucoxène (poussière de TiO₂) : la source du titane des sols.",
    note: "Petits coins brun-miel accessoires des granites et gneiss. En s'altérant, elle libère le titane qui reprécipite aussitôt en oxydes TiO₂ microscopiques — le titane ne voyage jamais loin.",
  },
  // ---------- Sorosilicates (tétraèdres en paires) ----------
  epidote: {
    nom: "Épidote (pistachite)", formule: "Ca₂(Al,Fe³⁺)₃(SiO₄)(Si₂O₇)O(OH)", famille: "Sorosilicate (groupe de l'épidote)", durete: 6.5, densite: 3.45,
    systeme: "monoclinique", clivage: "parfait", eclat: "vitreux",
    couleurs: "vert pistache caractéristique, vert-jaune, vert-noir",
    contexte: "Faciès des schistes verts, skarns, fentes alpines, basaltes altérés.",
    stabilite: 6, swatch: "#8a9a4a",
    devient: "→ argiles + oxydes de fer + Ca²⁺ dissous.",
    note: "Le vert pistache des roches métamorphiques de bas degré (faciès « schistes verts ») et des fissures alpines. Sa famille (zoïsite, clinozoïsite, allanite à terres rares) partage la même charpente à tétraèdres jumelés.",
  },
  // ---------- Cyclosilicates (anneaux) ----------
  beryl: {
    nom: "Béryl", formule: "Be₃Al₂(Si₆O₁₈)", famille: "Cyclosilicate (groupe du béryl)", durete: 7.75, densite: 2.7,
    systeme: "hexagonal", clivage: "imparfait", eclat: "vitreux",
    couleurs: "vert (émeraude), bleu (aigue-marine), rose (morganite), jaune (héliodore), incolore (goshénite)",
    contexte: "Pegmatites granitiques et greisens ; les émeraudes, elles, naissent au contact de roches ultrabasiques.",
    stabilite: 9, swatch: "#7fc9b0",
    devient: "Résiduel ; très lentement argiles + béryllium dispersé.",
    note: "Anneaux de six tétraèdres empilés en canaux. Vert chrome = émeraude, bleu = aigue-marine. Les pegmatites du Limousin et du Morvan en ont livré de beaux cristaux — et le béryllium industriel.",
  },
  tourmaline: {
    nom: "Schorl (tourmaline noire)", formule: "NaFe²⁺₃Al₆(Si₆O₁₈)(BO₃)₃(OH)₄", famille: "Cyclosilicate (groupe de la tourmaline)", durete: 7.25, densite: 3.1,
    systeme: "rhomboédrique", clivage: "aucun (cassure conchoïdale)", eclat: "vitreux",
    couleurs: "noir profond — baguettes striées à section triangulaire arrondie",
    contexte: "Granites, pegmatites, greisens : c'est la tourmaline la plus commune, plus de 95 % du groupe.",
    stabilite: 9, swatch: "#2f3a35",
    devient: "Résiduelle : baguettes noires des sables et arènes.",
    note: "Le grand réservoir de bore de la croûte. Baguettes noires striées des granites et pegmatites, piézoélectrique (elle se charge quand on la chauffe ou la comprime). Quasi inaltérable : marqueur de provenance dans les sables.",
  },
  cordierite: {
    nom: "Cordiérite (iolite)", formule: "Mg₂Al₄Si₅O₁₈", famille: "Cyclosilicate (groupe de la cordiérite)", durete: 7, densite: 2.65,
    systeme: "orthorhombique", clivage: "médiocre", eclat: "vitreux",
    couleurs: "bleu-violet à gris — change de couleur selon l'angle (fort pléochroïsme)",
    contexte: "Cornéennes du métamorphisme de contact et gneiss alumineux (basse pression).",
    stabilite: 5, swatch: "#5a6fa8",
    devient: "→ « pinite » (mélange de muscovite fine et chlorite), puis argiles.",
    note: "Son pléochroïsme est spectaculaire : la même pierre paraît bleu-violet vue sous un angle, jaune pâle sous un autre. Cette propriété lui vaut une légende tenace — les navigateurs vikings s'en seraient servis comme « pierre de soleil » : en la faisant tourner devant le ciel, la lumière polarisée révèle la position du soleil même à travers les nuages. Nommée d'après le géologue français Louis Cordier.",
  },
  // ---------- Inosilicates (chaînes) ----------
  wollastonite: {
    nom: "Wollastonite", formule: "CaSiO₃", famille: "Inosilicate — pyroxénoïde", durete: 4.75, densite: 2.93,
    systeme: "triclinique", clivage: "parfait selon deux directions → débit en aiguilles", eclat: "vitreux à nacré, soyeux sur les fibres",
    couleurs: "blanc, gris, parfois rosé ou brunâtre", stabilite: 3, swatch: "#e2ddd2",
    contexte: "Skarns et marbres siliceux : au contact d'un granite qui cuit un calcaire impur.",
    devient: "→ calcite + silice dissoute (carbonatation rapide).",
    note: "Née de la cuisson d'un calcaire au contact d'un granite (skarn) : CaCO₃ + SiO₂ → CaSiO₃ + CO₂. Aiguilles blanches utilisées dans céramiques et plastiques. C'est un PYROXÉNOÏDE : même principe de chaîne simple que les pyroxènes, mais la chaîne se répète tous les 3 tétraèdres au lieu de 2 — ce qui la fait ranger à part dans la classification de Strunz.",
  },
  actinote: {
    nom: "Actinote (actinolite)", formule: "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂", famille: "Inosilicate — amphibole calcique", durete: 5.5, densite: 3.05,
    systeme: "monoclinique", clivage: "parfait à ~56°/124° (deux directions)", eclat: "vitreux à soyeux sur les fibres",
    couleurs: "vert à vert sombre, vert-gris", stabilite: 3, swatch: "#5f8f6f",
    contexte: "Schistes verts : métamorphisme régional de basse pression des roches basiques.",
    devient: "→ chlorite, puis smectites + oxydes de fer.",
    note: "Amphibole verte fibreuse des schistes verts, en série continue avec la trémolite (elle en est le pôle ferreux). Ses variétés fibreuses comptent parmi les amiantes réglementés ; sa forme massive compacte est la néphrite, l'un des deux jades.",
  },
  glaucophane: {
    nom: "Glaucophane", formule: "Na₂(Mg,Fe)₃Al₂Si₈O₂₂(OH)₂", famille: "Inosilicate — amphibole sodique", durete: 6, densite: 3.1,
    systeme: "monoclinique", clivage: "parfait à ~56°/124° (deux directions)", eclat: "vitreux à nacré",
    couleurs: "bleu lavande à bleu-noir", stabilite: 4, swatch: "#4a5a9a",
    contexte: "Schistes bleus des zones de subduction (haute pression, basse température).",
    devient: "→ chlorite + albite lors de la remontée, puis argiles.",
    note: "L'amphibole bleu lavande des « schistes bleus » : elle ne se forme que sous très haute pression et basse température, dans les zones de subduction. L'île de Groix en est le musée français à ciel ouvert.",
  },
  // ---------- Tectosilicates supplémentaires ----------
  microcline: {
    nom: "Microcline", formule: "KAlSi₃O₈", famille: "Tectosilicate — feldspath alcalin", durete: 6.25, densite: 2.56,
    systeme: "triclinique", clivage: "parfait {001} et bon {010} (fines macles en quadrillage)", eclat: "vitreux",
    couleurs: "blanc, rose, jaune ; vert turquoise (amazonite)",
    contexte: "Granites, pegmatites, gneiss — le feldspath K des roches lentement refroidies.",
    stabilite: 7, swatch: "#d8b8a8",
    devient: "Hydrolyse → kaolinite ou illite + K⁺ et silice en solution.",
    note: "Le troisième visage du feldspath potassique (avec orthose et sanidine) : le polymorphe de basse température, le mieux ordonné, reconnaissable à ses fines macles en quadrillage. Sa variété vert turquoise est l'amazonite des pegmatites.",
  },
  nepheline: {
    nom: "Néphéline", formule: "(Na,K)AlSiO₄", famille: "Tectosilicate — feldspathoïde", durete: 5.75, densite: 2.6,
    systeme: "hexagonal", clivage: "médiocre", eclat: "vitreux à gras",
    couleurs: "incolore, blanc, gris, jaunâtre ; aspect graisseux",
    contexte: "Roches alcalines pauvres en silice : phonolites, syénites néphéliniques.",
    stabilite: 2, swatch: "#d5cfc2",
    devient: "→ zéolites (analcime) puis argiles, très vite.",
    note: "Le feldspathoïde type : un « feldspath sans assez de silice », qui ne coexiste jamais avec le quartz. Dans les phonolites du Velay. Pauvre en silice, elle s'hydrolyse bien plus vite que les feldspaths.",
  },
  leucite: {
    nom: "Leucite", formule: "KAlSi₂O₆", famille: "Tectosilicate — feldspathoïde", durete: 5.75, densite: 2.47,
    systeme: "quadratique (pseudo-cubique)", clivage: "très médiocre", eclat: "vitreux à terne",
    couleurs: "blanc, gris cendré, incolore",
    contexte: "Laves ultra-potassiques pauvres en silice (Vésuve, Latium).",
    stabilite: 2, swatch: "#ddd5c5",
    devient: "→ analcime puis argiles ; libère beaucoup de K⁺.",
    note: "Cristaux blancs en trapézoèdres (icositétraèdres) des laves ultra-potassiques. Sa richesse en potassium fait des sols sur ces laves des terres légendaires de fertilité — les vignes du Vésuve.",
  },
  analcime: {
    nom: "Analcime", formule: "NaAlSi₂O₆·H₂O", famille: "Zéolithe", durete: 5.25, densite: 2.26,
    systeme: "cubique", clivage: "très médiocre", eclat: "vitreux",
    couleurs: "incolore, blanc, gris, rosé",
    contexte: "Bulles des basaltes altérés, roches alcalines, sédiments.",
    stabilite: 3, swatch: "#d8d0c8",
    devient: "→ argiles ; échange ses cations avec l'eau en attendant.",
    note: "À la charnière du feldspathoïde et de la zéolithe : charpente ouverte parcourue de canaux où l'eau et les cations circulent librement, en beaux trapézoèdres. Tapisse les bulles des basaltes altérés ; les zéolithes industrielles adoucissent l'eau des lessives sur ce principe.",
  },
  // ---------- Carbonates supplémentaires ----------
  aragonite: {
    nom: "Aragonite", formule: "CaCO₃ (orthorhombique)", famille: "Carbonate", durete: 3.75, densite: 2.93,
    systeme: "orthorhombique", clivage: "net {010}", eclat: "vitreux",
    couleurs: "incolore, blanc, miel",
    contexte: "Coquilles, perles et nacre ; sources chaudes (pisolites de Karlovy Vary) ; ses macles pseudo-hexagonales viennent de Molina de Aragón, qui l'a nommée.",
    stabilite: 2, swatch: "#e6ddc8",
    devient: "→ calcite (recristallisation) ou dissolution complète.",
    note: "Le jumeau instable de la calcite : même formule, empilement différent. C'est elle que fabriquent coraux, nacres et coquilles d'ammonites — puis elle se réorganise en calcite dans les roches. Sources chaudes et grottes en font des « fleurs de fer ».",
  },
  siderite: {
    nom: "Sidérite", formule: "FeCO₃", famille: "Carbonate de fer", durete: 4, densite: 3.96,
    systeme: "rhomboédrique", clivage: "parfait rhomboédrique", eclat: "vitreux à nacré",
    couleurs: "brun miel à brun sombre — brunit encore en s'oxydant",
    contexte: "Gangue des filons, fers rubanés, nodules des argiles ; le « fer spathique » des vieilles mines (Allevard, en Dauphiné).",
    stabilite: 2, swatch: "#a8763e",
    devient: "Oxydation → goethite (chapeaux de fer, grès ferrugineux).",
    note: "Le carbonate du fer réduit : il ne se forme que là où l'oxygène manque (marais, sédiments confinés). À l'air, il rouille en goethite — les « fers des marais » et bien des minerais de fer historiques en dérivent.",
  },
  magnesite: {
    nom: "Magnésite", formule: "MgCO₃", famille: "Carbonate de magnésium", durete: 4, densite: 3.0,
    systeme: "rhomboédrique", clivage: "parfait rhomboédrique", eclat: "vitreux à mat",
    couleurs: "blanc, gris, jaunâtre",
    contexte: "Veines blanches dans les serpentinites altérées et amas métasomatiques ; source de magnésie réfractaire.",
    stabilite: 3, swatch: "#ded8cc",
    devient: "Dissolution lente : Mg²⁺ + HCO₃⁻.",
    note: "Carbonate de magnésium des serpentinites altérées (veines blanches « écume de terre ») et de rares dolomies transformées. C'est la magnésie des gymnastes et des réfractaires.",
  },
  rhodochrosite: {
    nom: "Rhodochrosite", formule: "MnCO₃", famille: "Carbonate de manganèse", durete: 3.75, densite: 3.7,
    systeme: "rhomboédrique", clivage: "parfait rhomboédrique", eclat: "vitreux à nacré",
    couleurs: "rose bonbon à rouge framboise",
    contexte: "Filons et amas à manganèse ; les stalactites zonées de Capillitas (Argentine) en sont l'icône.",
    stabilite: 2, swatch: "#d47a8f",
    devient: "Oxydation → oxydes noirs de manganèse (pyrolusite, birnessite).",
    note: "Le carbonate rose du manganèse réduit, superbe en bandes concentriques. Comme la sidérite, elle noircit à l'air en se transformant en oxydes de Mn — ses affleurements portent des « chapeaux » noirs.",
  },
  malachite: {
    nom: "Malachite", formule: "Cu₂CO₃(OH)₂", famille: "Carbonate de cuivre", durete: 3.75, densite: 4.0,
    systeme: "monoclinique", clivage: "parfait {-201} (rare en cristaux libres)", eclat: "soyeux (fibres) à mat",
    couleurs: "vert vif à vert sombre, en zones concentriques",
    contexte: "Chapeaux oxydés des mines de cuivre (Chessy-les-Mines en fut riche) ; pigment « vert de montagne » et pierre d'ornement des tsars.",
    stabilite: 6, swatch: "#2e8b57",
    devient: "Stable en surface — c'est déjà un minéral d'oxydation.",
    note: "Le vert éclatant des chapeaux d'oxydation des gisements de cuivre (et des toits en cuivre !). Concrétions rubanées polies depuis l'Antiquité ; Chessy, près de Lyon, fut un gisement célèbre.",
  },
  azurite: {
    nom: "Azurite", formule: "Cu₃(CO₃)₂(OH)₂", famille: "Carbonate de cuivre", durete: 3.75, densite: 3.83,
    systeme: "monoclinique", clivage: "net {011}", eclat: "vitreux",
    couleurs: "bleu azur profond",
    contexte: "Chapeaux oxydés du cuivre : la « chessylite » de Chessy-les-Mines (Rhône) fut la référence mondiale du minéral ; pigment des ciels médiévaux.",
    stabilite: 5, swatch: "#2b5aa0",
    devient: "→ malachite (hydratation) : les cristaux bleus verdissent.",
    note: "Sœur bleu profond de la malachite, un peu moins stable qu'elle. Les « chessylites » de Chessy (Rhône) sont parmi les plus beaux cristaux du monde ; pigment bleu des peintres médiévaux.",
  },
  // ---------- Sulfates supplémentaires ----------
  anhydrite: {
    nom: "Anhydrite", formule: "CaSO₄", famille: "Sulfate", durete: 3.25, densite: 2.97,
    systeme: "orthorhombique", clivage: "trois clivages pseudo-cubiques {010}{100}{001}", eclat: "vitreux à nacré",
    couleurs: "incolore, bleuté, lilas, gris",
    contexte: "Évaporites profondes du Keuper et du Muschelkalk ; n'atteint jamais la surface intacte — elle s'hydrate en gypse en gonflant.",
    stabilite: 1, swatch: "#e3ded4",
    devient: "→ gypse (hydratation, avec gonflement) ou dissolution.",
    note: "Le gypse « sec » des profondeurs. En s'hydratant près de la surface, elle gonfle de 60 % — un cauchemar de tunnelier (le tunnel du Lötschberg en sait quelque chose) et la cause de sources sulfatées.",
  },
  barytine: {
    nom: "Barytine (baryte)", formule: "BaSO₄", famille: "Sulfate", durete: 3.25, densite: 4.48,
    systeme: "orthorhombique", clivage: "parfait {001}", eclat: "vitreux à nacré",
    couleurs: "blanc, incolore, miel, bleuté — en « crêtes de coq »",
    contexte: "Filons et amas résiduels ; Chaillac (Indre) fut le grand gisement français, barytine et fluorine mêlées.",
    stabilite: 8, swatch: "#ded6c8",
    devient: "Quasi rien : insoluble, elle s'accumule en résidus.",
    note: "Si dense qu'on la confond avec un minerai métallique (« spath pesant »). Filons en crêtes de coq ; la France en a extrait à Chaillac (Indre). Alourdit les boues de forage et arrête les rayons X.",
  },
  jarosite: {
    nom: "Jarosite", formule: "KFe³⁺₃(SO₄)₂(OH)₆", famille: "Sulfate basique de fer", durete: 2.75, densite: 3.2,
    systeme: "rhomboédrique", clivage: "net {0001}", eclat: "résineux à mat",
    couleurs: "jaune ocre à brun",
    contexte: "Chapeaux acides des gisements à pyrite, terrils et drainages miniers ; détectée sur Mars par Opportunity (Meridiani Planum).",
    stabilite: 4, swatch: "#b8962e",
    devient: "→ goethite quand l'acidité se calme.",
    note: "L'ocre jaune des drainages miniers acides et des marais littoraux asséchés (sols « sulfatés acides ») : elle ne précipite qu'en dessous de pH ≈ 3. Sa détection sur Mars par Opportunity a prouvé qu'une eau acide y a coulé.",
  },
  alunite: {
    nom: "Alunite", formule: "KAl₃(SO₄)₂(OH)₆", famille: "Sulfate basique d'aluminium", durete: 3.75, densite: 2.7,
    systeme: "rhomboédrique", clivage: "net {0001}", eclat: "vitreux à nacré",
    couleurs: "blanc, gris, jaunâtre, rosé",
    contexte: "Altération acide (« alunisation ») des volcanites ; les alunières de Tolfa fournissaient l'alun des teinturiers et mégissiers.",
    stabilite: 5, swatch: "#d9cfc4",
    devient: "→ argiles + oxydes d'aluminium.",
    note: "Née des vapeurs sulfureuses qui rongent les roches volcaniques (altération « argilique avancée » des solfatares). C'est l'alun des teinturiers, exploité dès l'Antiquité (Tolfa, Italie).",
  },
  // ---------- Phosphates ----------
  apatite: {
    nom: "Apatite", formule: "Ca₅(PO₄)₃(F,OH,Cl)", famille: "Phosphate", durete: 5, densite: 3.19,
    systeme: "hexagonal", clivage: "imparfait", eclat: "vitreux à résineux",
    couleurs: "vert bouteille, bleu, violet, jaune, incolore",
    contexte: "Accessoire de presque toutes les roches magmatiques et métamorphiques ; nos os et nos dents sont de l'apatite biologique.",
    stabilite: 4, swatch: "#7aa88f",
    devient: "Dissolution lente → phosphore des sols et des rivières.",
    note: "L'étalon de dureté 5 et LE réservoir de phosphore de la planète : tout le phosphore des sols, des plantes — et de nos os (qui sont de l'apatite biologique !) — vient de sa dissolution. Accessoire dans presque toutes les roches magmatiques.",
  },
  monazite: {
    nom: "Monazite", formule: "(Ce,La,Nd,Th)PO₄", famille: "Phosphate (terres rares)", durete: 5.25, densite: 5.15,
    systeme: "monoclinique", clivage: "net {100}", eclat: "résineux à adamantin",
    couleurs: "brun rougeâtre, jaune miel, orangé",
    contexte: "Accessoire des granites et gneiss, concentrée dans les sables lourds (plages de l'Inde, du Brésil) ; minerai historique des terres rares et du thorium.",
    stabilite: 9, swatch: "#9a6b3f",
    devient: "Résiduelle : grains jaunes des placers et sables lourds.",
    note: "Le coffre-fort des terres rares (et du thorium radioactif — elle sert aussi à dater). Résistante et dense, elle se concentre dans les sables : les plages noires de l'Odet et certains placers bretons en regorgent.",
  },
  vivianite: {
    nom: "Vivianite", formule: "Fe²⁺₃(PO₄)₂·8H₂O", famille: "Phosphate hydraté de fer", durete: 1.75, densite: 2.68,
    systeme: "monoclinique", clivage: "parfait {010} — lamelles flexibles", eclat: "vitreux à nacré",
    couleurs: "incolore à peine sortie de terre, puis bleu profond à l'air",
    contexte: "Tourbières, argiles à ossements et coquilles, gangues de sidérite : le « fer bleu » qui cristallise autour des os enfouis.",
    stabilite: 2, swatch: "#3f6fb5",
    devient: "S'oxyde à l'air : incolore à l'abri, elle bleuit en s'oxydant.",
    note: "Le « fer bleu des tourbières » : elle cristallise dans les milieux gorgés d'eau riches en fer et en phosphore — tourbes, vases, autour des ossements enfouis. Fraîchement extraite elle est incolore ; l'air la fait virer au bleu de Prusse en quelques heures.",
  },
  // ---------- Sulfures supplémentaires ----------
  marcassite: {
    nom: "Marcassite", formule: "FeS₂ (orthorhombique)", famille: "Sulfure", durete: 6.25, densite: 4.9,
    systeme: "orthorhombique", clivage: "indistinct", eclat: "métallique",
    couleurs: "jaune laiton verdâtre, pâlissant",
    contexte: "Nodules rayonnés des craies (Cap Blanc-Nez) et marnes, filons de basse température.",
    stabilite: 1, swatch: "#b8a86a",
    devient: "Oxydation très rapide → sulfates de fer + acide sulfurique.",
    note: "Le jumeau instable de la pyrite : même formule, réseau différent, réactivité décuplée. Ses nodules dorés de la craie « fleurissent » en poussière sulfatée dans les tiroirs des collectionneurs — la maladie de la marcassite.",
  },
  galene: {
    nom: "Galène", formule: "PbS", famille: "Sulfure", durete: 2.5, densite: 7.5,
    systeme: "cubique", clivage: "parfait cubique {100} — se débite en petits cubes", eclat: "métallique brillant",
    couleurs: "gris de plomb",
    contexte: "Filons et amas plomb-zinc (Les Malines dans le Gard, Pontpéan en Bretagne) ; LE minerai du plomb et de l'argent qui l'accompagne.",
    stabilite: 3, swatch: "#6b7280",
    devient: "→ cérusite (carbonate) et anglésite (sulfate) de plomb.",
    note: "Cubes gris métallique brillants, si denses qu'ils étonnent toujours en main. Minerai de plomb (et d'argent) des filons de Pontgibaud et Poullaouen ; ses cristaux ont servi de détecteurs dans les premières radios « à galène ».",
  },
  blende: {
    nom: "Blende (sphalérite)", formule: "(Zn,Fe)S", famille: "Sulfure", durete: 3.75, densite: 4.05,
    systeme: "cubique", clivage: "parfait dodécaédrique {110}", eclat: "résineux à adamantin",
    couleurs: "brun miel à noir (d'autant plus sombre qu'elle est ferrifère)",
    contexte: "Filons et amas plomb-zinc (Saint-Salvy dans le Tarn fut la grande mine française) ; LE minerai du zinc.",
    stabilite: 3, swatch: "#7a5c3a",
    devient: "→ smithsonite, hémimorphite (les « calamines ») + Zn²⁺ dissous.",
    note: "LE minerai de zinc, du miel translucide au noir ferrifère — « blende » vient de l'allemand « tromper », car elle ne donnait pas le plomb promis par son éclat. Filons de Saint-Salvy (Tarn), les Malines (Gard).",
  },
  chalcopyrite: {
    nom: "Chalcopyrite", formule: "CuFeS₂", famille: "Sulfure", durete: 3.75, densite: 4.2,
    systeme: "quadratique", clivage: "indistinct", eclat: "métallique",
    couleurs: "jaune laiton, irisations bigarrées en s'altérant",
    contexte: "Filons hydrothermaux et porphyres cuprifères : le minerai de cuivre le plus répandu du monde.",
    stabilite: 2, swatch: "#c9a227",
    devient: "→ malachite, azurite et « cuivres gris » d'oxydation.",
    note: "Le premier minerai de cuivre du monde. Jaune laiton (plus jaune que la pyrite, plus tendre aussi), souvent irisée en « plumes de paon ». Son oxydation peint les affleurements en vert et bleu.",
  },
  // ---------- Halogénures ----------
  fluorine: {
    nom: "Fluorine (fluorite)", formule: "CaF₂", famille: "Halogénure", durete: 4, densite: 3.18,
    systeme: "cubique", clivage: "parfait octaédrique {111}", eclat: "vitreux",
    couleurs: "violette, verte, jaune, bleue — souvent zonée",
    contexte: "Filons de basse température : Morvan (Voltennes), Tarn (Mont-Roc), et Chaillac (Indre) où elle voisine la barytine.",
    stabilite: 5, swatch: "#7f9fd4",
    devient: "Dissolution très lente : Ca²⁺ + F⁻ (fluor des eaux).",
    note: "L'étalon de dureté 4, en cubes de toutes les couleurs (le violet domine). Grands filons du Morvan et du Tarn ; fondant de la sidérurgie (son nom vient de « fluere », couler) et source du fluor. C'est elle qui a donné son nom à la fluorescence.",
  },
  sylvite: {
    nom: "Sylvite", formule: "KCl", famille: "Halogénure", durete: 2, densite: 1.99,
    systeme: "cubique", clivage: "parfait cubique {100}", eclat: "vitreux",
    couleurs: "incolore, blanc, rouge orangé (inclusions d'hématite)",
    contexte: "Couches potassiques des bassins salifères (Alsace, Stassfurt) ; son amertume la distingue du sel gemme.",
    stabilite: 1, swatch: "#d8c8c0",
    devient: "Dissolution immédiate : K⁺ + Cl⁻.",
    note: "Le sel de potassium, encore plus soluble et rare en affleurement que la halite. Les couches de sylvinite d'Alsace ont fait tourner les Mines de Potasse (engrais) pendant un siècle. Goût amer caractéristique.",
  },
  // ---------- Éléments natifs ----------
  or_natif: {
    nom: "Or natif", formule: "Au", famille: "Élément natif", durete: 2.75, densite: 19.3,
    systeme: "cubique", clivage: "aucun (parfaitement malléable)", eclat: "métallique",
    couleurs: "jaune d'or, inaltérable",
    contexte: "Placers et filons de quartz aurifères ; orpaillé dans les gardons cévenols et l'Ariège, miné à Salsigne (Aude).",
    stabilite: 10, swatch: "#d4af37",
    devient: "Rien — l'inaltérable absolu. Se concentre en paillettes et pépites dans les placers.",
    note: "Inoxydable, insoluble, dense : l'altération des roches le libère intact et les rivières le trient par densité. On l'orpaille encore dans le Gardon, l'Ariège et l'Hérault ; Salsigne (Aude) fut la plus grande mine d'or d'Europe occidentale.",
  },
  graphite: {
    nom: "Graphite", formule: "C", famille: "Élément natif", durete: 1.5, densite: 2.2,
    systeme: "hexagonal", clivage: "parfait {0001} — feuillets glissants", eclat: "métallique gras",
    couleurs: "noir de fer à gris acier",
    contexte: "Gneiss, marbres et schistes ayant cuit de la matière organique ; la mine de crayon et le lubrifiant sec.",
    stabilite: 8, swatch: "#3b3b3b",
    devient: "Très lentement CO₂ (oxydation) ; surtout dispersé tel quel.",
    note: "Le carbone en feuillets — le cousin doux du diamant. Né de la cuisson métamorphique de matière organique, il rend gris et « graisseux » certains schistes et gneiss. Mines de crayon et lubrifiant sec.",
  },
  soufre_natif: {
    nom: "Soufre natif", formule: "S", famille: "Élément natif", durete: 2, densite: 2.07,
    systeme: "orthorhombique", clivage: "imparfait", eclat: "résineux à gras",
    couleurs: "jaune citron à jaune miel",
    contexte: "Fumerolles volcaniques, chapeaux bactériens des dômes de sel (Sicile, Texas), oxydation des sulfures.",
    stabilite: 1, swatch: "#e8d44d",
    devient: "Oxydation rapide → acide sulfurique puis sulfates (gypse).",
    note: "Cristaux jaune vif autour des fumerolles volcaniques et dans les dômes de sel, où des bactéries le fabriquent en respirant les sulfates. À l'air humide, il s'oxyde et acidifie tout son voisinage.",
  },
  // ---------- Borates (classe VI) ----------
  borax: {
    nom: "Borax", formule: "Na₂B₄O₇·10H₂O", famille: "Borate hydraté", durete: 2.25, densite: 1.71,
    systeme: "monoclinique", clivage: "parfait {100}", eclat: "vitreux, ternissant en blanc crayeux",
    couleurs: "incolore à blanc",
    contexte: "Croûtes des lacs salés boratés (Californie, Tibet, Anatolie) ; fondant des orfèvres et des verriers depuis la route de la soie.",
    stabilite: 1, swatch: "#e8e4d8",
    devient: "Dissolution rapide (très soluble).",
    note: "Le borate le plus connu, cristallisé dans les lacs salés des régions arides, pluie < 20 % de l'ETP (Californie, Turquie, désert d'Atacama). Absent de France métropolitaine ; source historique du bore, fondant et détergent.",
  },
  // ---------- Minéraux organiques (classe X) ----------
  ambre: {
    nom: "Ambre", formule: "≈ C₁₀H₁₆O", famille: "Minéral organique", durete: 2.25, densite: 1.06,
    stabilite: 3, swatch: "#c8791f",
    devient: "S'altère lentement à l'air (oxydation, craquèlement).",
    note: "Résine végétale fossilisée — un « minéral organique » (classe X de Strunz). Si léger qu'il flotte dans l'eau salée, il se charge d'électricité statique par frottement (ἤλεκτρον, elektron, en grec !). Les ambres crétacés des Charentes renferment des insectes fossiles mondialement étudiés.",
  },
});

// ---------- Arbre de classification générale ----------
// Chaque groupe liste des ids de MINERAUX. `lien` : page dédiée à ouvrir.
const MIN_CLASSIF = [
  {
    classe: "Silicates", n: 9, num: "IX", icone: "🔷",
    plus: "<p>C'est la <b>classe reine</b> : les silicates forment 92 % du volume de la croûte terrestre, et une seule brique les compose toutes — le tétraèdre <b>SiO₄</b>, un silicium au centre, quatre oxygènes aux sommets. Toute la diversité vient de la façon dont ces tétraèdres se <b>relient entre eux</b>.</p><p>Isolés, reliés seulement par des cations, ils donnent des minéraux denses mais vulnérables (<b>nésosilicates</b>) : l'olivine, cristallisée à 1 400 °C, est la première à céder en surface. Reliés en <b>chaînes</b> (inosilicates), ils font les minéraux sombres des basaltes et des gabbros — pyroxènes et amphiboles. Empilés en <b>feuillets</b> (phyllosilicates), ils donnent tout ce qui se clive en lamelles : les micas, les chlorites, et le monde entier des argiles. Reliés en <b>charpente tridimensionnelle</b> (tectosilicates), ils atteignent la solidité maximale : le quartz et les feldspaths, à eux seuls les deux tiers de la croûte.</p><p>Cette connectivité prédit directement la <b>résistance à l'altération</b> : plus le réseau est lié, plus il tient. C'est la <b>série de Goldich</b> — et son élégance est qu'elle suit exactement l'ordre inverse de la cristallisation des magmas. Ce qui s'est formé en premier, le plus chaud et le plus loin des conditions de surface, est aussi ce qui se détruit en premier une fois exposé à la pluie.</p><p>Ces six familles structurales, que Strunz code de <b>IX.A</b> (nésosilicates) à <b>IX.G</b> (zéolithes), couvrent l'immense majorité des silicates. Strunz ajoute deux tiroirs marginaux qu'on ne détaille pas ici : <b>IX.H</b>, un fourre-tout de « silicates non classés » à la structure encore indéterminée (des espèces très rares, rangées faute de mieux par leur chimie), et <b>IX.J</b>, les germanates, où le germanium remplace le silicium.</p>",
    desc: "La classe reine : ~92 % du volume de la croûte terrestre. Tout se joue sur la façon dont les tétraèdres SiO₄ se relient entre eux — isolés, en paires, en anneaux, en chaînes, en feuillets ou en charpente 3D. Plus le réseau est connecté, plus le minéral résiste à l'altération (série de Goldich).",
    groupes: [
      { nom: "Nésosilicates — tétraèdres isolés", code: "IX.A", motif: "SiO₄ indépendants, reliés par des cations",
        note: "Compacts et denses. Leur sort à l'altération dépend du cation : l'olivine (Mg, Fe) cède la première, le zircon (Zr) est immortel.",
        mineraux: ["olivine", "grenat", "zircon", "disthene", "andalousite", "sillimanite", "staurotide", "topaze", "titanite"] },
      { nom: "Sorosilicates — tétraèdres en paires", code: "IX.B", motif: "groupes Si₂O₇",
        note: "Petite classe de « tétraèdres jumeaux » : l'épidote et sa famille en sont les représentants courants.",
        mineraux: ["epidote"] },
      { nom: "Cyclosilicates — anneaux", code: "IX.C", motif: "anneaux Si₆O₁₈ (ou Si₃O₉…)",
        note: "Anneaux empilés en canaux : des minéraux durs, souvent gemmes, très résistants à l'altération.",
        mineraux: ["beryl", "tourmaline", "cordierite"] },
      { nom: "Inosilicates — chaînes de tétraèdres", code: "IX.D", motif: "chaînes SiO₃ (pyroxènes) & rubans Si₄O₁₁ (amphiboles)",
        note: "Les minéraux sombres des basaltes, gabbros et roches métamorphiques. Deux sous-classes, réunies par Strunz : les PYROXÈNES (chaîne simple, anhydres) et les AMPHIBOLES (chaîne double, hydratées, à clivages caractéristiques à ~120°).",
        mineraux: ["pyroxenes", "amphiboles"] },
      { nom: "Phyllosilicates — feuillets", code: "IX.E", motif: "feuillets Si₂O₅ empilés", lien: { hash: "#argiles", label: "Classification détaillée des argiles →" },
        note: "Micas, serpentines, talc, chlorites… et tous les minéraux argileux. Leur monde est si vaste qu'il a sa classification dédiée dans l'atlas.",
        mineraux: ["muscovite", "biotite", "glauconie", "serpentine", "chlorite_m", "kaolinite_m", "illite_m", "smectites_m"] },
      { nom: "Tectosilicates — charpente 3D", code: "IX.F", motif: "réseau SiO₄ tridimensionnel complet, sans eau",
        note: "Les deux tiers de la croûte : silice, feldspaths, feldspathoïdes, scapolites. Le réseau 3D complet fait leur solidité — sauf quand il manque de silice (feldspathoïdes). À noter : Strunz classe formellement le quartz et la silice (SiO₂) dans les oxydes (IV) ; on les garde ici, avec les feldspaths, pour la cohérence structurale.",
        mineraux: ["quartz", "orthose", "plagioclases"] },
      { nom: "Zéolithes — charpente ouverte hydratée", code: "IX.G", motif: "charpente 3D à larges canaux + eau et cations mobiles",
        note: "Même charpente 3D que les tectosilicates, mais AÉRÉE : de larges canaux la parcourent, remplis d'eau et de cations qui entrent, sortent et s'échangent librement. C'est ce qui vaut aux zéolithes leur classe Strunz à part (IX.G) et tous leurs usages : tamis moléculaires, adoucisseurs d'eau, catalyseurs, dépollution.",
        mineraux: ["analcime"] },
    ],
  },
  {
    classe: "Oxydes & hydroxydes", n: 4, num: "IV", icone: "🟠",
    plus: "<p>Les oxydes sont les <b>produits finaux de l'altération</b> : quand les silicates ont rendu leurs cations et que tout le reste a été emporté par les eaux, il reste le fer, l'aluminium, le manganèse et le titane, verrouillés avec l'oxygène.</p><p>Ce sont eux qui <b>peignent les paysages</b>. Moins de 1 % d'oxyde de fer suffit à colorer un sol : la goethite le rend ocre sous nos climats tempérés (8–15 °C), l'hématite le rend rouge sous les climats chauds à étés secs (> 15 °C, sol sec ≥ 45 jours d'affilée). Un sol rouge est donc une archive climatique. Leur chapitre dédié détaille chaque dynastie (Fe, Mn, Al, Ti) et permet de simuler quelles espèces se forment selon le climat, le drainage, le pH et la matière organique.</p><p>Une bizarrerie à connaître : Strunz range officiellement le <b>quartz</b> (SiO₂) dans cette classe, puisque c'est chimiquement un oxyde de silicium. Mais sa structure — une charpente tridimensionnelle de tétraèdres — en fait un tectosilicate. Nous l'avons laissé avec les silicates, là où sa logique structurale le place.</p>",
    desc: "Métal + oxygène (oxydes) ou métal + OH (hydroxydes) : les produits finaux de l'altération et les grands pigments de la nature. Fer, manganèse, aluminium, titane… chacun a sa dynastie — détaillée sur la page dédiée, avec les conditions de formation et le visualiseur pH–Eh.",
    lien: { hash: "#oxydes", label: "Page complète : oxydes & hydroxydes →" },
    groupes: [
      { nom: "Oxydes et hydroxydes métalliques", note: "Une famille par élément (fer, manganèse, aluminium, titane…) : cliquer sur une espèce pour sa carte d'identité, ou ouvrir l'onglet de l'élément pour ses conditions de formation.",
        mineraux: ["hematite", "magnetite", "goethite", "gibbsite"], dynamique: "oxydes" },
    ],
  },
  {
    classe: "Carbonates & nitrates", n: 5, num: "V", icone: "⚪",
    plus: "<p>Le groupement CO₃²⁻ a une propriété qui gouverne des paysages entiers : il <b>se dissout dans l'eau acide</b>. Or toute eau de pluie est légèrement acide, puisqu'elle dissout le CO₂ de l'air en tombant.</p><p>Résultat : les massifs calcaires se creusent de l'intérieur — grottes, gouffres, rivières souterraines, lapiaz, résurgences. C'est le <b>karst</b>, qui occupe près d'un tiers du territoire français (Causses, Vercors, Jura, Provence). Le calcium dissous est ensuite reprécipité ailleurs, dès que l'eau perd son CO₂ : stalactites, tufs, sources pétrifiantes — et le tartre de nos bouilloires, qui est la même chimie dans une casserole.</p><p>Ce cycle est aussi un <b>thermostat climatique</b> : l'altération des silicates consomme du CO₂ atmosphérique et l'exporte vers l'océan sous forme de carbonates, où il est stocké pour des millions d'années. Enfin, la calcite et l'aragonite — deux formes du même CaCO₃ — sont massivement fabriquées par le vivant : coquilles, coraux, plancton. La craie n'est rien d'autre qu'une accumulation de squelettes microscopiques.</p>",
    desc: "Le groupement CO₃²⁻ lié à Ca, Mg, Fe, Mn, Cu… Solubles dans les eaux acides (donc dans toute eau de pluie chargée en CO₂) : ce sont eux qui font les karsts, les grottes et les eaux dures.",
    groupes: [
      { nom: "Carbonates", motif: "CO₃²⁻",
        note: "De la calcite omniprésente aux carbonates métalliques colorés des chapeaux d'oxydation.",
        mineraux: ["calcite", "aragonite", "dolomite", "siderite", "magnesite", "rhodochrosite", "malachite", "azurite"] },
    ],
  },
  {
    classe: "Sulfates", n: 7, num: "VII", icone: "🟡",
    plus: "<p>Les sulfates naissent de deux façons opposées. <b>Par évaporation</b> d'abord : quand une lagune s'assèche, le gypse (CaSO₄·2H₂O) précipite juste avant le sel. C'est le gypse de Montmartre, exploité en carrières sous Paris — il a donné au monde le « <b>plâtre de Paris</b> ». Chauffé à 150 °C il perd son eau et devient poudre ; en la reprenant, il durcit et reprend sa forme. Sa version déshydratée, l'<b>anhydrite</b>, fait l'inverse en profondeur : elle gonfle de 60 % en s'hydratant — cauchemar des tunneliers.</p><p><b>Par oxydation</b> ensuite : quand les sulfures s'altèrent, le soufre libéré s'oxyde en sulfate. Naissent alors les ocres acides comme la <b>jarosite</b>, qui ne précipite qu'en dessous de pH 3. Sa détection sur Mars par le rover Opportunity a prouvé qu'une eau acide y avait coulé.</p><p>La <b>barytine</b>, elle, échappe à la règle de solubilité : si dense et si insoluble qu'on l'appelait le « spath pesant ». On l'utilise pour alourdir les boues de forage et pour arrêter les rayons X.</p>",
    desc: "Le groupement SO₄²⁻ : minéraux d'évaporation (gypse, anhydrite) ou d'oxydation des sulfures (jarosite, alunite). Solubles pour la plupart — la barytine fait exception.",
    groupes: [
      { nom: "Sulfates", motif: "SO₄²⁻",
        note: "Des évaporites aux ocres acides des mines.",
        mineraux: ["gypse_m", "anhydrite", "barytine", "jarosite", "alunite"] },
    ],
  },
  {
    classe: "Phosphates", n: 8, num: "VIII", icone: "🟢",
    plus: "<p>Discrète mais vitale, cette classe porte le <b>cycle du phosphore</b>. Presque tout le phosphore de la biosphère — celui des engrais, des plantes, de l'ADN, de nos os et de nos dents — provient de la lente dissolution d'un seul minéral : l'<b>apatite</b>, présente en quantités infimes dans presque toutes les roches magmatiques.</p><p>Nos os sont d'ailleurs faits d'apatite biologique : nous sommes, littéralement, construits sur un minéral. Et c'est un <b>élément limitant</b> : contrairement au carbone ou à l'azote, le phosphore n'a aucun réservoir atmosphérique. Une fois emporté à l'océan, il n'en revient qu'au bout de millions d'années, par soulèvement tectonique. D'où l'enjeu stratégique — et la finitude — des gisements de phosphate.</p><p>La <b>monazite</b>, elle, est le coffre-fort des <b>terres rares</b> et du thorium. Dense et quasi inaltérable, elle se concentre dans les sables lourds des placers, où on la récolte. La <b>vivianite</b> enfin, « fer bleu des tourbières », cristallise autour des ossements enfouis : incolore à l'abri, elle bleuit en quelques heures dès qu'on l'expose à l'air.</p>",
    desc: "Le groupement PO₄³⁻. Discrets mais vitaux : l'apatite nourrit en phosphore toute la biosphère, la monazite stocke les terres rares.",
    groupes: [
      { nom: "Phosphates", motif: "PO₄³⁻",
        note: "Le cycle du phosphore commence ici.",
        mineraux: ["apatite", "monazite", "vivianite"] },
    ],
  },
  {
    classe: "Sulfures & sulfosels", n: 2, num: "II", icone: "⚫",
    plus: "<p>Les sulfures sont les <b>minerais métalliques</b> par excellence : c'est sous cette forme que le cuivre, le plomb, le zinc et l'argent voyagent dans les fluides hydrothermaux chauds, puis se déposent en filons quand ces fluides refroidissent. Ils partagent un éclat métallique et une densité élevée qui les trahissent en main.</p><p>Mais tous ont le même défaut : ils sont nés <b>à l'abri de l'oxygène</b>, et l'air libre les détruit. Leur oxydation libère de l'acide sulfurique — c'est le <b>drainage minier acide</b> qui rougit les ruisseaux autour des anciennes mines, des terrils et des ardoisières.</p><p>Cette même oxydation sculpte le sommet des filons en un « <b>chapeau de fer</b> » rouillé (gossan), sous lequel les métaux lessivés se reconcentrent : les prospecteurs ont toujours cherché ces chapeaux, signatures visibles d'un gisement caché. La <b>pyrite</b>, l'« or des fous », est le plus commun d'entre eux ; sa jumelle la <b>marcassite</b>, de même formule mais de réseau différent, est si instable qu'elle se désagrège en poussière sulfatée dans les tiroirs des collectionneurs.</p>",
    desc: "Métal + soufre : les minerais métalliques par excellence, nés des fluides hydrothermaux. Tous instables à l'air libre — leur oxydation acidifie les eaux (drainage minier) et peint les affleurements.",
    groupes: [
      { nom: "Sulfures", motif: "S²⁻",
        note: "L'éclat métallique des filons.",
        mineraux: ["pyrite", "marcassite", "galene", "blende", "chalcopyrite"] },
    ],
  },
  {
    classe: "Halogénures", n: 3, num: "III", icone: "🧊",
    plus: "<p>Ce sont les minéraux du <b>sel</b> : un métal, un halogène (Cl, F, Br). Leur trait commun est la <b>solubilité</b>, souvent extrême — c'est pourquoi ils ne survivent en surface que sous les climats arides (pluie < 20 % de l'ETP), ou bien à l'abri sous terre.</p><p>La <b>halite</b> (le sel de cuisine) se dissout à 360 g/L : en France, les couches de sel du Trias ne sont connues que par les forages et les mines, jamais par un affleurement. Ces sels naissent de l'évaporation de lagunes et de lacs salés, et se déposent dans un <b>ordre strict dicté par leur solubilité</b> : d'abord les carbonates, puis le gypse, puis la halite, enfin les sels de potassium et de magnésium. Une séquence si régulière qu'elle sert d'horloge chimique aux géologues — et c'est elle qui a fait la fortune des Mines de Potasse d'Alsace.</p><p>La <b>fluorine</b> (CaF₂) fait exception : bien moins soluble, elle bâtit de beaux filons de cubes violets (Morvan, Tarn, Chaillac). Étalon de dureté 4, fondant de la sidérurgie — son nom vient de <i>fluere</i>, couler — c'est elle qui a donné son nom à la <b>fluorescence</b>.</p>",
    desc: "Métal + halogène (Cl, F). Les plus solubles des minéraux (halite, sylvite) — sauf la fluorine, assez robuste pour faire des filons.",
    groupes: [
      { nom: "Halogénures", motif: "Cl⁻, F⁻",
        note: "Des sels d'évaporation aux cubes violets des filons.",
        mineraux: ["halite_m", "sylvite", "fluorine"] },
    ],
  },
  {
    classe: "Éléments natifs", n: 1, num: "I", icone: "✨",
    plus: "<p>Qu'un élément se présente <b>pur</b> dans la nature est l'exception : la plupart réagissent aussitôt avec l'oxygène ou le soufre. Il faut donc soit une inertie chimique extrême, soit des conditions très particulières.</p><p>L'<b>or</b> ne s'oxyde pas, ne se dissout pas : l'altération des roches le libère intact et les rivières le trient par densité, en paillettes et en pépites. C'est ainsi qu'on l'orpaille depuis l'Antiquité dans le Gardon, l'Ariège et l'Hérault ; Salsigne (Aude) fut la plus grande mine d'or d'Europe occidentale.</p><p>Le <b>carbone</b>, lui, joue double jeu : empilé en feuillets glissants, c'est le graphite (dureté 1, la mine de crayon) ; relié en charpente tridimensionnelle, c'est le diamant (dureté 10). Même élément, deux structures — et les deux extrêmes de l'échelle de Mohs. Le <b>soufre natif</b>, enfin, se dépose autour des fumerolles volcaniques et dans les chapeaux des dômes de sel, où des bactéries le fabriquent en respirant les sulfates.</p>",
    desc: "Les rares éléments qui se présentent purs dans la nature : métaux inoxydables (or), semi-métaux et non-métaux (graphite, soufre).",
    groupes: [
      { nom: "Éléments natifs", motif: "un seul élément",
        note: "La matière à l'état brut.",
        mineraux: ["or_natif", "graphite", "soufre_natif"] },
    ],
  },
  {
    classe: "Borates", n: 6, num: "VI", icone: "🔶",
    plus: "<p>Les borates sont les <b>grands absents de la géologie française</b>. Le bore est un élément rare, qui ne se concentre que dans un contexte très précis : l'évaporation de lacs salés, en région aride, alimentés par un volcanisme ou des sources chaudes qui apportent le bore en solution.</p><p>Trois endroits au monde en fournissent l'essentiel : la Death Valley (Californie), l'Anatolie (Turquie) et le désert d'Atacama. Le <b>borax</b> y forme des croûtes blanches, exploitées depuis des siècles — d'abord comme fondant pour souder les métaux, puis comme détergent et comme source de bore pour le verre borosilicaté (le Pyrex).</p><p>Nous présentons cette classe pour la <b>complétude de la classification de Strunz</b>, mais c'est une famille qu'on ne rencontre pas sur le terrain en métropole — la boracite elle-même, pourtant minéral d'évaporites, n'a jamais été signalée dans nos sels lorrains.</p>",
    desc: "Le groupement borate (BO₃ ou BO₄) : minéraux des lacs salés évaporitiques des régions arides (pluie < 20 % de l'ETP). Quasi absents de France métropolitaine — classe présentée pour la complétude de la classification.",
    groupes: [
      { nom: "Borates", motif: "BO₃³⁻ / BO₄⁵⁻",
        note: "Nés de l'évaporation de lacs riches en bore (Death Valley, Turquie, Atacama).",
        mineraux: ["borax"] },
    ],
  },
  {
    classe: "Minéraux organiques", n: 10, num: "X", icone: "🟤", achever: true,
    plus: "<p>Une classe paradoxale : des molécules d'origine <b>biologique</b>, mais qui ont cristallisé — et remplissent donc bel et bien la définition du minéral.</p><p>L'<b>ambre</b> en est l'emblème : une résine de conifère fossilisée, si légère qu'elle flotte dans l'eau salée. Frottée, elle se charge d'électricité statique — les Grecs l'appelaient <i>elektron</i>, et c'est de là que vient le mot « <b>électricité</b> ». Les ambres crétacés des Charentes sont mondialement étudiés pour les insectes qu'ils emprisonnent, figés depuis 100 millions d'années. On range aussi ici des oxalates comme la whewellite, qui cristallise… dans les calculs rénaux.</p><p>À ne pas confondre avec la <b>matière organique amorphe</b> des sols et des charbons : celle-là n'est pas cristalline, ce n'est donc pas un minéral. Elle a sa propre partie dans l'atlas, avec les verres volcaniques. 🚧 Classe à compléter si tu veux l'étoffer.</p>",
    desc: "Les rares composés d'origine biologique cristallisés que l'IMA reconnaît comme minéraux : résines fossiles, oxalates, sels d'acides organiques. À ne pas confondre avec la matière organique amorphe des sols (voir la partie « Amorphes & organiques »).",
    groupes: [
      { nom: "Minéraux organiques", motif: "molécules carbonées cristallisées",
        note: "L'ambre en est le représentant le plus connu.",
        mineraux: ["ambre"] },
    ],
  },
];
