// ============================================================
// MINÉRAUX, ARGILES & CODES DE CARTES — extension de l'atlas
// Mêmes précautions que data.js : ordres de grandeur de la
// littérature (CEC, surfaces, rétention d'eau varient selon
// l'échantillon, le cation dominant et la méthode de mesure).
// ============================================================

// ---------- Dictionnaire des minéraux ----------
// stabilite : position qualitative dans la série de Goldich
// (1 = s'altère en premier … 10 = quasi inaltérable)
const MINERAUX = {
  quartz: {
    nom: "Quartz", formule: "SiO₂", famille: "Tectosilicate — silice", durete: 7, densite: 2.65,
    systeme: "rhomboédrique (trigonal)", clivage: "aucun (cassure conchoïdale)", eclat: "vitreux",
    couleurs: "incolore, blanc laiteux, fumé, rose, violet (améthyste), jaune (citrine)…",
    contexte: "Ubiquiste : granites, filons, grès, sables. Absent des roches pauvres en silice.",
    stabilite: 10, swatch: "#e8d8a8",
    devient: "Rien ou presque : il est libéré intact et devient le sable des rivières, plages et dunes.",
    note: "Réseau tridimensionnel de tétraèdres SiO₄ sans cation fragile : c'est le minéral commun le plus résistant à l'altération. Un même grain de quartz peut traverser plusieurs cycles érosion → dépôt → grès → érosion. Ses innombrables variétés colorées (améthyste, citrine, quartz fumé, rose) ne sont que des traces d'impuretés ou d'irradiation.",
  },
  opale: {
    nom: "Opale", formule: "SiO₂·nH₂O", famille: "Tectosilicate — silice (amorphe hydratée)", durete: 5.5, densite: 2.1,
    systeme: "amorphe", clivage: "aucun (cassure conchoïdale)", eclat: "vitreux à résineux, parfois jeu de couleurs",
    couleurs: "blanc, gris, jaune, orange (opale de feu) ; iridescences pour l'opale noble",
    contexte: "Silicifications, sources chaudes (geysérite), squelettes siliceux, tuffeau.",
    stabilite: 6, swatch: "#dcd7c5",
    devient: "Se dissout lentement (silice en solution) ou recristallise en calcédoine.",
    note: "Silice non cristallisée contenant de l'eau, souvent d'origine biologique (squelettes de diatomées, spicules d'éponges). L'opale noble diffracte la lumière en un jeu de couleurs grâce à un empilement régulier de microsphères de silice. Nettement plus soluble que le quartz — c'est elle qui rend le tuffeau si poreux et fragile.",
  },
  calcedoine: {
    nom: "Calcédoine (silex)", formule: "SiO₂ microcristalline", famille: "Tectosilicate — silice (microcristalline)", durete: 6.5, densite: 2.6,
    systeme: "rhomboédrique (fibres microscopiques)", clivage: "aucun (cassure conchoïdale)", eclat: "cireux à mat",
    couleurs: "gris, brun, blanc ; variétés agate, cornaline, jaspe, onyx",
    contexte: "Rognons de silex de la craie, meulière, géodes, bois silicifié.",
    stabilite: 9, swatch: "#b8ac96",
    devient: "Fragments de silex quasi indestructibles (argiles à silex, outils préhistoriques).",
    note: "Quartz en cristaux microscopiques fibreux. Forme les rognons de silex de la craie et la meulière. Sa résistance explique que les champs de Normandie soient truffés de silex alors que la craie qui les contenait a disparu. Ses variétés zonées (agate) ou colorées (cornaline, jaspe, onyx) sont des pierres ornementales.",
  },
  calcite: {
    nom: "Calcite", formule: "CaCO₃", famille: "Carbonate", durete: 3, densite: 2.71,
    systeme: "rhomboédrique", clivage: "parfait rhomboédrique (3 directions)", eclat: "vitreux à nacré",
    couleurs: "incolore, blanc, toutes teintes pastel",
    contexte: "Partout : calcaires, marbres, filons, grottes, coquilles — le minéral aux mille formes ; le spath d'Islande double les images.",
    stabilite: 3, swatch: "#e9e2d0",
    devient: "Dissolution totale : ions Ca²⁺ et HCO₃⁻ emportés par l'eau (eaux « dures », stalactites, tuf).",
    note: "Carbonate de calcium : un ion calcium lié à un groupement CO₃²⁻. Fait effervescence à l'acide (test HCl du géologue). Constituant de la calcite des coquilles, de la craie, des calcaires et du marbre. Se dissout dans l'eau chargée en CO₂ et reprécipite ailleurs (grottes, sources pétrifiantes).",
  },
  dolomite: {
    nom: "Dolomite", formule: "CaMg(CO₃)₂", famille: "Carbonate double", durete: 3.75, densite: 2.87,
    systeme: "rhomboédrique", clivage: "parfait rhomboédrique", eclat: "vitreux à nacré",
    couleurs: "blanc crème, rose saumon, gris",
    contexte: "Dolomies, filons et cargneules ; ses cristaux courbes « en selle de cheval » signent les gangues hydrothermales.",
    stabilite: 4, swatch: "#d9cdb2",
    devient: "Dissolution lente : Ca²⁺, Mg²⁺ et HCO₃⁻ en solution + sable dolomitique résiduel.",
    note: "Comme la calcite, mais un calcium sur deux est remplacé par du magnésium — ce qui la rend plus compacte et 3 à 10 fois moins soluble. Réagit à peine à l'acide froid.",
  },
  gypse_m: {
    nom: "Gypse (minéral)", formule: "CaSO₄·2H₂O", famille: "Sulfate hydraté", durete: 2, densite: 2.32,
    systeme: "monoclinique", clivage: "parfait {010} — lamelles flexibles", eclat: "vitreux, nacré ou soyeux (fibres)",
    couleurs: "incolore (« fers de lance »), blanc, miel",
    contexte: "Évaporites (Montmartre, Provence, Trias lorrain), efflorescences des marnes ; les roses des sables en sont, moulées dans le sable des déserts.",
    stabilite: 1, swatch: "#efe9dc",
    devient: "Dissolution rapide et totale : Ca²⁺ + SO₄²⁻ (eaux séléniteuses).",
    note: "Sulfate de calcium avec deux molécules d'eau dans son réseau. Se raye à l'ongle. Chauffé à 150 °C il perd son eau et devient le plâtre — qui la reprend en durcissant.",
  },
  halite_m: {
    nom: "Halite", formule: "NaCl", famille: "Chlorure", durete: 2.5, densite: 2.16,
    systeme: "cubique", clivage: "parfait cubique {100}", eclat: "vitreux",
    couleurs: "incolore, blanc, rose (bactéries), bleu (défauts d'irradiation)",
    contexte: "Évaporites du Keuper (Lorraine, Jura, Béarn) et de l'Oligocène rhénan ; croûtes des sebkhas actuelles.",
    stabilite: 1, swatch: "#f0f0f4",
    devient: "Dissolution immédiate : Na⁺ + Cl⁻ vers les rivières puis l'océan.",
    note: "Le sel de cuisine cristallisé en cubes. Soluble à 360 g/L : le minéral le plus fugace de la surface terrestre sous nos climats.",
  },
  orthose: {
    nom: "Orthose (feldspath K)", formule: "KAlSi₃O₈", famille: "Tectosilicate — feldspath alcalin", durete: 6, densite: 2.56,
    systeme: "monoclinique", clivage: "parfait {001} et bon {010}, à angle droit exact — c'est ce 90° qui lui vaut son nom (grec orthós, « droit »)", eclat: "vitreux à nacré",
    couleurs: "rose saumon, blanc, gris, incolore",
    contexte: "Granites, syénites, gneiss ; c'est lui qui rosit beaucoup de granites.",
    stabilite: 7, swatch: "#e2b8a8",
    devient: "Hydrolyse → kaolinite ou illite + K⁺ et silice en solution.",
    note: "Feldspath potassique, souvent rose (c'est lui qui colore le granite de Ploumanac'h). L'hydrolyse le transforme en argiles : K⁺ part nourrir sols et océans, l'aluminium et une partie de la silice restent et se réorganisent en kaolinite. Sa variété limpide et nacrée est l'adulaire (pierre de lune).",
  },
  plagioclases: {
    nom: "Plagioclases (série)", formule: "NaAlSi₃O₈ → CaAl₂Si₂O₈", famille: "Tectosilicate — feldspath plagioclase", durete: 6, densite: 2.68,
    systeme: "triclinique", clivage: "parfait {001} et {010} à ~94° (macles polysynthétiques striées)", eclat: "vitreux",
    couleurs: "blanc, gris, incolore ; reflets bleus (labradorite)",
    contexte: "Des granites (sodiques) aux basaltes et gabbros (calciques) : les feldspaths les plus répandus.",
    stabilite: 5, swatch: "#d8d3c8",
    devient: "Hydrolyse → smectites ou kaolinite + Na⁺/Ca²⁺ et silice en solution.",
    note: "Série continue entre un pôle sodique (albite) et un pôle calcique (anorthite), avec cinq jalons nommés selon la proportion des deux. Plus ils sont calciques, plus ils s'altèrent vite (série de Goldich) : les plagioclases des basaltes cèdent bien avant l'orthose des granites. Leurs fines stries parallèles (macles) les trahissent au microscope. Voir le détail des pôles dans la sous-famille.",
  },
  sanidine: {
    nom: "Sanidine", formule: "(K,Na)AlSi₃O₈", famille: "Tectosilicate — feldspath alcalin", durete: 6, densite: 2.52,
    systeme: "monoclinique", clivage: "parfait {001} et bon {010}", eclat: "vitreux",
    couleurs: "incolore, blanc, gris ; souvent limpide",
    contexte: "Laves felsiques refroidies vite (trachytes, rhyolites, phonolites).",
    stabilite: 6, swatch: "#e5ddd2",
    devient: "Hydrolyse → argiles (kaolinite, illite) + K⁺.",
    note: "Version haute température du feldspath potassique, où K et Na sont désordonnés dans la charpente (refroidissement rapide). Typique des laves comme le trachyte du puy de Dôme. Cristaux vitreux souvent visibles à l'œil nu.",
  },
  muscovite: {
    nom: "Muscovite (mica blanc)", formule: "KAl₂(AlSi₃O₁₀)(OH)₂", famille: "Phyllosilicate — mica dioctaédrique", durete: 2.5, densite: 2.82,
    systeme: "monoclinique", clivage: "parfait basal {001} — feuillets fins et élastiques", eclat: "nacré à vitreux",
    couleurs: "incolore, argenté, gris, jaunâtre ; variété verte chromifère = fuchsite",
    contexte: "Granites, pegmatites, micaschistes et gneiss ; paillettes détritiques dans les grès.",
    stabilite: 8, swatch: "#dcd9cf",
    devient: "Se transforme lentement en illite (elle en est quasiment la version « fraîche »).",
    note: "Mica clair en feuillets élastiques brillants. Son nom vient du « verre de Moscovie », ces grandes lamelles transparentes que l'on employait autrefois comme vitres en Russie. Très résistant à l'altération : ses paillettes voyagent loin dans les rivières, et l'illite des sols en est largement héritée. Sa variété vert émeraude, la fuchsite, colore certains quartzites.",
  },
  biotite: {
    nom: "Biotite (mica noir)", formule: "K(Mg,Fe)₃(AlSi₃O₁₀)(OH)₂", famille: "Phyllosilicate — mica trioctaédrique", durete: 2.75, densite: 3.0,
    systeme: "monoclinique", clivage: "parfait basal {001} — feuillets élastiques", eclat: "nacré à vitreux",
    couleurs: "brun-noir, noir, brun-vert",
    contexte: "Granites, gneiss, micaschistes, nombreuses roches magmatiques et métamorphiques.",
    stabilite: 4, swatch: "#5c5148",
    devient: "→ vermiculite (par perte de K⁺) puis smectites + oxydes de fer.",
    note: "Mica sombre riche en fer et magnésium — en réalité un nom de série (entre la phlogopite magnésienne et l'annite ferreuse). Beaucoup plus fragile que la muscovite : son fer s'oxyde (taches de rouille des granites altérés) et ses feuillets s'ouvrent pour donner la vermiculite.",
  },
  glauconie: {
    nom: "Glauconie (glauconite)", formule: "(K,Na)(Fe³⁺,Al,Mg)₂(Si,Al)₄O₁₀(OH)₂", famille: "Phyllosilicate — mica dioctaédrique ferrifère", durete: 2, densite: 2.6,
    systeme: "monoclinique", clivage: "parfait basal {001}", eclat: "terne à mat",
    couleurs: "vert olive à vert sombre",
    contexte: "Néoformation marine : fonds des mers peu profondes, « sables verts » et tuffeau.",
    stabilite: 5, swatch: "#6d8462", argile: "glauconite",
    devient: "→ oxydes de fer + argiles ; libère lentement son potassium.",
    note: "Un mica ferrifère à la frontière des argiles : des granules verts qui se forment aujourd'hui même au fond des mers peu profondes (néoformation marine). Donne leur teinte verdâtre au tuffeau et aux « sables verts » du Crétacé. Voir la fiche argile Glauconite pour le détail.",
  },
  olivine: {
    nom: "Olivine (série)", formule: "(Mg,Fe)₂SiO₄", famille: "Nésosilicate (groupe de l'olivine)", durete: 6.75, densite: 3.32,
    systeme: "orthorhombique", clivage: "imparfait (cassure conchoïdale)", eclat: "vitreux",
    couleurs: "vert olive à brun-vert ; le péridot gemme est vert pomme",
    contexte: "Basaltes, gabbros, péridotites : c'est le minéral principal du manteau supérieur.",
    stabilite: 1, swatch: "#8fa04f",
    devient: "→ smectites (ou serpentine en profondeur) + oxydes de fer + Mg²⁺ et silice dissous.",
    note: "Le minéral silicaté le plus vulnérable à l'altération (tout en haut de la série de Goldich) : cristallisé à ~1 400 °C, il est très loin de son équilibre en surface. Son altération consomme du CO₂ — d'où les projets d'épandage d'olivine broyée pour le climat.",
  },
  pyroxenes: {
    nom: "Pyroxènes (augite…)", formule: "(Ca,Mg,Fe)₂Si₂O₆", famille: "Inosilicates (chaîne simple)", durete: 5.5, densite: 3.3,
    stabilite: 2, swatch: "#4f5b46",
    devient: "→ smectites + oxydes de fer + Ca²⁺/Mg²⁺ dissous.",
    note: "Minéraux sombres des basaltes et gabbros, en chaînes simples de tétraèdres. S'altèrent vite, juste après l'olivine.",
  },
  amphiboles: {
    nom: "Amphiboles (hornblende)", formule: "Ca₂(Mg,Fe,Al)₅(Si,Al)₈O₂₂(OH)₂", famille: "Inosilicates (chaîne double)", durete: 5.5, densite: 3.2,
    stabilite: 3, swatch: "#3f4a41",
    devient: "→ smectites/vermiculite + oxydes de fer.",
    note: "Chaînes doubles avec des groupements OH : un peu plus résistantes que les pyroxènes. Typiques des andésites et trachyandésites du Cantal.",
  },
  magnetite: {
    nom: "Magnétite", formule: "Fe₃O₄", famille: "Oxyde de fer", durete: 6, densite: 5.17,
    stabilite: 8, swatch: "#3a3a40",
    devient: "→ hématite puis goethite (rouille) par oxydation lente.",
    note: "Oxyde de fer magnétique (elle attire l'aiguille de la boussole !). Résiduelle dans les sables noirs des plages et les sols sur basalte ou serpentinite.",
  },
  hematite: {
    nom: "Hématite", formule: "Fe₂O₃", famille: "Oxyde de fer", durete: 5.5, densite: 5.26,
    stabilite: 9, swatch: "#a04030",
    devient: "Stable — c'est déjà un produit final. Peut s'hydrater en goethite.",
    note: "LE pigment rouge de la nature : grès rouges, bauxite, terres méditerranéennes, ocres de Roussillon. Signature d'une altération sous climat chaud à étés secs (> 15 °C, sol sec ≥ 45 jours d'affilée).",
  },
  goethite: {
    nom: "Goethite", formule: "FeO(OH)", famille: "Oxyhydroxyde de fer", durete: 5.25, densite: 4.27,
    stabilite: 9, swatch: "#b07830",
    devient: "Stable — produit final de l'altération du fer.",
    note: "La « rouille » des sols tempérés (8–15 °C) : brun-jaune à ocre. C'est elle qui colore la plupart des sols français, les argiles de décalcification et les grès ferrugineux.",
  },
  pyrite: {
    nom: "Pyrite", formule: "FeS₂", famille: "Sulfure", durete: 6.25, densite: 5.01,
    systeme: "cubique", clivage: "indistinct (cassure conchoïdale)", eclat: "métallique",
    couleurs: "jaune laiton pâle",
    contexte: "Partout : vases anoxiques, schistes noirs, filons, charbons — le sulfure le plus abondant de la croûte.",
    stabilite: 2, swatch: "#c9a84c",
    devient: "Oxydation rapide → acide sulfurique + oxydes de fer (drainage minier acide).",
    note: "« L'or des fous » en cubes dorés. À l'air libre elle s'oxyde vite, acidifie les eaux (terrils, ardoisières) et tache de rouille marnes et ardoises.",
  },
  serpentine: {
    nom: "Serpentine (groupe)", formule: "Mg₃Si₂O₅(OH)₄", famille: "Phyllosilicate — serpentine (1:1)", durete: 3.5, densite: 2.57,
    systeme: "monoclinique", clivage: "variable selon l'espèce (fibreux à lamellaire)", eclat: "gras, cireux ou soyeux",
    couleurs: "vert (toutes nuances), vert-noir, jaune-vert",
    contexte: "Serpentinites : hydratation des péridotites du manteau et du plancher océanique.",
    stabilite: 4, swatch: "#5f7d64",
    devient: "→ smectites magnésiennes + oxydes de fer + Mg²⁺ dissous.",
    note: "Nom générique d'un groupe de trois espèces (chrysotile, antigorite, lizardite). Née de l'hydratation de l'olivine par l'eau de mer dans le plancher océanique. Structure en feuillets 1:1 comme la kaolinite, mais avec du magnésium. Sa variété fibreuse, le chrysotile, est l'amiante blanc.",
  },
  grenat: {
    nom: "Grenats (série)", formule: "A₃B₂(SiO₄)₃", famille: "Nésosilicate (groupe du grenat)", durete: 7.25, densite: 4.3,
    systeme: "cubique", clivage: "aucun (cassure conchoïdale)", eclat: "vitreux",
    couleurs: "rouge sombre (almandin), rouge feu (pyrope), orange (spessartine), vert (uvarovite)…",
    contexte: "Micaschistes et gneiss ; skarns ; péridotites du manteau. Le nom couvre toute une série.",
    stabilite: 7, swatch: "#7d3040",
    devient: "Résiduel (sables à grenats), puis lentement oxydes + argiles.",
    note: "Cristaux rouge sombre des micaschistes. Assez résistant pour former des placers : certaines plages bretonnes ont du sable rose grenat.",
  },
  gibbsite: {
    nom: "Gibbsite", formule: "Al(OH)₃", famille: "Hydroxyde d'aluminium", durete: 2.75, densite: 2.42,
    stabilite: 9, swatch: "#d8c8be",
    devient: "Stable — produit ultime de l'altération (allitisation).",
    note: "Quand l'hydrolyse est totale (climat équatorial très drainé), même la silice s'en va : il ne reste que ces hydroxydes d'aluminium. C'est le minerai de la bauxite — et la preuve d'un passé tropical de la Provence.",
  },
  verre: {
    nom: "Verre naturel", formule: "silicate amorphe", famille: "Amorphe (non cristallisé)", durete: 5.5, densite: 2.5,
    systeme: "amorphe (non cristallin)", clivage: "aucun (cassure conchoïdale)", eclat: "vitreux",
    couleurs: "noir, brun, vert bouteille ; incolore à brun clair en lame mince",
    contexte: "Laves figées (obsidienne, bordures des laves en coussins, hyaloclastites), ponces et cendres (tufs, ignimbrites), veines de pseudotachylite des failles, brèches d'impact (Rochechouart).",
    stabilite: 1, swatch: "#6a5a52",
    devient: "→ allophanes puis smectites/halloysite + ions dissous.",
    note: "Une roche fondue figée avant que ses atomes aient pu se ranger : une lave le plus souvent (verre volcanique), mais aussi une roche fondue par le frottement d'un séisme (pseudotachylite) ou par le choc d'une météorite (impactite). Sans réseau ordonné, il s'hydrolyse très vite : c'est pourquoi les jeunes sols volcaniques (andosols) sont si fertiles.",
  },
  matorg: {
    nom: "Matière organique", formule: "C, H, O, N…", famille: "Organique (non minérale)", durete: null, densite: 1.3,
    systeme: "amorphe (mélange de molécules)",
    contexte: "Horizons de surface des sols (humus), tourbières, vases ; roches organiques : tourbe, lignite, houille, anthracite, schistes bitumineux.",
    stabilite: 2, swatch: "#4a3a2a",
    devient: "→ CO₂ (minéralisation) + humus ; complexe argilo-humique avec les argiles.",
    note: "Débris végétaux plus ou moins transformés. Dans les sols, elle s'associe aux argiles pour former le complexe argilo-humique, réservoir de fertilité — dans la houille et la tourbe, elle EST la roche.",
  },
  // — argiles en tant que minéraux (fiches complètes dans ARGILES) —
  kaolinite_m: { nom: "Kaolinite", formule: "Al₂Si₂O₅(OH)₄", famille: "Argile 1:1", durete: 2.25, densite: 2.6, stabilite: 9, swatch: "#e9e4da", argile: "kaolinite", devient: "Stable (→ gibbsite si hydrolyse extrême).", note: "Voir la fiche argile complète." },
  illite_m: { nom: "Illite", formule: "K₀,₈(Al,Mg,Fe)₂(Si,Al)₄O₁₀(OH)₂", famille: "Argile 2:1", durete: 2, densite: 2.75, stabilite: 7, swatch: "#c9b98a", argile: "illite", devient: "→ vermiculite ou interstratifiés par perte de K⁺.", note: "Voir la fiche argile complète." },
  smectites_m: { nom: "Smectites", formule: "(Na,Ca)₀,₃(Al,Mg)₂Si₄O₁₀(OH)₂·nH₂O", famille: "Argile 2:1 gonflante", durete: 1.5, densite: 2.35, stabilite: 6, swatch: "#8fa387", argile: "smectites", devient: "→ kaolinite si le drainage s'améliore (perte de silice).", note: "Voir la fiche argile complète." },
  chlorite_m: { nom: "Chlorite", formule: "(Mg,Fe)₅Al(AlSi₃O₁₀)(OH)₈", famille: "Argile 2:1:1", durete: 2.25, densite: 2.65, stabilite: 4, swatch: "#6f8f72", argile: "chlorite", devient: "→ vermiculite puis smectites (oxydation du fer).", note: "Voir la fiche argile complète." },
};

// ---------- Fiches complètes des minéraux argileux ----------
// cec en cmol(+)/kg (= meq/100 g) ; surface en m²/g ;
// eau = g d'eau retenue pour 100 g d'argile sèche (ordre de grandeur)
const ARGILES = [
  {
    id: "kaolinite", nom: "Kaolinite", swatch: "#e9e4da",
    formule: "Al₂Si₂O₅(OH)₄",
    type: "1:1 (T-O)", espacement: "7,2 Å — fixe", chargeFoliaire: "≈ 0",
    cecMin: 3, cecMax: 15, surfMin: 10, surfMax: 30, eauMin: 20, eauMax: 40,
    gonflement: "Quasi nul", gonflementNiveau: 0,
    description: "L'argile blanche des climats tropicaux pluvieux (≥ 22 °C). Un feuillet de tétraèdres de silice collé à un feuillet d'octaèdres d'aluminium, le tout soudé par des liaisons hydrogène : rien ne peut s'insérer entre les feuillets, d'où sa sagesse — pas de gonflement, peu de réactivité.",
    origine: "Néoformation (+ héritage)",
    origineDetail: "Néoformée par hydrolyse poussée des feldspaths et micas quand le drainage évacue les cations (K⁺, Na⁺, Ca²⁺) et une partie de la silice : c'est la « monosiallitisation » des climats tropicaux humides. En France, on la trouve surtout héritée : kaolins d'arènes granitiques (Bretagne, Limousin), argiles plastiques éocènes (formées quand le climat parisien était tropical !).",
    contexte: "En France : kaolins de Bretagne (Ploemeur, Berrien) et des Charentes (Clérac), argiles plastiques de l'Éocène (Provins, Sparnacien du Bassin parisien), kaolin de Saint-Yrieix sur les granites du Limousin.",
    pedologie: "CEC très faible (3–15 cmol⁺/kg) : les sols kaolinitiques (sols tropicaux ferrallitiques, vieux sols sur arènes) retiennent mal les engrais et se dessaturent vite. En revanche structure stable, pas de fissures ni de gonflement.",
    rochesSources: ["granite", "gneiss", "rhyolite", "gres", "argile", "bauxite"],
    usages: "Porcelaine (kaolins de Limoges, découverts à Saint-Yrieix en 1768), papier glacé, céramiques, cosmétiques.",
    wikipedia: "https://fr.wikipedia.org/wiki/Kaolinite",
    interfoliaire: "liaisons H", // pour le schéma
  },
  {
    id: "illite", nom: "Illite", swatch: "#c9b98a",
    formule: "K₀,₆₋₀,₈(Al,Mg,Fe)₂(Si,Al)₄O₁₀(OH)₂",
    type: "2:1 (T-O-T)", espacement: "10 Å — fixe (verrouillé par K⁺) ; seuls les rares espaces sans K⁺ gonflent", chargeFoliaire: "0,6–0,9",
    cecMin: 10, cecMax: 40, surfMin: 80, surfMax: 120, eauMin: 50, eauMax: 100,
    gonflement: "Faible", gonflementNiveau: 1,
    description: "L'argile la plus abondante des sols et sédiments français. Deux feuillets de tétraèdres enserrent un feuillet d'octaèdres (sandwich T-O-T), et des ions potassium non hydratés verrouillent les feuillets entre eux comme des rivets : structure de mica en miniature, stable et peu gonflante.",
    origine: "Héritage (+ illitisation en profondeur)",
    origineDetail: "Essentiellement héritée de la dégradation des muscovites et de l'érosion des roches anciennes — les climats tempérés (8–15 °C), peu agressifs chimiquement, la laissent intacte. En profondeur (diagenèse > 2–3 km, > 70 °C), c'est l'inverse : les smectites se transforment en illite en capturant du potassium (« illitisation »), un chronomètre utilisé par les pétroliers.",
    contexte: "Domine dans les lœss, marnes, argilites et la plupart des sols de la moitié nord de la France.",
    pedologie: "CEC moyenne (10–40 cmol⁺/kg). Particularité agronomique majeure : elle fixe le potassium dans ses espaces interfoliaires — réserve utile à long terme, mais capable de « confisquer » l'engrais potassique à court terme (pouvoir fixateur des terres limoneuses).",
    rochesSources: ["gres", "argile", "marne", "loess", "ardoise", "micaschiste", "houille", "granite"],
    usages: "Terres à briques et tuiles, matière première céramique commune.",
    wikipedia: "https://fr.wikipedia.org/wiki/Illite",
    interfoliaire: "K⁺ fixés",
  },
  {
    id: "smectites", nom: "Smectites (montmorillonite)", swatch: "#8fa387",
    formule: "(Na,Ca)₀,₃(Al,Mg)₂Si₄O₁₀(OH)₂ · nH₂O",
    type: "2:1 (T-O-T) gonflante", espacement: "variable selon l'eau : 9,7 Å sèche, 12,6 Å (une couche d'eau), 15,6 Å (deux) ; dans l'eau ≈ 19 Å (Ca²⁺) ou 40 Å et plus (Na⁺)", chargeFoliaire: "0,2–0,6",
    cecMin: 80, cecMax: 150, surfMin: 600, surfMax: 800, eauMin: 150, eauMax: 500,
    gonflement: "Fort (jusqu'à plusieurs fois son volume)", gonflementNiveau: 3,
    description: "L'argile éponge. Même sandwich T-O-T que l'illite, mais la charge des feuillets est faible et compensée par des cations hydratés (Ca²⁺, Na⁺) : l'eau s'engouffre entre les feuillets, qui s'écartent — la montmorillonite (découverte à Montmorillon, Vienne !) peut absorber plusieurs fois sa masse d'eau. Les bentonites sodiques gonflent jusqu'à 15–20 fois leur volume sec.",
    origine: "Néoformation & transformation",
    origineDetail: "Néoformée là où les cations et la silice restent sur place : milieux confinés, mal drainés, alcalins — dépressions, plaines, climats à saisons contrastées (« bisiallitisation »). Aussi produite directement par l'altération des roches basiques (basaltes, gabbros) et du verre volcanique, ou par transformation de vermiculites et chlorites.",
    contexte: "Bas de versants, vertisols, marais ; altération des basaltes du Massif central ; argiles sédimentaires du Bassin parisien et du Nord (argile verte de Romainville, Argile des Flandres de l'Yprésien) ; terreforts du Lauragais.",
    pedologie: "CEC énorme (80–150 cmol⁺/kg) : réservoir de fertilité chimique. Mais le retrait-gonflement fissure les sols en été (vertisols) et les maisons : c'est le fameux aléa « RGA » qui coûte ~1 milliard €/an d'indemnisations en France. Rétention d'eau spectaculaire mais eau en partie inutilisable par les plantes (trop liée).",
    rochesSources: ["basalte", "gabbro", "pouzzolane", "trachyandesite", "marne", "argile", "peridotite", "serpentinite"],
    usages: "Bentonite : boues de forage, litières pour chats, étanchéité des décharges et bassins, moules de fonderie, clarification du vin.",
    wikipedia: "https://fr.wikipedia.org/wiki/Smectite",
    interfoliaire: "H₂O + Ca²⁺/Na⁺",
  },
  {
    id: "vermiculite", nom: "Vermiculite", swatch: "#b98b4e",
    formule: "(Mg,Fe)₃(Si,Al)₄O₁₀(OH)₂ · 4H₂O",
    type: "2:1 (T-O-T)", espacement: "14,36 Å à l'air, 14,81 Å dans l'eau — gonflement limité (2 couches d'eau max)", chargeFoliaire: "0,6–0,9",
    cecMin: 100, cecMax: 160, surfMin: 400, surfMax: 700, eauMin: 100, eauMax: 300,
    gonflement: "Modéré (limité)", gonflementNiveau: 2,
    description: "La fille des micas. Quand la biotite perd son potassium interfoliaire, remplacé par du magnésium hydraté, elle devient vermiculite : charge foliaire encore forte, donc gonflement bridé (deux couches d'eau maximum), mais la CEC la plus élevée de toutes les argiles.",
    origine: "Transformation",
    origineDetail: "Presque toujours issue de la transformation sur place des micas (surtout biotite) et des chlorites : le K⁺ s'en va, l'espace s'hydrate, mais l'ossature du mica demeure. Étape classique dans les sols tempérés (8–15 °C) sur granite, gneiss et micaschiste — souvent en route vers les smectites ou les interstratifiés.",
    contexte: "Sols acides tempérés sur roches cristallines (Massif central, Bretagne, Vosges).",
    pedologie: "CEC record (100–160 cmol⁺/kg) : excellente rétention des cations nutritifs. Comme l'illite, elle peut fixer K⁺ et NH₄⁺ entre ses feuillets. Présente en quantité modeste mais rôle chimique majeur dans les sols sur socle.",
    rochesSources: ["granite", "gneiss", "micaschiste", "gabbro"],
    usages: "Substrats horticoles (exfoliée), isolation, protection incendie.",
    wikipedia: "https://fr.wikipedia.org/wiki/Vermiculite",
    interfoliaire: "Mg²⁺ hydratés",
  },
  {
    id: "chlorite", nom: "Chlorite", swatch: "#6f8f72",
    formule: "(Mg,Fe)₅Al(AlSi₃O₁₀)(OH)₈",
    type: "2:1:1 (T-O-T + feuillet brucitique)", espacement: "14 Å — fixe (soudé par Mg(OH)₂)", chargeFoliaire: "élevée mais neutralisée",
    cecMin: 5, cecMax: 40, surfMin: 20, surfMax: 80, eauMin: 30, eauMax: 60,
    gonflement: "Nul", gonflementNiveau: 0,
    description: "L'argile verte des roches métamorphiques. Un sandwich T-O-T comme l'illite, mais l'espace interfoliaire est occupé par un feuillet continu d'hydroxyde de magnésium (type brucite) qui soude l'ensemble : pas de gonflement, pas d'échange interfoliaire. C'est elle qui verdit schistes, ardoises et « pierres vertes » alpines.",
    origine: "Héritage",
    origineDetail: "Héritée des roches métamorphiques de bas grade (schistes, ardoises, serpentinites) et de l'altération hydrothermale des minéraux ferromagnésiens. Dans les sols, elle est un état transitoire : l'oxydation de son fer et la dissolution du feuillet brucitique la transforment en vermiculite puis en smectites.",
    contexte: "Sols jeunes de montagne, éboulis de schistes, sédiments issus de massifs anciens peu altérés (Alpes, Pyrénées, ardoises d'Anjou et des Ardennes).",
    pedologie: "CEC faible à modérée (5–40 cmol⁺/kg). Sa disparition progressive d'un profil de sol, de bas en haut, est un excellent traceur de l'intensité de l'altération.",
    rochesSources: ["ardoise", "micaschiste", "serpentinite", "gabbro"],
    usages: "Peu d'usages directs ; sa cousine massive, la pierre ollaire, fait poêles et éviers.",
    wikipedia: "https://fr.wikipedia.org/wiki/Chlorite_(min%C3%A9ral)",
    interfoliaire: "feuillet Mg(OH)₂",
  },
  {
    id: "interstratifies", nom: "Interstratifiés (illite/smectite)", swatch: "#a9a08c",
    formule: "alternance de feuillets illite et smectite",
    type: "2:1 mixte (I/S, régulier ou aléatoire)", espacement: "10–17 Å — irrégulier", chargeFoliaire: "mixte",
    cecMin: 30, cecMax: 90, surfMin: 150, surfMax: 500, eauMin: 80, eauMax: 300,
    gonflement: "Variable (partiel)", gonflementNiveau: 2,
    description: "Des argiles « mille-feuilles » où alternent, dans un même cristal, des feuillets de type illite (verrouillés au K⁺) et de type smectite (gonflants). Ni tout à fait l'une, ni tout à fait l'autre : leurs propriétés sont intermédiaires et évoluent avec la proportion de chaque type.",
    origine: "Transformation (étapes intermédiaires)",
    origineDetail: "Ce sont les instantanés d'une transformation en cours : smectite → illite lors de l'enfouissement (diagenèse), ou illite/micas → smectite lors de l'altération dans les sols. Le pourcentage de feuillets gonflants sert de thermomètre géologique aux sédimentologues.",
    contexte: "Omniprésents dans les sols tempérés français et les bassins sédimentaires — la plupart des « argiles » d'un sol de limon en contiennent.",
    pedologie: "Propriétés intermédiaires (CEC 30–90 cmol⁺/kg, gonflement partiel). Leur abondance module l'aléa retrait-gonflement des terrains argileux, cartographié par le BRGM.",
    rochesSources: ["loess", "marne", "argile", "granite", "gneiss"],
    usages: "Pas d'usage spécifique ; étudiés comme marqueurs de diagenèse.",
    wikipedia: "https://fr.wikipedia.org/wiki/Min%C3%A9raux_argileux",
    interfoliaire: "K⁺ / H₂O alternés",
  },
  {
    id: "glauconite", nom: "Glauconite", swatch: "#5c7d5a",
    formule: "(K,Na)(Fe³⁺,Al,Mg)₂(Si,Al)₄O₁₀(OH)₂",
    type: "2:1 (mica ferrifère)", espacement: "10 Å — fixe", chargeFoliaire: "≈ 0,8",
    cecMin: 20, cecMax: 40, surfMin: 60, surfMax: 100, eauMin: 40, eauMax: 80,
    gonflement: "Faible", gonflementNiveau: 1,
    description: "L'argile verte des fonds marins. Cousine ferrifère de l'illite, elle cristallise en petits granules vert bouteille dans les sédiments marins peu profonds, là où la matière organique crée des micro-niches pauvres en oxygène. Elle verdit les « sables verts » crétacés et le tuffeau.",
    origine: "Néoformation marine",
    origineDetail: "Un des rares minéraux qu'on voit se former aujourd'hui au fond des mers (plateau continental, 50–500 m) : elle grandit dans les tests de foraminifères et les pelotes fécales, en dizaines de milliers d'années. Sa présence dans une roche = certificat d'origine marine.",
    contexte: "Sédiments marins condensés, sables verts et argile du Gault de l'Albien (Aube, pays de Bray), craies et tuffeaux glauconieux.",
    pedologie: "Libère lentement son potassium en s'altérant : les sables verts ont été épandus comme engrais potassique naturel au XIXᵉ siècle. Donne des sols légèrement verdâtres, assez fertiles.",
    rochesSources: ["tuffeau", "craie", "sable"],
    usages: "Engrais potassique historique, pigment (terre verte des peintres, de Vérone et de Brentonico).",
    wikipedia: "https://fr.wikipedia.org/wiki/Glauconie",
    interfoliaire: "K⁺ fixés",
  },
];

// ---------- Codes des cartes géologiques (notation BRGM) ----------
const NOTATION_GENERALE = [
  { code: "Fz / Fy / Fx…", sens: "Alluvions fluviatiles : z = récentes (fond de vallée actuel), y = basses terrasses, x, w… = terrasses de plus en plus anciennes et hautes" },
  { code: "C / E / Œ / LP", sens: "Colluvions / éboulis / lœss / limons des plateaux" },
  { code: "Gx, Gy / D / T / X", sens: "Dépôts glaciaires (moraines) / dunes / tourbes / remblais anthropiques" },
  { code: "p / m / g / e", sens: "Cénozoïque : Pliocène / Miocène / Oligocène / Éocène-Paléocène (le chiffre précise l'étage : g1 = Rupélien inf., e5 = Lutétien…)" },
  { code: "c / n", sens: "Crétacé supérieur (c1 Cénomanien → c6 Maastrichtien) / Crétacé inférieur (n)" },
  { code: "j / l / t", sens: "Jurassique moyen-sup. (Dogger-Malm) / Lias / Trias" },
  { code: "r / h / d / s / o / k", sens: "Permien / Carbonifère (h = houiller) / Dévonien / Silurien / Ordovicien / Cambrien" },
  { code: "γ  δ  θ", sens: "Plutoniques : granites / diorites / gabbros (lettres grecques)" },
  { code: "β  ρ  τ  α  π", sens: "Volcaniques & manteau : basaltes / rhyolites / trachytes / andésites / péridotites" },
  { code: "ζ  ξ  Σ", sens: "Métamorphiques : gneiss / micaschistes / serpentinites (usage variable selon les feuilles)" },
  { code: "Exposants & suffixes", sens: "Précisent le faciès local : g1AR = Rupélien basal, faciès « Argiles vertes de Romainville » ; t1 = grès vosgien du Trias inférieur…" },
];

// ---------- Extensions par roche ----------
// codes : exemples de notations rencontrées sur les cartes (varient selon les feuilles !)
// mineraux : [id, % typique] — argiles : minéraux argileux produits par altération
const ROCHE_EXTRAS = {
  calcaire: {
    codes: [
      { code: "j1–j9", sens: "calcaires du Jurassique (ex. j2 Bajocien des Causses)" },
      { code: "n4U", sens: "calcaires urgoniens (Barrémien-Aptien) du Vercors, selon feuilles" },
      { code: "e5", sens: "Lutétien : calcaire grossier de Paris" },
    ],
    mineraux: [["calcite", 95], ["quartz", 2], ["illite_m", 2], ["goethite", 1]],
    argiles: ["illite", "smectites", "kaolinite"],
    argilesNote: "Les argiles des calcaires sont le résidu insoluble hérité (illite dominante, un peu de smectites et kaolinite) : concentrées par dissolution, elles forment la terra rossa et les argiles de décalcification.",
  },
  craie: {
    codes: [{ code: "c1–c6", sens: "c1 Cénomanien → c6 Maastrichtien (ex. c3 craie coniacienne)" }],
    mineraux: [["calcite", 96], ["calcedoine", 2], ["illite_m", 1], ["glauconie", 1]],
    argiles: ["smectites", "illite", "glauconite"],
    argilesNote: "Le résidu de la craie est riche en smectites héritées de la mer crétacée ; l'argile à silex des plateaux en dérive, enrichie en silex par dissolution.",
  },
  tuffeau: {
    codes: [{ code: "c2", sens: "Turonien du Val de Loire (tuffeau blanc, tuffeau jaune)" }],
    mineraux: [["calcite", 50], ["opale", 20], ["quartz", 10], ["glauconie", 10], ["muscovite", 5], ["smectites_m", 5]],
    argiles: ["glauconite", "smectites"],
    argilesNote: "La glauconie (néoformée dans la mer turonienne) et des smectites accompagnent l'opale, ce qui rend le tuffeau léger et fragile.",
  },
  dolomie: {
    codes: [{ code: "t / j", sens: "selon l'âge : Trias alpin (t) ou Jurassique des Causses (ex. j5-j6 dolomies de Montpellier-le-Vieux)" }],
    mineraux: [["dolomite", 90], ["calcite", 5], ["illite_m", 4], ["goethite", 1]],
    argiles: ["illite", "smectites"],
    argilesNote: "Résidu insoluble hérité, comme pour le calcaire, mais dilué dans le sable dolomitique.",
  },
  marne: {
    codes: [
      { code: "j3–j5", sens: "marnes oxfordiennes (« Terres Noires » : j1-j3 selon feuilles alpines)" },
      { code: "j7-j8", sens: "marnes kimméridgiennes de Chablis" },
    ],
    mineraux: [["calcite", 50], ["illite_m", 25], ["smectites_m", 15], ["quartz", 8], ["pyrite", 2]],
    argiles: ["illite", "smectites", "interstratifies"],
    argilesNote: "La moitié argileuse de la marne (illite + smectites + interstratifiés) est directement héritée : la dissolution du carbonate la libère telle quelle dans les sols et les rivières.",
  },
  argile: {
    codes: [
      { code: "g1AR", sens: "Argiles vertes de Romainville (Rupélien basal, Bassin de Paris)" },
      { code: "e3", sens: "argiles plastiques du Sparnacien (faciès notés e3AP selon feuilles)" },
      { code: "n7", sens: "argiles du Gault (Albien), notation variable selon feuilles" },
    ],
    mineraux: [["illite_m", 40], ["smectites_m", 25], ["kaolinite_m", 15], ["quartz", 15], ["pyrite", 5]],
    argiles: ["illite", "smectites", "kaolinite", "interstratifies"],
    argilesNote: "Une argilite est déjà un concentré d'argiles héritées : sa composition (illite/smectite/kaolinite) raconte le climat et les reliefs qui l'ont nourrie. Les argiles plastiques éocènes, kaoliniques, témoignent d'un Bassin parisien tropical.",
  },
  sable: {
    codes: [
      { code: "g2", sens: "Stampien : sables de Fontainebleau" },
      { code: "Fz / Fy", sens: "alluvions sableuses récentes / terrasses" },
      { code: "D", sens: "dunes (Landes, littoraux)" },
    ],
    mineraux: [["quartz", 95], ["orthose", 2], ["muscovite", 1], ["magnetite", 1], ["goethite", 1]],
    argiles: [],
    argilesNote: "Un sable quartzeux pur ne produit quasiment pas d'argiles : il n'y a plus rien à hydrolyser. Seuls des films de goethite colorent les grains.",
  },
  gres: {
    codes: [
      { code: "t1", sens: "grès vosgien (Buntsandstein, Trias inférieur)" },
      { code: "o2", sens: "grès armoricain (Ordovicien, Bretagne)" },
      { code: "g2", sens: "grès de Fontainebleau (dalles silicifiées dans les sables stampiens)" },
    ],
    mineraux: [["quartz", 85], ["orthose", 5], ["calcedoine", 4], ["muscovite", 2], ["goethite", 4]],
    argiles: ["kaolinite", "illite"],
    argilesNote: "Les grès libèrent surtout leur sable ; la kaolinite vient de l'altération des feldspaths accessoires et du ciment, l'illite des micas.",
  },
  conglomerat: {
    codes: [{ code: "e-g", sens: "poudingues paléogènes (ex. poudingues de Palassou, notés e selon feuilles pyrénéennes)" }],
    mineraux: [["quartz", 50], ["calcite", 25], ["orthose", 10], ["illite_m", 10], ["goethite", 5]],
    argiles: ["illite", "kaolinite"],
    argilesNote: "Les argiles produites dépendent de la nature des galets et de la matrice — souvent illite héritée et kaolinite des feldspaths.",
  },
  loess: {
    codes: [{ code: "Œ / LP", sens: "lœss / limons des plateaux (Quaternaire)" }],
    mineraux: [["quartz", 70], ["calcite", 12], ["illite_m", 10], ["plagioclases", 5], ["muscovite", 3]],
    argiles: ["illite", "interstratifies", "smectites"],
    argilesNote: "Les argiles du lœss (illite + interstratifiés) sont héritées du broyage glaciaire ; la décarbonatation puis la « brunification » les enrichissent lentement en interstratifiés gonflants.",
  },
  gypse: {
    codes: [
      { code: "e7", sens: "Ludien : masses et marnes du gypse parisien (Montmartre)" },
      { code: "t", sens: "Keuper gypsifère (Lorraine, Provence, Alpes)" },
    ],
    mineraux: [["gypse_m", 92], ["calcite", 4], ["illite_m", 4]],
    argiles: ["illite"],
    argilesNote: "Le gypse ne fabrique pas d'argiles : celles qu'on trouve dans ses sols sont les impuretés marneuses libérées par dissolution.",
  },
  sel: {
    codes: [{ code: "t (profondeur)", sens: "Keuper salifère — jamais affleurant, connu par forages et mines" }],
    mineraux: [["halite_m", 95], ["gypse_m", 2], ["illite_m", 3]],
    argiles: ["illite"],
    argilesNote: "Comme le gypse : dissolution totale, les argiles résiduelles sont des impuretés.",
  },
  houille: {
    codes: [{ code: "h4-h5", sens: "Westphalien-Stéphanien (Carbonifère supérieur houiller)" }],
    mineraux: [["matorg", 80], ["illite_m", 10], ["quartz", 5], ["pyrite", 5]],
    argiles: ["illite", "kaolinite"],
    argilesNote: "Les cendres du charbon contiennent illite et kaolinite héritées des sols carbonifères ; les niveaux volcaniques intercalés (tonsteins) sont de la kaolinite quasi pure.",
  },
  tourbe: {
    codes: [{ code: "T (ou FzT)", sens: "tourbes et marais tourbeux holocènes" }],
    mineraux: [["matorg", 92], ["quartz", 4], ["illite_m", 4]],
    argiles: [],
    argilesNote: "La tourbe est organique : pas d'argiles produites, seulement des poussières minérales piégées.",
  },
  meuliere: {
    codes: [{ code: "g1-m1", sens: "meulières de Brie (g1) et de Montmorency, meulière de Beauce (m1) — selon feuilles franciliennes" }],
    mineraux: [["calcedoine", 85], ["opale", 8], ["smectites_m", 5], ["goethite", 2]],
    argiles: ["smectites", "kaolinite"],
    argilesNote: "Les « argiles à meulière » rousses qui l'emballent sont le résidu smectitique et kaolinique de la dissolution des calcaires lacustres silicifiés.",
  },
  bauxite: {
    codes: [{ code: "Bx", sens: "poches de bauxite karstique (notation locale, feuilles provençales)" }],
    mineraux: [["gibbsite", 45], ["hematite", 20], ["kaolinite_m", 22], ["goethite", 10], ["quartz", 3]],
    argiles: ["kaolinite"],
    argilesNote: "La bauxite est déjà au-delà des argiles : l'allitisation a détruit même la kaolinite pour ne laisser que gibbsite et oxydes. La kaolinite restante marque les zones les moins lessivées.",
  },
  granite: {
    codes: [
      { code: "γ", sens: "granites (γ² à γ⁵ selon le faciès : porphyroïde, leucogranite…)" },
      { code: "γ³", sens: "exemple : granites porphyroïdes varisques" },
    ],
    mineraux: [["orthose", 35], ["quartz", 30], ["plagioclases", 25], ["biotite", 7], ["muscovite", 3]],
    argiles: ["kaolinite", "illite", "vermiculite", "interstratifies"],
    argilesNote: "En climat tempéré (8–15 °C), l'arène granitique fabrique illite + vermiculite (biotite) et des interstratifiés ; en climat tropical (≥ 22 °C) sur sol drainé, l'hydrolyse pousse jusqu'à la kaolinite — les kaolins du Limousin et de Bretagne, matière première de la porcelaine.",
  },
  gabbro: {
    codes: [{ code: "θ", sens: "gabbros (ophiolites alpines, massifs varisques)" }],
    mineraux: [["plagioclases", 55], ["pyroxenes", 35], ["olivine", 5], ["magnetite", 5]],
    argiles: ["smectites", "vermiculite", "chlorite"],
    argilesNote: "Plagioclases calciques et pyroxènes donnent surtout des smectites ; chlorite héritée des zones hydrothermalisées.",
  },
  basalte: {
    codes: [{ code: "β", sens: "basaltes et coulées associées (βm : basaltes des plateaux, selon feuilles)" }],
    mineraux: [["plagioclases", 45], ["pyroxenes", 30], ["olivine", 15], ["magnetite", 7], ["verre", 3]],
    argiles: ["smectites"],
    argilesNote: "Le basalte est LA machine à smectites : olivine, pyroxènes, plagioclases calciques et verre livrent silice et magnésium sur place. Sous les tropiques, le lessivage pousse plus loin, vers kaolinite et gibbsite.",
  },
  trachyandesite: {
    codes: [{ code: "α, τα", sens: "andésites / trachyandésites des stratovolcans (notations variables : Cantal, Mont-Dore)" }],
    mineraux: [["plagioclases", 50], ["amphiboles", 15], ["pyroxenes", 15], ["sanidine", 10], ["biotite", 5], ["magnetite", 5]],
    argiles: ["smectites", "interstratifies"],
    argilesNote: "Smectites dominantes (via amphiboles et plagioclases), avec halloysite et allophanes dans les jeunes andosols.",
  },
  trachyte: {
    codes: [{ code: "τ", sens: "trachytes (dômes : puy de Dôme, Sancy)" }],
    mineraux: [["sanidine", 60], ["plagioclases", 20], ["amphiboles", 10], ["biotite", 5], ["magnetite", 3], ["quartz", 2]],
    argiles: ["kaolinite", "illite", "smectites"],
    argilesNote: "La sanidine s'hydrolyse en kaolinite/illite ; les faciès vitreux et ponces donnent plutôt smectites et allophanes.",
  },
  rhyolite: {
    codes: [{ code: "ρ", sens: "rhyolites et ignimbrites permiennes (Estérel : ρ1, ρ2… selon coulées)" }],
    mineraux: [["sanidine", 40], ["quartz", 30], ["plagioclases", 15], ["verre", 10], ["biotite", 5]],
    argiles: ["kaolinite", "illite"],
    argilesNote: "Bilan granitique : kaolinite et illite des feldspaths, sable quartzeux résiduel.",
  },
  pouzzolane: {
    codes: [{ code: "sc / βsc", sens: "cônes de scories stromboliens (notation locale, chaîne des Puys)" }],
    mineraux: [["verre", 50], ["pyroxenes", 20], ["olivine", 15], ["magnetite", 10], ["plagioclases", 5]],
    argiles: ["smectites"],
    argilesNote: "Le verre s'altère d'abord en allophanes (gels alumino-silicatés des andosols) qui évoluent vers halloysite puis smectites.",
  },
  peridotite: {
    codes: [{ code: "π", sens: "péridotites (lherzolites ariégeoises), notation variable" }],
    mineraux: [["olivine", 60], ["pyroxenes", 35], ["magnetite", 5]],
    argiles: ["smectites", "chlorite"],
    argilesNote: "Smectites magnésiennes (saponite) et serpentine d'altération ; les sols qui en dérivent, riches en Ni et Mg, portent une flore spécialisée.",
  },
  gneiss: {
    codes: [{ code: "ζ", sens: "gneiss et anatexites (ζ, ζγ selon degré de fusion) — usage variable selon feuilles" }],
    mineraux: [["quartz", 30], ["orthose", 25], ["plagioclases", 25], ["biotite", 12], ["muscovite", 5], ["grenat", 3]],
    argiles: ["kaolinite", "illite", "vermiculite"],
    argilesNote: "Comme le granite : illite/vermiculite en climat tempéré (8–15 °C), kaolinite si l'hydrolyse est poussée.",
  },
  micaschiste: {
    codes: [{ code: "ξ", sens: "micaschistes (ξ, ξS schistes lustrés selon feuilles alpines)" }],
    mineraux: [["muscovite", 35], ["quartz", 30], ["biotite", 15], ["grenat", 8], ["chlorite_m", 7], ["plagioclases", 5]],
    argiles: ["illite", "vermiculite", "chlorite"],
    argilesNote: "Les micas font de l'illite et de la vermiculite ; la chlorite est héritée puis se transforme à son tour.",
  },
  ardoise: {
    codes: [{ code: "o", sens: "schistes ardoisiers ordoviciens (ex. o2-o3 schistes d'Angers)" }],
    mineraux: [["illite_m", 45], ["quartz", 25], ["chlorite_m", 20], ["pyrite", 5], ["matorg", 5]],
    argiles: ["illite", "chlorite", "vermiculite"],
    argilesNote: "L'ardoise rend ses argiles quasi telles quelles : séricite (illite) et chlorite, qui évoluent en vermiculite dans les sols.",
  },
  quartzite: {
    codes: [
      { code: "o2", sens: "quartzites du grès armoricain (Ordovicien)" },
      { code: "t", sens: "quartzites triasiques du Briançonnais" },
    ],
    mineraux: [["quartz", 95], ["muscovite", 3], ["goethite", 2]],
    argiles: [],
    argilesNote: "Quasi aucune argile : il n'y a que du quartz. Les sols sur quartzite sont squelettiques et acides.",
  },
  marbre: {
    codes: [{ code: "cp / M", sens: "cipolins et marbres (notations locales selon feuilles pyrénéennes et alpines)" }],
    mineraux: [["calcite", 96], ["dolomite", 2], ["muscovite", 1], ["matorg", 1]],
    argiles: ["illite"],
    argilesNote: "Résidu infime d'illite et d'oxydes — ce sont eux qui dessinent les veines colorées du marbre.",
  },
  serpentinite: {
    codes: [{ code: "Σ", sens: "serpentinites (ophiolites) — notation variable selon feuilles" }],
    mineraux: [["serpentine", 85], ["magnetite", 8], ["pyroxenes", 4], ["olivine", 3]],
    argiles: ["smectites", "chlorite"],
    argilesNote: "Smectites magnésiennes et chlorite ; beaucoup de fer part en magnétite puis goethite — sols sombres, magnésiens, à flore « serpentinicole ».",
  },
};
