// ============================================================
// CLASSE X — COMPOSÉS ORGANIQUES (Strunz X)
// Chantier F.6 (29/09/2026) : toutes les espèces de la liste officielle de l'IMA (janvier 2026) dont
// la formule contient un groupement organique — 85 espèces, plus 2 « douteuses » (statut Q) citées en note.
// Sources : IMA Master List (2026-01) ; Handbook of Mineralogy (Anthony et al., MSA) ; articles de
// description (Mineralogical Magazine, American Mineralogist, European Journal of Mineralogy, Canadian
// Journal of Mineralogy and Petrology) ; Wikipédia FR/EN/DE ; Planet-Terre (septarias du Bassin vocontien).
// Champs sans mesure publiée : durete / densite à null (la ligne n'est pas affichée), textes « non mesuré ».
// Nouveaux champs propres à cette classe : ima (statut et numéro IMA), densiteCalc (densité calculée
// d'après la maille, faute de mesure), sources (références de la fiche, affichées en bas de page).
// ============================================================

(function () {
  const HOM = (n) => `<i>Handbook of Mineralogy</i> (J.W. Anthony et al., Mineralogical Society of America), fiche « ${n} ».`;
  const IMA = "Liste officielle des minéraux de l'IMA-CNMNC, version de janvier 2026 (formule, statut, année).";
  const ROWLEY = "A.R. Kampf et al., série d'articles sur les minéraux du guano de chauves-souris de la mine Rowley (Arizona), <i>Mineralogical Magazine</i> et <i>American Mineralogist</i>, 2019-2025.";
  const CATALINA = "H. Yang et al., descriptions des glycolates des Santa Catalina Mountains (Arizona), <i>American Mineralogist</i> 107 (2022) 509 et 110 (2025) 1481 ; <i>Canadian Journal of Mineralogy and Petrology</i> 62-64 (2024-2026) ; bulletins CNMNC 85-88.";
  const PICA = "Guano de Pabellón de Pica (Chili) : N.V. Chukanov et al. (chanabayaïte 2015, triazolite 2018), A.R. Kampf et al. (bojarite 2020, pabellóndepicaïte 2025), <i>Mineralogical Magazine</i>.";
  const VOCONTIEN = "B. Barailler (2023), « Les cristallisations rencontrées dans les septarias », Planet-Terre (ENS de Lyon).";
  const ALUM = "R.C. Rouse, D.R. Peacor et al. (1999, 2001), coskrénite, levinsonite et zugshunstite d'Alum Cave Bluff (Tennessee), <i>Canadian Mineralogist</i>.";

  Object.assign(MINERAUX, {
    // ─────────────────────────── OXALATES : groupe de la humboldtine ───────────────────────────
    humboldtine: {
      nom: "Humboldtine", formule: "Fe²⁺(C₂O₄)·2H₂O", famille: "Oxalate de fer (groupe de la humboldtine)",
      systeme: "monoclinique", durete: 1.75, densite: 2.28,
      clivage: "parfait {110} ; imparfait {100} et {010}", eclat: "mat à résineux",
      couleurs: "jaune à jaune ambré",
      contexte: "Enduits et masses fibreuses dans les fissures des lignites (Bohême : Korozluky près de Bílina, Lužice ; Allemagne : Grossalmerode) ; très rarement dans des pegmatites et des filons (île d'Elbe).",
      stabilite: 2, swatch: "#d9a53a",
      devient: "Peu soluble dans l'eau ; évolution à l'air non documentée.",
      ima: "espèce reconnue avant l'IMA (G), décrite en 1821",
      note: "Premier oxalate reconnu comme minéral : décrite en 1821 par Mariano de Rivero dans un lignite altéré de Bohême, elle porte le nom du naturaliste Alexander von Humboldt. Elle donne son nom au groupe des oxalates dihydratés de même structure : le fer y est remplacé par le manganèse (lindbergite), le magnésium (glushinskite), le zinc (katsarosite) ou le nickel (andreybulakhite). Dureté 1,5 à 2 : l'ongle la raye. L'acide oxalique vient de la décomposition de la matière végétale du charbon.",
      sources: [HOM("Humboldtine")],
    },
    lindbergite: {
      nom: "Lindbergite", formule: "Mn(C₂O₄)·2H₂O", famille: "Oxalate de manganèse (groupe de la humboldtine)",
      systeme: "monoclinique", durete: 2.5, densite: 2.1,
      clivage: "parfait {010}", eclat: "vitreux", couleurs: "blanc, agrégats blanc grisâtre",
      contexte: "Minéral secondaire des pegmatites granitiques (localité type : mine Boca Rica, Minas Gerais, Brésil) ; aussi dans d'anciennes mines de manganèse suisses (Parsettens, Grisons) et en Forêt-Noire.",
      stabilite: 2, swatch: "#ece8e2",
      devient: "Non documenté.",
      ima: "IMA 2003-029",
      note: "Elle se forme souvent en perdant de l'eau à partir de la falottaïte (le trihydrate) : ses cristaux gardent alors la forme de leur prédécesseur (pseudomorphose). Une origine liée à des lichens a aussi été décrite. Elle honore Marie Louise Lindberg, minéralogiste de l'US Geological Survey qui décrivit plusieurs phosphates des pegmatites voisines.",
      sources: [HOM("Lindbergite")],
    },
    glushinskite: {
      nom: "Glushinskite", formule: "Mg(C₂O₄)·2H₂O", famille: "Oxalate de magnésium (groupe de la humboldtine)",
      systeme: "monoclinique", durete: 2, densite: 1.85,
      clivage: "non observé (cristaux de quelques micromètres)", eclat: "subadamantin", couleurs: "blanc crème, incolore",
      contexte: "Sous le lichen <i>Lecanora atra</i> qui colonise une serpentinite (Mill of Johnston, Écosse) ; veinules dans des lignites imprégnés d'acide acétique naturel (Iakoutie) ; plantes du désert (vallée du Jourdain).",
      stabilite: 1, swatch: "#efe9d8",
      devient: "Soluble dans l'eau : ne se conserve qu'à l'abri de la pluie.",
      ima: "redéfinie en 1987 (Rd)",
      note: "L'oxalate du lichen des serpentinites : l'acide oxalique sécrété par le lichen attaque les minéraux magnésiens de la roche et le magnésium libéré cristallise sur place en grains de 5 µm (Wilson et al. 1980). Le Handbook la juge « probablement plus commune que ne le disent les localités connues ». Nommée pour P.I. Glushinskii, géologue du charbon.",
      sources: [HOM("Glushinskite"), "M.J. Wilson, D. Jones et J.D. Russell (1980), « Glushinskite, a naturally occurring magnesium oxalate », <i>Mineralogical Magazine</i> 43, 837."],
    },
    katsarosite: {
      nom: "Katsarosite", formule: "Zn(C₂O₄)·2H₂O", famille: "Oxalate de zinc (groupe de la humboldtine)",
      systeme: "monoclinique", durete: null, densite: null,
      clivage: "non mesuré (grains de 30 µm)", eclat: "non décrit", couleurs: "blanc ; jaune quand elle contient du fer",
      contexte: "Mine Esperanza, district du Laurion (Attique, Grèce), dans les minerais de zinc exploités depuis l'Antiquité.",
      stabilite: 2, swatch: "#f1efe6",
      devient: "Non documenté.",
      ima: "IMA 2020-014",
      note: "L'équivalent zincifère de la humboldtine, en grains arrondis d'une trentaine de micromètres, blancs quand ils sont purs et jaunes quand du fer remplace une partie du zinc. C'est le deuxième oxalate de zinc connu après l'altérite.",
      sources: [IMA, "Wikipédia EN, « Katsarosite »."],
    },
    andreybulakhite: {
      nom: "Andreybulakhite", formule: "Ni(C₂O₄)·2H₂O", famille: "Oxalate de nickel (groupe de la humboldtine)",
      systeme: "monoclinique", durete: null, densite: 2.42, densiteCalc: true,
      clivage: "non mesuré (cristaux de 30 µm)", eclat: "vitreux", couleurs: "incolore à vert pâle",
      contexte: "Dans les apothécies (organes reproducteurs) du lichen <i>Lecanora</i> cf. <i>polytropa</i> qui couvre un minerai de cuivre-nickel oxydé : gisement Nyud-II, massif de Montchegorsk, presqu'île de Kola (Russie).",
      stabilite: 2, swatch: "#dfe9d6",
      devient: "Non documenté.",
      ima: "IMA 2023-037",
      note: "Premier oxalate de nickel naturel (2025). Il cristallise à l'intérieur même du lichen, à partir du nickel que l'acide oxalique a arraché au minerai : un cas limite de la définition du minéral, accepté par l'IMA. Dureté non mesurable sur des grains aussi petits (probablement 1,5 à 2, comme les autres membres du groupe). Nommé pour Andreï Boulakh (1933-2020), minéralogiste de Saint-Pétersbourg.",
      sources: ["O.S. Vereshchagin et al. (2025), « Andreybulakhite, Ni(C₂O₄)·2H₂O, the first natural nickel oxalate », <i>European Journal of Mineralogy</i> 37, 63-74."],
    },

    // ─────────────────────────── OXALATES DE CALCIUM ───────────────────────────
    whewellite: {
      nom: "Whewellite", formule: "Ca(C₂O₄)·H₂O", famille: "Oxalate de calcium",
      systeme: "monoclinique", durete: 2.75, densite: 2.22,
      clivage: "bon {101} ; imparfait {010}", eclat: "vitreux, nacré sur {010}",
      couleurs: "incolore, blanc, parfois jaune ou brun pâle",
      contexte: "Filons hydrothermaux de basse température, géodes et septarias, houillères (Burgk près de Dresde ; Kladno, Bohême). En France : septarias des marnes callovo-oxfordiennes de Condorcet (Drôme), en cristaux d'environ 1 cm.",
      stabilite: 3, swatch: "#efeadf",
      devient: "Presque insoluble ; dans les sols, des bactéries s'en nourrissent et la transforment en calcite (voie oxalate-carbonate).",
      ima: "approuvée en 1967 (procédure spéciale)",
      note: "Le plus répandu des minéraux organiques. Il honore William Whewell (1794-1866), savant de Cambridge qui inventa le mot « scientist » et proposa une notation des faces cristallines reprise par son successeur W.H. Miller : les indices de Miller qu'utilise cet atlas. Ses cristaux atteignent 23 cm et sont très souvent maclés en « cœur ». C'est aussi la substance de la plupart des calculs rénaux ; mais un calcul, fabriqué par le corps, n'est pas un minéral (définition de l'IMA, 1995).",
      sources: [HOM("Whewellite"), "R. Martin (1989), « La whewellite de Condorcet (Drôme, France) », <i>Le Cristallier suisse</i> 8, 301-333.", "E.H. Nickel (1995), « The definition of a mineral », <i>Canadian Mineralogist</i> 33, 689-690.", "G. Cailleau, O. Braissant et E.P. Verrecchia (2011), « Turning sunlight into stone: the oxalate-carbonate pathway in a tropical tree ecosystem », <i>Biogeosciences</i> 8, 1755-1767."],
    },
    weddellite: {
      nom: "Weddellite", formule: "Ca(C₂O₄)·2H₂O", famille: "Oxalate de calcium",
      systeme: "quadratique", durete: 4, densite: 1.94,
      clivage: "aucun signalé (cassure subconchoïdale)", eclat: "vitreux",
      couleurs: "incolore à blanc ; brun par impuretés organiques",
      contexte: "Cristaux formés dans la vase du fond de la mer de Weddell (Antarctique) et d'autres mers ; sédiments de tourbières et de lacs calcaires ; grottes à guano (Australie). Aussi dans les patines que les lichens déposent sur les calcaires et les marbres.",
      stabilite: 2, swatch: "#f3f1ea",
      devient: "À l'air, perd une molécule d'eau et devient de la whewellite, qui garde la forme du cristal.",
      ima: "espèce reconnue avant l'IMA (G), 1942",
      note: "Signalée en 1936 dans les boues de la mer de Weddell, nommée en 1942. Ses bipyramides carrées, vues d'en haut, ressemblent à une enveloppe : c'est ainsi qu'on les reconnaît au microscope dans les sédiments… et dans les urines. Instable, elle se transforme en whewellite dès qu'elle sèche, si bien que beaucoup de spécimens de collection ont changé d'espèce sans changer de forme.",
      sources: [HOM("Weddellite")],
    },
    caoxite: {
      nom: "Caoxite", formule: "Ca(C₂O₄)·3H₂O", famille: "Oxalate de calcium",
      systeme: "triclinique", durete: null, densite: 1.87, densiteCalc: true,
      clivage: "bon {010}", eclat: "vitreux", couleurs: "incolore",
      contexte: "Veinules recoupant des radiolarites (jaspes) à manganèse et baryum d'une ophiolite : mine de Cerchiara, val di Vara (Ligurie, Italie).",
      stabilite: 2, swatch: "#f2f0ea",
      devient: "Non documenté.",
      ima: "IMA 1996-012",
      note: "Troisième oxalate de calcium, le plus hydraté. Son nom a deux lectures : CAlcium OXalate, ou « Centennial Anniversary Of X-rays », centenaire de la découverte des rayons X par Röntgen (1895-1995), l'outil sans lequel aucune de ces espèces n'aurait pu être identifiée.",
      sources: [HOM("Caoxite")],
    },

    // ─────────────────────────── AUTRES OXALATES SIMPLES ───────────────────────────
    moolooite: {
      nom: "Moolooïte", formule: "Cu(C₂O₄)·nH₂O (n < 1)", famille: "Oxalate de cuivre",
      systeme: "orthorhombique", durete: null, densite: 3.43, densiteCalc: true,
      clivage: "non mesuré (cristaux de 4 µm)", eclat: "mat à cireux", couleurs: "vert turquoise, vert, bleu",
      contexte: "Affleurement de quartz de Mooloo Station (Australie-Occidentale), où le guano d'oiseaux a réagi avec des minéraux de cuivre secondaires. En France : Sainte-Marie-aux-Mines (Haut-Rhin), dans un puits de mine, près de racines d'arbres.",
      stabilite: 2, swatch: "#5fb3a6",
      devient: "Non documenté.",
      ima: "IMA 1980-082",
      note: "L'oxalate de cuivre : la matière organique (guano, racines, lichens) fournit l'acide oxalique, le minerai de cuivre altéré fournit le métal. Des lichens qui poussent sur des roches à sulfures de cuivre en fabriquent aussi. C'est l'une des rares espèces organiques signalées en France.",
      sources: [HOM("Moolooite"), "R.M. Clarke et I.R. Williams (1986), <i>Mineralogical Magazine</i> 50, 295-298."],
    },
    natroxalate: {
      nom: "Natroxalate", formule: "Na₂(C₂O₄)", famille: "Oxalate de sodium",
      systeme: "monoclinique", durete: 3, densite: 2.32,
      clivage: "parfait {100} ; net {001} et {221}", eclat: "vitreux", couleurs: "crème à jaune pâle, teinté de rose ou de vert",
      contexte: "Pegmatite altérée par des fluides chauds dans le massif alcalin de Lovozero (mont Alluaiv, presqu'île de Kola).",
      stabilite: 1, swatch: "#efe3c2",
      devient: "Soluble dans l'eau.",
      ima: "IMA 1994-053",
      note: "Un oxalate qui ne doit rien au vivant : il s'est formé à haute température dans une pegmatite très alcaline, comme la kyanoxalite (un feldspathoïde qui contient de l'oxalate). La preuve que le groupement C₂O₄ peut naître de la seule chimie des roches.",
      sources: [HOM("Natroxalate"), "O.S. Vereshchagin et al. (2025), <i>European Journal of Mineralogy</i> 37, 63-74 (discussion)."],
    },
    oxammite: {
      nom: "Oxammite", formule: "(NH₄)₂(C₂O₄)·H₂O", famille: "Oxalate d'ammonium",
      systeme: "orthorhombique", durete: 2.5, densite: 1.5,
      clivage: "net {001}", eclat: "non décrit", couleurs: "incolore à jaune pâle",
      contexte: "Guano d'oiseaux (îles Guañape, Pérou), de chauves-souris (grotte Petrogale, Australie-Occidentale) ; œufs et restes d'oiseaux subfossiles (Oman).",
      stabilite: 1, swatch: "#f1ecd9",
      devient: "Soluble dans l'eau : lessivée par la première pluie.",
      ima: "espèce reconnue avant l'IMA (G), 1870",
      note: "Son nom dit sa composition : OXalate d'AMMonium. Décrite en 1870 dans le guano péruvien ; le spécimen de référence a disparu dans l'incendie de l'université de Virginie en 1916.",
      sources: [HOM("Oxammite")],
    },
    falottaite: {
      nom: "Falottaïte", formule: "Mn(C₂O₄)·3H₂O", famille: "Oxalate de manganèse",
      systeme: "orthorhombique", durete: 2.5, densite: 1.92, densiteCalc: true,
      clivage: "aucun", eclat: "vitreux", couleurs: "incolore, devient blanc laiteux",
      contexte: "Anciennes mines de manganèse de Falotta, Parsettens et Tinzen (Oberhalbstein, Grisons, Suisse) : lentilles de minerai dans des radiolarites d'une ophiolite, attaquées par les acides de l'humus et des plantes.",
      stabilite: 1, swatch: "#f0ede6",
      devient: "En quelques mois, perd de l'eau et devient de la lindbergite, blanche et opaque.",
      ima: "IMA 2013-044",
      note: "Des cristaux transparents en forme de barque, jusqu'à 1 mm, qui blanchissent en quelques mois dans les collections : en perdant une molécule d'eau, ils se changent en lindbergite.",
      sources: [HOM("Falottaite")],
    },
    middlebackite: {
      nom: "Middlebackite", formule: "Cu₂(C₂O₄)(OH)₂", famille: "Oxalate basique de cuivre",
      systeme: "monoclinique", durete: 2, densite: 3.64, densiteCalc: true,
      clivage: "un clivage parfait", eclat: "vitreux", couleurs: "bleu",
      contexte: "Niveaux supérieurs de la carrière Iron Monarch (Middleback Range, Australie-Méridionale), dans un minerai de fer manganésifère précambrien altéré ; retrouvée à Val di Fiemme (Italie).",
      stabilite: 2, swatch: "#4e86c4",
      devient: "Non documenté.",
      ima: "IMA 2015-115",
      note: "Récoltée en 1990 dans un bloc de la carrière, elle a attendu vingt-cinq ans que sa structure soit résolue au synchrotron. L'oxalate provient de matière organique en décomposition, le cuivre de sulfures altérés.",
      sources: [HOM("Middlebackite"), "Wikipédia EN, « Middlebackite »."],
    },
    fiemmeite: {
      nom: "Fiemmeïte", formule: "Cu₂(C₂O₄)(OH)₂·2H₂O", famille: "Oxalate basique de cuivre",
      systeme: "monoclinique", durete: null, densite: 2.78,
      clivage: "presque parfait {010} ou {001}", eclat: "vitreux à cireux", couleurs: "bleu ciel",
      contexte: "Troncs d'arbres houillifiés dans un grès continental traversé par des solutions riches en cuivre, uranium et arsenic : col de San Lugano, Val di Fiemme (Trentin, Italie).",
      stabilite: 2, swatch: "#8cc4e6",
      devient: "Non documenté.",
      ima: "IMA 2017-115",
      note: "Née dans un gisement d'uranium de type « front d'oxydoréduction » : les bois fossiles du grès y ont servi à la fois de piège chimique pour les métaux et de source d'oxalate.",
      sources: [HOM("Fiemmeite")],
    },
    edwindavisite: {
      nom: "Edwindavisite", formule: "Cu(C₂O₄)(NH₃)", famille: "Oxalate de cuivre et d'ammoniac",
      systeme: "orthorhombique", durete: 2, densite: null,
      clivage: "parfait {100}", eclat: "non décrit", couleurs: "vert",
      contexte: "Mine Rowley (comté de Maricopa, Arizona), dans les dépôts laissés par le guano de chauves-souris après l'exploitation.",
      stabilite: 1, swatch: "#7fb58a",
      devient: "Non documenté.",
      ima: "IMA 2023-056",
      note: "Un oxalate de cuivre qui porte encore une molécule d'ammoniac venue de la décomposition du guano. Nommée pour F. Edwin Davis, collectionneur et exploitant actuel de la mine Rowley.",
      sources: ["H. Yang et al. (2025), « Edwindavisite, Cu(C₂O₄)(NH₃), a new oxalate mineral », <i>Mineralogical Magazine</i> 89, 535."],
    },

    // ─────────────────────────── OXALATES DOUBLES ───────────────────────────
    stepanovite: {
      nom: "Stépanovite", formule: "Na[Mg(H₂O)₆]Fe³⁺(C₂O₄)₃·3H₂O", famille: "Oxalate double de fer et de magnésium",
      systeme: "trigonal", durete: 2, densite: 1.69,
      clivage: "non signalé", eclat: "vitreux", couleurs: "vert",
      contexte: "Minces veinules dans le lignite de Tyllakh, delta de la Léna (Iakoutie polaire, Russie).",
      stabilite: 1, swatch: "#6f9a4a",
      devient: "Très soluble dans l'eau.",
      ima: "approuvée en 1967 (procédure spéciale)",
      note: "Avec la zhemchuzhnikovite, c'est un « réseau métal-organique » naturel (Huskić et al. 2016) : les ions oxalate relient les atomes de fer en une charpente ouverte, percée de canaux, semblable aux matériaux poreux que les chimistes fabriquent depuis les années 1990 pour stocker des gaz. Nommée pour P.I. Stepanov, géologue du charbon.",
      sources: [HOM("Stepanovite"), "I. Huskić, I.V. Pekov, S.V. Krivovichev et T. Friščić (2016), « Minerals with metal-organic framework structures », <i>Science Advances</i> 2, e1600621."],
    },
    zhemchuzhnikovite: {
      nom: "Zhemchuzhnikovite", formule: "Na[Mg(H₂O)₆]Al(C₂O₄)₃·3H₂O", famille: "Oxalate double d'aluminium et de magnésium",
      systeme: "trigonal", durete: 2, densite: 1.69,
      clivage: "bon {0001}", eclat: "vitreux",
      couleurs: "vert fumé à la lumière du jour, violet améthyste à la lumière artificielle",
      contexte: "Veinules dans un lignite naturellement imprégné d'acide acétique, carotte de forage à 230 m de profondeur dans le pergélisol (gisement de Chai-Tumus, Iakoutie).",
      stabilite: 1, swatch: "#6f8a6a",
      devient: "Soluble dans l'eau (solution de pH 5,5).",
      ima: "approuvée en 1967 (procédure spéciale)",
      note: "Elle change de couleur avec l'éclairage, du vert fumé au violet, et sa structure est un réseau métal-organique poreux comme celle de la stépanovite, dont elle est l'équivalent à aluminium. Nommée pour Y.A. Zhemchuzhnikov, pétrographe du charbon.",
      sources: [HOM("Zhemchuzhnikovite"), "I. Huskić et al. (2016), <i>Science Advances</i> 2, e1600621."],
    },
    minguzzite: {
      nom: "Minguzzite", formule: "K₃Fe³⁺(C₂O₄)₃·3H₂O", famille: "Oxalate double de fer et de potassium",
      systeme: "monoclinique", durete: null, densite: 2.08,
      clivage: "parfait {010}", eclat: "vitreux", couleurs: "vert à vert-jaune",
      contexte: "Chapeau de fer oxydé formé dans une dolomie calcaire : Capo Calamita, île d'Elbe (Italie).",
      stabilite: 1, swatch: "#9fbf55",
      devient: "Soluble dans l'eau.",
      ima: "espèce reconnue avant l'IMA (G), 1955",
      note: "C'est, dans la nature, le ferrioxalate de potassium des chimistes : un composé que la lumière décompose, si régulièrement qu'on s'en sert pour mesurer la quantité de lumière reçue (actinomètre de Hatchard et Parker). Nommée pour Carlo Minguzzi, minéralogiste de Pavie.",
      sources: [HOM("Minguzzite")],
    },
    wheatleyite: {
      nom: "Wheatleyite", formule: "Na₂Cu(C₂O₄)₂·2H₂O", famille: "Oxalate double de cuivre et de sodium",
      systeme: "triclinique", durete: 1.5, densite: 2.27,
      clivage: "parfait {100}", eclat: "vitreux", couleurs: "bleu vif",
      contexte: "Un seul spécimen, trouvé sur les haldes d'un filon plomb-zinc : mine Wheatley, près de Phoenixville (Pennsylvanie).",
      stabilite: 1, swatch: "#3f7fd6",
      devient: "Soluble dans l'eau.",
      ima: "IMA 1984-040",
      note: "Aiguilles bleu vif de 2 mm au plus, connues d'un unique échantillon de halde ; le cuivre vient du minerai du filon.",
      sources: [HOM("Wheatleyite")],
    },
    antipinite: {
      nom: "Antipinite", formule: "KNa₃Cu₂(C₂O₄)₄", famille: "Oxalate double de cuivre et d'alcalins",
      systeme: "triclinique", durete: 2, densite: 2.53,
      clivage: "moyen dans trois directions", eclat: "vitreux", couleurs: "bleu",
      contexte: "Gisement de guano de Pabellón de Pica (province d'Iquique, Chili) : l'oxalate vient du guano, le cuivre de la chalcopyrite du gabbro sous-jacent. Aussi à la mine Rowley (Arizona).",
      stabilite: 1, swatch: "#3d78c7",
      devient: "Soluble dans l'eau.",
      ima: "IMA 2014-027",
      note: "Formée là où le guano, dans le désert d'Atacama, repose directement sur une roche contenant du cuivre. Nommée pour M.Y. Antipin (1951-2013), cristallochimiste des composés organométalliques.",
      sources: [HOM("Antipinite"), PICA],
    },
    novgorodovaite: {
      nom: "Novgorodovaïte", formule: "Ca₂(C₂O₄)Cl₂·2H₂O", famille: "Oxalate-chlorure de calcium",
      systeme: "monoclinique", durete: 2.5, densite: 2.38,
      clivage: "bon {110} et {100}", eclat: "vitreux", couleurs: "incolore",
      contexte: "Carotte de forage dans les évaporites du dôme de sel de Chelkar (Kazakhstan occidental).",
      stabilite: 1, swatch: "#eeeeea",
      devient: "Non documenté.",
      ima: "IMA 2000-039",
      note: "Un oxalate enfoui dans un dôme de sel, en grains jusqu'à 7 mm. Nommée pour Margarita Novgorodova, directrice du musée minéralogique Fersman de Moscou.",
      sources: [HOM("Novgorodovaite")],
    },

    // ─────────────────────────── OXALATES À SULFATE ET TERRES RARES ───────────────────────────
    coskrenite_ce: {
      nom: "Coskrénite-(Ce)", formule: "(Ce,Nd,La)₂(SO₄)₂(C₂O₄)·8H₂O", famille: "Sulfate-oxalate de terres rares",
      systeme: "triclinique", durete: null, densite: 2.88, densiteCalc: true,
      clivage: "parfait {001}", eclat: "vitreux",
      couleurs: "rose très pâle à la lumière des lampes à incandescence, bleu pâle sous les tubes fluorescents",
      contexte: "Alum Cave Bluff (Great Smoky Mountains, Tennessee) : l'altération d'un phyllade pyriteux produit des solutions sulfatées qui s'évaporent ; les terres rares viennent de la monazite et du xénotime.",
      stabilite: 1, swatch: "#eadde4",
      devient: "Soluble dans l'eau.",
      ima: "IMA 1996-056",
      note: "Sa couleur dépend de l'éclairage : les terres rares absorbent des raies précises, qui ne sont pas les mêmes dans la lumière d'une ampoule et dans celle d'un tube. Nommée pour T. Dennis Coskren, qui étudia les minéraux d'Alum Cave Bluff.",
      sources: [HOM("Coskrenite-(Ce)"), ALUM],
    },
    levinsonite_y: {
      nom: "Levinsonite-(Y)", formule: "YAl(SO₄)₂(C₂O₄)·12H₂O", famille: "Sulfate-oxalate de terres rares",
      systeme: "monoclinique", durete: null, densite: 2.18, densiteCalc: true,
      clivage: "parfait {101}", eclat: "non décrit", couleurs: "incolore",
      contexte: "Alum Cave Bluff (Great Smoky Mountains, Tennessee), dans les croûtes d'évaporation d'un phyllade pyriteux altéré.",
      stabilite: 1, swatch: "#efefe9",
      devient: "Soluble dans l'eau.",
      ima: "IMA 1996-057",
      note: "Elle honore Alfred Levinson, qui proposa en 1966 d'ajouter au nom des minéraux de terres rares le symbole de l'élément dominant entre parenthèses : c'est son système que l'on lit dans « levinsonite-(Y) » ou « coskrénite-(Ce) ».",
      sources: [HOM("Levinsonite-(Y)"), ALUM],
    },
    zugshunstite_ce: {
      nom: "Zugshunstite-(Ce)", formule: "CeAl(SO₄)₂(C₂O₄)·12H₂O", famille: "Sulfate-oxalate de terres rares",
      systeme: "monoclinique", durete: null, densite: 2.12, densiteCalc: true,
      clivage: "faible {010}", eclat: "non décrit",
      couleurs: "rose très pâle à la lumière des lampes à incandescence, bleu pâle sous les tubes fluorescents",
      contexte: "Alum Cave Bluff (Great Smoky Mountains, Tennessee), avec la coskrénite et la levinsonite.",
      stabilite: 1, swatch: "#e6dde6",
      devient: "Soluble dans l'eau.",
      ima: "IMA 1996-055",
      note: "Son nom vient du terme cherokee qui désigne les Great Smoky Mountains. Même origine que ses voisines : des solutions acides nées de l'oxydation de la pyrite, qui s'évaporent sous un surplomb rocheux.",
      sources: [HOM("Zugshunstite-(Ce)"), ALUM],
    },
    deveroite_ce: {
      nom: "Devéroïte-(Ce)", formule: "Ce₂(C₂O₄)₃·10H₂O", famille: "Oxalate de terres rares",
      systeme: "monoclinique", durete: 2.25, densite: 2.35, densiteCalc: true,
      clivage: "parfait {010}", eclat: "vitreux", couleurs: "incolore",
      contexte: "Fissures alpines du mont Cervandone (val Devero, Piémont, Italie), sur la cervandonite-(Ce) des filons de pegmatite.",
      stabilite: 2, swatch: "#efedec",
      devient: "Non documenté.",
      ima: "IMA 2013-003",
      note: "Des gerbes d'aiguilles de 50 µm posées sur un minéral de terres rares : l'eau de pluie, chargée de l'acide oxalique de lichens crustacés, a dissous le cérium de la cervandonite et l'a déposé en oxalate. Nommée pour le val Devero et son parc naturel.",
      sources: [HOM("Deveroite-(Ce)")],
    },
    alterite: {
      nom: "Altérite", formule: "Zn₂Fe³⁺₄(SO₄)₄(C₂O₄)₂(OH)₄·17H₂O", famille: "Sulfate-oxalate de zinc et de fer",
      systeme: "monoclinique", durete: 1.5, densite: null,
      clivage: "parfait (001)", eclat: "vitreux", couleurs: "vert jaunâtre",
      contexte: "Bois pétrifié riche en carbone d'un indice d'uranium des Vermilion Cliffs (comté de Coconino, Arizona), avec gypse, alunogène et natrojarosite.",
      stabilite: 1, swatch: "#b7c46a",
      devient: "Non documenté.",
      ima: "IMA 2018-070",
      note: "Premier oxalate de zinc décrit, trouvé dans un bois fossile riche en carbone avec des sulfates. À ne pas confondre avec l'« altérite » des pédologues, roche altérée en place : ici, c'est un nom d'espèce minérale.",
      sources: ["H. Yang et al. (2024), « Alterite and magnesioalterite, two new oxalate minerals », <i>Canadian Journal of Mineralogy and Petrology</i> 62, 353."],
    },
    magnesioalterite: {
      nom: "Magnésioaltérite", formule: "Mg₂Fe³⁺₄(SO₄)₄(C₂O₄)₂(OH)₄·17H₂O", famille: "Sulfate-oxalate de magnésium et de fer",
      systeme: "monoclinique", durete: 1.5, densite: null,
      clivage: "parfait (001)", eclat: "vitreux", couleurs: "vert jaunâtre",
      contexte: "Même bois pétrifié que l'altérite, Vermilion Cliffs (Arizona).",
      stabilite: 1, swatch: "#bcc47a",
      devient: "Non documenté.",
      ima: "IMA 2020-050",
      note: "L'équivalent magnésien de l'altérite : même charpente de quatre octaèdres de fer liés par des sulfates et des oxalates, avec le magnésium à la place du zinc.",
      sources: ["H. Yang et al. (2024), <i>Canadian Journal of Mineralogy and Petrology</i> 62, 353."],
    },

    // ─────────────────────────── OXALATES D'URANYLE ───────────────────────────
    uroxite: {
      nom: "Uroxite", formule: "[(UO₂)₂(C₂O₄)(OH)₂(H₂O)₂]·H₂O", famille: "Oxalate d'uranyle",
      systeme: "monoclinique", durete: 2, densite: 4.19, densiteCalc: true,
      clivage: "parfait {1̄02}, assez bon {001}", eclat: "vitreux", couleurs: "jaune clair ; fluorescence vert néon",
      contexte: "Croûtes d'efflorescence sur les parois de mines d'uranium du plateau du Colorado (mine Markey, Utah ; mine Burro, Colorado), sur une gangue d'asphaltite et de quartz.",
      stabilite: 1, swatch: "#e8e070",
      devient: "Radioactive ; évolution non documentée.",
      ima: "IMA 2018-100",
      note: "Avec la métauroxite, le premier oxalate d'uranyle connu (2020). Toutes deux sont apparues après l'exploitation, sur les parois des galeries : l'uranium vient de l'uraninite, l'oxalate du bois fossile (asphaltite) du minerai. Nom : URanyle + OXalate.",
      sources: [HOM("Uroxite"), "A.R. Kampf, J. Plášil et al. (2020), « Uroxite and metauroxite, the first two uranyl oxalate minerals », <i>Mineralogical Magazine</i> 84, 131."],
    },
    metauroxite: {
      nom: "Métauroxite", formule: "(UO₂)₂(C₂O₄)(OH)₂(H₂O)₂", famille: "Oxalate d'uranyle",
      systeme: "triclinique", durete: 2, densite: 4.4, densiteCalc: true,
      clivage: "bon {101} et {010}", eclat: "vitreux", couleurs: "jaune clair ; fluorescence gris-vert",
      contexte: "Mine Burro, district de Slick Rock (Colorado), sur les parois de la mine.",
      stabilite: 1, swatch: "#e6de82",
      devient: "Radioactive ; se dissout lentement dans l'acide chlorhydrique dilué.",
      ima: "IMA 2019-030",
      note: "Une molécule d'eau de moins que l'uroxite (le préfixe « méta » le signale) et une autre architecture : des paires d'octaèdres d'uranium reliées en chaînes par les oxalates, au lieu de feuillets.",
      sources: [HOM("Metauroxite"), "A.R. Kampf et al. (2020), <i>Mineralogical Magazine</i> 84, 131."],
    },

    // ─────────────────────────── PHOSPHATE-OXALATES (guano de chauves-souris) ───────────────────────────
    phoxite: {
      nom: "Phoxite", formule: "(NH₄)₂Mg₂(C₂O₄)(PO₃OH)₂(H₂O)₄", famille: "Phosphate-oxalate de magnésium",
      systeme: "monoclinique", durete: 2.5, densite: 1.98,
      clivage: "assez bon (100)", eclat: "vitreux à gras", couleurs: "incolore ; brun clair à beige par inclusions",
      contexte: "Mine Rowley, près de Theba (comté de Maricopa, Arizona) : niveau de −38 m, zone chaude et humide, dans des masses circulaires d'excréments de chauves-souris récents.",
      stabilite: 1, swatch: "#e9e2d2",
      devient: "Non documenté.",
      ima: "IMA 2018-009",
      note: "Le premier phosphate-oxalate naturel (2019) ; son nom réunit PHosphate et OXalate. Depuis, la mine Rowley a livré toute une famille d'espèces nées du guano de chauves-souris installées dans les galeries abandonnées : le guano apporte l'ammonium, le phosphate et l'oxalate, la roche et le minerai les métaux.",
      sources: [HOM("Phoxite"), ROWLEY],
    },
    thebaite_nh4: {
      nom: "Thébaïte-(NH₄)", formule: "(NH₄,K)₃Al(C₂O₄)(PO₃OH)₂(H₂O)", famille: "Phosphate-oxalate d'aluminium",
      systeme: "monoclinique", durete: 1.75, densite: 2.09, densiteCalc: true,
      clivage: "deux bons clivages dans la zone [010]", eclat: "vitreux", couleurs: "incolore",
      contexte: "Mine Rowley (Arizona), assemblage de minéraux du guano de chauves-souris.",
      stabilite: 1, swatch: "#eeeeea",
      devient: "Se dissout facilement dans les acides dilués.",
      ima: "IMA 2020-072",
      note: "Lames incolores de 0,1 mm, nommées d'après Theba, petite gare à une vingtaine de kilomètres de la mine. Le suffixe (NH₄) signale que l'ammonium domine le potassium.",
      sources: [HOM("Thebaite-(NH4)"), ROWLEY],
    },
    dendoraite_nh4: {
      nom: "Dendoraïte-(NH₄)", formule: "(NH₄)₂NaAl(C₂O₄)(PO₃OH)₂(H₂O)₂", famille: "Phosphate-oxalate d'aluminium",
      systeme: "monoclinique", durete: 2.5, densite: 2.12, densiteCalc: true,
      clivage: "non signalé (cassure en esquilles)", eclat: "vitreux", couleurs: "incolore",
      contexte: "Mine Rowley (Arizona), avec l'antipinite, la reliancéite-(K) et la struvite.",
      stabilite: 1, swatch: "#eeeeea",
      devient: "Non documenté.",
      ima: "IMA 2020-103",
      note: "Proche parente de la thébaïte-(NH₄) : même motif aluminium-oxalate-phosphate, avec du sodium en plus.",
      sources: [HOM("Dendoraite-(NH4)"), ROWLEY],
    },
    davidbrownite_nh4: {
      nom: "Davidbrownite-(NH₄)", formule: "(NH₄,K)₅(V⁴⁺O)₂(C₂O₄)[PO₂,₇₅(OH)₁,₂₅]₄·3H₂O", famille: "Phosphate-oxalate de vanadium",
      systeme: "monoclinique", durete: 2, densite: 2.12,
      clivage: "deux bons clivages dans la zone [010]", eclat: "vitreux", couleurs: "vert-bleu clair",
      contexte: "Mine Rowley (Arizona), zone chaude et humide à −38 m.",
      stabilite: 1, swatch: "#8ec3c0",
      devient: "Se dissout facilement dans les acides dilués.",
      ima: "IMA 2018-129",
      note: "Premier oxalate de vanadium et premier minéral organique à vanadium. Il honore I. David Brown, auteur de la théorie des valences de liaison, qui sert à vérifier les structures cristallines et à placer les hydrogènes.",
      sources: [HOM("Davidbrownite-(NH4)"), ROWLEY],
    },
    relianceite_k: {
      nom: "Reliancéite-(K)", formule: "K₄Mg(V⁴⁺O)₂(C₂O₄)(PO₃OH)₄(H₂O)₁₀", famille: "Phosphate-oxalate de vanadium",
      systeme: "monoclinique", durete: 2.5, densite: 2.11, densiteCalc: true,
      clivage: "parfait {100}, bon {001} (déduits de la structure)", eclat: "vitreux", couleurs: "bleu ciel",
      contexte: "Mine Rowley (Arizona), avec la dendoraïte-(NH₄), la vanadinite et la wulfénite.",
      stabilite: 1, swatch: "#86bde6",
      devient: "Se dissout facilement dans les acides dilués.",
      ima: "IMA 2020-102",
      note: "Nommée d'après l'autre nom de la mine Rowley, la « Reliance mine ». Deux octaèdres de vanadium y sont reliés par un pont oxalate.",
      sources: [HOM("Relianceite-(K)"), ROWLEY],
    },
    ferriphoxite: {
      nom: "Ferriphoxite", formule: "[(NH₄)₂K(H₂O)][Fe³⁺(HPO₄)₂(C₂O₄)]", famille: "Phosphate-oxalate de fer",
      systeme: "monoclinique", durete: 2, densite: null,
      clivage: "non signalé (cassure en esquilles)", eclat: "vitreux", couleurs: "incolore",
      contexte: "Mine Rowley (Arizona), avec l'antipinite, l'aphthitalite, la barytine et la fluorine.",
      stabilite: 1, swatch: "#efeeea",
      devient: "Non documenté.",
      ima: "IMA 2023-096",
      note: "Lames rectangulaires de 0,1 mm : le fer ferrique y remplace le magnésium de la phoxite. Des chaînes doubles d'octaèdres de fer et de tétraèdres de phosphate portent les groupes oxalate.",
      sources: ["A.R. Kampf et al. (2025), « Ferriphoxite and carboferriphoxite », <i>Mineralogical Magazine</i> 89, 162."],
    },
    carboferriphoxite: {
      nom: "Carboferriphoxite", formule: "[(NH₄)K(H₂CO₃)][Fe³⁺(HPO₄)(H₂PO₄)(C₂O₄)]", famille: "Phosphate-oxalate de fer",
      systeme: "triclinique", durete: 2, densite: null,
      clivage: "non signalé (cassure en esquilles)", eclat: "vitreux", couleurs: "incolore",
      contexte: "Mine Rowley (Arizona), en gerbes et en nœuds papillon d'aiguilles de 0,2 mm.",
      stabilite: 1, swatch: "#efeeea",
      devient: "Non documenté.",
      ima: "IMA 2023-097",
      note: "Sa formule contient une molécule entière d'acide carbonique, H₂CO₃, logée dans la structure ; d'où le préfixe « carbo ». Cet acide, instable en solution, n'existe d'ordinaire que fugitivement.",
      sources: ["A.R. Kampf et al. (2025), <i>Mineralogical Magazine</i> 89, 162."],
    },

    // ─────────────────────────── FORMIATES, ACÉTATES, MÉTHANESULFONATE ───────────────────────────
    formicaite: {
      nom: "Formicaïte", formule: "Ca(HCOO)₂", famille: "Formiate de calcium",
      systeme: "quadratique", durete: 1, densite: 1.9,
      clivage: "parfait {100}", eclat: "non décrit", couleurs: "blanc à bleu pâle ; fluorescence bleu pâle",
      contexte: "Veinules hydrothermales recoupant un minerai de bore à kurchatovite et sakhaïte (gisement de Solongo, Bouriatie) ; marbre de skarn (gisement de Novofrolovskoïe, Oural du Nord).",
      stabilite: 1, swatch: "#e9edf2",
      devient: "Soluble dans l'eau.",
      ima: "IMA 1998-030",
      note: "Un formiate, sel de l'acide formique. Cet acide doit son nom aux fourmis (latin <i>formica</i>) : c'est en distillant des fourmis qu'on l'a obtenu la première fois, au XVIIᵉ siècle.",
      sources: [HOM("Formicaite")],
    },
    dashkovaite: {
      nom: "Dashkovaïte", formule: "Mg(HCOO)₂·2H₂O", famille: "Formiate de magnésium",
      systeme: "monoclinique", durete: 1, densite: 1.74, densiteCalc: true,
      clivage: "non signalé", eclat: "vitreux", couleurs: "blanc ; fibres jusqu'à 3 mm",
      contexte: "Rare, dans des veinules hydrothermales qui traversent la serpentine d'un marbre dolomitique : skarn à fer et bore de Korshunovskoïe (région d'Irkoutsk, Sibérie).",
      stabilite: 1, swatch: "#f0f0ec",
      devient: "Soluble dans l'eau.",
      ima: "IMA 2000-006",
      note: "Elle honore Ekaterina Dachkova (1744-1810), nommée en 1783 directrice de l'Académie des sciences de Saint-Pétersbourg : la première femme à diriger une académie des sciences.",
      sources: [HOM("Dashkovaite")],
    },
    acetamide: {
      nom: "Acétamide", formule: "CH₃CONH₂", famille: "Amide de l'acide acétique",
      systeme: "trigonal", durete: 1.25, densite: 1.17,
      clivage: "aucun (cassure conchoïdale fine)", eclat: "vitreux à gras", couleurs: "incolore ; gris quand il contient du charbon",
      contexte: "Terrils de charbon en combustion, où il se forme entre 50 et 150 °C (bassin de Lviv-Volhynie, Ukraine ; Shamokin, Pennsylvanie).",
      stabilite: 1, swatch: "#ecece8",
      devient: "Très soluble ; se volatilise à l'air et au soleil : les échantillons disparaissent d'eux-mêmes.",
      ima: "IMA 1974-039",
      note: "Un minéral qui s'évapore : il faut le garder en flacon fermé. Il cristallise dans les terrils de charbon qui brûlent lentement, là où la température reste comprise entre 50 et 150 °C. Goût très amer.",
      sources: [HOM("Acetamide")],
    },
    calclacite: {
      nom: "Calclacite", formule: "Ca(CH₃COO)Cl·5H₂O", famille: "Acétate-chlorure de calcium",
      systeme: "monoclinique", durete: null, densite: 1.5,
      clivage: "non signalé", eclat: "soyeux (agrégats)", couleurs: "blanc ; efflorescences en cheveux jusqu'à 4 cm",
      contexte: "Connue seulement sur des objets de musée : roches calcaires, fossiles et tessons conservés dans des meubles en chêne, dont le bois dégage de l'acide acétique.",
      stabilite: 1, swatch: "#f3f2ee",
      devient: "Soluble dans l'eau.",
      ima: "espèce reconnue avant l'IMA (G), 1945",
      note: "Née dans les tiroirs des musées : l'acide acétique libéré par le chêne attaque le calcaire des collections. Elle garde son statut d'espèce décrite avant l'IMA ; aujourd'hui, une substance formée ainsi par l'homme ne serait plus acceptée comme minéral.",
      sources: [HOM("Calclacite"), "E.H. Nickel et J.D. Grice (1998), règles de nomenclature de l'IMA (substances d'origine humaine), <i>Canadian Mineralogist</i> 36, 913."],
    },
    hoganite: {
      nom: "Hoganite", formule: "Cu(CH₃COO)₂·H₂O", famille: "Acétate de cuivre",
      systeme: "monoclinique", durete: 1.5, densite: 1.91, densiteCalc: true,
      clivage: "parfait {001}, net {110}", eclat: "vitreux", couleurs: "vert bleuté foncé",
      contexte: "Chapeau de fer de la fosse Potosi (Broken Hill, Nouvelle-Galles du Sud) : les minerais oxydés y ont réagi avec la litière de feuilles et, peut-être, avec les bois de soutènement de la mine.",
      stabilite: 1, swatch: "#2f7f7a",
      devient: "Soluble dans l'eau.",
      ima: "IMA 2001-029",
      note: "Le même composé que le « vert-de-gris neutre », pigment vert des peintres obtenu depuis l'Antiquité en exposant du cuivre à des vapeurs de vinaigre. Nommée pour Graham Hogan, mineur et collectionneur de Broken Hill.",
      sources: [HOM("Hoganite")],
    },
    paceite: {
      nom: "Paceïte", formule: "CaCu(CH₃COO)₄·6H₂O", famille: "Acétate double de cuivre et de calcium",
      systeme: "quadratique", durete: 1.5, densite: 1.47, densiteCalc: true,
      clivage: "parfait {100} et {110}", eclat: "vitreux", couleurs: "bleu ciel foncé",
      contexte: "Fosse Potosi, Broken Hill (Nouvelle-Galles du Sud), avec la hoganite.",
      stabilite: 1, swatch: "#3f8fd0",
      devient: "Soluble dans l'eau.",
      ima: "IMA 2001-030",
      note: "Décrite en même temps que la hoganite, dans le même chapeau de fer. Nommée pour Frank Pace, mineur de Broken Hill qui la remarqua le premier.",
      sources: [HOM("Paceite")],
    },
    ernstburkeite: {
      nom: "Ernstburkéite", formule: "Mg(CH₃SO₃)₂·12H₂O", famille: "Méthanesulfonate de magnésium",
      systeme: "trigonal", durete: null, densite: 1.36, densiteCalc: true,
      clivage: "aucun (bon plan de séparation)", eclat: "cireux", couleurs: "incolore",
      contexte: "Inclusions de 5 µm dans une carotte de glace prélevée à 576,5 m sous la station Dôme Fuji (Antarctique de l'Est).",
      stabilite: 1, swatch: "#eef3f6",
      devient: "Très soluble : disparaît dès que la glace fond.",
      ima: "IMA 2010-059",
      note: "Un minéral trouvé dans la glace de l'Antarctique. L'acide méthanesulfonique se forme dans l'air par oxydation du sulfure de diméthyle que libère le plancton marin ; fixé sur des poussières alcalines pendant son long transport, il a cristallisé dans la glace. Dureté inférieure à 2. Nommée pour Ernst Burke, minéralogiste d'Amsterdam.",
      sources: [HOM("Ernstburkeite")],
    },

    // ─────────────────────────── GLYCOLATES (Santa Catalina Mountains) ───────────────────────────
    lazaraskeite: {
      nom: "Lazaraskéite", formule: "Cu(C₂H₃O₃)₂", famille: "Glycolate de cuivre",
      systeme: "monoclinique", durete: 2, densite: 2.12,
      clivage: "parfait {101}", eclat: "vitreux", couleurs: "bleu verdâtre",
      contexte: "Extrémité ouest de Pusch Ridge, à 975 m d'altitude (Santa Catalina Mountains, au nord de Tucson, Arizona).",
      stabilite: 2, swatch: "#4fa2a0",
      devient: "Non documenté.",
      ima: "IMA 2018-137",
      note: "Le premier glycolate naturel (2022). L'acide glycolique, issu de la décomposition des plantes ou de l'activité des bactéries, a réagi avec le cuivre libéré par l'altération des minéraux de la roche. Deux variantes d'empilement (polytypes) coexistent. Nommée pour Warren Lazar et Beverly Raskin, prospecteurs qui trouvèrent les échantillons. Depuis, dix glycolates ont été décrits sur cette même crête.",
      sources: [HOM("Lazaraskeite"), "H. Yang et al. (2022), « Lazaraskeite, Cu(C₂H₃O₃)₂, the first organic mineral containing glycolate », <i>American Mineralogist</i> 107, 509."],
    },
    stanevansite: {
      nom: "Stanevansite", formule: "Mg(C₂H₃O₃)₂·2H₂O", famille: "Glycolate de magnésium",
      systeme: "monoclinique", durete: null, densite: null,
      clivage: "non disponible", eclat: "non disponible", couleurs: "incolore",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona), en gerbes de lames de 0,4 mm.",
      stabilite: 2, swatch: "#efefeb",
      devient: "Insoluble dans l'eau ; se dissout lentement dans l'acide chlorhydrique.",
      ima: "IMA 2022-085",
      note: "Le premier glycolate hydraté : chaque atome de magnésium est entouré de deux ions glycolate et de deux molécules d'eau, et ces petits complexes ne tiennent ensemble que par des liaisons hydrogène. Nommée pour Stanley H. Evans, minéralogiste de l'université d'Arizona.",
      sources: [CATALINA],
    },
    domitrovicite: {
      nom: "Domitrovicite", formule: "Zn(C₂H₃O₃)₂·2H₂O", famille: "Glycolate de zinc",
      systeme: "monoclinique", durete: 1.5, densite: null,
      clivage: "non disponible", eclat: "vitreux", couleurs: "incolore",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona).",
      stabilite: 2, swatch: "#efefeb",
      devient: "Non documenté.",
      ima: "IMA 2023-125",
      note: "L'équivalent zincifère de la stanevansite : même complexe isolé, le zinc à la place du magnésium.",
      sources: [CATALINA],
    },
    puschridgeite: {
      nom: "Puschridgeïte", formule: "Mn(C₂H₃O₃)₂·2H₂O", famille: "Glycolate de manganèse",
      systeme: "monoclinique", durete: null, densite: null,
      clivage: "non disponible", eclat: "non disponible", couleurs: "non disponible",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona), qui lui donne son nom.",
      stabilite: 2, swatch: "#efe9ea",
      devient: "Non documenté.",
      ima: "IMA 2025-030",
      note: "Premier glycolate de manganèse, équivalent de la stanevansite. Approuvée en 2025 ; seules la formule et la maille sont publiées à ce jour (bulletin 86 de la commission de l'IMA).",
      sources: [CATALINA],
    },
    jimkrieghite: {
      nom: "Jimkrieghite", formule: "Ca(C₂H₃O₃)₂", famille: "Glycolate de calcium",
      systeme: "orthorhombique", durete: 2.5, densite: null,
      clivage: "parfait {100}", eclat: "vitreux", couleurs: "incolore",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona), en cristaux pseudo-cubiques de 0,1 mm, avec calcite, malachite, wulfénite et lazaraskéite.",
      stabilite: 2, swatch: "#efefeb",
      devient: "Non documenté.",
      ima: "IMA 2022-138",
      note: "Le glycolate de calcium anhydre ; sa version hydratée est la rasmussénite.",
      sources: ["H. Yang et al. (2025), « Jimkrieghite, Ca(C₂H₃O₃)₂ », <i>Canadian Journal of Mineralogy and Petrology</i> 63, 91."],
    },
    rasmussenite: {
      nom: "Rasmussénite", formule: "Ca(C₂H₃O₃)₂·3H₂O", famille: "Glycolate de calcium",
      systeme: "triclinique", durete: 1, densite: null,
      clivage: "non disponible", eclat: "vitreux", couleurs: "incolore à blanc",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona), en gerbes d'aiguilles de 0,3 mm.",
      stabilite: 2, swatch: "#f2f2ee",
      devient: "Non documenté.",
      ima: "IMA 2024-018",
      note: "Sa structure est celle du glycinate de calcium trihydraté, un composé identifié récemment dans des calculs rénaux humains : le même édifice, avec le glycolate à la place de l'acide aminé glycine.",
      sources: [CATALINA],
    },
    glecklerite: {
      nom: "Glecklérite", formule: "Na(C₂H₃O₃)", famille: "Glycolate de sodium",
      systeme: "non disponible", durete: null, densite: null,
      clivage: "non disponible", eclat: "non disponible", couleurs: "non disponible",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona), avec barytine, fluorine, jarosite, jimkrieghite et rasmussénite.",
      stabilite: 1, swatch: "#f2f2ee",
      devient: "Non documenté.",
      ima: "IMA 2023-071",
      note: "Le glycolate de sodium. Sa description complète paraît en 2026 (<i>Canadian Journal of Mineralogy and Petrology</i> 64) ; elle n'a pas été consultée ici.",
      sources: [CATALINA],
    },
    henrysunite: {
      nom: "Henrysunite", formule: "Na₂(C₂H₃O₃)₂(H₂O)", famille: "Glycolate de sodium",
      systeme: "orthorhombique", durete: null, densite: null,
      clivage: "non disponible", eclat: "non disponible", couleurs: "non disponible",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona).",
      stabilite: 1, swatch: "#f2f2ee",
      devient: "Non documenté.",
      ima: "IMA 2025-065",
      note: "Proche de la glecklérite, avec une molécule d'eau. Approuvée en 2025 ; seules la formule et la maille sont publiées (bulletin 88 de la commission de l'IMA).",
      sources: [CATALINA],
    },
    lianbinite: {
      nom: "Lianbinite", formule: "(NH₄)(C₂H₃O₃)(C₂H₄O₃)", famille: "Glycolate d'ammonium",
      systeme: "non disponible", durete: 1.25, densite: 1.5, densiteCalc: true,
      clivage: "non disponible", eclat: "vitreux", couleurs: "incolore",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona), en lames et aiguilles.",
      stabilite: 1, swatch: "#f2f2ee",
      devient: "Non documenté.",
      ima: "IMA 2023-016",
      note: "Le premier minéral qui contient les deux formes du glycolate : l'ion glycolate et la molécule d'acide glycolique entière.",
      sources: ["H. Yang et al. (2025), « Lianbinite, (NH₄)(C₂H₃O₃)(C₂H₄O₃) », <i>American Mineralogist</i> 110, 1481."],
    },
    fuchunite: {
      nom: "Fuchunite", formule: "Ba(C₂H₃O₃)₂(C₂H₄O₃)₂", famille: "Glycolate de baryum",
      systeme: "non disponible", durete: null, densite: null,
      clivage: "non disponible", eclat: "non disponible", couleurs: "non disponible",
      contexte: "Pusch Ridge (Santa Catalina Mountains, Arizona).",
      stabilite: 1, swatch: "#f2f2ee",
      devient: "Non documenté.",
      ima: "IMA 2025-011",
      note: "Comme la lianbinite, elle associe ions glycolate et molécules d'acide glycolique, ici autour du baryum. Approuvée en 2025 ; seules la formule et la maille sont publiées (bulletin 85 de la commission de l'IMA).",
      sources: [CATALINA],
    },

    // ─────────────────────────── MELLITATE ET CITRATE ───────────────────────────
    mellite: {
      nom: "Mellite", formule: "Al₂[C₆(COO)₆]·16H₂O", famille: "Mellitate d'aluminium",
      systeme: "quadratique", durete: 2.25, densite: 1.64,
      clivage: "indistinct", eclat: "résineux à vitreux",
      couleurs: "jaune miel, rouge foncé, brun, gris, blanc ; parfois fluorescence jaune pâle à bleue",
      contexte: "Minéral secondaire des lignites et des charbons bruns, l'aluminium venant des argiles : Artern (Thuringe) et Bitterfeld (Allemagne) ; Bohême ; mine de Csordakút à Tatabánya (Hongrie), cristaux jusqu'à 7,5 cm ; Malevka près de Toula (Russie).",
      stabilite: 2, swatch: "#d9962e",
      devient: "Non documenté.",
      ima: "espèce reconnue avant l'IMA (G), 1793",
      note: "La « pierre de miel » (grec <i>méli</i>). En l'analysant, Klaproth découvrit en 1799 l'acide mellitique : un cycle de six atomes de carbone, comme celui du benzène, portant six groupes acide. Ses bipyramides dorées, tendres (2 à 2,5), comptent parmi les plus beaux cristaux organiques.",
      sources: [HOM("Mellite")],
    },
    earlandite: {
      nom: "Earlandite", formule: "Ca₃(C₆H₅O₇)₂·4H₂O", famille: "Citrate de calcium",
      systeme: "triclinique", durete: null, densite: 1.87,
      clivage: "non signalé", eclat: "non décrit", couleurs: "blanc à jaune pâle",
      contexte: "Nodules verruqueux d'environ 1,5 mm dans les sédiments du fond de la mer de Weddell (Antarctique), à 2 580 m de profondeur.",
      stabilite: 2, swatch: "#f1ecd6",
      devient: "Peu soluble.",
      ima: "espèce reconnue avant l'IMA (G), 1936",
      note: "Le citrate de calcium : un sel de l'acide des citrons, trouvé dans les mêmes vases de la mer de Weddell que la weddellite. Sa maille a été donnée orthorhombique, puis monoclinique, puis triclinique. Nommée pour Arthur Earland, spécialiste des foraminifères.",
      sources: [HOM("Earlandite"), "Wikipédia EN, « Earlandite »."],
    },

    // ─────────────────────────── SELS AZOTÉS : THIOCYANATE, ISOCYANURATE, TRIAZOLATES ───────────────────────────
    julienite: {
      nom: "Juliénite", formule: "Na₂Co(SCN)₄·8H₂O", famille: "Thiocyanate de cobalt",
      systeme: "monoclinique (pseudo-quadratique)", durete: null, densite: 1.65,
      clivage: "parallèle à l'allongement", eclat: "non décrit", couleurs: "bleu",
      contexte: "Encroûtement très rare sur un talcschiste : Chamibumba près de Kambove (Katanga, République démocratique du Congo).",
      stabilite: 1, swatch: "#2f55b8",
      devient: "Très soluble ; dissoute, elle donne une solution rose.",
      ima: "renommée en 2007 (Rn)",
      note: "Des aiguilles bleues qui donnent une eau rose : dans le cristal, chaque cobalt est entouré de quatre ions thiocyanate (bleu) ; dissous, il s'entoure de six molécules d'eau (rose). C'est le même changement de couleur que celui des indicateurs d'humidité au chlorure de cobalt. Nommée pour Henri Julien, qui la découvrit.",
      sources: [HOM("Julienite")],
    },
    joanneumite: {
      nom: "Joanneumite", formule: "Cu(C₃N₃O₃H₂)₂(NH₃)₂", famille: "Isocyanurate de cuivre",
      systeme: "triclinique", durete: 1, densite: 2.02, densiteCalc: true,
      clivage: "non signalé", eclat: "vitreux", couleurs: "violet",
      contexte: "Fissures d'un gabbro sous le guano de Pabellón de Pica (Chili), là où se rencontrent les solutions du cuivre oxydé et l'azote du guano, en climat aride.",
      stabilite: 1, swatch: "#7a4fa8",
      devient: "Non documenté.",
      ima: "IMA 2012-001",
      note: "Le premier isocyanurate naturel : un cycle alterné de trois carbones et trois azotes, le même que celui de l'acide cyanurique qui stabilise le chlore des piscines. Nommée pour le Joanneum de Graz, musée qui fêtait ses deux cents ans en 2011.",
      sources: [HOM("Joanneumite")],
    },
    chanabayaite: {
      nom: "Chanabayaïte", formule: "Cu₂(N₃C₂H₂)₂Cl(NH₃,Cl,H₂O,□)₄", famille: "Triazolate de cuivre",
      systeme: "orthorhombique", durete: 2, densite: 1.48,
      clivage: "parfait {001} ; imparfait {100} et {010}", eclat: "vitreux", couleurs: "bleu profond",
      contexte: "Gisement de guano de Pabellón de Pica, près du village de Chanabaya (province d'Iquique, Chili).",
      stabilite: 1, swatch: "#1f4fae",
      devient: "Non documenté ; remplacée en place par la bojarite.",
      ima: "IMA 2013-065",
      note: "Le premier minéral à cycle triazole : cinq atomes, dont trois d'azote, un motif très rare dans la nature, apparu ici dans le guano. Nommée pour le village voisin de Chanabaya.",
      sources: [HOM("Chanabayaite"), PICA],
    },
    triazolite: {
      nom: "Triazolite", formule: "NaCu₂(N₃C₂H₂)₂(NH₃)₂Cl₃·4H₂O", famille: "Triazolate de cuivre",
      systeme: "orthorhombique", durete: 2, densite: 2.03, densiteCalc: true,
      clivage: "parfait {001} ; imparfait {100} et {010}", eclat: "vitreux", couleurs: "bleu profond",
      contexte: "Cavités au contact du guano et de la roche encaissante, Pabellón de Pica (désert d'Atacama, Chili).",
      stabilite: 1, swatch: "#244fb0",
      devient: "Non documenté.",
      ima: "IMA 2017-025",
      note: "Son nom annonce l'ion 1,2,4-triazolate qu'elle contient. Prismes bleus de 0,1 mm en agrégats rayonnants.",
      sources: [HOM("Triazolite"), PICA],
    },
    bojarite: {
      nom: "Bojarite", formule: "Cu₃(N₃C₂H₂)₃(OH)Cl₂·6H₂O", famille: "Triazolate de cuivre",
      systeme: "cubique", durete: 2, densite: 2.06, densiteCalc: true,
      clivage: "non signalé", eclat: "mat (agrégats)", couleurs: "bleu",
      contexte: "Croûtes terreuses sur le gabbro à amphibole, sous le guano de Pabellón de Pica (Chili), en pseudomorphoses d'agrégats de chanabayaïte.",
      stabilite: 1, swatch: "#3a64b8",
      devient: "Insoluble dans l'eau ; se dissout dans l'acide chlorhydrique dilué.",
      ima: "IMA 2020-037",
      note: "Une charpente poreuse de triangles de cuivre reliés par des cycles triazole : un réseau métal-organique microporeux, comme les matériaux que les chimistes conçoivent pour piéger des gaz. Nommée pour Hans-Peter Bojar, minéralogiste du Joanneum de Graz.",
      sources: [HOM("Bojarite"), PICA],
    },
    pabellondepicaite: {
      nom: "Pabellóndepicaïte", formule: "Cu₂(N₃C₂H₂)₂(NH₃)₂(NO₃)Cl·2H₂O", famille: "Triazolate de cuivre",
      systeme: "non disponible", durete: 2.5, densite: 1.95,
      clivage: "non disponible", eclat: "non disponible", couleurs: "bleu indigo",
      contexte: "Gisement de guano de Pabellón de Pica (Chili), qui lui donne son nom.",
      stabilite: 1, swatch: "#34459c",
      devient: "Non documenté.",
      ima: "IMA 2023-104",
      note: "Quatrième triazolate du même gisement, le seul à contenir aussi du nitrate — l'azote du guano sous deux formes dans un même cristal.",
      sources: [PICA],
    },

    // ─────────────────────────── HYDROCARBURES ───────────────────────────
    fichtelite: {
      nom: "Fichtélite", formule: "C₁₉H₃₄", famille: "Hydrocarbure saturé (dérivé des résines de conifères)",
      systeme: "monoclinique", durete: 1, densite: 1.03,
      clivage: "bon {001} et {100}", eclat: "gras", couleurs: "incolore, blanc, jaune pâle",
      contexte: "Bois de pin fossilisé des tourbières du Fichtelgebirge (Wampen, Zeitelmoos, Bavière) et de Soběslav (Bohême) ; sédiments marins actuels riches en matière organique.",
      stabilite: 2, swatch: "#f1ecd6",
      devient: "Fond dès 44-45 °C.",
      ima: "espèce reconnue avant l'IMA (G), 1841",
      note: "Des paillettes blanches dans le bois de pins enfouis dans la tourbe : la résine du pin, en se décomposant, a perdu ses fonctions acides et laissé ce squelette carboné. Nommée pour le Fichtelgebirge (Bavière), décrite en 1841.",
      sources: [HOM("Fichtelite")],
    },
    branchite: {
      nom: "Branchite (ex-hartite)", formule: "C₂₀H₃₄", famille: "Hydrocarbure saturé (phyllocladane)",
      systeme: "triclinique", durete: 1, densite: 1.05,
      clivage: "un clivage très bon", eclat: "vitreux", couleurs: "blanc, gris, incolore",
      contexte: "Veines de lignite et fractures de troncs fossiles houillifiés ou silicifiés : Oberhart (Basse-Autriche), Castelnuovo di Valdarno (Toscane), Bílina (Bohême). En France, signalée dans les septarias des marnes du Bassin vocontien (Drôme, Hautes-Alpes).",
      stabilite: 2, swatch: "#ece8dc",
      devient: "Fond à 71 °C.",
      ima: "renommée en 2021 (Rn)",
      note: "Longtemps appelée hartite (Haidinger, 1841). En 2022, des échantillons décrits à la fin des années 1830 par le naturaliste toscan Paolo Savi sous le nom de branchite se sont révélés identiques : le nom le plus ancien a été rétabli, en l'honneur du chimiste pisan Giuseppe Branchi. C'est un phyllocladane, molécule considérée comme une signature des conifères.",
      sources: [HOM("Hartite"), "F. Bonaccorsi et al. (2022), « 'Hartite' renamed branchite », <i>Mineralogical Magazine</i> 86, 405-411.", VOCONTIEN],
    },
    dinite: {
      nom: "Dinite", formule: "C₂₀H₃₆", famille: "Hydrocarbure saturé",
      systeme: "orthorhombique", durete: null, densite: 1.01,
      clivage: "non signalé (très fragile)", eclat: "« glacé »", couleurs: "jaune pâle",
      contexte: "Bois fossile bitumineux dans des sédiments de rivière non consolidés : Castelnuovo di Garfagnana, vallée du Serchio (Toscane).",
      stabilite: 1, swatch: "#f3ecc2",
      devient: "Fond à 34 °C.",
      ima: "espèce reconnue avant l'IMA (G), 1852",
      note: "Un minéral qui fond dans la main : son point de fusion (34 °C) est inférieur à la température du corps. Décrite en 1852, elle a été retrouvée et redéfinie récemment. Nommée pour Olinto Dini, physicien de l'université de Pise, qui découvrit les premiers échantillons.",
      sources: [HOM("Dinite")],
    },
    simonellite: {
      nom: "Simonellite", formule: "C₁₉H₂₄", famille: "Hydrocarbure aromatique partiel (dérivé des résines de conifères)",
      systeme: "orthorhombique", durete: null, densite: 1.08,
      clivage: "non signalé", eclat: "non décrit", couleurs: "blanc",
      contexte: "Lignite de Fognano, près de Montepulciano (Toscane), issu de forêts de conifères ; aussi présent dans d'autres charbons bruns, détecté par extraction.",
      stabilite: 2, swatch: "#f1efe8",
      devient: "Non documenté.",
      ima: "espèce reconnue avant l'IMA (G), 1919",
      note: "Comme la fichtélite et la branchite, un reste de la résine des conifères transformée dans le lignite. Nommée pour Vittorio Simonelli, géologue de Bologne.",
      sources: [HOM("Simonellite")],
    },
    wampenite: {
      nom: "Wampénite", formule: "C₁₈H₁₆", famille: "Hydrocarbure aromatique",
      systeme: "monoclinique", durete: null, densite: 1.15,
      clivage: "net {001}", eclat: "gras", couleurs: "ambre pâle",
      contexte: "Bois de conifère fossile de Wampen (Fichtelgebirge, Bavière), la localité de la fichtélite.",
      stabilite: 2, swatch: "#e9c98a",
      devient: "Non documenté.",
      ima: "IMA 2015-061",
      note: "Tablettes de 0,4 mm, presque toujours maclées, plus tendres que le talc (dureté inférieure à 1). Approuvée en 2015, sur un bois fossile de la même localité que la fichtélite, décrite près de 175 ans plus tôt.",
      sources: [HOM("Wampenite")],
    },
    kratochvilite: {
      nom: "Kratochvílite", formule: "C₁₃H₁₀", famille: "Hydrocarbure aromatique (fluorène)",
      systeme: "orthorhombique", durete: null, densite: 1.21,
      clivage: "non signalé", eclat: "non décrit", couleurs: "incolore ; fluorescence bleu-violet vif",
      contexte: "Combustion de schistes pyriteux : mine Nejedlý I, Libušín, bassin houiller de Kladno (Bohême).",
      stabilite: 1, swatch: "#eeeef2",
      devient: "Non documenté.",
      ima: "espèce reconnue avant l'IMA (G), 1937",
      note: "Le fluorène naturel, déposé par les fumées d'un terril en combustion. Nommé pour Josef Kratochvíl, pétrographe de l'université Charles de Prague.",
      sources: [HOM("Kratochvilite")],
    },
    ravatite: {
      nom: "Ravatite", formule: "C₁₄H₁₀", famille: "Hydrocarbure aromatique (phénanthrène)",
      systeme: "monoclinique", durete: 1, densite: 1.11,
      clivage: "parfait {001}", eclat: "vitreux à cireux", couleurs: "incolore, blanc, gris pâle ; fluorescence jaune pâle",
      contexte: "Sublimé rare dans des couches de charbon en feu, à moins de 50-60 °C : près de l'ancien village de Ravat, vallée du Yagnob (Tadjikistan).",
      stabilite: 1, swatch: "#efefea",
      devient: "Non documenté.",
      ima: "IMA 1992-019",
      note: "Le phénanthrène : trois cycles benzéniques accolés en ligne brisée. La freitalite a exactement la même formule, C₁₄H₁₀, mais ses trois cycles sont alignés (anthracène) : deux molécules, deux minéraux.",
      sources: [HOM("Ravatite")],
    },
    freitalite: {
      nom: "Freitalite", formule: "C₁₄H₁₀", famille: "Hydrocarbure aromatique (anthracène)",
      systeme: "monoclinique", durete: 1, densite: 1.24,
      clivage: "non signalé (lames souples et malléables)", eclat: "vitreux à nacré",
      couleurs: "violet intense à blanc ; fluorescence blanc bleuté",
      contexte: "Haldes du puits Königin Carola (mine Paul Berndt), Freital près de Dresde (Saxe) ; Libušín (Bohême). Sublimée dans les gaz d'un terril en combustion lente, pauvre en oxygène.",
      stabilite: 1, swatch: "#9a7fc4",
      devient: "Sous les ultraviolets, ses molécules s'associent deux à deux (photodimérisation).",
      ima: "IMA 2019-116",
      note: "L'anthracène naturel, en lames de quelques millimètres, violettes. Freital est aussi la ville de la whewellite de Burgk : les terrils du bassin houiller de Dresde sont un laboratoire naturel de minéraux organiques.",
      sources: [HOM("Freitalite"), "T. Witzke et al. (2021), « Freitalite, C₁₄H₁₀, a new aromatic hydrocarbon mineral from Freital, Saxony, Germany », <i>European Journal of Mineralogy</i> 33, 1."],
    },
    idrialite: {
      nom: "Idrialite", formule: "≈ C₂₂H₁₄", famille: "Hydrocarbures aromatiques polycycliques (mélange)",
      systeme: "orthorhombique", durete: 1.25, densite: 1.23,
      clivage: "parfait {001}, faible {100}", eclat: "vitreux à adamantin",
      couleurs: "brun pâle à jaune verdâtre pâle ; fluorescence bleu pâle ou vert vif",
      contexte: "Mine de mercure d'Idrija (Slovénie), mêlée au cinabre, à l'argile, à la pyrite et au gypse ; sources chaudes et mines de mercure de Californie. En France, signalée dans les septarias des marnes du Bassin vocontien.",
      stabilite: 2, swatch: "#c9b46a",
      devient: "Stable ; brûle facilement.",
      ima: "espèce reconnue avant l'IMA (G), 1832",
      note: "Le « cinabre inflammable » des mineurs d'Idrija. Ce n'est pas une molécule mais un mélange de plus de cent hydrocarbures aromatiques de six familles, nés de la pyrolyse de matière organique et transportés par des fluides chauds. La « curtisite » de Californie en est une variété.",
      sources: [HOM("Idrialite"), VOCONTIEN],
    },
    carpathite: {
      nom: "Carpathite", formule: "C₂₄H₁₂", famille: "Hydrocarbure aromatique (coronène)",
      systeme: "monoclinique", durete: 1, densite: 1.37,
      clivage: "parfait {001}, {100} et {201}", eclat: "vitreux",
      couleurs: "jaune, brunissant à l'air ; fluorescence bleu ciel intense",
      contexte: "Cavités au contact d'une porphyrite dioritique et d'argilites (Olenevo, Transcarpatie, Ukraine) ; filons hydrothermaux de basse température avec le cinabre (mine Picacho, Californie ; Kamtchatka).",
      stabilite: 2, swatch: "#e8cf5a",
      devient: "Brunit à la lumière ; flexible, presque plastique.",
      ima: "approuvée en 1971 (procédure spéciale)",
      note: "Du coronène presque pur : sept cycles benzéniques en couronne. Sa pureté vient de son empilement serré, qui n'admet pas d'autres molécules. Née de matière organique marine chauffée, épurée par les fluides hydrothermaux et déposée sous 250 °C. Redécrite en Californie en 1967 sous le nom de « pendletonite », avant qu'on s'aperçoive qu'elle était connue depuis 1955.",
      sources: [HOM("Karpatite"), "J. Potticary et al. (2017), « Nanostructural origin of blue fluorescence in the mineral karpatite », <i>Scientific Reports</i> 7."],
    },
    hokkaidoite: {
      nom: "Hokkaidoïte", formule: "C₂₂H₁₂", famille: "Hydrocarbure aromatique (benzo[ghi]pérylène)",
      systeme: "non disponible", durete: null, densite: null,
      clivage: "non disponible", eclat: "cireux à résineux (dans l'opale)",
      couleurs: "jaune brunâtre en lits dans l'opale ; plaquettes jaune pâle ; fluorescence jaune à vert-jaune vif",
      contexte: "Opales d'anciennes sources chaudes de Shikaribetsu (Shikaoi) et filons de quartz d'Aibetsu (Hokkaidō, Japon).",
      stabilite: 2, swatch: "#d9c35a",
      devient: "Non documenté.",
      ima: "IMA 2022-104",
      note: "Premier hydrocarbure aromatique polycyclique décrit au Japon (2023) : six cycles benzéniques accolés, piégés en lits dans l'opale déposée par d'anciennes sources chaudes, qui brillent en vert-jaune sous ultraviolets.",
      sources: [IMA, "Science Japan (juillet 2023), annonce de la découverte de la hokkaidoïte."],
    },
    evenkite: {
      nom: "Évenkite", formule: "C₂₃H₄₈", famille: "Paraffine (alcane à longue chaîne)",
      systeme: "orthorhombique", durete: 1, densite: 0.92,
      clivage: "bon, en feuillets comme un mica", eclat: "cireux", couleurs: "incolore à jaunâtre",
      contexte: "Géodes d'un filon de quartz recoupant un tuf soudé, Toungouska inférieure (Évenkie, Sibérie) ; accessoire des charbons. En France : septarias des marnes oxfordiennes des Alpes du Sud (Curbans, Orpierre).",
      stabilite: 2, swatch: "#f3edc9",
      devient: "Non documenté.",
      ima: "espèce reconnue avant l'IMA (G), 1953",
      note: "Une cire de bougie cristallisée : une chaîne de 23 atomes de carbone, si légère (0,92) qu'elle flotte sur l'eau. La liste de l'IMA donne C₂₃H₄₈ ; d'autres sources indiquent C₂₄H₅₀. Dans les septarias des Alpes du Sud, casser un nodule sur place libère parfois un liquide visqueux jaune verdâtre, comme s'il y était enfermé sous pression.",
      sources: [HOM("Evenkite"), "J.E. Spangenberg (1998), « Geochemistry of the organic mineral evenkite in septarian concretions in the Oxfordian marls of the French Alps », <i>Mineralogical Magazine</i> 62A, 1436.", VOCONTIEN],
    },

    // ─────────────────────────── COMPOSÉS DIVERS ───────────────────────────
    refikite: {
      nom: "Réfikite", formule: "C₂₀H₃₄O₂", famille: "Acide résinique fossile",
      systeme: "orthorhombique", durete: null, densite: 1.09, densiteCalc: true,
      clivage: "non signalé", eclat: "résineux", couleurs: "blanc",
      contexte: "Lignite de Montorio al Vomano (Abruzzes, Italie) ; racines d'épicéas fossiles d'un marécage (Kolbermoor, Bavière) ; Krásno (Bohême).",
      stabilite: 2, swatch: "#f2efe6",
      devient: "Fond à 182 °C.",
      ima: "espèce reconnue avant l'IMA (G), 1853",
      note: "Écailles blanches très tendres issues de la résine des conifères. La liste de l'IMA donne C₂₀H₃₄O₂, le Handbook C₂₀H₃₂O₂. Nommée pour Refik Bey, journaliste turc.",
      sources: [HOM("Refikite")],
    },
    flagstaffite: {
      nom: "Flagstaffite", formule: "C₁₀H₂₂O₃", famille: "Hydrate de terpine",
      systeme: "orthorhombique", durete: 1, densite: 1.09,
      clivage: "imparfait {110}", eclat: "non décrit", couleurs: "incolore",
      contexte: "Fissures de troncs de pins enfouis en décomposition, au pied des San Francisco Peaks, au nord de Flagstaff (Arizona).",
      stabilite: 1, swatch: "#eef0ee",
      devient: "Fond à 116 °C.",
      ima: "espèce reconnue avant l'IMA (G), 1920",
      note: "L'hydrate de terpine, qui fut longtemps vendu comme expectorant dans les sirops contre la toux. Ses cristaux sont fortement pyroélectriques : chauffés, ils se chargent d'électricité à leurs deux extrémités, parce que leur structure n'a pas de centre de symétrie.",
      sources: [HOM("Flagstaffite")],
    },
    hoelite: {
      nom: "Hoelite", formule: "C₁₄H₈O₂", famille: "Anthraquinone",
      systeme: "monoclinique", durete: null, densite: 1.43,
      clivage: "non signalé", eclat: "non décrit", couleurs: "jaune, jaune verdâtre ; fines aiguilles",
      contexte: "Croûtes autour des évents d'un gisement de charbon en feu : mont Pyramiden, Spitzberg (Svalbard).",
      stabilite: 1, swatch: "#e5d95a",
      devient: "Non documenté.",
      ima: "espèce reconnue avant l'IMA (G), 1922",
      note: "L'anthraquinone naturelle, squelette de nombreux colorants dont l'alizarine, le rouge de la garance. Nommée pour Adolf Hoel, chef de l'expédition au Spitzberg qui la trouva.",
      sources: [HOM("Hoelite")],
    },
    kladnoite: {
      nom: "Kladnoïte", formule: "C₆H₄(CO)₂NH", famille: "Phtalimide",
      systeme: "monoclinique", durete: null, densite: 1.47,
      clivage: "non signalé", eclat: "non décrit", couleurs: "incolore, blanc, jaune pâle",
      contexte: "Incendies de terrils houillers : mine Scholler à Libušín (bassin de Kladno) et Radvanice (Bohême).",
      stabilite: 1, swatch: "#f1eed9",
      devient: "Fond à 234 °C.",
      ima: "espèce reconnue avant l'IMA (G), 1942",
      note: "Le phtalimide naturel, déposé par les gaz d'un terril en feu. Nommée pour le bassin de Kladno, près de Prague, qui a aussi livré la kratochvílite.",
      sources: [HOM("Kladnoite")],
    },
    abelsonite: {
      nom: "Abelsonite", formule: "NiC₃₁H₃₂N₄", famille: "Porphyrine de nickel",
      systeme: "triclinique", durete: null, densite: 1.45,
      clivage: "probable {111}", eclat: "submétallique à adamantin",
      couleurs: "violet gris foncé, rouge violacé pâle, brun rouge",
      contexte: "Surfaces de fractures et plans de stratification des schistes bitumineux de la formation de Green River (Éocène) : bassins d'Uinta (Utah) et de Piceance (Colorado).",
      stabilite: 3, swatch: "#6a3f5c",
      devient: "Insoluble dans l'eau ; soluble dans le benzène et l'acétone.",
      ima: "IMA 1975-013",
      note: "Une chlorophylle fossile : le même cycle porphyrine, où le nickel a pris la place du magnésium au cours de la diagenèse. C'est la seule géoporphyrine connue sous forme cristallisée. Dureté inférieure à 3. Nommée pour Philip Abelson, géochimiste, rédacteur en chef de la revue <i>Science</i> et co-découvreur du neptunium en 1940.",
      sources: [HOM("Abelsonite")],
    },
    guanine: {
      nom: "Guanine", formule: "C₅H₃(NH₂)N₄O", famille: "Base purique",
      systeme: "monoclinique", durete: null, densite: null,
      clivage: "non signalé", eclat: "non décrit", couleurs: "blanc ; croûtes granuleuses",
      contexte: "Croûtes phosphatées du guano d'oiseaux marins ou de chauves-souris : île Chincha Nord (Pérou) ; grottes d'Australie-Occidentale.",
      stabilite: 2, swatch: "#f3f2ec",
      devient: "Non documenté.",
      ima: "IMA 1973-056",
      note: "L'une des quatre bases de l'ADN, la « G ». Son nom vient du guano (quechua <i>wanu</i>). L'éclat argenté des écailles de poisson est dû à des cristaux de guanine ; fabriqués par l'animal, ceux-là ne sont pas des minéraux.",
      sources: [HOM("Guanine")],
    },
    urea: {
      nom: "Urée", formule: "CO(NH₂)₂", famille: "Urée",
      systeme: "quadratique", durete: null, densite: 1.33,
      clivage: "non signalé", eclat: "non décrit", couleurs: "jaune pâle à brun pâle",
      contexte: "Guano et urine de chauves-souris, stable seulement en climat très aride : Toppin Hill et grotte de Wilgie Mia (Australie-Occidentale).",
      stabilite: 1, swatch: "#efe6c6",
      devient: "Très soluble : disparaît à la première humidité.",
      ima: "IMA 1972-031",
      note: "La molécule qui a fait tomber la frontière entre chimie du vivant et chimie minérale : en 1828, Friedrich Wöhler la fabriqua à partir d'un sel minéral, le cyanate d'ammonium, sans l'aide d'aucun être vivant. Dans la nature, elle ne cristallise que là où il ne pleut presque jamais.",
      sources: [HOM("Urea")],
    },
    uricite: {
      nom: "Uricite", formule: "C₅H₄N₄O₃", famille: "Acide urique",
      systeme: "monoclinique", durete: null, densite: 1.85, densiteCalc: true,
      clivage: "non signalé", eclat: "non décrit", couleurs: "incolore, blanc",
      contexte: "Guanos : Pérou ; grotte Dingo Donga, près de Rawlinna (Australie-Occidentale).",
      stabilite: 2, swatch: "#f3f2ec",
      devient: "Peu soluble.",
      ima: "IMA 1973-055",
      note: "L'acide urique cristallisé. Les oiseaux éliminent leur azote sous cette forme, peu soluble : c'est la partie blanche de leurs fientes, et le principal ingrédient du guano.",
      sources: [HOM("Uricite")],
    },
    tinnunculite: {
      nom: "Tinnunculite", formule: "C₅H₄N₄O₃·2H₂O", famille: "Acide urique dihydraté",
      systeme: "monoclinique", durete: null, densite: 1.68, densiteCalc: true,
      clivage: "net {010}", eclat: "vitreux", couleurs: "incolore, blanc, jaunâtre, rougeâtre ou lilas pâle",
      contexte: "Fientes d'oiseaux en climat arctique froid et humide (massifs de Khibiny et de Lovozero, Kola) ; terril de charbon en feu de Kopeïsk (Oural du Sud), où les gaz chauds ont réagi avec des fientes.",
      stabilite: 1, swatch: "#efe9ef",
      devient: "Non documenté.",
      ima: "IMA 2015-021a",
      note: "Nommée d'après le faucon crécerelle (<i>Falco tinnunculus</i>), dont les fientes, déposées sur un terril en combustion, ont fourni l'acide urique du premier gisement.",
      sources: [HOM("Tinnunculite")],
    },
    allantoin: {
      nom: "Allantoïne", formule: "C₄H₆N₄O₃", famille: "Dérivé de l'acide urique",
      systeme: "monoclinique", durete: 1.5, densite: 1.72,
      clivage: "bon {100}", eclat: "vitreux", couleurs: "incolore",
      contexte: "Guano de chauves-souris : mine Rowley (Arizona) ; grotte Kahf Kharrat Najem (Émirats arabes unis), sous une colonie active.",
      stabilite: 1, swatch: "#f1f1ed",
      devient: "Se dissout lentement dans l'eau.",
      ima: "IMA 2020-004a",
      note: "La plupart des mammifères, mais pas l'homme, transforment leur acide urique en allantoïne avant de l'éliminer ; les chauves-souris en déposent ainsi dans leur guano. On la trouve aussi dans de nombreuses crèmes cosmétiques.",
      sources: [HOM("Allantoin"), ROWLEY],
    },
    marchettiite: {
      nom: "Marchettiite", formule: "(NH₄)C₅H₃N₄O₃", famille: "Urate d'ammonium",
      systeme: "triclinique", durete: 2.25, densite: 1.69, densiteCalc: true,
      clivage: "non signalé", eclat: "mat", couleurs: "rose pâle à blanc, opaque",
      contexte: "Fissure du mont Cervandone (val Devero, Piémont, Italie), déposée par des eaux de pluie froides chargées de matière biologique altérée.",
      stabilite: 2, swatch: "#f1e2e2",
      devient: "Peu soluble.",
      ima: "IMA 2017-066",
      note: "L'équivalent naturel de l'hydrogénourate d'ammonium, un constituant de certains calculs urinaires. Le mont Cervandone a livré, dans les mêmes fissures alpines, la devéroïte-(Ce).",
      sources: [HOM("Marchettiite"), "« Marchettiite, (NH₄)C₅H₃N₄O₃, a new organic mineral from Mount Cervandone, Devero Valley », <i>Mineralogical Magazine</i> (IMA 2017-066)."],
    },
    natrosulfatourea: {
      nom: "Natrosulfatourée", formule: "Na₂(SO₄)[CO(NH₂)₂]", famille: "Sulfate de sodium et urée",
      systeme: "orthorhombique", durete: 1.5, densite: 1.92,
      clivage: "parfait {100}", eclat: "vitreux", couleurs: "incolore",
      contexte: "Mine Rowley (Arizona), à −38 m, par évaporation sur les parois, avec l'aphthitalite et l'urée.",
      stabilite: 1, swatch: "#f1f1ed",
      devient: "Soluble dans l'eau.",
      ima: "IMA 2019-134",
      note: "Un sulfate de sodium qui a intégré dans son réseau une molécule d'urée entière. Le nom dit la composition : natro (sodium), sulfato, urée.",
      sources: [HOM("Natrosulfatourea"), ROWLEY],
    },
  });

  // ─────────────────────────── L'AMBRE : minéraloïde, sorti de la classe X ───────────────────────────
  Object.assign(MINERAUX.ambre, {
    famille: "Minéraloïde — résine fossile (non cristalline)",
    systeme: "amorphe (non cristallin)", eclat: "résineux",
    couleurs: "jaune miel à brun-rouge, parfois blanchâtre",
    clivage: "aucun (cassure conchoïdale)",
    contexte: "Sédiments riches en débris de forêts : ambres crétacés des Charentes (surtout cénomaniens, 94 à 100 millions d'années ; Archingeay, Fouras) ; grands gisements de la Baltique.",
    sources: ["Wikipédia FR, « Ambre » et « Ambre des Charentes ».", "Liste officielle des minéraux de l'IMA-CNMNC, janvier 2026 (l'ambre n'y figure pas)."],
    note: "Une résine d'arbre fossilisée, sans réseau cristallin : ce n'est donc pas un minéral, mais un minéraloïde. L'IMA ne la compte pas parmi les espèces, et la classification de Strunz ne la cite qu'à part. Si légère (1,05 à 1,10) qu'elle flotte dans l'eau salée, elle se charge d'électricité quand on la frotte : son nom grec, <i>élektron</i>, a donné le mot électricité. Les ambres crétacés des Charentes renferment des insectes fossiles étudiés dans le monde entier.",
  });

  // ─────────────────────────── AUTRES SUBSTANCES ORGANIQUES NON CRISTALLINES (partie Amorphes) ───────────────────────────
  Object.assign(MINERAUX, {
    jais: {
      nom: "Jais", formule: "carbone ≈ 75 %, oxygène ≈ 12 %, soufre et hydrogène (composition variable)",
      famille: "Minéraloïde — bois fossile (variété de lignite)",
      systeme: "amorphe (non cristallin)", durete: 3.25, densite: 1.35,
      clivage: "aucun (cassure conchoïdale)", eclat: "cireux à vitreux", couleurs: "noir, parfois brun ; trait brun",
      contexte: "Bois fossile transformé dans des sédiments marins : gisements jurassiques de Whitby (Angleterre) et des Asturies (Espagne). En France, extrait autrefois à Vilhac, à Dreuilhe et en Provence, et travaillé dans la vallée de l'Hers (Ariège et Aude) aux XVIIᵉ-XVIIIᵉ siècles.",
      stabilite: 3, swatch: "#1f1c1e",
      devient: "Se fend quand la température change brusquement ; brûle en sentant le charbon.",
      note: "Une variété de lignite si compacte qu'on la taille et la polit comme une pierre fine : c'est le « noir de jais » des bijoux de deuil. Sans réseau cristallin, ce n'est pas un minéral mais un minéraloïde. Au XVIIIᵉ siècle, le pays d'Olmes employait jusqu'à 1 200 ouvriers à le tailler dans des « moulins à jayet » ; les gisements locaux épuisés, les fabricants en firent venir d'Aragon, de 150 à 200 tonnes par an de 1754 à la Révolution. Son trait brun le distingue du « jais de Paris », qui est du verre noir.",
      sources: ["Wikipédia FR, « Jais » ; Wikipédia EN, « Jet (gemstone) » (dureté, densité, composition).", "Fédération des moulins de France, « Les moulins à jais ou jayet, une industrie méridionale disparue dans la vallée de l'Hers » ; B. Evans, <i>Cahiers de Framespa</i> 35."],
    },
    asphalte: {
      nom: "Bitume naturel (asphalte)", formule: "mélange d'hydrocarbures lourds, de résines et d'asphaltènes, riche en soufre, azote, nickel et vanadium",
      famille: "Minéraloïde — pétrole extra-lourd dégradé",
      systeme: "amorphe (non cristallin)", durete: null, densite: null,
      clivage: "aucun", eclat: "gras à brillant", couleurs: "brun foncé à noir",
      contexte: "Imprègne des sables (sables bitumineux) ou des calcaires (calcaires asphaltiques). En France, mines d'asphalte de Seyssel et Pyrimont (Ain et Haute-Savoie), de Chanay (Ain) et de Lovagny près d'Annecy ; Pechelbronn (Alsace) ; gisement près de Nîmes (Gard), exploité jusqu'en 2008.",
      stabilite: 3, swatch: "#2b2420",
      devient: "Se ramollit à la chaleur ; insoluble dans l'eau.",
      note: "Un pétrole si lourd qu'il est pâteux ou solide : près de la surface, l'eau, l'oxygène et les bactéries lui ont fait perdre ses molécules légères, et il s'est enrichi en résines et en asphaltènes. Mélange sans réseau cristallin, c'est un minéraloïde. Connu depuis l'Antiquité (Hérodote le signale dans les murs de Babylone), il a servi dès les années 1820 à revêtir les trottoirs de Paris ; à Seyssel et Pyrimont, la société Coignet l'exploitait à partir de 1837. Il contient du nickel et du vanadium.",
      sources: ["Wikipédia FR, « Asphalte » et « Bitume ».", "Mines d'asphalte de Pyrimont-Seyssel, exploitées par Coignet et Cⁱᵉ à partir de 1837 (archives de la Haute-Savoie, 1864-1910)."],
    },
    ozokerite: {
      nom: "Ozokérite", formule: "mélange de paraffines à longue chaîne (C₂₂ à C₅₃), 85 à 87 % de carbone",
      famille: "Minéraloïde — cire minérale",
      systeme: "sans réseau cristallin défini (mélange)", durete: null, densite: 0.9,
      clivage: "aucun", eclat: "cireux", couleurs: "jaune pâle à brun foncé, reflets verts",
      contexte: "Veines dans les roches pétrolifères : Boryslav et Starunia (Galicie, versant nord des Carpates), presqu'île de Cheleken (Turkménistan), Utah. Présente dans une trentaine de pays.",
      stabilite: 3, swatch: "#b89a4e",
      devient: "Fond entre 58 et 100 °C selon les gisements ; soluble dans l'éther, le pétrole et le benzène.",
      note: "La « cire de terre » (du grec « qui sent » et « cire ») : un mélange de paraffines laissé dans les fissures par un pétrole qui s'est lentement évaporé et oxydé. Densité 0,85 à 0,95 : plus légère que l'eau. C'est le cousin désordonné de l'évenkite, une seule paraffine assez pure pour cristalliser, qui elle est un minéral. Exploitée en Galicie dans des mines de 200 m de profondeur à la fin du XIXᵉ siècle.",
      sources: ["Wikipédia FR, « Ozokérite » ; Wikipédia EN, « Ozokerite »."],
    },
    copal: {
      nom: "Copal", formule: "résine végétale en cours de polymérisation (composition variable)",
      famille: "Minéraloïde — résine subfossile",
      systeme: "amorphe (non cristallin)", durete: null, densite: null,
      clivage: "aucun (cassure conchoïdale)", eclat: "résineux", couleurs: "jaune citrin à blanc laiteux, plus clair que l'ambre",
      contexte: "Résines de quelques centaines de milliers à 3-4 millions d'années : Afrique de l'Est (Tanzanie, Zanzibar, Madagascar), Colombie, République dominicaine, Nouvelle-Zélande (gomme de kauri).",
      stabilite: 2, swatch: "#e2c46a",
      devient: "Devient collant au contact de l'alcool ou de l'acétone ; avec le temps et l'enfouissement, se polymérise et devient de l'ambre.",
      note: "Un ambre « jeune » : la même résine, moins polymérisée. On passe de l'un à l'autre sans frontière nette ; le copal reste soluble dans l'alcool, pas l'ambre. Son nom vient du nahuatl <i>copalli</i>, « encens » : les peuples du Mexique le brûlaient lors des rituels. Il sert aussi à fabriquer des vernis. Souvent vendu comme de l'ambre, parfois avec des insectes piégés.",
      sources: ["Wikipédia FR, « Copal » et « Ambre » ; Wikipédia EN, « Copal »."],
    },
  });
})();

// ─────────────────────────── SOUS-FAMILLES ET GROUPES DE LA CLASSE X ───────────────────────────
const ORGA_OXALATES = [
  { nom: "Groupe de la humboldtine", formule: "M²⁺(C₂O₄)·2H₂O — M = Fe, Mn, Mg, Zn, Ni",
    section: "Oxalates simples",
    note: "Une même structure pour cinq métaux : des chaînes d'octaèdres métalliques reliés par les ions oxalate, deux molécules d'eau par métal. La humboldtine (fer) est connue depuis 1821 ; les quatre autres ont été décrites entre 1980 et 2025, souvent là où un lichen attaque une roche.",
    mineraux: ["humboldtine", "lindbergite", "glushinskite", "katsarosite", "andreybulakhite"] },
  { nom: "Oxalates de calcium", formule: "Ca(C₂O₄)·nH₂O — n = 1, 2, 3",
    section: "Oxalates simples",
    note: "La whewellite (une molécule d'eau), la weddellite (deux) et la caoxite (trois). La whewellite est la seule stable : les deux autres perdent leur eau et s'y transforment. Ce sont aussi les oxalates que fabriquent les plantes et le corps humain (calculs rénaux) — mais ces cristaux-là, formés dans un être vivant, ne sont pas des minéraux.",
    mineraux: ["whewellite", "weddellite", "caoxite"] },
  { nom: "Autres oxalates simples", formule: "oxalates de Cu, Na, NH₄, Mn",
    section: "Oxalates simples",
    note: "Le cuivre y domine : le métal vient d'un minerai altéré, l'oxalate du guano, des racines ou des lichens. Exception notable, la natroxalate s'est formée à haute température dans une pegmatite, sans aucun apport du vivant.",
    mineraux: ["moolooite", "natroxalate", "oxammite", "falottaite", "middlebackite", "fiemmeite", "edwindavisite"] },
  { nom: "Oxalates doubles", formule: "deux métaux dans le même réseau",
    section: "Oxalates doubles et mixtes",
    note: "Des oxalates de deux métaux à la fois. La stépanovite et la zhemchuzhnikovite, trouvées dans des lignites de Iakoutie, ont une structure poreuse de « réseau métal-organique » (Huskić et al. 2016), comme les matériaux que les chimistes synthétisent pour stocker des gaz.",
    mineraux: ["stepanovite", "zhemchuzhnikovite", "minguzzite", "wheatleyite", "antipinite", "novgorodovaite"] },
  { nom: "Oxalates à sulfate et terres rares", formule: "SO₄ + C₂O₄ ; Ce, Y, Zn, Mg",
    section: "Oxalates doubles et mixtes",
    note: "Des oxalates où entrent aussi des sulfates, nés de l'évaporation d'eaux acides issues de l'oxydation de la pyrite (Alum Cave Bluff, Tennessee) ou de bois fossile (Vermilion Cliffs, Arizona). Les terres rares viennent de la monazite, du xénotime ou de la cervandonite.",
    mineraux: ["coskrenite_ce", "levinsonite_y", "zugshunstite_ce", "deveroite_ce", "alterite", "magnesioalterite"] },
  { nom: "Oxalates d'uranyle", formule: "(UO₂)₂(C₂O₄)(OH)₂·nH₂O",
    section: "Oxalates doubles et mixtes",
    note: "Les deux seuls oxalates d'uranium connus, apparus sur les parois de mines du plateau du Colorado après leur exploitation. L'oxalate vient du bois fossile du minerai.",
    mineraux: ["uroxite", "metauroxite"] },
  { nom: "Phosphate-oxalates du guano de chauves-souris", formule: "PO₃OH + C₂O₄ ; Mg, Al, Fe, V",
    section: "Oxalates doubles et mixtes",
    note: "Une famille découverte depuis 2019 dans une seule mine, la mine Rowley (Arizona), où des chauves-souris ont colonisé les galeries chaudes et humides abandonnées. Le guano apporte l'ammonium, le phosphate et l'oxalate ; la roche, le magnésium, l'aluminium, le fer ou le vanadium.",
    mineraux: ["phoxite", "thebaite_nh4", "dendoraite_nh4", "davidbrownite_nh4", "relianceite_k", "ferriphoxite", "carboferriphoxite"] },
];

const ORGA_SELS = [
  { nom: "Formiates", formule: "HCOO⁻",
    note: "Les sels de l'acide formique, le plus simple des acides organiques (un seul carbone). Les deux espèces connues viennent de veinules hydrothermales de gisements de bore et de skarns de Sibérie et de l'Oural.",
    mineraux: ["formicaite", "dashkovaite"] },
  { nom: "Acétates et acétamide", formule: "CH₃COO⁻, CH₃CONH₂",
    note: "L'acide acétique, celui du vinaigre, et son amide. On les trouve là où du bois ou des feuilles se décomposent contre un minerai (Broken Hill), dans les terrils en feu (acétamide)… et dans les meubles de musée (calclacite).",
    mineraux: ["acetamide", "calclacite", "hoganite", "paceite"] },
  { nom: "Glycolates", formule: "C₂H₃O₃⁻ (et acide glycolique C₂H₄O₃)",
    note: "Dix espèces décrites entre 2022 et 2026, toutes sur une même crête des Santa Catalina Mountains (Arizona) : l'acide glycolique, produit par la décomposition des plantes ou par des bactéries, y a réagi avec les métaux de la roche altérée. Trop récents pour les tables de Strunz de 2001, ils sont rangés ici avec les autres sels d'acides organiques simples.",
    mineraux: ["lazaraskeite", "stanevansite", "domitrovicite", "puschridgeite", "jimkrieghite", "rasmussenite", "glecklerite", "henrysunite", "lianbinite", "fuchunite"] },
  { nom: "Méthanesulfonate", formule: "CH₃SO₃⁻",
    note: "Un seul minéral, trouvé en inclusions microscopiques dans la glace profonde de l'Antarctique.",
    mineraux: ["ernstburkeite"] },
];

const ORGA_HYDROCARBURES = [
  { nom: "Hydrocarbures des résines de conifères", formule: "C₁₈-C₂₀, cycles saturés ou en partie aromatiques",
    note: "Des molécules héritées de la résine des conifères, transformée dans les tourbes, les lignites et les bois fossiles. Elles fondent entre 34 et 71 °C.",
    mineraux: ["fichtelite", "branchite", "dinite", "simonellite", "wampenite"] },
  { nom: "Aromatiques des charbons en feu", formule: "C₁₃-C₁₄, deux ou trois cycles",
    note: "Fluorène, phénanthrène, anthracène : ils se déposent, par sublimation, autour des fissures des terrils et des couches de charbon qui brûlent lentement, pauvres en oxygène, à moins d'une centaine de degrés.",
    mineraux: ["kratochvilite", "ravatite", "freitalite"] },
  { nom: "Aromatiques hydrothermaux", formule: "C₂₂-C₂₄, cinq à sept cycles",
    note: "De grosses molécules aromatiques, nées de la matière organique chauffée en profondeur, transportées par des fluides chauds et déposées dans des filons, souvent avec le cinabre. Toutes fluorescentes sous ultraviolets.",
    mineraux: ["idrialite", "carpathite", "hokkaidoite"] },
  { nom: "Paraffines", formule: "CₙH₂ₙ₊₂, longue chaîne",
    note: "Des alcanes à longue chaîne, les molécules de la cire de bougie. L'évenkite est la seule reconnue comme espèce.",
    mineraux: ["evenkite"] },
];

const ORGA_DIVERS = [
  { nom: "Résines et bois fossiles", formule: "acides et alcools des résines",
    note: "Des composés oxygénés tirés de la résine des conifères : un acide résinique dans des lignites (réfikite), l'hydrate de terpine dans des troncs de pins en décomposition (flagstaffite).",
    mineraux: ["refikite", "flagstaffite"] },
  { nom: "Composés des charbons en feu", formule: "anthraquinone, phtalimide",
    note: "Des molécules oxygénées ou azotées déposées par les gaz des gisements de charbon en combustion.",
    mineraux: ["hoelite", "kladnoite"] },
  { nom: "Porphyrine", formule: "NiC₃₁H₃₂N₄",
    note: "La seule géoporphyrine cristallisée : le cycle de la chlorophylle, conservé dans un schiste bitumineux avec du nickel à la place du magnésium.",
    mineraux: ["abelsonite"] },
  { nom: "Déchets azotés des animaux", formule: "urée, acide urique, guanine, allantoïne",
    note: "Les molécules par lesquelles oiseaux et mammifères éliminent leur azote. Solubles pour la plupart, elles ne cristallisent en minéraux que dans le guano des régions arides ou des grottes, ou sous des fientes gelées de l'Arctique.",
    mineraux: ["guanine", "urea", "uricite", "tinnunculite", "allantoin", "marchettiite", "natrosulfatourea"] },
];

(function () {
  const c = MIN_CLASSIF.find((x) => x.n === 10);
  delete c.achever;
  c.classe = "Composés organiques";
  c.desc = "Des composés du carbone et de l'hydrogène cristallisés par des processus géologiques : oxalates, autres sels d'acides organiques, hydrocarbures. 85 espèces reconnues par l'IMA (liste de janvier 2026), presque toutes rares ; la plupart naissent de la rencontre d'une matière venue du vivant (bois fossile, charbon, guano, lichen) avec une roche.";
  c.plus = "<p>Pour l'IMA, un minéral est un solide normalement cristallin formé par des <b>processus géologiques</b> (Nickel 1995). Une substance fabriquée entièrement par un être vivant n'en est pas un : ni les calculs rénaux, ni les cristaux d'oxalate des feuilles, ni les coquilles. Mais si la géologie intervient, le produit est accepté : la whewellite d'un filon, la mellite d'un lignite, l'évenkite d'un nodule enfoui, l'urée d'un guano desséché.</p>"
    + "<p>La frontière reste discutée, surtout pour les oxalates que font naître les lichens (encadré ci-dessus).</p>"
    + "<p>L'<b>ambre</b>, qu'on range souvent ici, n'est pas un minéral : résine fossile sans réseau cristallin, il ne figure pas dans la liste de l'IMA. Il est présenté avec les substances amorphes, comme le copal, le jais, le bitume naturel et l'ozokérite. Les charbons, eux, sont des roches.</p>"
    + "<p>En 2016, R. Hazen et ses collègues ont calculé qu'au moins 145 minéraux du carbone restaient à découvrir, dont beaucoup d'organiques ; la campagne internationale lancée pour les trouver (« Carbon Mineral Challenge ») et les recherches qui ont suivi ont fait passer la classe d'environ 65 espèces en 2016 à 85 en 2026. Dix glycolates ont ainsi été décrits en quatre ans sur une seule crête d'Arizona.</p>"
    + "<p>En France, on connaît la whewellite des septarias de Condorcet (Drôme), l'évenkite, la branchite et l'idrialite des septarias des Alpes du Sud, et la moolooïte de Sainte-Marie-aux-Mines (Haut-Rhin). Deux espèces anciennes, la phyllorétine (C₁₈H₁₈, Danemark, 1839) et la pigotite (composé organique d'aluminium, 1840), gardent le statut « douteux » de l'IMA et ne sont pas détaillées ici.</p>";
  const chip = (id) => `<button class="min-chip" data-min="${id}"><span class="sw" style="background:${MINERAUX[id].swatch}"></span>${MINERAUX[id].nom}</button>`;
  c.encarts = [{
    titre: "Les minéraux nés sous les lichens",
    html: "<p>Un lichen est l'association d'un champignon et d'une algue. Il sécrète de l'<b>acide oxalique</b>, qui dissout les minéraux de la pierre sur laquelle il pousse. Le métal libéré se combine aussitôt à l'oxalate et cristallise : entre le lichen et la roche, à la surface de la pierre, parfois dans le lichen lui-même.</p>"
      + "<p><b>Pourquoi ce sont des minéraux.</b> Depuis 1995, l'IMA exclut ce qu'un être vivant fabrique seul : un calcul rénal, les cristaux d'oxalate d'une feuille, une coquille. Ici, l'organisme ne fournit que l'acide ; le métal vient de la roche, et le cristal naît d'une réaction chimique au contact de la pierre. La géologie participe à sa formation, et c'est ce qui le fait accepter — le même raisonnement vaut pour les minéraux du guano. La limite reste discutée : l'andreybulakhite, décrite en 2025, cristallise à l'intérieur des organes reproducteurs du lichen.</p>"
      + "<p><b>Ce que chaque roche donne.</b> Sur une serpentinite, riche en magnésium : glushinskite. Sur un minerai de nickel : andreybulakhite. Sur un calcaire ou un marbre : whewellite et weddellite, dont les patines couvrent aussi des monuments. Sur un minéral de terres rares, dans une fissure alpine : devéroïte-(Ce).</p>"
      + `<div class="min-chips">${["glushinskite", "andreybulakhite", "whewellite", "weddellite", "deveroite_ce"].map(chip).join("")}</div>`,
  }];
  c.sources = ["liste officielle des minéraux de l'IMA-CNMNC, janvier 2026", "E.H. Nickel (1995), « The definition of a mineral », <i>Canadian Mineralogist</i> 33, 689",
    "R.M. Hazen et al. (2016), « Carbon mineral ecology: predicting the undiscovered minerals of carbon », <i>American Mineralogist</i> 101, 889",
    "tables de Nickel-Strunz, 10ᵉ édition", "<i>Handbook of Mineralogy</i> (Mineralogical Society of America)",
    "M.J. Wilson et al. (1980), <i>Mineralogical Magazine</i> 43, 837 (glushinskite)", "O.S. Vereshchagin et al. (2025), <i>European Journal of Mineralogy</i> 37, 63 (andreybulakhite)",
    "I. Huskić et al. (2016), <i>Science Advances</i> 2, e1600621", "B. Barailler (2023), Planet-Terre (septarias)", "Wikipédia FR et EN, « Minéral organique » / « Organic mineral »",
    "chaque fiche détaille ses propres sources"];
  c.groupes = [
    { nom: "Oxalates", code: "X.AB", motif: "C₂O₄²⁻",
      note: "Le plus grand groupe de la classe : l'ion oxalate, deux carbones et quatre oxygènes, lié à un ou plusieurs métaux. L'acide oxalique vient presque toujours du vivant (plantes, lichens, champignons, guano), le métal de la roche.",
      sousGroupes: ORGA_OXALATES, mineraux: ORGA_OXALATES.flatMap((sf) => sf.mineraux) },
    { nom: "Formiates, acétates, glycolates", code: "X.AA", motif: "anions carboxylates simples",
      note: "Les sels d'acides organiques à un ou deux carbones. Le code X.AA de Strunz couvre les formiates et les acétates ; les glycolates et le méthanesulfonate, décrits après 2001, n'ont pas de code dans ces tables.",
      sousGroupes: ORGA_SELS, mineraux: ORGA_SELS.flatMap((sf) => sf.mineraux) },
    { nom: "Mellitate et citrate", code: "X.AC", motif: "C₆(COO)₆⁶⁻, citrate",
      note: "Deux sels d'acides organiques plus lourds : la mellite des lignites, dont l'anion est un cycle benzénique portant six groupes acide, et l'earlandite, citrate de calcium des vases de l'Antarctique.",
      mineraux: ["mellite", "earlandite"] },
    { nom: "Sels azotés : thiocyanate, isocyanurate, triazolates", code: "X.AD", motif: "SCN⁻, C₃N₃O₃, N₃C₂H₂⁻",
      note: "Des anions organiques qui contiennent de l'azote. Le code X.AD de Strunz (cyanates) couvre la juliénite ; l'isocyanurate et les triazolates, tous nés du guano de Pabellón de Pica (Chili) depuis 2012, sont postérieurs aux tables.",
      mineraux: ["julienite", "joanneumite", "chanabayaite", "triazolite", "bojarite", "pabellondepicaite"] },
    { nom: "Hydrocarbures", code: "X.BA", motif: "CₓHᵧ",
      note: "Des molécules de carbone et d'hydrogène seulement, sans charge : elles ne tiennent ensemble que par de faibles forces entre molécules, d'où des minéraux très tendres (dureté 1), légers et qui fondent souvent sous 100 °C.",
      sousGroupes: ORGA_HYDROCARBURES, mineraux: ORGA_HYDROCARBURES.flatMap((sf) => sf.mineraux) },
    { nom: "Composés organiques divers", code: "X.CA", motif: "molécules neutres oxygénées ou azotées",
      note: "Tout ce qui n'est ni un sel ni un hydrocarbure : résines fossiles, produits des charbons en feu, une porphyrine, et les déchets azotés des animaux cristallisés dans le guano.",
      sousGroupes: ORGA_DIVERS, mineraux: ORGA_DIVERS.flatMap((sf) => sf.mineraux) },
  ];
})();
