// ============================================================
// OXYDES & HYDROXYDES MÉTALLIQUES — extension de l'atlas
// Fer, manganèse, aluminium, titane (et autres) : fiches,
// conditions de formation (visualiseur pédogenèse) et
// domaines de stabilité pH–Eh (diagrammes de Pourbaix).
// Chargé après mineraux.js, avant app.js.
//
// `cond` : préférences de formation dans les sols, sur 4 axes
//   t   : température moyenne annuelle (0–35 °C)
//   eau : régime hydrique (0 = sec / drainé à saisons sèches,
//         50 = humide bien drainé, 100 = engorgé en permanence)
//   ph  : pH du sol (3–9)
//   mo  : matière organique (0–100)
// Les espèces sans `cond` portent un `badge` : elles ne se
// forment pas par pédogenèse (héritées, hydrothermales…).
// ============================================================

const OXYDES = [
  {
    id: "fer", element: "Fer", symbole: "Fe", couleur: "#b0542e",
    intro: "Le grand peintre des paysages : moins d'un pour cent d'oxydes de fer suffit à colorer un sol. Chaque espèce est un thermomètre-hygromètre fossile — goethite des climats tempérés humides (8–15 °C), hématite des climats chauds à étés secs (> 15 °C), lépidocrocite des sols engorgés par intermittence.",
    especes: [
      { id: "ferrihydrite", nom: "Ferrihydrite", formule: "≈ 5 Fe₂O₃ · 9 H₂O", systeme: "nanocristallin (2–6 nm)",
        clivage: "— (masses terreuses nanocristallines)", eclat: "terreux, mat",
        durete: null, densite: 3.8, stabilite: 3, swatch: "#8a4a2a", couleurs: "brun rouille vif",
        contexte: "Partout où du fer dissous rencontre brutalement l'oxygène : sources ferrugineuses, drains, fossés, racines des sols engorgés.",
        devient: "→ goethite (lentement, sols tempérés, 8–15 °C) ou hématite (via déshydratation, sols à plus de 15 °C et étés secs).",
        note: "Le « premier jet » du fer : un gel nanocristallin à surface énorme (200–600 m²/g) qui précipite en quelques heures dès que Fe²⁺ s'oxyde. Toujours transitoire : c'est la matière première des vraies dynasties, goethite et hématite. Piège redoutable pour arsenic et phosphates.",
        cond: { t: [0, 35], eau: [45, 95], ph: [4.5, 8], mo: [45, 100] },
        condNote: "Précipitation rapide au contact de l'oxygène ; la matière organique bloque sa maturation et la maintient à l'état de ferrihydrite." },
      { id: "goethite", nom: "Goethite", formule: "α-FeO(OH)", systeme: "orthorhombique",
        clivage: "parfait {010}", eclat: "adamantin à terne ; soyeux en fibres",
        durete: 5.25, densite: 4.27, stabilite: 9, swatch: "#b07830", couleurs: "brun-jaune à ocre",
        contexte: "L'oxyde de fer des sols tempérés (8–15 °C) — la quasi-totalité des sols français lui doivent leur teinte brun-ocre.",
        devient: "Stable — produit final de l'altération du fer.",
        note: "La « rouille » thermodynamiquement stable : brun-jaune à ocre, elle colore la plupart des sols français, les argiles de décalcification et les grès ferrugineux. Nommée en hommage à Goethe, minéralogiste à ses heures.",
        cond: { t: [0, 24], eau: [20, 85], ph: [3, 8.5], mo: [15, 100] },
        condNote: "Favorisée par les climats tempérés humides (8–15 °C, pluie > 65 % de l'ETP), la matière organique et les pH acides à neutres : la voie « lente » de maturation de la ferrihydrite." },
      { id: "lepidocrocite", nom: "Lépidocrocite", formule: "γ-FeO(OH)", systeme: "orthorhombique",
        clivage: "parfait {010} (écailles)", eclat: "sub-métallique nacré",
        durete: 5, densite: 4.09, stabilite: 7, swatch: "#c96a2e", couleurs: "orange vif",
        contexte: "Taches et gaines orange des sols hydromorphes (pseudogleys), le long des racines et des fissures.",
        devient: "→ goethite (recristallisation lente).",
        note: "Le polymorphe « orange » de la goethite, signature des sols qui alternent engorgement et assèchement : le fer réduit Fe²⁺ se réoxyde vite, sans carbonates dans les parages (ils imposeraient la goethite). Un indicateur d'hydromorphie que les pédologues lisent d'un coup d'œil.",
        cond: { t: [0, 20], eau: [55, 95], ph: [4, 7], mo: [20, 80] },
        condNote: "Exige des cycles réduction-oxydation (nappes fluctuantes) et l'absence de carbonates ; jamais dans les sols calcaires." },
      { id: "hematite", nom: "Hématite", formule: "α-Fe₂O₃", systeme: "rhomboédrique",
        clivage: "aucun (cassure esquilleuse)", eclat: "métallique (cristaux) à terreux (ocres)",
        durete: 5.5, densite: 5.26, stabilite: 9, swatch: "#a04030", couleurs: "rouge sang à gris acier",
        contexte: "Sols méditerranéens (15–16 °C, étés secs) et tropicaux à saison sèche (≥ 22 °C), terra rossa, grès rouges, bauxites.",
        devient: "Stable — peut s'hydrater en goethite si le climat devient humide (pluie > 65 % de l'ETP).",
        note: "LE pigment rouge de la nature : grès rouges, bauxite, terres méditerranéennes, ocres de Roussillon. Elle naît par déshydratation de la ferrihydrite — il lui faut de la chaleur (plus de 15 °C en moyenne annuelle), une saison sèche (sol sec ≥ 45 jours d'affilée) et peu de matière organique. Un sol rouge est une archive de climat chaud.",
        cond: { t: [16, 35], eau: [0, 40], ph: [5.5, 9], mo: [0, 30] },
        condNote: "Chaleur (> 15 °C) + saison sèche (sol sec ≥ 45 jours d'affilée) + peu d'humus : la voie « sèche » de la ferrihydrite. Le rapport hématite/goethite d'un sol est un paléo-thermomètre." },
      { id: "maghemite", nom: "Maghémite", formule: "γ-Fe₂O₃", systeme: "cubique (spinelle lacunaire)",
        clivage: "aucun", eclat: "sub-métallique terne",
        durete: 5.5, densite: 4.86, stabilite: 7, swatch: "#7d4a38", couleurs: "brun chocolat",
        contexte: "Horizons de surface des sols tropicaux (≥ 22 °C), souvent liés aux feux de brousse ; sols sur basalte.",
        devient: "→ hématite (chauffage ou vieillissement).",
        note: "L'hématite magnétique : même formule, structure de spinelle. Elle se forme quand goethite ou ferrihydrite sont chauffées en présence de matière organique — les feux de brousse en fabriquent des quantités. C'est elle qui rend certains sols tropicaux magnétiques (et les archéologues l'adorent : elle enregistre le champ magnétique).",
        cond: { t: [20, 35], eau: [0, 45], ph: [4.5, 8], mo: [35, 100] },
        condNote: "Formation : oxyde de fer + matière organique + chaleur (incendies). Fréquente en surface des sols tropicaux." },
      { id: "magnetite", nom: "Magnétite", formule: "Fe₃O₄ (Fe²⁺Fe³⁺₂O₄)", systeme: "cubique (spinelle)",
        clivage: "aucun net (séparation octaédrique)", eclat: "métallique",
        durete: 6, densite: 5.17, stabilite: 8, swatch: "#3a3a40", couleurs: "noir métallique",
        contexte: "Héritée des roches magmatiques et métamorphiques ; sables noirs des plages.",
        devient: "→ hématite puis goethite (oxydation lente, « martitisation »).",
        badge: "héritée (magmatique)",
        note: "L'oxyde de fer magnétique (elle attire l'aiguille de la boussole !). Dans les sols, elle est presque toujours héritée de la roche mère — les bactéries magnétotactiques en fabriquent toutefois des nanocristaux pour se guider. Fe²⁺ et Fe³⁺ cohabitent dans son réseau : elle témoigne de conditions pauvres en oxygène à sa naissance.",
        condNote: "Ne se néoforme pas dans les sols aérés : cristallisée dans les magmas (~1 000 °C) ou par des bactéries en milieu peu oxygéné." },
      { id: "fougerite", nom: "Fougérite (rouille verte)", formule: "[Fe²⁺,Fe³⁺,Mg]₆(OH)₁₂[CO₃] · 3H₂O", systeme: "trigonal (feuillets)",
        clivage: "— (feuillets nanométriques)", eclat: "terne",
        durete: null, densite: 2.7, stabilite: 1, swatch: "#5a7060", couleurs: "vert bleuté (fugace)",
        contexte: "Horizons réduits bleu-vert des sols engorgés en permanence (gleys).",
        devient: "→ lépidocrocite ou goethite en quelques minutes dès que l'air entre.",
        note: "Le minéral français par excellence : décrit dans les gleys de la forêt de Fougères (Ille-et-Vilaine) en 1996. C'est la fameuse « rouille verte » des chimistes, mélange de Fe²⁺ et Fe³⁺ en feuillets, si avide d'oxygène qu'elle vire à l'ocre sous vos yeux quand on ouvre une fosse pédologique. C'est elle qui donne leur teinte gris bleu-vert aux gleys.",
        cond: { t: [0, 25], eau: [85, 100], ph: [6, 8.5], mo: [30, 100] },
        condNote: "Engorgement permanent, fer réduit, pas d'oxygène : l'horizon Gr des gleys. Éphémère à l'air libre." },
      { id: "akaganeite", nom: "Akaganéite", formule: "β-FeO(OH,Cl)", systeme: "monoclinique (canaux)",
        clivage: "— (microcristalline, en canaux)", eclat: "terne",
        durete: null, densite: 3.55, stabilite: 5, swatch: "#96562e", couleurs: "brun-jaune",
        contexte: "Milieux riches en chlorures : embruns, sols salés, rouille marine, météorites ferreuses.",
        devient: "→ goethite ou hématite quand le chlore s'en va.",
        badge: "milieux chlorurés",
        note: "L'oxyhydroxyde du bord de mer : sa structure en canaux a besoin d'ions chlorure pour tenir. C'est la rouille des coques de navires, des embruns — et des météorites ferreuses qui s'altèrent, dont celle du mont Akagané (Japon) qui lui a donné son nom.",
        condNote: "Uniquement en présence de chlorures (littoraux, sols salés) : pas un minéral de sol « ordinaire »." },
      { id: "wustite", nom: "Wüstite", formule: "FeO", systeme: "cubique (type halite)",
        clivage: "aucun net", eclat: "métallique gras",
        durete: 5, densite: 5.7, stabilite: 2, swatch: "#3a3236", couleurs: "gris-noir",
        contexte: "Milieux extrêmement réduits : manteau profond, météorites, laitiers de haut-fourneau.",
        devient: "→ magnétite puis goethite dès qu'un peu d'oxygène apparaît.",
        badge: "très réductrice / héritée",
        note: "Le monoxyde de fer, Fe²⁺ pur — la forme la plus réduite du fer minéral. Elle n'existe que là où l'oxygène est quasi absent (manteau, météorites, scories métallurgiques) et s'oxyde aussitôt à l'air. Son domaine borne le côté « sans oxygène » des diagrammes du fer.",
        condNote: "N'apparaît qu'en l'absence quasi totale d'oxygène ; instable dans tout sol aéré." },
      { id: "limonite", nom: "Limonite (terme de terrain)", formule: "≈ FeO(OH)·nH₂O (mélange)", systeme: "amorphe à microcristallin (mélange)",
        clivage: "— (mélange terreux)", eclat: "terreux à sub-métallique (croûtes)",
        durete: null, densite: 3.6, stabilite: 8, swatch: "#9a6a2e", couleurs: "jaune-brun à brun ocre, terne",
        contexte: "Croûtes, concrétions et « chapeaux de fer » (gossans) de tous les milieux oxydés.",
        devient: "Se déshydrate/recristallise en goethite ou hématite.",
        badge: "terme de terrain (mélange)",
        note: "Pas une espèce minérale, mais le vieux nom de terrain des masses brun-jaune d'oxyhydroxydes de fer mal cristallisés — surtout de la goethite, mêlée de ferrihydrite, de lépidocrocite et d'eau. C'est la « rouille » des concrétions, des chapeaux de fer et du minerai des marais. On le garde car il reste très employé sur le terrain.",
        condNote: "Recouvre tout mélange d'oxyhydroxydes ferriques de basse cristallinité ; à préciser en goethite/ferrihydrite dès qu'on analyse." },
    ],
  },
  {
    id: "manganese", element: "Manganèse", symbole: "Mn", couleur: "#4a3d5c",
    intro: "Le fer a un frère de l'ombre : le manganèse, mille fois moins abondant mais tout aussi bavard. Ses oxydes noirs — souvent des taches, films et « dendrites » qu'on prend pour des fossiles de fougères — sont des éponges à métaux lourds et des catalyseurs naturels. Presque tous naissent grâce aux bactéries.",
    especes: [
      { id: "vernadite", nom: "Vernadite", formule: "δ-MnO₂ · nH₂O", systeme: "nanocristallin désordonné",
        clivage: "— (nanocristalline désordonnée)", eclat: "terne, terreux",
        durete: null, densite: 3.0, stabilite: 3, swatch: "#4a4448", couleurs: "noir brunâtre",
        contexte: "Films et enduits noirs des sols, précipité biologique initial du manganèse.",
        devient: "→ birnessite puis todorokite en vieillissant.",
        note: "La « ferrihydrite du manganèse » : le premier précipité, ultra-désordonné, fabriqué principalement par les bactéries et champignons qui oxydent Mn²⁺. Surface énorme, piège à cobalt, nickel, plomb — une poignée de vernadite nettoie une eau contaminée.",
        cond: { t: [0, 35], eau: [40, 90], ph: [5.5, 8.5], mo: [40, 100] },
        condNote: "Oxydation microbienne rapide de Mn²⁺ : là où l'eau réduite riche en Mn rencontre l'oxygène et la vie." },
      { id: "birnessite", nom: "Birnessite", formule: "(Na,Ca,K)₀,₅(Mn⁴⁺,Mn³⁺)₂O₄ · 1,5 H₂O", systeme: "monoclinique (feuillets)",
        clivage: "parfait basal (feuillets)", eclat: "terne à sub-métallique",
        durete: 1.5, densite: 3.0, stabilite: 4, swatch: "#3a3438", couleurs: "noir",
        contexte: "L'oxyde de Mn le plus commun des sols : taches, nodules, dendrites des diaclases.",
        devient: "Stable dans les sols ; → todorokite en milieu confiné.",
        note: "Le principal oxyde de manganèse des sols, bâti en feuillets comme une argile — il en a la capacité d'échange ! Ce sont souvent ses « dendrites » arborescentes qu'on admire sur les calcaires en les prenant pour des fossiles de mousses. Éponge à métaux lourds et oxydant naturel puissant.",
        cond: { t: [0, 35], eau: [30, 80], ph: [6, 9], mo: [20, 80] },
        condNote: "Sols neutres à calcaires, alternances humide/sec modérées (sol sec moins de 90 jours par an) : le régime de croisière du manganèse pédologique." },
      { id: "lithiophorite", nom: "Lithiophorite", formule: "(Al,Li)Mn⁴⁺O₂(OH)₂", systeme: "trigonal (feuillets)",
        clivage: "parfait basal (feuillets)", eclat: "sub-métallique terne",
        durete: 3, densite: 3.4, stabilite: 5, swatch: "#44404a", couleurs: "noir bleuté",
        contexte: "Sols et altérites acides, souvent tropicaux (≥ 22 °C) ; nodules des sols ferrallitiques.",
        devient: "Stable en sol acide.",
        note: "L'oxyde de manganèse des sols acides : ses feuillets alternent Mn et Al (avec un peu de lithium). Là où birnessite exige la neutralité, la lithiophorite prospère dans les latérites et les vieux sols lessivés.",
        cond: { t: [15, 35], eau: [30, 75], ph: [3, 6], mo: [10, 70] },
        condNote: "Le pendant acide de la birnessite : sols tropicaux lessivés (≥ 22 °C, pluie > ETP), altérites sur granite." },
      { id: "todorokite", nom: "Todorokite", formule: "(Na,Ca,K)₂Mn₆O₁₂ · 4,5 H₂O", systeme: "monoclinique (tunnels 3×3)",
        clivage: "fibreux (charpente en tunnels)", eclat: "soyeux à terne",
        durete: null, densite: 3.5, stabilite: 5, swatch: "#3f3a42", couleurs: "noir brunâtre",
        contexte: "Nodules polymétalliques des fonds océaniques, croûtes de Mn marines.",
        devient: "Stable au fond des océans.",
        badge: "fonds marins",
        note: "L'architecture en larges tunnels (3 octaèdres × 3) qui loge Ni, Cu et Co : c'est elle qui fait la richesse des fameux nodules polymétalliques des grands fonds — des patates de manganèse qui grandissent d'un centimètre par million d'années.",
        condNote: "Mûrit à partir de la vernadite dans les sédiments marins : hors du domaine des sols." },
      { id: "cryptomelane", nom: "Cryptomélane", formule: "K(Mn⁴⁺,Mn²⁺)₈O₁₆", systeme: "quadratique (tunnels 2×2)",
        clivage: "— (masses compactes)", eclat: "sub-métallique",
        durete: 6, densite: 4.3, stabilite: 6, swatch: "#38343a", couleurs: "noir gris",
        contexte: "Chapeaux d'oxydation des gisements de manganèse, croûtes massives.",
        devient: "Stable.",
        badge: "supergène (chapeaux de Mn)",
        note: "Des tunnels 2×2 verrouillés au potassium : le « hollandite » du potassium. Constituant massif des chapeaux d'oxydation — comme ceux qui coiffaient les gisements de manganèse des Pyrénées (Las Cabesses) et de Romanèche.",
        condNote: "Concentration supergène au-dessus d'un gisement de Mn : eaux de surface qui lessivent et réoxydent." },
      { id: "romanechite", nom: "Romanéchite (psilomélane)", formule: "(Ba,H₂O)₂(Mn⁴⁺,Mn³⁺)₅O₁₀", systeme: "monoclinique (tunnels 2×3)",
        clivage: "— (masses mamelonnées)", eclat: "sub-métallique",
        durete: 5.5, densite: 4.7, stabilite: 6, swatch: "#35313a", couleurs: "noir mat, concrétions botryoïdales",
        contexte: "Concrétions mamelonnées des chapeaux d'oxydation ; le « psilomélane » des anciens.",
        devient: "Stable.",
        badge: "supergène (chapeaux de Mn)",
        note: "Un minéral au nom bien de chez nous : décrit à Romanèche-Thorins (Saône-et-Loire), au pays du moulin-à-vent ! Ses tunnels au baryum bâtissent les masses noires mamelonnées longtemps appelées « psilomélane ». Les peintres de Lascaux ont dessiné avec des oxydes de Mn semblables.",
        condNote: "Précipite dans les zones d'oxydation riches en baryum — gisement type : Romanèche (71)." },
      { id: "pyrolusite", nom: "Pyrolusite", formule: "β-MnO₂", systeme: "quadratique (tunnels 1×1)",
        clivage: "parfait {110}", eclat: "métallique (cristaux) à terreux (dendrites)",
        durete: 6, densite: 5.06, stabilite: 7, swatch: "#2f2b33", couleurs: "noir métallique",
        contexte: "Aboutissement de la maturation des oxydes de Mn ; filons et chapeaux anciens, dendrites recristallisées.",
        devient: "Stable — le terme ultime du manganèse oxydé.",
        note: "La forme la plus stable et la plus « rangée » de MnO₂ : des tunnels minuscules, plus de place pour l'eau ni les cations. C'est le minerai de manganèse classique — et l'additif qui décolore le verre depuis les Romains (« savon des verriers »).",
        cond: { t: [5, 35], eau: [0, 45], ph: [6, 9], mo: [0, 30] },
        condNote: "Vieillissement et recristallisation en conditions franchement oxydantes et sèches : la fin de l'histoire." },
      { id: "manganite", nom: "Manganite", formule: "γ-MnO(OH)", systeme: "monoclinique",
        clivage: "parfait {010}", eclat: "sub-métallique",
        durete: 4, densite: 4.34, stabilite: 4, swatch: "#3d3640", couleurs: "noir acier, cristaux prismatiques",
        contexte: "Milieux modérément oxydants : concrétions des marais, filons basse température.",
        devient: "→ pyrolusite (oxydation complète).",
        note: "Le Mn³⁺ fait de la résistance : mi-chemin entre le Mn²⁺ dissous et le MnO₂ final. Beaux cristaux prismatiques striés (Ilfeld, Harz). Dans les sols, c'est un intermédiaire des concrétions qui se forment autour des nappes fluctuantes.",
        cond: { t: [0, 25], eau: [55, 95], ph: [6, 9], mo: [20, 80] },
        condNote: "Oxydation incomplète en milieu alternativement réduit : l'étage intermédiaire du manganèse." },
      { id: "hausmannite", nom: "Hausmannite", formule: "Mn²⁺Mn³⁺₂O₄", systeme: "quadratique (spinelle déformé)",
        clivage: "parfait {001}", eclat: "sub-métallique",
        durete: 5.5, densite: 4.86, stabilite: 5, swatch: "#463c42", couleurs: "brun-noir",
        contexte: "Gisements métamorphisés ou hydrothermaux de manganèse.",
        devient: "→ oxydes Mn⁴⁺ en surface.",
        badge: "hydrothermale / métamorphique",
        note: "La « magnétite du manganèse » : même structure spinelle mêlant deux valences. Elle demande de la chaleur — gisements métamorphisés ou fluides hydrothermaux — et ne se forme pas dans les sols.",
        condNote: "Réservée aux gisements chauffés : métamorphisme ou hydrothermalisme." },
      { id: "braunite", nom: "Braunite", formule: "Mn²⁺Mn³⁺₆SiO₁₂", systeme: "quadratique",
        clivage: "parfait {112}", eclat: "sub-métallique",
        durete: 6.25, densite: 4.8, stabilite: 6, swatch: "#3a2f38", couleurs: "brun-noir à noir",
        contexte: "Gisements métamorphiques de manganèse et filons hydrothermaux (Inde, Afrique du Sud).",
        devient: "→ oxydes de Mn⁴⁺ (pyrolusite, romanéchite) + argiles en surface.",
        badge: "métamorphique / hydrothermale",
        note: "Un oxyde de manganèse contenant un peu de silicium : c'est le minerai « primaire » des grands gisements métamorphisés, avant que l'altération de surface ne le transforme en oxydes noirs supergènes. Nommée d'après le minéralogiste allemand Kaspar Braun.",
        condNote: "Cristallise dans les gisements chauffés ; l'altération la remanie en oxydes Mn⁴⁺." },
      { id: "bixbyite", nom: "Bixbyite", formule: "(Mn,Fe)₂O₃", systeme: "cubique",
        clivage: "séparation {111}", eclat: "métallique",
        durete: 6.25, densite: 4.95, stabilite: 6, swatch: "#2f2a30", couleurs: "noir, éclat métallique",
        contexte: "Cavités des rhyolites (Thomas Range, Utah) et gisements métamorphiques de manganèse.",
        devient: "→ oxydes de Mn⁴⁺ en surface.",
        badge: "hydrothermale / métamorphique",
        note: "Le sesquioxyde de manganèse (Mn³⁺), l'analogue manganésifère de l'hématite, en beaux cubes noirs brillants dans les cavités rhyolitiques de l'Utah. Nommée d'après le collecteur Maynard Bixby.",
        condNote: "Milieux chauds (rhyolites, métamorphisme) ; jamais dans un sol." },
      { id: "manganosite", nom: "Manganosite", formule: "MnO", systeme: "cubique (type halite)",
        clivage: "parfait cubique {100}", eclat: "vitreux",
        durete: 5.5, densite: 5.4, stabilite: 2, swatch: "#3a4a3e", couleurs: "vert émeraude, noircissant à l'air",
        contexte: "Gisements métamorphiques de manganèse (Långban, Suède).",
        devient: "Noircit et s'oxyde en oxydes Mn³⁺/⁴⁺ à l'air.",
        badge: "métamorphique / très réductrice",
        note: "Le monoxyde de manganèse (Mn²⁺ pur), l'équivalent manganésifère de la wüstite : vert émeraude à l'état frais mais qui noircit à vue d'œil en s'oxydant. Rare, des gisements suédois de Långban.",
        condNote: "N'existe qu'en milieu très réduit ; instable dès qu'il rencontre l'oxygène." },
    ],
  },
  {
    id: "aluminium", element: "Aluminium", symbole: "Al", couleur: "#8a7d6a",
    intro: "L'aluminium ne change jamais de valence : ses oxydes ne racontent pas l'oxygène, mais l'intensité de l'altération. Quand l'hydrolyse a tout emporté — cations, puis silice — il ne reste que ses hydroxydes : la bauxite. Des Baux-de-Provence au corindon des marbres, une dynastie de plus en plus déshydratée.",
    especes: [
      { id: "gibbsite", nom: "Gibbsite", formule: "γ-Al(OH)₃", systeme: "monoclinique (feuillets)",
        clivage: "parfait basal {001}", eclat: "nacré à vitreux",
        durete: 2.75, densite: 2.42, stabilite: 9, swatch: "#d8c8be", couleurs: "blanc, gris, rosé",
        contexte: "Sols ferrallitiques et bauxites latéritiques des climats équatoriaux très drainés.",
        devient: "Stable — produit ultime de l'altération (allitisation).",
        note: "Quand l'hydrolyse est totale (climat équatorial : ≥ 22 °C, pluie > ETP presque tous les mois, sol très drainé), même la silice s'en va : il ne reste que ces hydroxydes d'aluminium en feuillets. C'est le principal minéral des bauxites latéritiques — et la preuve d'un passé tropical de la Provence.",
        cond: { t: [20, 35], eau: [40, 85], ph: [4, 6.5], mo: [0, 50] },
        condNote: "Tropical (≥ 22 °C), pluie > ETP presque tous les mois, sol très drainé : la désilicification complète (allitisation). L'anti-argile : là où elle domine, même la kaolinite a rendu l'âme." },
      { id: "bayerite", nom: "Bayérite", formule: "α-Al(OH)₃", systeme: "monoclinique",
        clivage: "parfait basal", eclat: "nacré",
        durete: null, densite: 2.53, stabilite: 5, swatch: "#d5cabe", couleurs: "blanc",
        contexte: "Rare dans la nature (cavités basaltiques altérées) ; abondante… en usine.",
        devient: "→ gibbsite (recristallisation).",
        badge: "rare / industrielle",
        note: "Le polymorphe « industriel » de Al(OH)₃ : c'est lui qui précipite dans le procédé Bayer qui tire l'alumine de la bauxite (d'où la quasi-homonymie, fortuite !). Dans la nature, quelques occurrences dans des fissures de roches altérées.",
        condNote: "Précipitation rapide en laboratoire ou en usine ; la nature préfère prendre son temps et faire de la gibbsite." },
      { id: "nordstrandite", nom: "Nordstrandite", formule: "Al(OH)₃ (3ᵉ polymorphe)", systeme: "triclinique",
        clivage: "parfait basal", eclat: "vitreux à nacré",
        durete: 3, densite: 2.44, stabilite: 6, swatch: "#d2c6b8", couleurs: "blanc nacré",
        contexte: "Poches karstiques alcalines, sols sur calcaires des bauxites.",
        devient: "Stable (rare).",
        badge: "karsts alcalins",
        note: "Le troisième frère Al(OH)₃, qui choisit les milieux carbonatés alcalins — poches de dissolution des karsts à bauxite. Une curiosité minéralogique plus qu'un acteur des sols.",
        condNote: "pH alcalin des poches karstiques : l'exception qui confirme la règle gibbsitique." },
      { id: "boehmite", nom: "Boehmite", formule: "γ-AlO(OH)", systeme: "orthorhombique",
        clivage: "parfait {010}", eclat: "nacré",
        durete: 3.5, densite: 3.03, stabilite: 8, swatch: "#c9b8a8", couleurs: "blanc à crème",
        contexte: "Le minéral dominant des bauxites karstiques méditerranéennes (Les Baux !).",
        devient: "Stable ; → diaspore si enfouie et chauffée.",
        note: "L'oxyhydroxyde des bauxites « à la française » : celles des Baux-de-Provence (qui ont donné leur nom à la roche) sont surtout boehmitiques. Un cran plus déshydratée que la gibbsite — climat plus contrasté, bauxites plus vieilles ou légèrement enfouies.",
        cond: { t: [22, 35], eau: [10, 55], ph: [5, 8], mo: [0, 30] },
        condNote: "Chaleur (≥ 22 °C) et saison sèche marquée (sol sec 90 jours ou plus par an), ou léger vieillissement/enfouissement d'une bauxite gibbsitique." },
      { id: "diaspore", nom: "Diaspore", formule: "α-AlO(OH)", systeme: "orthorhombique",
        clivage: "parfait {010}", eclat: "vitreux à nacré brillant",
        durete: 6.75, densite: 3.38, stabilite: 9, swatch: "#c2ad9a", couleurs: "blanc, gris, brun rosé",
        contexte: "Bauxites enfouies et métamorphisées, émeris, schistes alumineux.",
        devient: "→ corindon (déshydratation métamorphique).",
        badge: "diagenèse / métamorphisme",
        note: "Le grand frère dur et dense : même formule que la boehmite, mais structurée comme la goethite. Il faut enfouir et chauffer une bauxite pour l'obtenir — l'émeri de Naxos, abrasif de l'Antiquité, est un mélange diaspore-corindon.",
        condNote: "Ne se forme pas dans les sols : diagenèse profonde ou métamorphisme de bauxites anciennes." },
      { id: "corindon", nom: "Corindon", formule: "α-Al₂O₃", systeme: "rhomboédrique",
        clivage: "aucun (séparation rhomboédrique)", eclat: "vitreux à adamantin",
        durete: 9, densite: 3.99, stabilite: 10, swatch: "#b89cae", couleurs: "incolore… ou rubis et saphir",
        contexte: "Marbres, gneiss et pegmatites désilicifiées ; placers gemmifères.",
        devient: "Rien — dureté 9, quasi éternel ; se concentre dans les placers.",
        badge: "métamorphique",
        note: "L'aluminium chauffé au point de perdre toute son eau : l'étalon de dureté 9 de Mohs. Une pincée de chrome le rougit (rubis), un soupçon de fer-titane le bleuit (saphir). En France, petits saphirs des sables du Puy et du Sioulot — cadeaux du volcanisme.",
        condNote: "Métamorphisme de haute température de roches alumineuses pauvres en silice ; jamais un minéral de sol." },
    ],
  },
  {
    id: "titane", element: "Titane", symbole: "Ti", couleur: "#5a6a72",
    intro: "Le titane est l'immobile : insoluble à tout pH naturel, il ne voyage qu'en grains. Ses oxydes hérités (rutile, ilménite) traversent les cycles d'érosion intacts et se concentrent dans les sables noirs ; dans les sols, il reprécipite sur place en anatase microscopique. Les pédologues s'en servent d'étalon interne : lui, au moins, ne bouge pas.",
    especes: [
      { id: "rutile", nom: "Rutile", formule: "TiO₂ (quadratique)", systeme: "quadratique",
        clivage: "net {110}", eclat: "adamantin à métallique",
        durete: 6.25, densite: 4.25, stabilite: 10, swatch: "#8a4a3a", couleurs: "rouge sombre à noir, éclat adamantin",
        contexte: "Accessoire des roches métamorphiques et magmatiques ; sables lourds des placers.",
        devient: "Rien — l'un des minéraux les plus inaltérables qui soient.",
        badge: "hérité",
        note: "La forme haute température de TiO₂, reconnaissable à ses aiguilles rouges dans le quartz (« cheveux de Vénus »). Quasi indestructible, il s'accumule dans les sables lourds — les grands gisements de titane sont des plages fossiles. Pigment blanc universel une fois broyé et purifié.",
        condNote: "Hérité des roches : il traverse l'altération sans broncher." },
      { id: "anatase", nom: "Anatase", formule: "TiO₂ (quadratique, basse T)", systeme: "quadratique",
        clivage: "parfait {011} et {001}", eclat: "adamantin",
        durete: 5.75, densite: 3.89, stabilite: 9, swatch: "#4a5a68", couleurs: "bleu-noir, jaune-brun",
        contexte: "Microcristaux néoformés dans les sols et altérites ; cristaux des fentes alpines.",
        devient: "→ rutile (si métamorphisme).",
        note: "Le TiO₂ « de basse température » : quand la titanite ou l'ilménite s'altèrent, le titane libéré reprécipite sur place en anatase microscopique — le titane ne fait jamais un mètre en solution. Les belles bipyramides bleues des fentes alpines sont sa version de luxe.",
        cond: { t: [0, 35], eau: [10, 90], ph: [3, 9], mo: [0, 100] },
        condNote: "Se néoforme dans à peu près tous les sols, dès qu'un minéral titané s'altère : l'omniprésent discret." },
      { id: "brookite", nom: "Brookite", formule: "TiO₂ (orthorhombique)", systeme: "orthorhombique",
        clivage: "indistinct", eclat: "adamantin à sub-métallique",
        durete: 5.75, densite: 4.12, stabilite: 9, swatch: "#5c4a3a", couleurs: "brun rougeâtre",
        contexte: "Fentes alpines, veines hydrothermales basse température.",
        devient: "→ rutile (chauffage).",
        badge: "hydrothermale",
        note: "Le troisième polymorphe de TiO₂, le plus rare : plaques brunes striées des fentes alpines (le Bourg-d'Oisans en a fourni de célèbres). Une affaire de cristalliers plus que de pédologues.",
        condNote: "Cristallise dans les fissures hydrothermales alpines, pas dans les sols." },
      { id: "ilmenite", nom: "Ilménite", formule: "FeTiO₃", systeme: "rhomboédrique",
        clivage: "aucun (séparation basale)", eclat: "métallique",
        durete: 5.5, densite: 4.72, stabilite: 8, swatch: "#3a3c42", couleurs: "noir métallique",
        contexte: "Accessoire des gabbros, basaltes, anorthosites ; sables noirs littoraux.",
        devient: "→ « leucoxène » (le fer part, le titane reste en TiO₂ microcristallin).",
        badge: "héritée (magmatique)",
        note: "L'oxyde mixte fer-titane, cousin de l'hématite : le principal minerai de titane mondial. Son altération est un divorce : le fer s'en va rouiller ailleurs, le titane reste sur place en poussière blanchâtre de TiO₂ (le « leucoxène »). Sables noirs des plages avec la magnétite.",
        condNote: "Héritée des roches basiques ; s'altère lentement en leucoxène dans les sols." },
      { id: "leucoxene", nom: "Leucoxène", formule: "TiO₂ microcristallin (± Fe)", systeme: "mélange (anatase/rutile fins)",
        clivage: "— (agrégats microcristallins)", eclat: "mat, blanc laiteux",
        durete: null, densite: 3.9, stabilite: 9, swatch: "#b8b0a4", couleurs: "blanc jaunâtre, terne",
        contexte: "Produit d'altération de l'ilménite et de la titanite, dans roches altérées et sables.",
        devient: "Stable (c'est déjà un produit final).",
        note: "Pas une espèce officielle, mais le nom que les pétrographes donnent à la poussière blanche de TiO₂ qui remplace ilménite et titanite altérées : un mélange microcristallin d'anatase et de rutile. Sa présence signe un grain d'ilménite qui a vécu.",
        cond: { t: [0, 35], eau: [15, 90], ph: [3, 8.5], mo: [0, 100] },
        condNote: "Partout où un minéral fer-titane s'altère : l'aboutissement pédologique du titane." },
      { id: "perovskite", nom: "Pérovskite", formule: "CaTiO₃", systeme: "orthorhombique (pseudo-cubique)",
        clivage: "imparfait {001}", eclat: "adamantin à métallique",
        durete: 5.5, densite: 4.0, stabilite: 7, swatch: "#3a3630", couleurs: "noir, brun-rouge",
        contexte: "Roches alcalines pauvres en silice : carbonatites, kimberlites, skarns.",
        devient: "→ anatase/leucoxène + carbonates.",
        badge: "magmatique (roches alcalines)",
        note: "Le titanate de calcium — dont le nom est devenu célèbre bien au-delà de la minéralogie : la « structure pérovskite » est celle des supraconducteurs, des cellules solaires nouvelle génération, et de la bridgmanite, le minéral le plus abondant de la Terre (manteau profond). Le minéral lui-même vit dans les carbonatites et kimberlites.",
        condNote: "Cristallise dans les magmas sous-saturés en silice ; hérité ensuite." },
      { id: "geikielite", nom: "Geikiélite", formule: "MgTiO₃", systeme: "rhomboédrique (type ilménite)",
        clivage: "aucun net", eclat: "métallique à sub-métallique",
        durete: 6, densite: 4.05, stabilite: 7, swatch: "#4a4038", couleurs: "noir, brun-rouge",
        contexte: "Marbres dolomitiques métamorphisés et kimberlites ; placers (Sri Lanka).",
        devient: "→ leucoxène + carbonates.",
        badge: "métamorphique",
        note: "Le pôle magnésien de l'ilménite (MgTiO₃), des marbres dolomitiques et des kimberlites. Elle forme une série continue avec l'ilménite (Fe) et la pyrophanite (Mn). Nommée d'après le géologue écossais Archibald Geikie.",
        condNote: "Métamorphisme des dolomies titanées ; hérité, puis concentré en placers." },
    ],
  },
  {
    id: "cuivre", element: "Cuivre", symbole: "Cu", couleur: "#a85a3a",
    intro: "Les oxydes de cuivre vivent dans les « chapeaux » d'oxydation des gisements cuprifères, entre le cuivre natif du fond et les carbonates verts et bleus (malachite, azurite) de la surface. Rouges puis noirs, ils jalonnent les étapes de la rouille du cuivre.",
    especes: [
      { id: "cuprite", nom: "Cuprite", formule: "Cu₂O", systeme: "cubique",
        clivage: "imparfait {111}", eclat: "adamantin à sub-métallique",
        durete: 3.75, densite: 6.14, stabilite: 4, swatch: "#8a3028", couleurs: "rouge rubis à rouge brique",
        contexte: "Zones d'oxydation des gisements de cuivre, au contact du cuivre natif.",
        devient: "→ malachite (carbonatation) en surface.",
        badge: "supergène (chapeaux de Cu)",
        note: "Le cuivre à moitié oxydé, rouge rubis dans les chapeaux des filons cuprifères, souvent en croûtes sur le cuivre natif. Chessy (Rhône) en a livré de superbes cristaux passés malachite en surface — les « chessylites » des collections.",
        condNote: "Oxydation modérée d'un gisement de cuivre : l'étage sous la malachite." },
      { id: "tenorite", nom: "Ténorite", formule: "CuO", systeme: "monoclinique",
        clivage: "— (écailles, masses)", eclat: "métallique terne",
        durete: 3.75, densite: 6.5, stabilite: 4, swatch: "#2a2624", couleurs: "noir, gris de fer",
        contexte: "Chapeaux d'oxydation des gisements de cuivre ; fumerolles volcaniques (Vésuve).",
        devient: "→ malachite / carbonates en surface.",
        badge: "supergène / fumerollien",
        note: "L'oxyde cuivrique noir (Cu²⁺), en croûtes ou paillettes terreuses au-dessus de la cuprite dans les chapeaux des gisements de cuivre. On la trouve aussi autour des fumerolles du Vésuve. Nommée d'après le botaniste Michele Tenore.",
        condNote: "Oxydation avancée d'un gisement de cuivre, ou sublimation autour des fumerolles." },
    ],
  },
  {
    id: "zinc", element: "Zinc", symbole: "Zn", couleur: "#8a7a4a",
    intro: "Les oxydes de zinc sont l'affaire d'un gisement hors norme : Franklin, dans le New Jersey — un skarn à zinc-manganèse métamorphisé qui a livré à lui seul plus de 350 espèces minérales et la plupart des minéraux fluorescents des collections.",
    especes: [
      { id: "zincite", nom: "Zincite", formule: "ZnO", systeme: "hexagonal (type würtzite)",
        clivage: "parfait {10-10}", eclat: "résineux à adamantin",
        durete: 4, densite: 5.6, stabilite: 5, swatch: "#c05a3a", couleurs: "rouge-orangé à jaune",
        contexte: "Presque exclusivement à Franklin / Sterling Hill (New Jersey).",
        devient: "→ smithsonite / hémimorphite en surface.",
        badge: "métamorphique (Franklin)",
        note: "L'oxyde de zinc, rouge-orangé à cause de traces de manganèse — le ZnO pur est blanc, c'est le « blanc de zinc » des peintres et l'écran solaire minéral. Emblématique de Franklin, l'un des gisements les plus extraordinaires du monde.",
        condNote: "Née du métamorphisme d'un gisement de zinc ; ne se forme pas dans les sols." },
      { id: "gahnite", nom: "Gahnite", formule: "ZnAl₂O₄", systeme: "cubique (spinelle)",
        clivage: "aucun (séparation)", eclat: "vitreux",
        durete: 7.75, densite: 4.6, stabilite: 9, swatch: "#2f4a4a", couleurs: "vert foncé, bleu-vert, noir",
        contexte: "Pegmatites granitiques, gisements métamorphiques de zinc, granulites.",
        devient: "Résiduelle (dure et inaltérable) → placers.",
        badge: "métamorphique / pegmatitique",
        note: "Le spinelle de zinc (ZnAl₂O₄), vert bleuté à noir. Dure et inaltérable, elle sert de minéral-guide dans la prospection des gisements de sulfures métamorphisés. Nommée d'après le chimiste suédois Johan Gahn.",
        condNote: "Cristallise dans les roches métamorphiques et les pegmatites zincifères." },
      { id: "franklinite", nom: "Franklinite", formule: "(Zn,Mn²⁺,Fe²⁺)(Fe³⁺,Mn³⁺)₂O₄", systeme: "cubique (spinelle)",
        clivage: "aucun", eclat: "métallique",
        durete: 6, densite: 5.2, stabilite: 8, swatch: "#2a2a2e", couleurs: "noir, faiblement magnétique",
        contexte: "Franklin / Sterling Hill (New Jersey), sa quasi-unique localité.",
        devient: "Résiduelle.",
        badge: "métamorphique (Franklin)",
        note: "Le spinelle de zinc et de manganèse, minerai de zinc de Franklin. Faiblement magnétique, associée à la zincite et à la willémite dans la fameuse « trinité » fluorescente. Nommée d'après Benjamin Franklin.",
        condNote: "Née du métamorphisme du gisement de Franklin ; inaltérable ensuite." },
    ],
  },
  {
    id: "chrome", element: "Chrome", symbole: "Cr", couleur: "#4a6a4a",
    intro: "Le chrome est un enfant du manteau : ses oxydes cristallisent dans les roches ultrabasiques (péridotites, ophiolites) et en sortent quasi intacts. Noirs comme la chromite ou vert intense comme l'eskolaïte, ils sont le minerai unique de ce métal des aciers inoxydables.",
    especes: [
      { id: "chromite", nom: "Chromite", formule: "Fe²⁺Cr₂O₄", systeme: "cubique (spinelle)",
        clivage: "aucun", eclat: "métallique à sub-métallique",
        durete: 5.5, densite: 4.79, stabilite: 9, swatch: "#3c3a34", couleurs: "noir brunâtre",
        contexte: "Péridotites et serpentinites (ophiolites) ; sables lourds.",
        devient: "Quasi rien — résiduelle ; le chrome libéré peut contaminer les sols serpentiniques.",
        badge: "héritée (manteau)",
        note: "Le seul minerai de chrome : cumulats noirs des roches du manteau. Quasi inaltérable, elle passe dans les sols serpentiniques puis dans les sables. C'est le chrome des latérites calédoniennes et des aciers inoxydables.",
        condNote: "Héritée des roches ultrabasiques : l'altération la libère intacte." },
      { id: "eskolaite", nom: "Eskolaïte", formule: "Cr₂O₃", systeme: "rhomboédrique (type corindon)",
        clivage: "aucun", eclat: "métallique",
        durete: 8.5, densite: 5.2, stabilite: 9, swatch: "#2f5a3a", couleurs: "vert émeraude à noir",
        contexte: "Roches métamorphiques chromifères, skarns, filons ; rare.",
        devient: "Résiduelle.",
        badge: "métamorphique / hydrothermale",
        note: "Le sesquioxyde de chrome (Cr₂O₃), l'analogue chromifère du corindon, d'un vert intense. C'est le pigment « vert de chrome » et l'abrasif des pâtes à polir. Nommée d'après le pétrologue finlandais Pentti Eskola.",
        condNote: "Rare, dans les roches métamorphiques riches en chrome ; inaltérable." },
    ],
  },
  {
    id: "magnesium", element: "Magnésium", symbole: "Mg", couleur: "#6a8a7a",
    intro: "Les oxydes et hydroxydes de magnésium naissent de la cuisson ou de l'hydratation des roches magnésiennes — dolomies au contact des intrusions, serpentinites du manteau hydraté. Le spinelle en est le membre noble, gemme des marbres.",
    especes: [
      { id: "periclase", nom: "Périclase", formule: "MgO", systeme: "cubique (type halite)",
        clivage: "parfait cubique {100}", eclat: "vitreux",
        durete: 5.75, densite: 3.6, stabilite: 4, swatch: "#c8c0b8", couleurs: "incolore, gris, vert, jaune",
        contexte: "Marbres dolomitiques métamorphisés au contact d'une intrusion (skarns).",
        devient: "→ brucite (hydratation quasi immédiate).",
        badge: "métamorphique (contact)",
        note: "Le monoxyde de magnésium, né de la cuisson des dolomies : CaMg(CO₃)₂ → MgO + CaCO₃ + CO₂. Très réfractaire (il fond à 2800 °C) — c'est la « magnésie » des briques de four. À l'air humide, il s'hydrate vite en brucite.",
        condNote: "Métamorphisme de contact des dolomies ; instable à l'humidité (→ brucite)." },
      { id: "brucite", nom: "Brucite", formule: "Mg(OH)₂", systeme: "trigonal (feuillets)",
        clivage: "parfait {0001} — lamelles flexibles", eclat: "nacré à cireux",
        durete: 2.75, densite: 2.39, stabilite: 3, swatch: "#c8d2c0", couleurs: "blanc verdâtre, nacré",
        contexte: "Veines des serpentinites, marbres dolomitiques hydratés.",
        devient: "→ hydromagnésite/magnésite (carbonatation) : elle capte le CO₂ de l'air !",
        note: "L'hydroxyde de magnésium pur — et l'archétype structural : c'est le fameux « feuillet brucitique » qui soude les chlorites. En veines nacrées dans les serpentinites. Sa réaction avec le CO₂ atmosphérique en fait une piste sérieuse de capture du carbone.",
        cond: { t: [0, 25], eau: [40, 90], ph: [8, 9], mo: [0, 40] },
        condNote: "Hydratation des roches ultrabasiques, milieux très alcalins (pH > 9) : les sources hyperalcalines des ophiolites en précipitent encore." },
      { id: "spinelle", nom: "Spinelle", formule: "MgAl₂O₄", systeme: "cubique",
        clivage: "aucun (séparation octaédrique)", eclat: "vitreux",
        durete: 8, densite: 3.6, stabilite: 9, swatch: "#8a4a5c", couleurs: "rouge, rose, bleu, noir",
        contexte: "Marbres et roches métamorphiques magnésiennes ; placers gemmifères.",
        devient: "Résiduel — dureté 8, finit dans les placers.",
        badge: "métamorphique",
        note: "Le chef de file structural de toute une famille (magnétite, chromite, maghémite, gahnite, franklinite sont des « spinelles »). Son pôle ferreux est l'hercynite (FeAl₂O₄). Les plus célèbres rubis historiques — le « rubis du Prince Noir » des joyaux anglais — sont en réalité des spinelles rouges.",
        condNote: "Métamorphisme de contact des dolomies ; hérité ensuite." },
    ],
  },
  {
    id: "etain", element: "Étain", symbole: "Sn", couleur: "#5a5a6a",
    intro: "L'étain tient dans un seul oxyde, mais quel oxyde : la cassitérite, si dense et inaltérable qu'on la récolte dans les rivières depuis l'âge du bronze. Toute la métallurgie de l'étain repose sur elle.",
    especes: [
      { id: "cassiterite", nom: "Cassitérite", formule: "SnO₂", systeme: "quadratique (type rutile)",
        clivage: "imparfait {100}", eclat: "adamantin gras",
        durete: 6.5, densite: 6.99, stabilite: 10, swatch: "#4a4238", couleurs: "brun-noir, éclat adamantin",
        contexte: "Greisens et pegmatites ; placers stannifères.",
        devient: "Rien — inaltérable et très dense : reine des placers.",
        badge: "héritée (greisens)",
        note: "Le minerai d'étain de l'âge du bronze : si dense et inaltérable qu'on l'a toujours récoltée dans les rivières. Les placers de Piriac et d'Abbaretz (Loire-Atlantique) et les greisens du Limousin ont fait la « route de l'étain » gauloise.",
        condNote: "Cristallisée dans les coupoles granitiques ; l'érosion la concentre en placers." },
    ],
  },
  {
    id: "zirconium", element: "Zirconium", symbole: "Zr", couleur: "#6a5a4a",
    intro: "Là où le silicium manque, le zirconium ne peut pas faire de zircon (ZrSiO₄) : il cristallise en oxyde pur, la baddeleyite. Un minéral des roches alcalines, aussi réfractaire et inaltérable que son cousin silicaté — et qu'on date de la même façon.",
    especes: [
      { id: "baddeleyite", nom: "Baddeleyite", formule: "ZrO₂", systeme: "monoclinique",
        clivage: "parfait {001}", eclat: "gras à vitreux",
        durete: 6.5, densite: 5.8, stabilite: 9, swatch: "#3a352e", couleurs: "brun, brun-jaune, noir",
        contexte: "Carbonatites, syénites et roches basiques pauvres en silice ; placers.",
        devient: "Résiduelle (très inaltérable).",
        badge: "magmatique (carbonatites)",
        note: "Le dioxyde de zirconium naturel — la « zircone » —, des roches alcalines pauvres en silice où le zircon ne peut se former faute de silice. Extrêmement réfractaire ; on la date à l'uranium-plomb comme le zircon. Sa version synthétique imite le diamant.",
        condNote: "Cristallise dans les magmas sous-saturés ; inaltérable, concentrée en placers." },
    ],
  },
  {
    id: "uranium", element: "Uranium & thorium", symbole: "U", couleur: "#5a6a3a",
    intro: "Les dioxydes d'uranium et de thorium sont des jumeaux lourds et radioactifs, isostructuraux. L'uraninite est le grand minerai d'uranium — celui de la découverte du radium ; la thorianite, son analogue au thorium. Denses et éternels, ils datent les plus vieilles roches de la Terre.",
    especes: [
      { id: "uraninite", nom: "Uraninite (pechblende)", formule: "UO₂", systeme: "cubique (type fluorine)",
        clivage: "aucun", eclat: "gras à sub-métallique",
        durete: 5.5, densite: 9.5, stabilite: 6, swatch: "#2a2620", couleurs: "noir, gris-vert, éclat gras",
        contexte: "Pegmatites, filons hydrothermaux, grès uranifères ; le principal minerai d'uranium.",
        devient: "→ minéraux d'uranyle jaunes et verts (autunite, torbernite) par oxydation.",
        badge: "hydrothermale / pegmatitique — radioactive",
        note: "Le grand minerai d'uranium, noir et très dense (sa variété massive est la pechblende). C'est en l'étudiant que Marie et Pierre Curie ont isolé le polonium et le radium ; les mines du Limousin et du Forez l'ont exploitée. Sa désintégration en plomb sert à dater les roches les plus anciennes.",
        condNote: "Cristallise dans les fluides chauds et les pegmatites ; s'oxyde en minéraux d'uranyle." },
      { id: "thorianite", nom: "Thorianite", formule: "ThO₂", systeme: "cubique (type fluorine)",
        clivage: "aucun net", eclat: "résineux à sub-métallique",
        durete: 6.5, densite: 9.9, stabilite: 8, swatch: "#2f2a22", couleurs: "noir, brun sombre",
        contexte: "Pegmatites, carbonatites ; placers (Sri Lanka, Madagascar).",
        devient: "Résiduelle (dense) → placers.",
        badge: "pegmatitique — radioactive",
        note: "Le dioxyde de thorium, analogue de l'uraninite. Des pegmatites et des placers de Sri Lanka. Le thorium est un combustible nucléaire potentiel, plus abondant que l'uranium — d'où l'intérêt renouvelé pour ce minéral.",
        condNote: "Cristallise dans les pegmatites et carbonatites ; inaltérable, concentrée en placers." },
    ],
  },
  {
    id: "niobium", element: "Niobium & tantale", symbole: "Nb", couleur: "#4a4a5a",
    intro: "Niobium et tantale sont des jumeaux géochimiques inséparables, cachés dans les pegmatites et les carbonatites. Leurs oxydes — le « coltan » et le pyrochlore — sont les minerais stratégiques des condensateurs, des aciers spéciaux et des aimants supraconducteurs.",
    especes: [
      { id: "columbite", nom: "Columbite-tantalite (coltan)", formule: "(Fe,Mn)(Nb,Ta)₂O₆", systeme: "orthorhombique",
        clivage: "net {010}", eclat: "sub-métallique",
        durete: 6.25, densite: 5.7, stabilite: 9, swatch: "#2a2622", couleurs: "noir à brun-noir, éclat submétallique",
        contexte: "Pegmatites granitiques à rare-métaux ; placers.",
        devient: "Résiduelle → placers.",
        badge: "pegmatitique",
        note: "Le « coltan » : une série continue entre la columbite (pôle niobium) et la tantalite (pôle tantale), minerai stratégique du tantale des condensateurs de nos smartphones. Dense et inaltérable, elle se concentre en placers — avec les enjeux géopolitiques que l'on connaît en Afrique centrale.",
        condNote: "Cristallise dans les pegmatites ; inaltérable, concentrée en placers." },
      { id: "pyrochlore", nom: "Pyrochlore", formule: "(Na,Ca)₂Nb₂O₆(OH,F)", systeme: "cubique",
        clivage: "aucun (séparation octaédrique)", eclat: "vitreux à résineux",
        durete: 5.25, densite: 4.4, stabilite: 8, swatch: "#4a3a2a", couleurs: "brun, brun-rouge, jaune",
        contexte: "Carbonatites et syénites néphéliniques ; latérites sur carbonatite.",
        devient: "Résiduel — concentré dans les latérites d'altération des carbonatites.",
        badge: "magmatique (carbonatites)",
        note: "Le principal minerai de niobium au monde, des carbonatites du Brésil et du Canada. Le niobium sert aux aciers spéciaux et aux aimants supraconducteurs. Souvent riche en terres rares et légèrement radioactif ; son nom (grec « feu vert ») vient de sa couleur au chalumeau.",
        condNote: "Cristallise dans les carbonatites ; l'altération latéritique le concentre encore." },
    ],
  },
];

// ---------- fusion dans MINERAUX (fiches modales unifiées) ----------
for (const fam of OXYDES) {
  for (const m of fam.especes) {
    const famNom = { fer: "de fer", manganese: "de manganèse", aluminium: "d'aluminium", titane: "de titane",
      cuivre: "de cuivre", zinc: "de zinc", chrome: "de chrome", magnesium: "de magnésium", etain: "d'étain",
      zirconium: "de zirconium", uranium: "d'uranium/thorium", niobium: "de niobium/tantale" }[fam.id];
    const base = {
      nom: m.nom, formule: m.formule,
      famille: (m.formule.includes("OH") ? "Oxy-hydroxyde " : "Oxyde ") + famNom,
      durete: m.durete, densite: m.densite, stabilite: m.stabilite, swatch: m.swatch,
      devient: m.devient, note: m.note, clivage: m.clivage, eclat: m.eclat,
      systeme: m.systeme, couleurs: m.couleurs, contexte: m.contexte, oxydeDe: fam.id,
    };
    // les minéraux déjà décrits (goethite, hématite…) gardent leur prose d'origine
    MINERAUX[m.id] = Object.assign(base, MINERAUX[m.id] || {});
    Object.assign(MINERAUX[m.id], { systeme: m.systeme, couleurs: m.couleurs, contexte: m.contexte, oxydeDe: fam.id });
  }
}

// ============================================================
// DIAGRAMMES pH–Eh (Pourbaix) — 25 °C, activité des espèces dissoutes ≈ 10⁻⁶
// Tous CALCULÉS par tools/pourbaix.py à partir de constantes publiées (champ `source`), méthode classique
// de Pourbaix : ne pas retoucher `points` ni `lignes` à la main, relancer le calcul.
// Étiquettes : `etiquette` [pH, Eh] ou false, `court` (une ligne), `angle` (degrés), `renvoi` [pH, Eh]
// (trait vers un domaine trop fin pour porter son nom) ; `eau: { o2, h2 }` : pH où finit la légende d'un
// tireté de l'eau (13,8 par défaut). `lignes` : repères tiretés d'une phase métastable (ferrihydrite).
// ============================================================
const POURBAIX = {
  fer: {
    nom: "Fer",
    eau: { h2: 3.6 },
    note: "Le fer voyage en Fe²⁺ dans les milieux privés d'oxygène et précipite en oxydes ferriques dès qu'il en rencontre ; Fe³⁺ ne reste dissous que sous pH 1,9. Tiretés orange : précipitation de la ferrihydrite, le premier solide réellement formé.",
    source: "ThermoChimie v12a (PHREEQC) ; ferrate d'après Wood (1958).",
    domaines: [
      { id: "fe2", nom: "Fe²⁺ dissous", formule: "Fe²⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.28)",
        desc: "Fer ferreux dissous : le fer mobile des nappes, des sols engorgés et des eaux privées d'oxygène.",
        points: [[9.25, -0.648], [9.25, -0.579], [8.585, -0.421], [1.862, 0.772], [0, 0.772], [0, -0.648]], etiquette: [1.98, 0.059] },
      { id: "fe3", nom: "Fe³⁺ dissous", formule: "Fe³⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.28)",
        desc: "Fer ferrique dissous : seulement dans les eaux très acides et oxydantes (pH < 1,9), comme les drainages miniers.",
        points: [[1.268, 2], [0, 2], [0, 0.772], [1.862, 0.772], [1.862, 1.906]], etiquette: [0.94, 1.796] },
      { id: "feoh", nom: "FeOH⁺ dissous", formule: "FeOH⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Fer ferreux hydroxylé, sur un liseré vers pH 9,3.",
        points: [[9.25, -0.579], [9.25, -0.648], [9.53, -0.656], [9.53, -0.62]], etiquette: false },
      { id: "feoh4", nom: "Fe(OH)₄²⁻ dissous", formule: "Fe(OH)₄²⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Fer ferreux redevenu soluble à l'extrême alcalin et réducteur.",
        points: [[14, -0.934], [14, -0.844], [13.77, -0.871], [13.77, -0.907]], etiquette: false },
      { id: "fe0", nom: "Fe métal", formule: "Fe", type: "solide", couleur: "rgba(95, 95, 105, 0.48)",
        desc: "Fer métal, stable seulement sous −0,65 V, hors de l'eau naturelle : d'où la rareté du fer natif.",
        points: [[0, -1], [14, -1], [14, -0.934], [13.77, -0.907], [9.53, -0.656], [9.25, -0.648], [0, -0.648]], etiquette: [0.76, -0.8] },
      { id: "feoh2", nom: "Fe(OH)₂", formule: "Fe(OH)₂", type: "solide", couleur: "rgba(110, 150, 125, 0.40)",
        desc: "Hydroxyde ferreux blanc-vert, en milieu très réducteur et alcalin (pH > 9,5).",
        points: [[13.77, -0.907], [13.77, -0.871], [9.53, -0.62], [9.53, -0.656]], etiquette: [11.2, -0.93], court: "Fe(OH)₂", renvoi: [12, -0.784] },
      { id: "feoh3", nom: "Oxydes ferriques (Fe³⁺ solide)", formule: "Fe₂O₃ / FeO(OH)", type: "solide", couleur: "rgba(176, 120, 48, 0.40)", mineraux: ["ferrihydrite", "goethite", "lepidocrocite", "hematite", "maghemite"],
        desc: "Fer(III) solide : ferrihydrite d'abord, puis goethite ou hématite, presque aussi stables l'une que l'autre (le calcul retient l'hématite). C'est l'état normal du fer des sols aérés, d'où leurs couleurs ocre et rouge.",
        points: [[14, -0.742], [14, 0.709], [1.862, 1.906], [1.862, 0.772], [8.585, -0.421]], etiquette: [10.64, 0.242] },
      { id: "fe3o4", nom: "Fe₃O₄", formule: "Fe₃O₄ (magnétite)", type: "solide", couleur: "rgba(58, 58, 64, 0.42)", mineraux: ["magnetite"],
        desc: "Magnétite, mélange Fe²⁺/Fe³⁺ des milieux réducteurs et alcalins (pH > 8,6) ; avec du CO₂ ou du soufre, sidérite et pyrite prennent sa place.",
        points: [[14, -0.844], [14, -0.742], [8.585, -0.421], [9.25, -0.579], [9.53, -0.62], [13.77, -0.871]], etiquette: [13.35, -0.795], court: "Fe₃O₄", angle: 9.3 },
      { id: "feo4", nom: "FeO₄²⁻", formule: "FeO₄²⁻ (Fe⁶⁺) — dissous", type: "dissous", couleur: "rgba(150, 60, 160, 0.20)",
        desc: "Ferrate (fer VI), oxydant de laboratoire : tout son domaine est au-dessus de la limite de l'eau.",
        points: [[14, 0.709], [14, 2], [1.268, 2], [1.862, 1.906]], etiquette: [11.6, 1.558] },
    ],
    lignes: [
      { id: "ferrihydrite", nom: "ferrihydrite", couleur: "#c0662b", points: [[3.98, 1.634], [3.98, 0.585], [9.25, -0.35], [11.11, -0.57]], etiquette: [6.62, 0.117, 26.3] },
    ],
  },
  manganese: {
    nom: "Manganèse",
    eau: { o2: 3.1 },
    note: "Le manganèse reste dissous bien plus longtemps que le fer : à pH 6, jusqu'à +0,71 V contre +0,04 V pour le fer. Ses taches noires se déposent donc après les taches ocre.",
    source: "ThermoChimie v12a (PHREEQC).",
    domaines: [
      { id: "mn2", nom: "Mn²⁺ dissous", formule: "Mn²⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.28)",
        desc: "Manganèse dissous : il reste mobile bien plus longtemps que le fer et migre plus loin dans les profils.",
        points: [[0, -1], [10.2, -1], [10.2, -0.067], [8.39, 0.361], [7.27, 0.56], [0, 1.42]], etiquette: [3.3, -0.024] },
      { id: "mnoh4", nom: "Mn(OH)₄²⁻ dissous", formule: "Mn(OH)₄²⁻ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Manganèse(II) dissous en milieu extrêmement alcalin (pH > 13,5).",
        points: [[13.5, -1], [14, -1], [14, -0.283], [13.5, -0.343]], etiquette: [13.83, -0.572], court: "Mn(OH)₄²⁻", angle: -90 },
      { id: "mn2oh3", nom: "Mn₂(OH)₃⁺ dissous", formule: "Mn₂(OH)₃⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Complexe à deux atomes de manganèse, en milieu alcalin et réducteur (pH 10,2 à 12).",
        points: [[10.2, -1], [12.001, -1], [12.001, -0.254], [10.2, -0.067]], etiquette: [11.1, -0.407], court: "Mn₂(OH)₃⁺" },
      { id: "mno4", nom: "MnO₄⁻ (permanganate)", formule: "MnO₄⁻ (Mn⁷⁺) — dissous", type: "dissous", couleur: "rgba(150, 60, 160, 0.20)",
        desc: "Permanganate violet (Mn⁷⁺), au-dessus de la limite de l'eau : jamais dans la nature.",
        points: [[14, 0.555], [14, 2], [0, 2], [0, 1.574], [12.918, 0.555]], etiquette: [11.18, 1.423] },
      { id: "mno4b", nom: "MnO₄²⁻ (manganate)", formule: "MnO₄²⁻ (Mn⁶⁺)", type: "dissous", couleur: "rgba(80, 140, 110, 0.26)",
        desc: "Manganate vert (Mn⁶⁺), en milieu très alcalin et très oxydant.",
        points: [[14, 0.427], [14, 0.555], [12.918, 0.555]], etiquette: false },
      { id: "mn3o4", nom: "Hausmannite", formule: "Mn₃O₄ (Mn²⁺, Mn³⁺)", type: "solide", couleur: "rgba(90, 76, 84, 0.40)", mineraux: ["hausmannite"],
        desc: "Hausmannite (Mn²⁺–Mn³⁺), en milieu alcalin peu oxydant (pH > 8,4) ; surtout dans les gisements chauffés.",
        points: [[14, -0.283], [14, 0.029], [8.39, 0.361], [10.2, -0.067], [12.001, -0.254], [13.5, -0.343]], etiquette: [12.87, -0.081] },
      { id: "mnooh", nom: "Manganite (Mn³⁺)", formule: "MnO(OH)", type: "solide", couleur: "rgba(61, 54, 64, 0.35)", mineraux: ["manganite"],
        desc: "Manganite (Mn³⁺), étage intermédiaire en milieu neutre à alcalin (pH > 7,3).",
        points: [[14, 0.029], [14, 0.162], [7.27, 0.56], [8.39, 0.361]], etiquette: [8.97, 0.373], court: "MnOOH", angle: 9.3 },
      { id: "mno2", nom: "Oxydes Mn⁴⁺ (pyrolusite, birnessite)", formule: "MnO₂", type: "solide", couleur: "rgba(47, 43, 51, 0.42)", mineraux: ["pyrolusite", "birnessite", "vernadite"],
        desc: "Oxydes noirs de manganèse(IV), en milieu franchement oxydant. Calcul fait pour la pyrolusite ; dans les sols, vernadite et birnessite forment films, dendrites et nodules.",
        points: [[14, 0.162], [14, 0.427], [12.918, 0.555], [0, 1.574], [0, 1.42], [7.27, 0.56]], etiquette: [11.23, 0.47], court: "MnO₂" },
      { id: "mnoh2", nom: "Pyrochroïte", formule: "Mn(OH)₂", type: "solide", couleur: "rgba(190, 170, 160, 0.45)",
        desc: "Hydroxyde de manganèse(II), en milieu très alcalin et réducteur (pH > 12).",
        points: [[12.001, -1], [13.5, -1], [13.5, -0.343], [12.001, -0.254]], etiquette: [12.76, -0.441] },
    ],
  },
  aluminium: {
    nom: "Aluminium",
    eau: { o2: 8.4 },
    note: "Pas d'oxydo-réduction : seul le pH compte. Solide de pH 4,6 à 9,1, l'aluminium repasse en solution des deux côtés.",
    source: "ThermoChimie v12a (PHREEQC), phase retenue : gibbsite (le diaspore, plus stable mais formé en profondeur, donnerait pH 4,3 à 10,0).",
    domaines: [
      { id: "al3", nom: "Al³⁺ dissous", formule: "Al³⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.25)",
        desc: "Aluminium dissous, toxique, des milieux très acides (pH < 4,6) : sols acidifiés, drainages miniers.",
        points: [[0, -1], [4.58, -1], [4.58, 2], [0, 2]], etiquette: [2.31, 1.372] },
      { id: "al4", nom: "Aluminate dissous", formule: "Al(OH)₄⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.25)",
        desc: "Aluminate dissous, en milieu très alcalin (pH > 9,1).",
        points: [[9.13, -1], [14, -1], [14, 2], [9.13, 2]], etiquette: [11.58, 1.44] },
      { id: "gibb", nom: "Gibbsite / boehmite", formule: "Al(OH)₃ / AlO(OH)", type: "solide", couleur: "rgba(216, 200, 190, 0.45)", mineraux: ["gibbsite", "boehmite"],
        desc: "Aluminium solide de pH 4,6 à 9,1 : hydroxydes des bauxites ou, avec la silice, argiles. La boehmite a pratiquement la même solubilité que la gibbsite.",
        points: [[4.58, -1], [9.13, -1], [9.13, 2], [4.58, 2]], etiquette: [6.85, 0.115] },
    ],
  },
  titane: {
    nom: "Titane",
    note: "TiO₂ est stable dans toute l'eau naturelle (solubilité ≈ 10⁻⁹·⁶ mol/L) : le titane ne migre pas, d'où son rôle d'étalon immobile en pédologie.",
    source: "LLNL (PHREEQC).",
    domaines: [
      { id: "tio2", nom: "TiO₂ (anatase, rutile)", formule: "TiO₂", type: "solide", couleur: "rgba(74, 90, 104, 0.35)", mineraux: ["anatase", "rutile", "brookite"],
        desc: "TiO₂ reste solide dans toute l'eau naturelle. Calcul fait pour le rutile ; l'anatase des sols, dix fois plus soluble, ne change rien au diagramme.",
        points: [[7.264, -1], [14, -1], [14, 2], [0, 2], [0, -0.57]], etiquette: [8.68, 0.523] },
      { id: "ti2o3", nom: "Ti₂O₃ (titane III)", formule: "Ti₂O₃", type: "solide", couleur: "rgba(60, 70, 82, 0.45)",
        desc: "Oxyde de titane(III), seulement très en dessous de la limite de l'eau.",
        points: [[0, -1], [7.264, -1], [0, -0.57]], etiquette: [1.27, -0.842] },
    ],
  },
  cuivre: {
    nom: "Cuivre",
    note: "Métal noble : le cuivre natif reste stable dans le domaine de l'eau. Le cuivre ne voyage qu'en milieu acide (Cu²⁺ jusqu'à pH 6,8), puis précipite en ténorite ou, un cran plus bas, en cuprite.",
    source: "ThermoChimie v12a (PHREEQC).",
    domaines: [
      { id: "cu2", nom: "Cu²⁺ dissous", formule: "Cu²⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.26)",
        desc: "Cuivre(II) dissous en milieu acide (pH < 6,8) : c'est ainsi qu'il est lessivé des chapeaux d'oxydation.",
        points: [[6.815, 2], [0, 2], [0, 0.167], [5.69, 0.167], [6.815, 0.234]], etiquette: [3.92, 1.168] },
      { id: "cu1", nom: "Cu⁺ dissous", formule: "Cu⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.30)",
        desc: "Cuivre(I) dissous, dans une bande très étroite (0,15 à 0,17 V) ; les chlorures l'élargissent en eau salée.",
        points: [[5.69, 0.167], [0, 0.167], [0, 0.151], [5.69, 0.151]], etiquette: [1, -0.15], court: "Cu⁺ dissous", renvoi: [1.6, 0.159] },
      { id: "cuoh2", nom: "Cu(OH)₂⁻ dissous", formule: "Cu(OH)₂⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Cuivre(I) dissous en milieu très alcalin et réducteur (pH > 12,5).",
        points: [[14, -0.428], [14, -0.215], [13.1, -0.109], [13, -0.103], [12.51, -0.103], [12.51, -0.252]], etiquette: [13.31, -0.273], court: "Cu(OH)₂⁻", angle: 18.2 },
      { id: "cuoh3", nom: "Cu(OH)₃⁻ dissous", formule: "Cu(OH)₃⁻ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Cuprate, sur une bande de 0,1 unité de pH.",
        points: [[13.1, 2], [13, 2], [13, -0.103], [13.1, -0.109]], etiquette: false },
      { id: "cuoh4", nom: "Cu(OH)₄²⁻ dissous", formule: "Cu(OH)₄²⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Cuprate dissous au-delà de pH 13, sans équivalent naturel.",
        points: [[14, -0.215], [14, 2], [13.1, 2], [13.1, -0.109]], etiquette: [13.62, 1.677], court: "Cu(OH)₄²⁻", angle: -90 },
      { id: "cu0", nom: "Cuivre natif", formule: "Cu", type: "solide", couleur: "rgba(184, 115, 51, 0.42)", mineraux: ["cuivre_natif"],
        desc: "Cuivre natif, stable jusqu'à +0,15 V, au-dessus de la limite de l'eau : une eau privée d'oxygène ne l'attaque pas.",
        points: [[0, -1], [14, -1], [14, -0.428], [12.51, -0.252], [5.69, 0.151], [0, 0.151]], etiquette: [2.12, -0.409] },
      { id: "cu2o", nom: "Cuprite", formule: "Cu₂O (cuivre I)", type: "solide", couleur: "rgba(138, 48, 40, 0.38)", mineraux: ["cuprite"],
        desc: "Cuprite, cuivre(I) solide, entre le métal et la ténorite (pH > 5,7).",
        points: [[12.51, -0.252], [12.51, -0.103], [6.815, 0.234], [5.69, 0.167], [5.69, 0.151]], etiquette: [8.95, 0.013], court: "Cu₂O", angle: 9.3 },
      { id: "cuo", nom: "Ténorite", formule: "CuO (cuivre II)", type: "solide", couleur: "rgba(42, 38, 36, 0.30)", mineraux: ["tenorite"],
        desc: "Ténorite, cuivre(II) solide (pH > 6,8) ; avec du CO₂, malachite et azurite prennent le relais.",
        points: [[13, 2], [6.815, 2], [6.815, 0.234], [12.51, -0.103], [13, -0.103]], etiquette: [9.93, 1.1] },
    ],
  },
  zinc: {
    nom: "Zinc",
    note: "Une seule valence, donc des limites verticales : le zinc reste dissous jusqu'à pH 8,6, quel que soit le potentiel.",
    source: "LLNL (PHREEQC).",
    domaines: [
      { id: "zn2", nom: "Zn²⁺ dissous", formule: "Zn²⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.26)",
        desc: "Zinc dissous jusqu'à pH 8,6 : l'un des métaux les plus mobiles des sols acides à neutres.",
        points: [[8.604, -0.941], [8.604, 2], [0, 2], [0, -0.941]], etiquette: [4.29, 0.658] },
      { id: "znoh3", nom: "Zn(OH)₃⁻ dissous", formule: "Zn(OH)₃⁻ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Zincate dissous en milieu très alcalin : le zinc est amphotère, comme l'aluminium.",
        points: [[11.628, -1], [12.768, -1], [12.768, 2], [11.628, 2]], etiquette: [12.19, 1.915], court: "Zn(OH)₃⁻" },
      { id: "znoh4", nom: "Zn(OH)₄²⁻ dissous", formule: "Zn(OH)₄²⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Zincate dominant au-delà de pH 12,8.",
        points: [[12.768, -1], [14, -1], [14, 2], [12.768, 2]], etiquette: [13.38, 1.915], court: "Zn(OH)₄²⁻" },
      { id: "zno", nom: "Zincite", formule: "ZnO", type: "solide", couleur: "rgba(200, 160, 60, 0.36)", mineraux: ["zincite", "smithsonite", "hemimorphite"],
        desc: "Zincite, de pH 8,6 à 11,6. Dans la nature, le zinc précipite plutôt en smithsonite ou en hémimorphite.",
        points: [[9.605, -1], [11.628, -1], [11.628, 2], [8.604, 2], [8.604, -0.941]], etiquette: [10.11, 1.542] },
      { id: "zn0", nom: "Zinc métal", formule: "Zn", type: "solide", couleur: "rgba(95, 95, 105, 0.48)",
        desc: "Zinc métal, stable seulement sous −0,94 V : il se corrode spontanément, d'où son rôle de protection de l'acier.",
        points: [[0, -1], [9.605, -1], [8.604, -0.941], [0, -0.941]], etiquette: [3, -0.78], court: "Zinc métal", renvoi: [3.6, -0.97] },
    ],
  },
  chrome: {
    nom: "Chrome",
    note: "Le chrome(III), insoluble, occupe presque tout le domaine de l'eau ; le chrome(VI), soluble et toxique, n'apparaît qu'en milieu oxydant, d'autant plus facilement que le pH est élevé.",
    source: "ThermoChimie v12a (PHREEQC).",
    domaines: [
      { id: "cro4", nom: "CrO₄²⁻ dissous", formule: "CrO₄²⁻ (Cr⁶⁺)", type: "dissous", couleur: "rgba(222, 185, 40, 0.30)",
        desc: "Chromate jaune (chrome VI). À pH 9, il apparaît dès +0,37 V : dans les sols alcalins sur serpentinite, les oxydes de manganèse suffisent à le former.",
        points: [[14, -0.123], [14, 2], [6.52, 2], [6.52, 0.614]], etiquette: [10.96, 1.168] },
      { id: "cr2", nom: "Cr²⁺ dissous", formule: "Cr²⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.30)",
        desc: "Chrome(II), sous la limite de l'eau qu'il décompose : absent de la nature.",
        points: [[0, -1], [5.3, -1], [5.3, -0.735], [3.292, -0.379], [0, -0.379]], etiquette: [1.37, -0.667] },
      { id: "cr3", nom: "Cr³⁺ dissous", formule: "Cr³⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.26)",
        desc: "Chrome(III) dissous, seulement en milieu acide (pH < 3,3).",
        points: [[0, 1.323], [0, -0.379], [3.292, -0.379], [3.292, 0.869]], etiquette: [1.65, 0.576] },
      { id: "croh", nom: "Cr(OH)⁺ dissous", formule: "Cr(OH)⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Chrome(II) hydroxylé, sous la limite de l'eau.",
        points: [[5.3, -1], [7.539, -1], [5.3, -0.735]], etiquette: [5.82, -0.939], court: "Cr(OH)⁺" },
      { id: "hcro4", nom: "HCrO₄⁻ dissous", formule: "HCrO₄⁻ (Cr⁶⁺)", type: "dissous", couleur: "rgba(230, 130, 40, 0.30)",
        desc: "Chrome(VI) dissous en milieu acide et oxydant : soluble, toxique et cancérogène.",
        points: [[6.52, 0.614], [6.52, 2], [0, 2], [0, 1.323], [3.292, 0.869]], etiquette: [4.34, 1.457] },
      { id: "cr2o3", nom: "Eskolaïte (chrome III)", formule: "Cr₂O₃", type: "solide", couleur: "rgba(47, 110, 70, 0.34)", mineraux: ["eskolaite", "chromite"],
        desc: "Chrome(III) solide, insoluble et peu toxique : l'état normal du chrome des roches et des sols, où il est enfermé dans la chromite.",
        points: [[7.539, -1], [14, -1], [14, -0.123], [6.52, 0.614], [3.292, 0.869], [3.292, -0.379], [5.3, -0.735]], etiquette: [7.96, -0.252] },
    ],
  },
  magnesium: {
    nom: "Magnésium",
    note: "Une seule limite : le magnésium reste dissous jusqu'à pH 11,5 et ne précipite qu'en milieu très alcalin.",
    source: "ThermoChimie v12a (PHREEQC).",
    domaines: [
      { id: "mg2", nom: "Mg²⁺ dissous", formule: "Mg²⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.26)",
        desc: "Magnésium dissous jusqu'à pH 11,5 : l'un des cations majeurs des eaux.",
        points: [[0, -1], [11.55, -1], [11.55, 2], [0, 2]], etiquette: [4.67, 0.523] },
      { id: "brucite", nom: "Brucite", formule: "Mg(OH)₂", type: "solide", couleur: "rgba(170, 190, 160, 0.55)", mineraux: ["brucite"],
        desc: "Brucite, en milieu très alcalin (pH > 11,5), comme dans les sources des ophiolites.",
        points: [[11.55, -1], [14, -1], [14, 2], [11.55, 2]], etiquette: [12.78, 1.643] },
    ],
  },
  etain: {
    nom: "Étain",
    note: "La cassitérite occupe presque tout le diagramme : l'étain ne se dissout qu'en milieu très acide et réducteur, ou très alcalin.",
    source: "ThermoChimie v12a (PHREEQC).",
    domaines: [
      { id: "sn2", nom: "Sn²⁺ dissous", formule: "Sn²⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.30)",
        desc: "Étain(II) dissous, en milieu acide et réducteur (pH < 3,5).",
        points: [[3.53, -0.319], [3.53, -0.318], [0, 0.1], [0, -0.319]], etiquette: [0.85, -0.189] },
      { id: "snoh3", nom: "Sn(OH)₃⁻ dissous", formule: "Sn(OH)₃⁻ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Étain(II) dissous en milieu alcalin très réducteur.",
        points: [[13.146, -1], [13.829, -1], [10.365, -0.693], [9.34, -0.662]], etiquette: false },
      { id: "snoh6", nom: "Sn(OH)₆²⁻ dissous", formule: "Sn(OH)₆²⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Stannate dissous au-delà de pH 10,4.",
        points: [[13.829, -1], [14, -1], [14, 2], [10.365, 2], [10.365, -0.693]], etiquette: [12.21, 1.66] },
      { id: "sno2", nom: "Cassitérite", formule: "SnO₂ (étain IV)", type: "solide", couleur: "rgba(74, 66, 56, 0.30)", mineraux: ["cassiterite"],
        desc: "Cassitérite, de pH 0 à 10,4 : quasi insoluble (≈ 10⁻⁸ mol/L), elle se concentre dans les alluvions.",
        points: [[10.365, 2], [0, 2], [0, 0.1], [3.53, -0.318], [3.56, -0.32], [9.34, -0.662], [10.365, -0.693]], etiquette: [6.28, 0.726] },
      { id: "sn0", nom: "Étain métal", formule: "Sn (étain blanc β)", type: "solide", couleur: "rgba(150, 150, 162, 0.46)",
        desc: "Étain métal, stable juste sous la limite de l'eau ; à l'air, une pellicule de SnO₂ le protège.",
        points: [[0, -1], [13.146, -1], [9.34, -0.662], [3.56, -0.32], [3.53, -0.319], [0, -0.319]], etiquette: [1.65, -0.642] },
    ],
  },
  zirconium: {
    nom: "Zirconium",
    note: "La zircone est stable sur tout le diagramme : comme le titane, le zirconium ne migre pas. Dans les roches, il est fixé dans le zircon.",
    source: "ThermoChimie v12a (PHREEQC), d'après la revue OCDE-AEN (Brown et al., 2005).",
    domaines: [
      { id: "zro2", nom: "Baddeleyite (zircone)", formule: "ZrO₂", type: "solide", couleur: "rgba(106, 90, 74, 0.24)", mineraux: ["baddeleyite", "zircon"],
        desc: "Zircone, stable de pH 0 à 14 (solubilité ≈ 10⁻⁹ mol/L).",
        points: [[0, -1], [14, -1], [14, 2], [0, 2]], etiquette: [5.24, 0.523] },
    ],
  },
  uranium: {
    nom: "Uranium",
    note: "Soluble à l'état U(VI) dans les eaux oxydantes, insoluble à l'état U(IV) dès que le milieu devient réducteur : l'uranium se concentre aux fronts d'oxydo-réduction. Le thorium, lui, est solide (ThO₂) dès pH 1,9.",
    source: "ThermoChimie v12a (PHREEQC), d'après les revues OCDE-AEN.",
    domaines: [
      { id: "uo2", nom: "UO₂²⁺ dissous", formule: "uranyle, U⁶⁺ (aq)", type: "dissous", couleur: "rgba(224, 86, 63, 0.26)",
        desc: "Ion uranyle (U⁶⁺) : la forme mobile de l'uranium des eaux oxydantes et acides.",
        points: [[5.25, 2], [0, 2], [0, 0.267], [0.288, 0.233], [3.755, 0.233], [5.123, 0.26], [5.25, 0.276]], etiquette: [2.64, 1.304] },
      { id: "u4", nom: "U⁴⁺ dissous", formule: "U⁴⁺ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.30)",
        desc: "Uranium(IV) dissous, en milieu extrêmement acide (pH < 0,3).",
        points: [[0.288, 0.233], [0, 0.267], [0, -0.553], [0.288, -0.553]], etiquette: false },
      { id: "u3", nom: "U³⁺ dissous", formule: "U³⁺ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Uranium(III), sous la limite de l'eau.",
        points: [[0, -1], [2.176, -1], [0.288, -0.553], [0, -0.553]], etiquette: [0.52, -0.859], court: "U³⁺" },
      { id: "uo23oh5", nom: "(UO₂)₃(OH)₅⁺ dissous", formule: "(UO₂)₃(OH)₅⁺ (aq)", type: "dissous", couleur: "rgba(200, 120, 150, 0.26)",
        desc: "Complexe polynucléaire, sur une bande très fine vers pH 5,7.",
        points: [[5.717, 2], [5.661, 2], [5.661, 0.288], [5.717, 0.287]], etiquette: false },
      { id: "uo2oh", nom: "UO₂OH⁺ dissous", formule: "UO₂OH⁺ (aq)", type: "dissous", couleur: "rgba(224, 140, 90, 0.24)",
        desc: "Premier complexe hydroxylé de l'uranyle (pH 5,25 à 5,7).",
        points: [[5.661, 2], [5.25, 2], [5.25, 0.276], [5.661, 0.288]], etiquette: [5.53, 1.83], court: "UO₂OH⁺", angle: -90 },
      { id: "uo2oh3", nom: "UO₂(OH)₃⁻ dissous", formule: "UO₂(OH)₃⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Uranyle redissous en milieu alcalin ; dans la nature, surtout en complexes carbonatés.",
        points: [[12.15, 2], [9.32, 2], [9.32, 0.073], [10.004, -0.028], [12.15, -0.24]], etiquette: [10.74, 1.796] },
      { id: "uo2oh4", nom: "UO₂(OH)₄²⁻ dissous", formule: "UO₂(OH)₄²⁻ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Uranate dissous au-delà de pH 12.",
        points: [[14, -0.465], [14, 2], [12.15, 2], [12.15, -0.24], [12.445, -0.281]], etiquette: [13.09, 1.83], court: "UO₂(OH)₄²⁻" },
      { id: "uo2oh2", nom: "Hydroxyde d'uranyle", formule: "UO₂(OH)₂ ≈ schoepite", type: "solide", couleur: "rgba(222, 190, 60, 0.42)", mineraux: ["autunite", "torbernite"],
        desc: "Uranium(VI) solide près de la neutralité (pH 5,7 à 9,3) : famille de la schoepite ; avec du phosphate, autunite ou torbernite.",
        points: [[9.32, 2], [5.717, 2], [5.717, 0.287], [9.32, 0.073]], etiquette: [7.51, 1.711] },
      { id: "u4o9", nom: "U₄O₉", formule: "UO₂,₂₅", type: "solide", couleur: "rgba(80, 92, 60, 0.38)", mineraux: ["uraninite"],
        desc: "Oxyde mixte U(IV)–U(VI), premier palier d'oxydation de l'uraninite.",
        points: [[12.445, -0.281], [12.15, -0.24], [10.004, -0.028], [5.123, 0.26], [3.755, 0.233]], etiquette: [11, -0.38], court: "U₄O₉", renvoi: [10.5, -0.12] },
      { id: "u3o8", nom: "U₃O₈", formule: "UO₂,₆₇", type: "solide", couleur: "rgba(120, 130, 70, 0.34)",
        desc: "Oxyde mixte plus oxydé, dernier palier avant l'uranium(VI).",
        points: [[10.004, -0.028], [9.32, 0.073], [5.717, 0.287], [5.661, 0.288], [5.25, 0.276], [5.123, 0.26]], etiquette: [9, 0.33], court: "U₃O₈", renvoi: [8.5, 0.091] },
      { id: "uraninite", nom: "Uraninite", formule: "UO₂ (U⁴⁺)", type: "solide", couleur: "rgba(42, 38, 32, 0.36)", mineraux: ["uraninite"],
        desc: "Uranium(IV) quasi insoluble (≈ 10⁻¹⁵ mol/L) : en milieu réducteur, l'uranium précipite en pechblende.",
        points: [[2.176, -1], [14, -1], [14, -0.465], [12.445, -0.281], [3.755, 0.233], [0.288, 0.233], [0.288, -0.553]], etiquette: [3.17, -0.361] },
    ],
  },
  niobium: {
    nom: "Niobium",
    note: "Solide jusqu'à pH 8,2 sur toute la hauteur de l'eau, le niobium ne se dissout qu'en milieu alcalin ; ses oxydes réduits n'existent que sous la limite de l'eau.",
    source: "solides NIST-JANAF, espèces dissoutes ThermoChimie v12a (PHREEQC).",
    domaines: [
      { id: "nboh6", nom: "Nb(OH)₆⁻ dissous", formule: "Nb(OH)₆⁻ (aq)", type: "dissous", couleur: "rgba(90, 140, 200, 0.16)",
        desc: "Niobate dissous au-delà de pH 8,2.",
        points: [[8.88, -0.827], [8.88, 2], [8.19, 2], [8.19, -0.745]], etiquette: [8.57, 1.745], court: "Nb(OH)₆⁻", angle: -90 },
      { id: "nboh7", nom: "Nb(OH)₇²⁻ dissous", formule: "Nb(OH)₇²⁻ (aq)", type: "dissous", couleur: "rgba(120, 110, 200, 0.20)",
        desc: "Niobate dominant au-delà de pH 8,9.",
        points: [[9.855, -1], [14, -1], [14, 2], [8.88, 2], [8.88, -0.827]], etiquette: [11.43, 1.389] },
      { id: "nb2o5", nom: "Nb₂O₅ (niobium V)", formule: "Nb₂O₅", type: "solide", couleur: "rgba(74, 58, 42, 0.28)", mineraux: ["pyrochlore", "columbite"],
        desc: "Niobium(V) solide jusqu'à pH 8,2 (solubilité ≈ 10⁻⁹ mol/L) ; dans la nature, il est dans le pyrochlore, la columbite ou le rutile.",
        points: [[8.19, -0.745], [8.19, 2], [0, 2], [0, -0.261]], etiquette: [4.11, 0.828] },
      { id: "nb0", nom: "Niobium métal", formule: "Nb", type: "solide", couleur: "rgba(95, 95, 105, 0.48)",
        desc: "Niobium métal, sous −0,8 V.",
        points: [[0, -1], [3.346, -1], [0, -0.802]], etiquette: [0.24, -0.938], court: "Nb" },
      { id: "nbo2", nom: "NbO₂", formule: "niobium IV", type: "solide", couleur: "rgba(70, 70, 92, 0.40)",
        desc: "Oxyde de niobium(IV), sous la limite de l'eau.",
        points: [[7.259, -1], [9.855, -1], [8.88, -0.827], [8.19, -0.745], [0, -0.261], [0, -0.571]], etiquette: [6.04, -0.753] },
      { id: "nbo", nom: "NbO", formule: "niobium II", type: "solide", couleur: "rgba(92, 92, 112, 0.46)",
        desc: "Monoxyde de niobium, encore plus réduit.",
        points: [[3.346, -1], [7.259, -1], [0, -0.571], [0, -0.802]], etiquette: [3.16, -0.893], court: "NbO" },
    ],
  },
};

// milieux naturels types pour le visualiseur pH–Eh
const PHEH_MILIEUX = [
  { nom: "Eau de pluie / sol aéré", ph: 5.6, eh: 0.6 },
  { nom: "Sol calcaire aéré", ph: 8.0, eh: 0.45 },
  { nom: "Sol tropical lessivé", ph: 4.5, eh: 0.65 },
  { nom: "Marais / tourbière", ph: 5.0, eh: -0.15 },
  { nom: "Gley (nappe permanente)", ph: 6.8, eh: -0.2 },
  { nom: "Sédiment marin réduit", ph: 7.5, eh: -0.25 },
  { nom: "Eau de mer", ph: 8.1, eh: 0.4 },
  { nom: "Drainage minier acide", ph: 2.5, eh: 0.8 },
];
