// ============================================================
// CLASSE II — SULFURES & SULFOSELS (Strunz II)
// Sources : Wikipédia FR/EN, Mindat, Strunz 10e éd.
// ============================================================

Object.assign(MINERAUX, {
  chalcocite: {
    nom: "Chalcocite", formule: "Cu₂S", famille: "Sulfure riche en métal",
    systeme: "monoclinique (pseudo-hexagonal)", durete: 2.75, densite: 5.7,
    clivage: "indistinct", eclat: "métallique, gris de plomb",
    couleurs: "gris sombre à noir, ternissant en noir mat",
    contexte: "Zone de cémentation des gisements de cuivre : elle s'enrichit sous le chapeau de fer, aux dépens des sulfures primaires.",
    stabilite: 2, swatch: "#4a4a50",
    devient: "S'oxyde en malachite, azurite et cuprite.",
    note: "Le minerai de cuivre le plus riche (80 % de métal). C'est le trésor des « zones de cémentation » : l'eau acide du chapeau de fer redépose en profondeur le cuivre lessivé, transformant un gisement médiocre en bonanza. Chessy-les-Mines (Rhône) en fut l'exemple français classique.",
  },
  bornite: {
    nom: "Bornite", formule: "Cu₅FeS₄", famille: "Sulfure riche en métal",
    systeme: "orthorhombique (pseudo-cubique)", durete: 3, densite: 5.1,
    clivage: "très indistinct", eclat: "métallique",
    couleurs: "bronze rosé frais → irisations bleu-violet-pourpre spectaculaires",
    contexte: "Filons et gisements de cuivre, avec chalcopyrite et chalcocite.",
    stabilite: 2, swatch: "#7a5570",
    devient: "S'oxyde en malachite et azurite via la chalcocite.",
    note: "La « gorge-de-pigeon » des mineurs : sa surface s'irise en quelques jours de bleus et de violets métalliques — un simple film d'oxydation, comme l'essence sur l'eau. Fraîchement cassée, elle est bronze rosé ; les échantillons trop flamboyants du commerce ont souvent été « aidés » à l'acide.",
  },
  acanthite: {
    nom: "Acanthite (argentite)", formule: "Ag₂S", famille: "Sulfure riche en métal",
    systeme: "monoclinique (cubique > 173 °C : argentite)", durete: 2.25, densite: 7.3,
    clivage: "indistinct — sécable au couteau comme du plomb", eclat: "métallique terne",
    couleurs: "gris de plomb à noir",
    contexte: "Filons argentifères, en cristaux ou en masses sécables ; c'est aussi elle qui noircit l'argenterie.",
    stabilite: 2, swatch: "#3f3f45",
    devient: "Stable en profondeur ; en surface, suit le destin des filons oxydés (argent natif, chlorargyrite).",
    note: "Le principal minerai d'argent. Le ternissement noir des couverts en argent est exactement le même minéral, formé par le soufre de l'air et des aliments — chaque cuillère noircie fabrique de l'acanthite. Les filons de Sainte-Marie-aux-Mines et du Mexique colonial reposaient sur elle.",
  },
  pentlandite: {
    nom: "Pentlandite", formule: "(Fe,Ni)₉S₈", famille: "Sulfure riche en métal",
    systeme: "cubique", durete: 3.75, densite: 4.8,
    clivage: "aucun (cassure conchoïdale)", eclat: "métallique",
    couleurs: "bronze jaunâtre",
    contexte: "Ségrégations magmatiques dans les roches ultrabasiques et les impacts (Sudbury, Norilsk), toujours mêlée à la pyrrhotite.",
    stabilite: 2, swatch: "#a08858",
    devient: "S'altère en violarite puis en oxydes de fer et nickel dissous.",
    note: "Le grand minerai de nickel sulfuré. Le gisement de Sudbury (Canada) tapisse le fond d'un cratère d'impact vieux de 1,85 milliard d'années : l'astéroïde a fait fondre la croûte, et les gouttes de sulfures se sont déposées comme l'huile au fond d'une vinaigrette. Un tiers du nickel mondial vient de là.",
  },
  pyrrhotite: {
    nom: "Pyrrhotite", formule: "Fe₁₋ₓS", famille: "Sulfure 1:1 (déficitaire en fer)",
    systeme: "monoclinique / hexagonal", durete: 3.75, densite: 4.6,
    clivage: "aucun net", eclat: "métallique",
    couleurs: "bronze rougeâtre, ternissant vite",
    contexte: "Roches magmatiques basiques, gisements de nickel, roches métamorphiques ; le plus commun des sulfures après la pyrite.",
    stabilite: 1, swatch: "#8a6a4f",
    devient: "S'oxyde très vite : oxydes de fer + acide sulfurique (drainage minier).",
    note: "Le seul sulfure commun franchement magnétique — d'où son surnom de « pyrite magnétique ». Son truc : il manque du fer dans son réseau (Fe₀,₈S à FeS), et ce déficit fait son magnétisme. Incorporée par accident dans des bétons québécois, sa pyrrhotite gonflante a fissuré des milliers de fondations : un scandale géologique moderne.",
  },
  cinabre: {
    nom: "Cinabre", formule: "HgS", famille: "Sulfure 1:1",
    systeme: "rhomboédrique", durete: 2.25, densite: 8.1,
    clivage: "parfait {10-10}", eclat: "adamantin à mat",
    couleurs: "rouge vermillon à rouge brunâtre",
    contexte: "Imprégnations de basse température autour des sources chaudes et volcans de boue (Almadén, Idrija, Monte Amiata).",
    stabilite: 4, swatch: "#9e2b25",
    devient: "Très stable ; libère parfois des gouttelettes de mercure natif.",
    note: "LE minerai du mercure et LE rouge vermillon des peintres — des fresques de Pompéi aux laques chinoises. Broyé, il donne le pigment ; chauffé, il libère le mercure. Les forçats d'Almadén et les peintres saturnins en ont payé la toxicité. Sa densité (8) trahit le métal qu'il enferme.",
  },
  covellite: {
    nom: "Covellite", formule: "CuS", famille: "Sulfure 1:1",
    systeme: "hexagonal", durete: 1.75, densite: 4.7,
    clivage: "parfait {0001} (feuillets flexibles)", eclat: "sub-métallique",
    couleurs: "bleu indigo profond, irisations pourpres",
    contexte: "Zone de cémentation des gisements de cuivre, en placages sur les autres sulfures.",
    stabilite: 2, swatch: "#26356e",
    devient: "S'oxyde en carbonates de cuivre (malachite).",
    note: "Le bleu le plus profond du monde des sulfures — un indigo métallique qui vire au pourpre sous un filet d'eau. Décrite au Vésuve par Niccolò Covelli, elle tapisse en placages minces les zones enrichies des mines de cuivre. Trop tendre et trop rare pour être un minerai majeur : c'est la touche de couleur des collections.",
  },
  nickeline: {
    nom: "Nickéline", formule: "NiAs", famille: "Sulfure 1:1 (arséniure)",
    systeme: "hexagonal", durete: 5.25, densite: 7.8,
    clivage: "aucun", eclat: "métallique",
    couleurs: "rouge cuivré pâle caractéristique",
    contexte: "Filons hydrothermaux à Co-Ni-Ag et roches basiques (Erzgebirge, Cobalt en Ontario).",
    stabilite: 2, swatch: "#b3785a",
    devient: "S'altère en annabergite, arséniate de nickel vert pomme.",
    note: "Le minéral qui a nommé le nickel : les mineurs saxons, croyant tenir du cuivre (Kupfer), n'en tiraient rien et accusèrent un lutin malicieux, le « Nickel » — d'où Kupfernickel, le faux-cuivre. Quand le métal fut isolé en 1751, le nom du lutin lui resta.",
  },
  stibine: {
    nom: "Stibine", formule: "Sb₂S₃", famille: "Sulfure pauvre en métal",
    systeme: "orthorhombique", durete: 2, densite: 4.6,
    clivage: "parfait {100} ({010} dans la notation Pbnm des ouvrages)", eclat: "métallique brillant",
    couleurs: "gris acier, irisations noirâtres",
    contexte: "Filons de basse température ; districts antimonifères français (Brioude-Massiac, La Lucette, Vendée).",
    stabilite: 2, swatch: "#5f6066",
    devient: "S'oxyde en ocres blancs et jaunes d'antimoine (valentinite, stibiconite).",
    note: "Ses gerbes de cristaux aciculaires brillants sont parmi les plus élégantes du règne minéral (les géantes viennent du Japon et de Chine). LE minerai d'antimoine — celui qui fit de la France le premier producteur mondial vers 1900, de Brioude-Massiac (Haute-Loire) à La Lucette (Mayenne). Fusible à la flamme d'une simple allumette.",
  },
  orpiment: {
    nom: "Orpiment", formule: "As₂S₃", famille: "Sulfure pauvre en métal",
    systeme: "monoclinique", durete: 1.75, densite: 3.5,
    clivage: "parfait {010} (feuillets flexibles)", eclat: "résineux à nacré",
    couleurs: "jaune d'or à jaune citron",
    contexte: "Fumerolles, sources chaudes et filons de très basse température, souvent avec le réalgar.",
    stabilite: 3, swatch: "#e0a91f",
    devient: "S'oxyde lentement en arsénolite.",
    note: "L'« or en pigment » (auripigmentum) : le jaune royal des enlumineurs médiévaux et des peintres persans — magnifique et toxique, comme son frère rouge le réalgar. Les deux vont ensemble dans les dépôts de sources chaudes : un duo jaune-rouge qui criait « arsenic » aux prospecteurs.",
  },
  realgar: {
    nom: "Réalgar", formule: "As₄S₄", famille: "Sulfure pauvre en métal",
    systeme: "monoclinique", durete: 1.75, densite: 3.6,
    clivage: "bon {010}", eclat: "résineux",
    couleurs: "rouge orangé vif",
    contexte: "Filons de basse température et fumerolles ; la mine de Matra (Corse) en fut un gisement européen classique.",
    stabilite: 2, swatch: "#c43a26",
    devient: "La lumière le désagrège en pararéalgar jaune-orangé pulvérulent.",
    note: "Le « rubis d'arsenic » a un talon d'Achille : la lumière. Exposé en vitrine, un cristal rouge se délite en quelques années en poudre orangée (pararéalgar) — les collectionneurs le gardent dans le noir. La mine de Matra, en Corse, a fourni les beaux réalgars européens du début du XXe siècle.",
  },
  molybdenite: {
    nom: "Molybdénite", formule: "MoS₂", famille: "Sulfure pauvre en métal",
    systeme: "hexagonal", durete: 1.25, densite: 4.7,
    clivage: "parfait {0001} (feuillets gras, flexibles)", eclat: "métallique",
    couleurs: "gris de plomb bleuté",
    contexte: "Greisens, pegmatites et porphyres granitiques ; en lamelles hexagonales dans le quartz.",
    stabilite: 3, swatch: "#5a616b",
    devient: "S'oxyde très lentement en wulfénite et poudres jaunes de molybdène.",
    note: "Si semblable au graphite qu'on les a confondus des siècles (molybdos = plomb, encore une confusion !). Même toucher gras, même trace grise — mais sur porcelaine, sa trace tire au vert-bleu. Ses feuillets qui glissent en font un lubrifiant haute température (le « moly » des mécaniciens), et l'électronique découpe aujourd'hui ses monocouches comme celles du graphène.",
  },
  arsenopyrite: {
    nom: "Arsénopyrite (mispickel)", formule: "FeAsS", famille: "Sulfure pauvre en métal",
    systeme: "monoclinique (pseudo-orthorhombique)", durete: 5.75, densite: 6.1,
    clivage: "net {101}", eclat: "métallique",
    couleurs: "blanc d'étain à gris acier",
    contexte: "Filons hydrothermaux, skarns et gisements d'or : l'or « invisible » se cache souvent dans son réseau (Salsigne).",
    stabilite: 2, swatch: "#8f9299",
    devient: "S'oxyde en scorodite verdâtre ; libère arsenic et acide (drainage minier).",
    note: "Frappée au marteau, elle crache des étincelles et une odeur d'ail — la signature de l'arsenic. C'est elle qui piégeait l'or « invisible » de Salsigne (Aude), plus grande mine d'or d'Europe occidentale… et source de l'arsenic qui pollue encore la vallée de l'Orbiel : l'héritage a deux faces.",
  },
  tetraedrite: {
    nom: "Tétraédrite", formule: "Cu₁₂Sb₄S₁₃ (série avec la tennantite à As)", famille: "Sulfosel",
    systeme: "cubique", durete: 3.75, densite: 4.9,
    clivage: "aucun", eclat: "métallique",
    couleurs: "gris acier à noir",
    contexte: "Filons hydrothermaux : le « cuivre gris » des mineurs, souvent riche en argent (Banca au Pays basque, Alpes).",
    stabilite: 2, swatch: "#54565c",
    devient: "S'oxyde en malachite, azurite et ocres d'antimoine.",
    note: "Ses cristaux en tétraèdres parfaits lui ont donné son nom. Sous le nom de « cuivre gris », elle fut le minerai complexe des filons français et alpins : cuivre, antimoine, et surtout l'argent qui s'y glisse — beaucoup de « mines d'argent » historiques, comme Banca au Pays basque, exploitaient en réalité du cuivre gris argentifère.",
  },
  bournonite: {
    nom: "Bournonite", formule: "PbCuSbS₃", famille: "Sulfosel",
    systeme: "orthorhombique", durete: 2.75, densite: 5.8,
    clivage: "imparfait", eclat: "métallique",
    couleurs: "gris acier à noir",
    contexte: "Filons à plomb-antimoine ; macles caractéristiques en « roue dentée » (cogwheel).",
    stabilite: 2, swatch: "#4c4e54",
    devient: "S'oxyde en cérusite et ocres d'antimoine.",
    note: "Ses macles s'emboîtent en « roues d'engrenage » — les wheel ores des mineurs de Cornouailles. Elle honore le comte Jacques-Louis de Bournon, cristallographe français émigré à Londres pendant la Révolution : la minéralogie du XIXe siècle parlait français, même en exil.",
  },
  boulangerite: {
    nom: "Boulangérite", formule: "Pb₅Sb₄S₁₁", famille: "Sulfosel",
    systeme: "monoclinique", durete: 2.75, densite: 6.2,
    clivage: "bon {100}", eclat: "métallique soyeux",
    couleurs: "gris de plomb, souvent en feutrage d'aiguilles",
    contexte: "Filons plomb-zinc-antimoine, en masses fibreuses ou en « cheveux » emmêlés dans le quartz.",
    stabilite: 2, swatch: "#5b5d64",
    devient: "S'oxyde en cérusite et ocres d'antimoine.",
    note: "Un sulfosel bien français : décrit en 1837 sur les échantillons de Molières-sur-Cèze (Gard) et dédié à l'ingénieur des mines Charles Boulanger. Ses aiguilles grises feutrées, parfois fines comme des cheveux, emplissent les géodes de quartz — les Alpes et la Bretagne minière en ont livré de jolis « plumeaux ».",
  },
  proustite: {
    nom: "Proustite", formule: "Ag₃AsS₃", famille: "Sulfosel (argent rouge)",
    systeme: "rhomboédrique", durete: 2.25, densite: 5.6,
    clivage: "net {10-11}", eclat: "adamantin",
    couleurs: "rouge écarlate translucide — noircit à la lumière",
    contexte: "Filons argentifères riches, en cristaux dans les géodes (Chañarcillo au Chili, Sainte-Marie-aux-Mines).",
    stabilite: 2, swatch: "#8e1f2a",
    devient: "La lumière la noircit (argent photolytique) ; l'altération libère l'argent des filons.",
    note: "L'« argent rouge clair » : un rubis métallique translucide, parmi les plus beaux minéraux du monde — et les plus fragiles : la lumière le noircit comme une pellicule photo, par le même mécanisme argentique. Elle honore Joseph Proust, le chimiste français de la loi des proportions définies. Sa jumelle antimoniée, la pyrargyrite, est l'« argent rouge sombre ».",
  },
  pyrargyrite: {
    nom: "Pyrargyrite", formule: "Ag₃SbS₃", famille: "Sulfosel (argent rouge)",
    systeme: "rhomboédrique", durete: 2.5, densite: 5.85,
    clivage: "net {10-11}", eclat: "adamantin",
    couleurs: "rouge sombre à noir rougeâtre, translucide en lame mince",
    contexte: "Filons argentifères, plus commune que la proustite (Andreasberg, Guanajuato, filons vosgiens).",
    stabilite: 2, swatch: "#5e1a22",
    devient: "Noircit à la lumière ; source d'argent des zones d'enrichissement.",
    note: "Le pendant antimonié de la proustite — « feu d'argent » (pyr-argyros). Plus sombre, plus commune, elle fut un vrai minerai dans les bonanzas mexicaines et du Harz. Louis XIII de Saxe enfermait déjà le duo des « argents rouges » à l'abri de la lumière.",
  },
});

(function () {
  const c = MIN_CLASSIF.find((x) => x.n === 2);
  c.groupes = [
    {
      nom: "Sulfures riches en métal", code: "II.B", motif: "métal:soufre > 1:1 (Cu₂S, Ag₂S…)",
      note: "Les plus riches en métal, donc les minerais les plus convoités : c'est le monde des zones de cémentation, où le cuivre et l'argent lessivés en surface se reconcentrent en profondeur.",
      mineraux: ["chalcocite", "bornite", "acanthite", "pentlandite"],
    },
    {
      nom: "Sulfures 1:1", code: "II.C", motif: "métal:soufre ≈ 1:1 (PbS, ZnS, FeS…)",
      note: "Le cœur de la classe : galène, blende et chalcopyrite forment le trio plomb-zinc-cuivre de presque tous les filons du monde. Autour d'eux, les curiosités : cinabre du mercure, covellite indigo, nickéline du lutin Nickel.",
      mineraux: ["galene", "blende", "chalcopyrite", "pyrrhotite", "cinabre", "covellite", "nickeline"],
    },
    {
      nom: "Sulfures pauvres en métal", code: "II.D-F", motif: "métal:soufre ≤ 2:3 (FeS₂, Sb₂S₃, MoS₂…)",
      note: "Pyrite en tête — le minéral le plus commun de la classe — avec les sulfures d'arsenic et d'antimoine qui firent la fortune minière du Massif central, et la molybdénite aux feuillets lubrifiants.",
      mineraux: ["pyrite", "marcassite", "arsenopyrite", "stibine", "orpiment", "realgar", "molybdenite"],
    },
    {
      nom: "Sulfosels", code: "II.G-J", motif: "structures complexes S + semi-métal (Sb, As) + métaux",
      note: "Des architectures à trois étages où l'antimoine ou l'arsenic jouent les charpentiers. Les « cuivres gris » furent les minerais d'argent de bien des mines françaises ; les « argents rouges » sont les joyaux — photosensibles ! — des collections.",
      mineraux: ["tetraedrite", "bournonite", "boulangerite", "proustite", "pyrargyrite"],
    },
  ];
})();
