// ============ Texture de la roche (C.3, étape 3) : réglages des roches, hors prototypes de textures.js ============
// Chargé après textures.js. Les teneurs viennent de la fiche (roche.mineraux) : les aides ci-dessous en déduisent
// l'essentiel ; chaque roche ne précise que ce qui la distingue (taille, ordre de cristallisation, texte).
(function () {
  "use strict";
  const R3 = ["Formés en premier : entiers, à faces nettes", "Puis : s'arrêtent contre les premiers (moulés sur eux)", "En dernier : remplit les vides"];

  // formes des cristaux en roche grenue, pour une échelle 1 (tailles en mm, multipliées par `e`)
  const P = {
    plagioclases: { taille: [2.6, 5], allong: [1.5, 2.3], biseau: 0.18 }, albite: { taille: [2.6, 5], allong: [1.5, 2.3], biseau: 0.18 },
    orthose: { taille: [4.5, 8.5], allong: [1.4, 1.9], biseau: 0.1 }, sanidine: { taille: [4.5, 8.5], allong: [1.4, 1.9], biseau: 0.1 },
    biotite: { taille: [1.3, 2.6], allong: [2, 3.4], amas: 0.45 }, phlogopite: { taille: [1.3, 2.6], allong: [2, 3.4] },
    muscovite: { taille: [1.4, 2.4], allong: [2, 3] },
    hornblende: { taille: [1.5, 4], allong: [2, 3.2], biseau: 0.3 }, amphiboles: { taille: [1.5, 4], allong: [2, 3.2], biseau: 0.3 },
    pyroxenes: { taille: [1.5, 3.2], allong: [1.1, 1.8], sections: 8 }, augite: { taille: [1.5, 3.2], allong: [1.1, 1.8], sections: 8 },
    enstatite: { taille: [1.5, 3.2], allong: [1.3, 2], sections: 8 }, aegyrine: { taille: [1.2, 3.5], allong: [3, 5], biseau: 0.3 },
    olivine: { taille: [1, 3], allong: [1.2, 1.7], sections: 6 },
    magnetite: { taille: [0.3, 0.8], allong: [1, 1.2], sections: 8, amas: 0.3 }, chromite: { taille: [0.3, 0.7], allong: [1, 1], sections: 4 },
    apatite: { taille: [0.3, 0.9], allong: [2.5, 4], sections: 6 }, titanite: { taille: [0.8, 2], allong: [1.4, 1.9], sections: 4 },
    nepheline: { taille: [1.5, 4], allong: [1, 1.3], sections: 6 }, grenat: { taille: [1, 3], allong: [1, 1.1], sections: 8 },
    calcite: { taille: [1, 3], allong: [1, 1.4], sections: 6 }, dolomite: { taille: [1, 3], allong: [1, 1.4], sections: 6 },
    pyrochlore: { taille: [0.3, 0.7], allong: [1, 1], sections: 8 },
    tourmaline: { taille: [2, 6], allong: [3, 6], biseau: 0.25 }, beryl: { taille: [2, 5], allong: [1.4, 2.4], sections: 6 },
  };
  // roche grenue : `ordre` = [[minéral, temps (1–2), réglages]], `remplit` = minéraux du dernier temps (Voronoï)
  function grenue(o) {
    const e = o.e ?? 1;
    const ordre = o.ordre.map(([min, temps, x = {}]) => {
      const p = P[min] || { taille: [1, 2.5], allong: [1.2, 2] };
      return { min, temps, ...p, chevauche: temps === 1 ? 0.01 : 0.3, ...x, taille: (x.taille || p.taille).map((v) => v * (x.taille ? 1 : e)) };
    });
    ordre.push({ min: o.remplit[0], temps: 3, espacement: o.espacement ?? 3 * e, remplit: o.remplit, role: o.roleRemplit });
    return { mode: "grenue", nom: o.nom || "grenue", champ: o.champ || 30, vue: o.vue || "Surface sciée et polie", grain: o.grain, intro: o.intro, ordre, temps: o.temps || R3 };
  }


  // cristaux des laves : formes par minéral ([taille en mm] donnée par roche)
  const PL = {
    olivine: { sections: 6, allong: [1.2, 1.6] }, pyroxenes: { sections: 8, allong: [1, 1.4] }, augite: { sections: 8, allong: [1, 1.4] },
    hornblende: { biseau: 0.3, allong: [2, 3.5] }, amphiboles: { biseau: 0.3, allong: [2, 3.5] }, aegyrine: { biseau: 0.3, allong: [3, 5] },
    plagioclases: { biseau: 0.15, allong: [2.5, 4] }, albite: { biseau: 0.15, allong: [2.5, 4] }, sanidine: { biseau: 0.1, allong: [1.5, 2.2] },
    orthose: { biseau: 0.1, allong: [1.4, 2] }, biotite: { allong: [2, 3.5] }, phlogopite: { allong: [1.8, 3] }, quartz: { sections: 6, allong: [1, 1.2] },
    nepheline: { sections: 6, allong: [1, 1.2] }, hauyne: { sections: 8, allong: [1, 1.1] }, magnetite: { sections: 8, allong: [1, 1.2] },
    chromite: { sections: 8, allong: [1, 1.1] }, titanite: { sections: 4, allong: [1.4, 1.9] }, apatite: { sections: 6, allong: [2.5, 4] },
  };
  // [minéral, part de la surface, [taille mm], réglages]
  const cristaux = (liste) => liste.map(([min, part, taille, x = {}]) => ({ min, part, taille, ...(PL[min] || { allong: [1.2, 2] }), ...x }));
  const PATES = {
    basique: { fond: "#4b423c", taches: ["#7d8f55", "#7d8f55", "#f5f2ea", "#141414", "#141414"] },
    intermediaire: { fond: "#6f6a64", taches: ["#f5f2ea", "#f5f2ea", "#3e5540", "#7d8f55", "#141414"] },
    acide: { fond: "#c9b8ae", taches: ["#e9e2d6", "#b9bebc", "#e3ae94", "#8f8480"] },
    alcaline: { fond: "#8e9a86", taches: ["#eceee6", "#e3ddcf", "#3f5a33", "#5d7fb8"] },
  };
  function lave(o) {
    return { mode: "microlitique", nom: o.nom || "microlitique", champ: o.champ || 5, vue: o.vue || "Vue au microscope", grain: o.grain, intro: o.intro,
      fluidalite: o.fluidalite ?? 0.3, flux: o.flux ?? 0.15, domaines: o.domaines, vacuoles: o.vacuoles,
      phenos: cristaux(o.phenos), microlites: cristaux(o.microlites).map((m) => ({ ...m, biseau: 0, sections: m.sections && m.min !== "olivine" ? m.sections : undefined, ...m.x })),
      pate: { nom: o.pate.nom || "Verre et petits grains", role: o.pate.role, pas: 3, rayon: [0.8, 1.7], ...PATES[o.pate.type], ...o.pate } };
  }
  function porphyrique(o) {
    return { mode: "porphyrique", nom: o.nom || "microgrenue porphyrique", champ: o.champ || 20, vue: o.vue || "Surface sciée et polie", grain: o.grain, intro: o.intro,
      phenos: cristaux(o.phenos), pate: { nom: "Pâte", pas: 4, ...PATES[o.pate.type], ...o.pate } };
  }


  // roche détritique ou bréchique : grains = [minéral, part, réglages] ou { cle, ab, nom, fond, taches, part, role }
  function detritique(o) {
    const grains = o.grains.map((g) => (Array.isArray(g) ? { min: g[0], part: g[1], ...(g[2] || {}) } : g));
    return { mode: "detritique", nom: o.nom || "détritique", champ: o.champ, vue: o.vue || (o.champ <= 10 ? "Vue au microscope" : "Surface sciée et polie"),
      taille: o.taille, arrondi: o.arrondi ? 1 : 0, jointif: o.jointif, serre: o.serre ?? 0.95, grains, titreGrains: o.titreGrains,
      liant: { titre: o.liant.titre || "Entre les grains", pas: 3, ...o.liant }, pores: o.pores, titreLegende: o.titreLegende, grain: o.grain, intro: o.intro };
  }
  const lits = (o) => ({ mode: "litee", nom: o.nom || "litée", champ: o.champ, vue: o.vue || (o.champ <= 10 ? "Vue au microscope" : "Surface sciée et polie"), ondulation: o.ondulation ?? 2, lits: o.lits, vides: o.vides, titreLegende: o.titreLegende, grain: o.grain, intro: o.intro });


  const bio = (o) => ({ mode: "bioclastique", nom: o.nom || "bioclastique", champ: o.champ, vue: o.vue || (o.champ <= 10 ? "Vue au microscope" : "Surface sciée et polie"),
    elements: o.elements, titreElements: o.titreElements, fond: { titre: "Liant", ...o.fond }, grain: o.grain, intro: o.intro });
  // mosaïque : grains = minéraux de la fiche (parts de la fiche), sauf porphyroblastes ; micas en paillettes
  const MICAS = ["muscovite", "biotite", "phlogopite", "chlorite_m", "zinnwaldite", "graphite"];
  // (composition lue au moment du dessin : fonctions de la roche)
  const partDe = (roche, m) => { const l = roche.mineraux || [], t = l.reduce((s, [, p]) => s + p, 0) || 1; return ((l.find(([x]) => x === m) || [0, 0])[1]) / t; };
  function mosa(id, o) {
    const pb = (roche) => (o.porphyro || []).map(([min, x]) => ({ min, part: partDe(roche, min), taille: [1, 3], allong: [1, 1.1], sections: 8, ...x }));
    const grains = (roche) => (roche.mineraux || []).filter(([m]) => !(o.porphyro || []).some(([p]) => p === m) && !(o.exclure || []).includes(m)).map(([min]) => ({ min, part: partDe(roche, min),
      ...(MICAS.includes(min) ? { lamelle: true, taille: o.lamelle || [o.taille * 0.8, o.taille * 2], allong: [3, 6] } : {}), ...(o.reglages || {})[min] }));
    return { mode: "mosaique", nom: o.nom || "granoblastique (en mosaïque)", champ: o.champ, vue: o.vue || (o.champ <= 10 ? "Vue au microscope" : "Surface sciée et polie"),
      taille: o.taille, aplatissement: o.aplatissement, porphyro: o.porphyro ? pb : undefined, grains, fantomes: o.fantomes, maille: o.maille, titreGrains: o.titreGrains, grain: o.grain, intro: o.intro };
  }
  // foliée : porphyroblastes et minéraux couchés dans la foliation (parts de la fiche), le reste en grains aplatis
  function foli(o) {
    const pb = (roche) => (o.porphyro || []).map(([min, x]) => ({ min, part: partDe(roche, min), taille: [0.5, 1.5], allong: [1, 1.1], sections: 8, ...x }));
    const mi = (roche) => o.micas.map(([min, x]) => ({ min, part: partDe(roche, min), taille: [0.3, 1], allong: [4, 7], ...x }));
    const pris = [...(o.porphyro || []), ...o.micas].map(([m]) => m);
    const grains = (roche) => (roche.mineraux || []).filter(([m]) => !pris.includes(m)).map(([min]) => ({ min, part: partDe(roche, min), sansMarque: min === "quartz" }));
    return { mode: "foliee", nom: o.nom || "foliée (schisteuse)", champ: o.champ, vue: o.vue || "Vue au microscope", taille: o.taille, aplatissement: o.aplatissement ?? 2.2,
      films: o.films ?? 0.9, ondulation: o.ondulation, porphyro: o.porphyro ? pb : undefined, micas: mi, grains, grain: o.grain, intro: o.intro };
  }

  // aides exposées pour les variétés (textures-varietes.js)
  Textures.aides = { P, PL, PATES, R3, grenue, lave, porphyrique, detritique, lits, bio, mosa, foli };

  Textures.definir({
    // ───────────── métamorphiques ─────────────
    ardoise: foli({ nom: "foliée (schistosité ardoisière)", champ: 0.5, taille: 0.018, aplatissement: 3, films: 0.03, ondulation: 0.04,
      porphyro: [["pyrite", { taille: [0.015, 0.04], allong: [1, 1], sections: 4 }]],
      micas: [["illite_m", { taille: [0.02, 0.06], allong: [6, 10], role: "paillettes microscopiques, toutes parallèles" }], ["chlorite_m", { taille: [0.02, 0.05], allong: [5, 9] }]],
      grain: "paillettes de quelques centièmes de millimètre, invisibles à l'œil nu",
      intro: "Une argile enfouie à quelques kilomètres et légèrement chauffée (vers 200–300 °C) : ses minuscules paillettes ont recristallisé toutes parallèles, perpendiculairement à la compression, d'où le débit en plaques fines." }),
    schiste_vert: foli({ nom: "foliée (schiste vert)", champ: 5, taille: 0.15, films: 0.4,
      porphyro: [["albite", { taille: [0.3, 0.8], allong: [1, 1.3], sections: 8, role: "petits cristaux ronds nés dans la roche" }]],
      micas: [["chlorite_m", { taille: [0.2, 0.7], allong: [4, 7] }], ["actinote", { taille: [0.3, 1.2], allong: [7, 12], role: "aiguilles vertes alignées" }]],
      grain: "paillettes et aiguilles de 0,2 à 1 mm",
      intro: "Un basalte ou un gabbro recristallisé vers 300–450 °C et 10–20 km de profondeur : chlorite, actinote et épidote, tous verts, lui donnent sa couleur ; les minéraux allongés s'alignent dans la schistosité." }),
    schiste_bleu: foli({ nom: "foliée (schiste bleu)", champ: 5, taille: 0.15, films: 0.4,
      porphyro: [["grenat", { taille: [0.5, 1.3] }], ["lawsonite", { taille: [0.3, 0.8], allong: [1.3, 1.8], sections: 4, role: "tablettes blanches" }]],
      micas: [["glaucophane", { taille: [0.3, 1.2], allong: [5, 9], role: "prismes bleus alignés" }], ["muscovite", { taille: [0.2, 0.8], allong: [4, 7] }], ["chlorite_m", { taille: [0.2, 0.6], allong: [4, 7] }]],
      grain: "prismes et paillettes de 0,2 à 1 mm, grenats de 0,5 à 1,3 mm",
      intro: "Un basalte du plancher océanique entraîné dans une zone de subduction, à 20–35 km de profondeur mais seulement 200–450 °C : à haute pression et basse température, le glaucophane, une amphibole bleue, remplace les minéraux verts." }),
    amphibolite: foli({ nom: "foliée (nématoblastique)", champ: 10, taille: 0.4, films: 0.6, ondulation: 0.06,
      porphyro: [["grenat", { taille: [0.8, 2] }]],
      micas: [["hornblende", { taille: [0.6, 2.5], allong: [3, 6], role: "prismes noirs alignés dans l'étirement" }]],
      grain: "prismes de 0,5 à 3 mm, grenats de 1 à 2 mm",
      intro: "Un basalte ou un gabbro recristallisé vers 500–700 °C et 15–30 km de profondeur : hornblende noire et plagioclase blanc, les prismes alignés dans le sens de l'étirement." }),
    calcschiste: foli({ nom: "foliée (schistes lustrés)", champ: 5, taille: 0.2, films: 0.35, aplatissement: 2.5,
      porphyro: [["pyrite", { taille: [0.1, 0.3], allong: [1, 1], sections: 4 }]],
      micas: [["muscovite", { taille: [0.3, 1], allong: [5, 8] }], ["chlorite_m", { taille: [0.2, 0.7], allong: [4, 7] }], ["graphite", { taille: [0.1, 0.4], allong: [4, 7], role: "paillettes noires de carbone" }]],
      grain: "grains de calcite et paillettes de 0,1 à 1 mm",
      intro: "Une marne (calcaire argileux) transformée dans la chaîne alpine en « schistes lustrés » : lits de calcite recristallisée et films de mica blanc et de chlorite qui brillent sur les plans de schistosité." }),
    migmatite: { mode: "rubanee", nom: "rubanée plissée (migmatitique)", champ: 30, vue: "Surface sciée et polie", taille: 1.2, aplatissement: 1.4, plis: 16, longueurPli: 38,
      grain: "veines claires et sombres de 1 à 6 mm, plissées",
      intro: "Une roche portée vers 650–800 °C, au point de commencer à fondre : le liquide granitique, clair, s'est rassemblé en veines plissées (leucosome), séparées du résidu sombre riche en biotite, sillimanite et cordiérite (mélanosome).",
      clair: { titre: "Leucosome : le liquide granitique cristallisé", part: 0.55, epaisseur: [1.5, 6], grains: [
        { min: "quartz", part: 0.3, sansMarque: true, role: "grains gris" }, { min: "orthose", part: 0.25, role: "grains roses" }, { min: "plagioclases", part: 0.12, role: "grains blancs striés" }] },
      sombre: { titre: "Mélanosome : le résidu qui n'a pas fondu", part: 0.45, epaisseur: [1, 3.5],
        micas: [{ min: "biotite", part: 0.15, taille: [1, 2.5], allong: [3, 5], role: "paillettes noires" }, { min: "sillimanite", part: 0.05, taille: [1, 3], allong: [6, 10], role: "fines aiguilles blanches" }],
        porphyro: [{ min: "cordierite", part: 0.05, taille: [1, 2.2], role: "grains gris-bleu" }],
        grains: [{ min: "plagioclases", part: 0.5, role: "grains blancs" }, { min: "quartz", part: 0.5, sansMarque: true, role: "grains gris" }] } },
    leptynite: mosa("leptynite", { nom: "granoblastique aplatie", champ: 10, taille: 0.45, aplatissement: 1.8, porphyro: [["grenat", { taille: [0.4, 1] }]], lamelle: [0.4, 1.2],
      reglages: { quartz: { sansMarque: true } }, grain: "grains aplatis de 0,2 à 1 mm",
      intro: "Un gneiss clair à grain fin, presque sans minéraux sombres : quartz et feldspaths recristallisés en petits grains aplatis, quelques paillettes de mica et de petits grenats." }),
    granulite_meta: mosa("granulite_meta", { champ: 10, taille: 0.6, porphyro: [["grenat", { taille: [0.8, 2.2] }]],
      reglages: { quartz: { sansMarque: true }, sillimanite: { lamelle: true, taille: [0.6, 1.6], allong: [6, 10] } }, grain: "grains de 0,3 à 1 mm, grenats de 1 à 2 mm",
      intro: "Le métamorphisme le plus chaud de la croûte, au-delà de 800 °C vers 25–40 km : les micas, qui contiennent de l'eau, ont disparu au profit du grenat et de l'orthopyroxène ; la roche est sèche et dense." }),
    eclogite: mosa("eclogite", { champ: 10, taille: 0.5, porphyro: [["grenat", { taille: [0.8, 2.6] }], ["rutile", { taille: [0.1, 0.35], allong: [1.5, 3], sections: 4 }]],
      reglages: { quartz: { sansMarque: true }, disthene: { lamelle: true, taille: [0.5, 1.4], allong: [3, 6] } }, grain: "grenats de 1 à 2,5 mm dans des grains d'omphacite de 0,3 à 1 mm",
      intro: "Un basalte entraîné à plus de 45 km de profondeur dans une zone de subduction : à très haute pression, il se change en grenat rouge et en omphacite verte (un pyroxène sodique), et devient bien plus dense (environ 3,5 contre 3,0)." }),
    corneenne: mosa("corneenne", { nom: "granoblastique à porphyroblastes (cornéenne)", champ: 5, taille: 0.18,
      porphyro: [["andalousite", { taille: [0.6, 1.6], allong: [1, 1.15], sections: 4 }], ["cordierite", { taille: [0.4, 1], allong: [1, 1.2], sections: 6 }]],
      lamelle: [0.12, 0.35], reglages: { quartz: { sansMarque: true } }, grain: "grains de 0,05 à 0,3 mm, andalousite et cordiérite de 0,5 à 1,5 mm",
      intro: "Au contact d'un granite chaud (500–700 °C), une argile a recristallisé sans être déformée : roche dure, sans feuilletage, où grandissent de gros cristaux d'andalousite (chiastolite, marquée d'une croix sombre) et de cordiérite." }),
    skarn: mosa("skarn", { nom: "granoblastique (skarn)", champ: 10, taille: 0.7, porphyro: [["grossulaire", { taille: [1, 2.5] }], ["andradite", { taille: [0.8, 2] }]],
      reglages: { wollastonite: { lamelle: true, taille: [0.6, 1.8], allong: [4, 8] } }, grain: "grenats de 1 à 2,5 mm, grains de 0,3 à 1,5 mm",
      intro: "Au contact d'un granite et d'un calcaire, des fluides chauds ont échangé silicium, fer et calcium : le calcaire s'est changé en silicates calciques (grenats, pyroxène, wollastonite) et parfois en minerai (magnétite, scheelite)." }),
    greisen: mosa("greisen", { nom: "granoblastique (greisen)", champ: 10, taille: 0.8, lamelle: [0.8, 2.5], reglages: { quartz: { sansMarque: true } },
      grain: "grains de quartz et paillettes de mica de 0,5 à 2 mm",
      intro: "Le toit d'un granite traversé par des fluides chauds riches en fluor : les feldspaths ont été remplacés par du quartz et du mica blanc, avec topaze, fluorine et cassitérite, le minerai d'étain." }),
    fenite: mosa("fenite", { nom: "granoblastique (fénite)", champ: 10, taille: 0.7, grain: "grains de 0,3 à 1,5 mm",
      intro: "L'auréole d'une carbonatite ou d'un magma alcalin : les fluides riches en sodium et en potassium qui s'en échappent changent la roche voisine en feldspath alcalin et en minéraux sodiques (aegyrine, arfvedsonite)." }),
    rodingite: mosa("rodingite", { nom: "granoblastique (rodingite)", champ: 10, taille: 0.6, porphyro: [["grossulaire", { taille: [0.6, 2] }]],
      grain: "grenats de 0,6 à 2 mm, grains de 0,3 à 1 mm",
      intro: "Un gabbro ou un filon basaltique pris dans une péridotite en cours de serpentinisation : le calcium libéré par la serpentinisation l'a changé en grenat grossulaire, diopside et vésuvianite." }),
    serpentinite: mosa("serpentinite", { nom: "maillée (serpentinite)", champ: 5, taille: 0.45, exclure: ["olivine"], porphyro: [["magnetite", { taille: [0.03, 0.12], allong: [1, 1.2], sections: 8 }]],
      maille: { bord: "serpentine", coeur: "olivine", fibres: "#4f6a43", reliques: 0.3 }, titreGrains: "Mailles de serpentine, parfois autour d'un reste d'olivine",
      grain: "mailles de 0,2 à 0,8 mm",
      intro: "Une péridotite du manteau hydratée vers 200–400 °C par l'eau de mer au fond de l'océan : l'olivine se change en serpentine le long d'un réseau de fissures, en mailles dont le cœur garde parfois un reste d'olivine ; le fer libéré cristallise en magnétite." }),
    // ───────────── carbonatées, siliceuses, organiques, chimiques, résiduelles ─────────────
    craie: bio({ champ: 1, grain: "foraminifères de 0,1 à 0,3 mm dans une boue de coccolithes de quelques millièmes de millimètre",
      elements: [{ type: "foraminifere", ab: "Fo", nom: "Foraminifères", part: 0.12, taille: [0.08, 0.25], couleur: "#fbf8f0", role: "coquilles à loges du plancton" },
        { type: "coquille", ab: "Co", nom: "Débris de coquilles", part: 0.05, taille: [0.2, 0.6], role: "fragments de bivalves (inocérames)" },
        { type: "grain", ab: "Glt", min: "glauconie", part: 0.01, taille: [0.03, 0.08], role: "rares grains verts" }],
      fond: { nom: "Boue de coccolithes", fond: "#f4f1e8", taches: ["#e3ddcf", "#ffffff", "#cfc8b6", "#dcd6c4"], role: "plaquettes de calcite d'algues planctoniques, trop petites pour être dessinées, un peu d'argile et de silice" },
      intro: "Une boue faite de milliards de coccolithes, plaquettes de calcite produites par des algues planctoniques, accumulée au fond d'une mer du Crétacé supérieur (il y a 100 à 66 millions d'années)." }),
    tuffeau: bio({ nom: "bioclastique silteuse", champ: 3, grain: "débris de 0,05 à 1 mm dans un ciment calcaire tendre",
      elements: [{ type: "coquille", ab: "Co", nom: "Débris de coquilles", part: 0.08, taille: [0.3, 1.2], role: "fragments courbes" },
        { type: "spicule", ab: "Sp", nom: "Spicules d'éponges", cle: "opale", part: 0.06, taille: [0.2, 0.6], couleur: "#eee8da", role: "baguettes d'opale" },
        { type: "foraminifere", ab: "Fo", nom: "Foraminifères", part: 0.05, taille: [0.15, 0.4], couleur: "#fbf8f0", role: "coquilles à loges" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.1, taille: [0.05, 0.2], role: "grains de sable fin" },
        { type: "grain", ab: "Glt", min: "glauconie", part: 0.08, taille: [0.08, 0.25], role: "grains verts" }],
      fond: { nom: "Ciment calcaire et opale", fond: "#ece4cf", taches: ["#ddd6bb", "#e6e1d6", "#a8a08a"], role: "calcite fine, silice issue des spicules, paillettes de mica" },
      intro: "La craie sableuse et micacée de la vallée de la Loire (Turonien) : débris de coquilles, grains de quartz et de glauconie verte, et beaucoup de silice venue des spicules d'éponges, dans un ciment calcaire tendre." }),
    falun: bio({ nom: "bioclastique grossière (coquillière)", champ: 20, grain: "coquilles et débris de 1 à 12 mm dans un sable à peine cimenté",
      elements: [{ type: "coquille", ab: "Co", nom: "Coquilles et débris", part: 0.4, taille: [3, 12], role: "bivalves et gastéropodes" },
        { type: "foraminifere", ab: "Fo", nom: "Bryozoaires et foraminifères", part: 0.05, taille: [0.8, 1.6], couleur: "#fbf8f0", role: "petits squelettes à loges" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.15, taille: [0.2, 0.8], role: "grains de sable" },
        { type: "grain", ab: "Glt", min: "glauconie", part: 0.05, taille: [0.2, 0.6], role: "grains verts" }],
      fond: { nom: "Sable coquillier fin", fond: "#d9c9a4", taches: ["#f1ece0", "#b8742f", "#c7cbc9"], role: "débris d'aragonite et de calcite, oxyde de fer" },
      intro: "Le sable de coquilles de la mer peu profonde qui recouvrait la Touraine et l'Anjou au Miocène, il y a environ 15 millions d'années : bivalves, gastéropodes, bryozoaires, grains de quartz et de glauconie, à peine cimentés." }),
    lignite: bio({ nom: "organique (débris ligneux)", champ: 10, grain: "débris de bois de 1 à 8 mm dans une matière brune",
      elements: [{ type: "debris", ab: "B", nom: "Débris de bois", cle: "matorg", part: 0.4, taille: [2, 9], angle: 0, couleur: "#3a2b1f", trait: "#5b4632", role: "encore reconnaissables, couchés à plat" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.05, taille: [0.1, 0.4], role: "grains de sable" }],
      fond: { nom: "Charbon brun", fond: "#4a3a2c", taches: ["#5e4a38", "#9c8f7b", "#c9b04a"], role: "matière organique décomposée, argile, pyrite et calcite" },
      intro: "Un charbon jeune (Tertiaire) et peu enfoui : les débris de bois, encore reconnaissables, sont noyés dans une matière brune riche en eau." }),
    tourbe: bio({ nom: "organique (végétale)", champ: 10, grain: "tiges, feuilles et racines de 0,5 à 8 mm",
      elements: [{ type: "debris", ab: "V", nom: "Débris végétaux", cle: "matorg", part: 0.55, taille: [1.5, 9], couleur: "#6b4f35", trait: "#8a6c4c", role: "mousses, roseaux et racines peu décomposés" }],
      fond: { nom: "Matière organique fine", fond: "#3d2e22", taches: ["#4d3b2c", "#c7cbc9", "#9c8f7b"], role: "végétaux décomposés, un peu de sable et d'argile" },
      intro: "Mousses (sphaignes), roseaux et racines accumulés dans une tourbière gorgée d'eau, où le manque d'oxygène empêche leur décomposition ; elle s'épaissit de l'ordre d'un millimètre par an." }),
    silex: bio({ nom: "siliceuse cryptocristalline", champ: 2, grain: "calcédoine aux cristaux invisibles, fantômes de fossiles de 0,1 à 0,5 mm",
      elements: [{ type: "spicule", ab: "Sp", nom: "Fantômes de spicules", cle: "spicules:calcedoine", part: 0.1, taille: [0.1, 0.5], role: "baguettes d'éponges remplacées" },
        { type: "foraminifere", ab: "Fo", nom: "Fantômes de foraminifères", cle: "foram:calcedoine", part: 0.04, taille: [0.1, 0.3], couleur: "#d9d2c2", role: "loges remplies de calcédoine" }],
      fond: { nom: "Calcédoine", fond: "#b9b2a4", taches: ["#a8a194", "#c9c2b4", "#e6e1d6", "#b8742f"], role: "silice en fibres microscopiques, un peu d'opale et d'oxyde de fer" },
      intro: "De la silice dissoute, venue des spicules d'éponges et du plancton siliceux, a précipité en nodules dans la craie encore meuble en remplaçant la calcite : on y devine des fantômes de spicules et de foraminifères." }),
    meuliere: bio({ titreElements: "Vides", nom: "siliceuse caverneuse", champ: 5, grain: "cavités de 0,3 à 2 mm dans une masse de calcédoine",
      elements: [{ type: "nodule", ab: "C", nom: "Cavités", cle: "pores", part: 0.15, taille: [0.3, 2], couleur: "#fbfaf6", role: "vides laissés par la dissolution" }],
      fond: { nom: "Calcédoine et opale", fond: "#d4c7ae", taches: ["#c4b597", "#b8742f", "#e6e1d6", "#a8a08a"], role: "silice qui a remplacé le calcaire, argile, oxyde de fer" },
      intro: "Un calcaire de lac de la région parisienne dont la calcite a été remplacée par de la silice (calcédoine, opale) sous un climat chaud ; la dissolution a laissé de nombreuses cavités, d'où son usage pour les meules." }),
    radiolarite: bio({ nom: "biosiliceuse", champ: 1.5, grain: "radiolaires de 0,1 à 0,3 mm dans une boue siliceuse rouge",
      elements: [{ type: "radiolaire", ab: "Rad", nom: "Radiolaires", cle: "calcedoine", part: 0.35, taille: [0.1, 0.3], role: "coques siliceuses percées de pores" }],
      fond: { nom: "Boue siliceuse rougie", fond: "#9a4a3a", taches: ["#8c3b2e", "#b0634f", "#9c8f7b", "#c7cbc9"], role: "calcédoine, quartz, argile et hématite" },
      intro: "La boue de squelettes siliceux de radiolaires, du plancton unicellulaire, déposée au fond d'un océan profond, là où la calcite se dissout ; l'hématite la colore en rouge. Elle affleure avec les ophiolites des Alpes." }),
    diatomite: bio({ nom: "biosiliceuse", champ: 0.5, grain: "frustules de diatomées de 0,02 à 0,1 mm",
      elements: [{ type: "diatomee", ab: "Dia", nom: "Diatomées", cle: "opale", part: 0.55, taille: [0.03, 0.12], role: "frustules d'opale, en disque ou en navette" }],
      fond: { nom: "Argile et débris", fond: "#d9d2c2", taches: ["#c7bfae", "#a8a08a", "#b9bebc"], role: "débris de frustules, argiles, grains de quartz" },
      intro: "L'accumulation des frustules d'opale de diatomées, des algues microscopiques, au fond d'un lac : une roche légère et poreuse (gisements du Cantal)." }),
    gaize: bio({ nom: "siliceuse (opaline)", champ: 2, grain: "grains de 0,03 à 0,2 mm et spicules dans un ciment d'opale",
      elements: [{ type: "spicule", ab: "Sp", nom: "Spicules d'éponges", cle: "opale", part: 0.12, taille: [0.1, 0.4], role: "baguettes d'opale" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.25, taille: [0.03, 0.15], role: "grains de sable fin" },
        { type: "grain", ab: "Glt", min: "glauconie", part: 0.1, taille: [0.05, 0.2], role: "grains verts" }],
      fond: { nom: "Ciment d'opale", fond: "#cfc8b6", taches: ["#bdb6a3", "#a8a08a", "#f1ece0"], role: "opale, argile et calcite" },
      intro: "Un grès fin très léger de l'Argonne et des Ardennes (Crétacé) : grains de quartz et de glauconie dans un ciment d'opale issu de la dissolution des spicules d'éponges." }),
    phosphorite: bio({ titreElements: "Grains phosphatés et débris d'os", nom: "phosphatée (pelletoïdale)", champ: 4, grain: "grains et nodules phosphatés de 0,2 à 1 mm",
      elements: [{ type: "pisolithe", ab: "Ph", nom: "Grains phosphatés", cle: "grains:apatite", part: 0.4, taille: [0.2, 0.8], couleur: "#8a6a4a", trait: "#5a4030", role: "boulettes et enrobages d'apatite" },
        { type: "debris", ab: "Os", nom: "Débris d'os et de dents", cle: "os:apatite", part: 0.1, taille: [0.4, 1.4], couleur: "#c9b28a", trait: "#9c8662", role: "restes de poissons" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.08, taille: [0.1, 0.4], role: "grains de sable" }],
      fond: { nom: "Ciment calcaire", fond: "#e3dac5", taches: ["#9c8f7b", "#b8742f"], role: "calcite, argile et oxyde de fer" },
      intro: "Du phosphate de calcium (apatite) concentré au fond de mers où remontent des eaux profondes riches en nutriments : grains, nodules, débris d'os et de dents de poissons, cimentés par de la calcite." }),
    roche_ferrifere: bio({ titreElements: "Oolithes et débris de coquilles", nom: "oolithique ferrugineuse", champ: 4, grain: "oolithes de fer de 0,3 à 1 mm",
      elements: [{ type: "pisolithe", ab: "Oo", nom: "Oolithes ferrugineuses", cle: "goethite", part: 0.45, taille: [0.3, 0.9], couleur: "#9a5a2e", trait: "#5a2f18", role: "sphères à enveloppes de goethite et d'hématite" },
        { type: "coquille", ab: "Co", nom: "Débris de coquilles", part: 0.06, taille: [0.6, 1.6], role: "fragments courbes" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.08, taille: [0.1, 0.4], role: "grains de sable" }],
      fond: { nom: "Ciment", fond: "#b99a78", taches: ["#8c3b2e", "#1d1d1f", "#b39463", "#f1ece0"], role: "calcite, sidérite, hématite, magnétite et apatite" },
      intro: "Le minerai de fer oolithique de Lorraine (la « minette », Jurassique) : de petites sphères d'oxydes de fer, formées par enrobages successifs sur les fonds agités d'une mer peu profonde, cimentées par la calcite et la sidérite." }),
    laterite: bio({ titreElements: "Concrétions", nom: "résiduelle pisolithique", champ: 20, grain: "pisolithes de 1 à 6 mm dans une argile rouge",
      elements: [{ type: "pisolithe", ab: "Pi", nom: "Pisolithes ferrugineuses", cle: "goethite", part: 0.35, taille: [1, 6], couleur: "#8c3b2e", trait: "#4a1a12", role: "concrétions d'oxydes de fer" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.08, taille: [0.3, 1.5], role: "grains de quartz résiduels" }],
      fond: { nom: "Argile rouge", fond: "#b8653a", taches: ["#e9e2d2", "#8c3b2e", "#e6dcc8"], role: "kaolinite, gibbsite et hématite" },
      intro: "Un sol très ancien des régions tropicales humides : l'eau a emporté presque toute la silice et les éléments solubles ; il ne reste que l'argile kaolinite et les oxydes de fer et d'aluminium, souvent en pisolithes." }),
    bauxite: bio({ titreElements: "Concrétions", nom: "résiduelle pisolithique", champ: 10, grain: "pisolithes de 0,5 à 3 mm dans une masse argileuse",
      elements: [{ type: "pisolithe", ab: "Pi", nom: "Pisolithes", cle: "hematite", part: 0.3, taille: [0.5, 3], couleur: "#9a3f2a", trait: "#5a1f14", role: "concrétions d'hématite et de goethite" }],
      fond: { nom: "Gibbsite et kaolinite", fond: "#c9794f", taches: ["#e6dcc8", "#e9e2d2", "#8c3b2e"], role: "hydroxyde d'aluminium, argile et oxydes de fer" },
      intro: "Une latérite poussée à l'extrême, riche en hydroxyde d'aluminium (gibbsite) : c'est le minerai d'aluminium, nommé d'après les Baux-de-Provence." }),
    terra_rossa: bio({ titreElements: "Concrétions", nom: "résiduelle argileuse", champ: 5, grain: "nodules et grains de 0,1 à 1 mm dans une argile rouge",
      elements: [{ type: "nodule", ab: "N", nom: "Nodules ferrugineux", cle: "hematite", part: 0.12, taille: [0.2, 1], couleur: "#6f2a1c", role: "concrétions d'oxydes de fer" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.08, taille: [0.05, 0.3], role: "grains insolubles" },
        { type: "grain", ab: "Cal", min: "calcite", part: 0.04, taille: [0.1, 0.5], role: "débris du calcaire" }],
      fond: { nom: "Argile rouge", fond: "#a4472f", taches: ["#b8742f", "#e9e2d2", "#9c8f7b"], role: "kaolinite, illite et goethite" },
      intro: "L'argile rouge qui tapisse les calcaires méditerranéens : le résidu insoluble d'un calcaire dissous par la pluie, enrichi en oxydes de fer qui la colorent." }),
    calcrete: bio({ titreElements: "Concrétions", nom: "nodulaire (encroûtement)", champ: 10, grain: "nodules de 1 à 4 mm et grains de sable dans une calcite fine",
      elements: [{ type: "nodule", ab: "N", nom: "Nodules de calcite", cle: "calcite", part: 0.35, taille: [0.8, 4], couleur: "#f1e9d6", trait: "#cfc2a6", role: "concrétions formées dans le sol" },
        { type: "grain", ab: "Qz", min: "quartz", part: 0.1, taille: [0.1, 0.5], role: "grains du sol englobés" }],
      fond: { nom: "Calcite fine", fond: "#e3d7bd", taches: ["#cfc2a6", "#9c8f7b", "#b8742f"], role: "calcite microcristalline, argile, oxyde de fer, dolomite" },
      intro: "Une croûte calcaire formée dans le sol sous un climat sec : l'eau qui remonte et s'évapore dépose la calcite en nodules puis en croûte dure, en englobant les grains du sol." }),
    argile_silex: detritique({ nom: "résiduelle à silex", champ: 40, taille: [2, 14], arrondi: false, jointif: [0.6, 0.85], serre: 0.9,
      titreGrains: "Silex restés après la dissolution de la craie",
      grains: [{ cle: "calcedoine", ab: "Sx", nom: "Silex", fond: "#5a524a", taches: "#e8e1d0", part: 0.35, role: "rognons cassés, gris-noir, à patine blanche" }, ["quartz", 0.05, { sansMarque: true, role: "grains de sable" }]],
      liant: { nom: "Argile brun-rouge", fond: "#b86a3c", taches: ["#e9e2d2", "#8c3b2e", "#a8a08a"], role: "kaolinite, smectite et oxydes de fer" },
      grain: "silex de 2 à 15 mm et plus dans une argile", intro: "Ce qui reste de la craie dissoute par les pluies pendant des millions d'années : les silex, insolubles, s'accumulent dans une argile brun-rouge (plateaux de Normandie et du Bassin parisien)." }),
    cargneule: detritique({ nom: "bréchique cellulaire", champ: 30, taille: [1.5, 9], arrondi: false, jointif: [0.8, 0.95], serre: 0.92,
      titreGrains: "Fragments de la brèche d'origine",
      grains: [{ cle: "dolomite", ab: "Dol", nom: "Fragments de dolomie", fond: "#dcc6a0", taches: "#c2a97e", part: 0.55, role: "anguleux" },
        { cle: "pores", ab: "C", nom: "Cellules vides", fond: "#fbfaf6", part: 0.15, role: "fragments (ou gypse) dissous" }],
      liant: { nom: "Ciment de calcite", fond: "#e8dcc4", taches: ["#b8742f", "#9c8f7b", "#f1ece0"], role: "calcite, argile et oxyde de fer" },
      grain: "fragments et cellules de 1,5 à 9 mm", intro: "Une brèche de dolomie cimentée par la calcite, dont une partie des fragments (ou le gypse qui les accompagnait) a été dissoute : la roche prend un aspect de nid d'abeilles. Fréquente à la base des nappes de charriage des Alpes." }),
    // litées
    marne: lits({ champ: 3, grain: "lits de 0,1 à 0,8 mm, grains invisibles",
      lits: [{ cle: "calc", ab: "C", nom: "Lits plus calcaires", part: 0.55, epaisseur: [0.2, 0.8], fond: "#d9d0bd", taches: ["#ece6d8", "#b9bebc", "#c9bda5"], micas: 0.3, role: "boue de calcite" },
        { cle: "arg", ab: "A", nom: "Lits plus argileux", part: 0.45, epaisseur: [0.1, 0.5], fond: "#9d9484", taches: ["#8a8070", "#c9b04a", "#b3a992"], micas: 0.6, mica: "#c9bfa6", role: "illite et smectite, pyrite" }],
      intro: "Un mélange de boue calcaire et d'argile déposé en mer calme : selon les apports, les lits sont un peu plus calcaires ou un peu plus argileux." }),
    argile: lits({ champ: 1, grain: "particules de moins de 0,002 mm, en lits très fins",
      lits: [{ cle: "arg", ab: "A", nom: "Lits argileux", part: 0.8, epaisseur: [0.05, 0.25], fond: "#8a8070", taches: ["#7d7263", "#9f937f", "#c9b04a"], micas: 1, mica: "#b3a88f", role: "paillettes d'argile couchées à plat, pyrite" },
        { cle: "silt", ab: "S", nom: "Lits silteux", part: 0.2, epaisseur: [0.02, 0.08], fond: "#b3a992", taches: ["#b9bebc", "#e8e2d4"], micas: 0.3, role: "grains de quartz" }],
      intro: "Des particules plus fines que 2 millièmes de millimètre, déposées par une décantation très lente en eau calme : les paillettes d'argile se couchent à plat, en feuillets." }),
    schiste_bitumineux: lits({ champ: 3, ondulation: 1.5, grain: "lits de 0,05 à 0,5 mm",
      lits: [{ cle: "org", ab: "MO", nom: "Lits riches en matière organique", part: 0.4, epaisseur: [0.05, 0.3], fond: "#2f2a25", taches: ["#3f3830", "#c9b04a"], micas: 0.4, mica: "#5b5046", role: "plancton non décomposé, pyrite" },
        { cle: "arg", ab: "A", nom: "Lits argilo-silteux", part: 0.6, epaisseur: [0.1, 0.5], fond: "#6f6a60", taches: ["#8a8070", "#b9bebc", "#f1ece0", "#c9b04a"], micas: 0.8, mica: "#9c9280", role: "illite, quartz et calcite" }],
      intro: "Une boue argileuse déposée au fond d'une mer sans oxygène, où la matière organique du plancton ne s'est pas décomposée : très finement litée et riche en pyrite ; chauffée, elle libère des hydrocarbures." }),
    houille: lits({ nom: "litée (charbon)", champ: 5, ondulation: 1.5, grain: "lits brillants et mats de 0,3 à 3 mm",
      lits: [{ cle: "vitrain", ab: "Vi", nom: "Lits brillants (vitrain)", part: 0.45, epaisseur: [0.3, 2], fond: "#1c1a19", taches: ["#2e2b29"], role: "anciens morceaux de bois" },
        { cle: "durain", ab: "Du", nom: "Lits mats (durain)", part: 0.55, epaisseur: [0.5, 3], fond: "#3a3532", taches: ["#6f6a64", "#9c8f7b", "#c9b04a"], role: "spores, débris végétaux, argile et pyrite" }],
      intro: "Les végétaux des forêts marécageuses du Carbonifère (il y a 300 millions d'années), enfouis à quelques kilomètres : la chaleur en a chassé l'eau et les gaz. Les lits brillants viennent du bois, les lits mats des spores, des débris et de l'argile." }),
    anthracite: lits({ nom: "litée (charbon)", champ: 10, ondulation: 1, grain: "masse noire brillante, rares lits argileux",
      lits: [{ cle: "vitr", ab: "An", nom: "Anthracite", part: 0.88, epaisseur: [1, 4], fond: "#151415", taches: ["#232225", "#2e2d30"], role: "carbone presque pur" },
        { cle: "arg", ab: "A", nom: "Lits argileux", part: 0.12, epaisseur: [0.25, 0.7], fond: "#4a4642", taches: ["#9c8f7b", "#c9b04a", "#b9bebc"], role: "argile, quartz et pyrite" }],
      intro: "Le charbon le plus « cuit » : enfoui plus profondément et chauffé plus longtemps que la houille, il ne contient presque plus que du carbone et brille d'un éclat presque métallique." }),
    vase_tangue: lits({ nom: "litée (dépôt de marée)", champ: 5, ondulation: 3, grain: "lits de 0,2 à 1 mm déposés marée après marée",
      lits: [{ cle: "sable", ab: "T", nom: "Lits de sable coquillier (tangue)", part: 0.45, epaisseur: [0.3, 1.2], fond: "#cfc3a8", taches: ["#b9bebc", "#f6f1e6", "#f6f1e6", "#9c8f7b"], micas: 0.3, role: "grains de quartz et débris de coquilles" },
        { cle: "vase", ab: "V", nom: "Lits de vase", part: 0.55, epaisseur: [0.2, 0.8], fond: "#6f6a5e", taches: ["#5a554b", "#c9b04a", "#2b2420"], micas: 0.5, mica: "#8a8474", role: "argiles, matière organique et pyrite" }],
      intro: "Au fond des baies à marée (baie du Mont-Saint-Michel), chaque marée dépose un lit : sable fin chargé de débris de coquilles quand le courant est fort, vase argileuse et organique à l'étale." }),
    travertin: lits({ nom: "litée concrétionnée", champ: 20, ondulation: 4, grain: "lits de calcite de 0,5 à 3 mm, vides de 0,5 à 4 mm",
      vides: { part: 0.12, taille: [0.5, 4], aplat: [0.2, 0.5], nom: "Vides", role: "moules de tiges et de feuilles emprisonnées" },
      lits: [{ cle: "dense", ab: "D", nom: "Lits compacts", part: 0.5, epaisseur: [0.5, 2], fond: "#e6d9bd", taches: ["#d8c6a0", "#f1ece0"], role: "calcite en fines couches" },
        { cle: "poreux", ab: "P", nom: "Lits poreux", part: 0.5, epaisseur: [0.8, 3], fond: "#d8c6a0", taches: ["#c4b08a", "#b8742f", "#f1ece0"], role: "calcite, un peu d'aragonite et d'oxyde de fer" }],
      intro: "Un calcaire déposé par une source ou une cascade : l'eau riche en calcaire perd son gaz carbonique en s'agitant et en passant sur les mousses, la calcite précipite en couches successives et emprisonne tiges et feuilles, dont il reste des vides." }),
    flysch: lits({ nom: "litée granoclassée (turbidites)", champ: 30, ondulation: 1.5, grain: "bancs de grès fin de 2 à 8 mm alternant avec des lits d'argile",
      lits: [{ cle: "gres", ab: "G", nom: "Bancs de grès fin", part: 0.55, epaisseur: [2, 8], fond: "#b9b1a0", taches: ["#c7cbc9", "#f5f2ea", "#f1ece0", "#9c8f7b"], micas: 0.5, role: "quartz, feldspath et calcite, du plus gros en bas au plus fin en haut" },
        { cle: "pelite", ab: "P", nom: "Lits d'argile", part: 0.45, epaisseur: [1, 4], fond: "#6f6c64", taches: ["#86a77e", "#5a554b", "#c9b04a"], micas: 0.8, mica: "#8a8474", role: "illite et chlorite, pyrite" }],
      intro: "Au pied d'un talus sous-marin, des avalanches de boue et de sable (courants de turbidité) se sont succédé : chaque banc de grès passe vers le haut à une argile qui se dépose lentement jusqu'à l'avalanche suivante." }),
    // mosaïques sédimentaires
    dolomie: mosa("dolomie", { champ: 4, taille: 0.3, grain: "cristaux de dolomite de 0,1 à 0,5 mm, jointifs", titreGrains: "Cristaux recristallisés, soudés en mosaïque",
      intro: "Un calcaire dont la calcite a été remplacée, grain à grain, par la dolomite (carbonate de calcium et de magnésium) sous l'effet d'eaux riches en magnésium : la roche devient une mosaïque de cristaux, souvent poreuse." }),
    gypse: mosa("gypse", { nom: "cristalline (évaporite)", champ: 10, taille: 0.9, grain: "cristaux de gypse de 0,5 à 2 mm", titreGrains: "Cristaux précipités par évaporation",
      intro: "Du sulfate de calcium hydraté précipité dans une lagune où l'eau de mer s'évapore : le gypse cristallise quand l'eau est environ 3,8 fois plus concentrée que l'eau de mer (le sel, vers 10,6 fois)." }),
    anhydrite: mosa("anhydrite", { nom: "cristalline (évaporite)", champ: 4, taille: 0.35, grain: "cristaux de 0,1 à 0,6 mm à clivages en croix", titreGrains: "Cristaux jointifs",
      intro: "Du sulfate de calcium sans eau : le gypse enfoui perd son eau vers 42–58 °C, ou l'anhydrite se forme directement dans des saumures chaudes ; ses cristaux ont trois clivages à angle droit." }),
    sel: mosa("sel", { nom: "cristalline (évaporite)", champ: 20, taille: 2.5, grain: "cristaux de halite de 1 à 5 mm", titreGrains: "Cristaux précipités par évaporation",
      intro: "Le sel gemme : l'eau de mer concentrée environ 10,6 fois a déposé des cristaux cubiques de halite, recristallisés ensuite en une mosaïque de grains de quelques millimètres." }),
    sylvinite: mosa("sylvinite", { nom: "cristalline (évaporite)", champ: 20, taille: 2.5, grain: "cristaux de 1 à 5 mm, blancs et rouges", titreGrains: "Cristaux précipités en fin d'évaporation",
      intro: "Un mélange de halite et de sylvite (chlorure de potassium, souvent rougie par de fines paillettes d'hématite), précipité en toute fin d'évaporation d'une saumure très concentrée : c'est le minerai de potasse d'Alsace." }),
    // ───────────── détritiques et bréchiques ─────────────
    sable: detritique({ nom: "détritique meuble", champ: 3, taille: [0.15, 0.6], arrondi: true, jointif: [0.98, 1.04],
      titreGrains: "Grains apportés par l'eau ou le vent, sans ciment",
      grains: [["quartz", 0.93, { sansMarque: true, role: "grains gris arrondis" }], ["orthose", 0.02, { role: "rares grains roses" }]],
      liant: { nom: "Vides et poussières", fond: "#f4f1ea", taches: ["#b9bebc", "#b8742f", "#141414", "#ddd6bb"], role: "espaces vides entre les grains, quelques paillettes de mica et grains d'oxyde" },
      grain: "grains de 0,15 à 0,6 mm, libres", intro: "Un sable n'est pas cimenté : ses grains, surtout du quartz très résistant, se touchent sans être soudés, et l'eau circule librement entre eux." }),
    arkose: detritique({ nom: "détritique (arénacée)", champ: 4, taille: [0.2, 1], arrondi: false, jointif: [0.95, 1.02],
      grains: [["quartz", 0.55, { sansMarque: true, role: "grains gris anguleux" }], ["orthose", 0.25, { role: "grains roses de feldspath" }], ["plagioclases", 0.08, { role: "grains blancs striés" }]],
      liant: { nom: "Matrice et ciment", fond: "#c9a98c", taches: ["#9c8f7b", "#b8742f", "#ddd6bb"], role: "argile, mica et oxyde de fer" },
      grain: "grains anguleux de 0,2 à 1 mm, mal triés", intro: "Le produit de l'érosion rapide d'un granite voisin, enfoui avant que les feldspaths aient eu le temps de s'altérer en argile : quartz et feldspath roses, encore anguleux." }),
    grauwacke: detritique({ nom: "détritique à matrice", champ: 3, taille: [0.1, 0.7], arrondi: false, jointif: [0.8, 0.92], serre: 0.92,
      grains: [["quartz", 0.4, { sansMarque: true, role: "grains gris anguleux" }], ["plagioclases", 0.15, { role: "grains de feldspath" }]],
      liant: { titre: "Entre les grains", nom: "Matrice", fond: "#7d8a78", taches: ["#86a77e", "#9c8f7b", "#141414", "#c9b04a", "#ddd6bb"], role: "argile et chlorite vertes, mica, magnétite et pyrite" },
      grain: "grains anguleux de 0,1 à 0,7 mm noyés dans une matrice abondante", intro: "Grès sombre et mal trié, déposé par des avalanches sous-marines de boue et de sable : les grains n'ont pas été lavés, une matrice argileuse abondante les enrobe." }),
    conglomerat: detritique({ champ: 60, taille: [3, 22], arrondi: true, jointif: [0.8, 0.94], serre: 0.9,
      titreGrains: "Galets roulés par un cours d'eau ou sur une plage",
      grains: [{ cle: "quartz", ab: "Qz", nom: "Galets de quartz", fond: "#d9dcd9", part: 0.35, role: "blancs à gris, très résistants" },
        { cle: "calcite", ab: "Cal", nom: "Galets de calcaire", fond: "#ece4d2", taches: "#cfc2a6", part: 0.2, role: "beiges" },
        { cle: "orthose", ab: "Gr", nom: "Galets de granite", fond: "#d9b3a3", taches: "#2f2a27", part: 0.1, role: "roses mouchetés" }],
      liant: { nom: "Matrice sableuse", fond: "#cdb896", taches: ["#b9bebc", "#f1ece0", "#b8742f", "#9c8f7b"], role: "sable, argile et oxyde de fer cimentés" },
      grain: "galets arrondis de 3 à 20 mm et plus, dans un sable cimenté", intro: "Des galets arrondis par un long transport dans un torrent ou sur une plage, puis cimentés : leur nature raconte les roches qui affleuraient en amont." }),
    molasse: detritique({ nom: "détritique (grès calcaire)", champ: 3, taille: [0.1, 0.45], arrondi: false, jointif: [0.9, 0.98],
      grains: [["quartz", 0.45, { sansMarque: true, role: "grains gris" }], { cle: "calcite", ab: "Cal", nom: "Grains de calcaire", fond: "#ece4d2", taches: "#cfc2a6", part: 0.12, role: "débris de roches calcaires" }, ["plagioclases", 0.08, { role: "grains de feldspath" }]],
      liant: { nom: "Ciment calcaire", fond: "#e6dfcf", taches: ["#5d8a4f", "#9c8f7b", "#ddd6bb"], role: "calcite, avec argile, mica et grains verts de glauconie" },
      grain: "grains de 0,1 à 0,5 mm liés par de la calcite", intro: "Grès tendre, fait des débris d'une chaîne de montagnes en cours d'érosion (les Alpes) accumulés dans le bassin à son pied, en partie sous la mer." }),
    tillite: detritique({ nom: "détritique non triée (diamictite)", champ: 40, taille: [0.5, 12], arrondi: false, jointif: [0.55, 0.85], serre: 0.88,
      titreGrains: "Fragments de toutes tailles, déposés par la glace",
      grains: [{ cle: "quartz", ab: "Qz", nom: "Fragments de quartz", fond: "#d9dcd9", part: 0.2, role: "anguleux à émoussés" },
        { cle: "plagioclases", ab: "Cr", nom: "Fragments de roches cristallines", fond: "#e3dcd0", taches: "#2f2a27", part: 0.1, role: "granite, gneiss" },
        { cle: "calcite", ab: "Cal", nom: "Fragments de calcaire", fond: "#ece4d2", part: 0.06, role: "beiges" }],
      liant: { nom: "Matrice argilo-silteuse", fond: "#9a978c", taches: ["#86a77e", "#b9bebc", "#b8742f"], role: "farine de roche broyée par le glacier, durcie" },
      grain: "fragments de quelques dixièmes de mm à plusieurs cm, sans tri, dans une matrice fine", intro: "Une ancienne moraine durcie : un glacier a déposé pêle-mêle blocs, graviers et farine de roche, sans aucun tri ; certains fragments portent des stries de frottement." }),
    moraine: detritique({ nom: "détritique non triée", champ: 40, taille: [0.5, 14], arrondi: false, jointif: [0.55, 0.85], serre: 0.88,
      titreGrains: "Fragments de toutes tailles, déposés par la glace",
      grains: [{ cle: "quartz", ab: "Qz", nom: "Fragments de quartz", fond: "#d9dcd9", part: 0.2, role: "anguleux à émoussés" },
        { cle: "calcite", ab: "Cal", nom: "Fragments de calcaire", fond: "#ece4d2", part: 0.12, role: "beiges, parfois striés" },
        { cle: "plagioclases", ab: "Cr", nom: "Fragments de roches cristallines", fond: "#e3dcd0", taches: "#2f2a27", part: 0.08, role: "granite, gneiss" }],
      liant: { nom: "Matrice meuble", fond: "#a8a294", taches: ["#86a77e", "#b9bebc", "#b8742f"], role: "farine de roche, sable et argile" },
      grain: "fragments de quelques dixièmes de mm à plusieurs cm, sans tri", intro: "Ce que la glace a raboté, transporté et abandonné en fondant : blocs, cailloux et farine de roche mélangés sans aucun tri." }),
    loess: detritique({ nom: "détritique fine (silt)", champ: 0.8, taille: [0.015, 0.06], arrondi: false, jointif: [0.8, 0.92],
      grains: [["quartz", 0.62, { sansMarque: true, role: "grains anguleux" }], ["plagioclases", 0.05, { sansMarque: true, role: "grains de feldspath" }]],
      liant: { nom: "Liant calcaire et argileux", fond: "#d9ccb2", taches: ["#f1ece0", "#9c8f7b", "#ddd6bb"], role: "calcite, argile et paillettes de mica" },
      grain: "grains de silt de 0,02 à 0,06 mm, très bien triés", intro: "Une poussière soulevée par le vent au bord des grands glaciers du Quaternaire, redéposée en couches épaisses : grains de silt anguleux liés par un peu de calcite et d'argile." }),
    alluvions: detritique({ nom: "détritique meuble mal triée", champ: 20, taille: [0.3, 7], arrondi: true, jointif: [0.8, 0.95], serre: 0.9,
      titreGrains: "Galets et grains roulés par la rivière",
      grains: [["quartz", 0.45, { sansMarque: true, role: "galets et grains gris" }], { cle: "calcite", ab: "Cal", nom: "Graviers de calcaire", fond: "#ece4d2", part: 0.08, role: "beiges" }, ["orthose", 0.05, { role: "grains de feldspath" }], ["plagioclases", 0.05, { role: "grains blancs" }]],
      liant: { nom: "Sable fin, limon et argile", fond: "#c9b48f", taches: ["#9c8f7b", "#b8742f", "#ddd6bb", "#b9bebc"], role: "déposés entre les galets" },
      grain: "galets, graviers et sables de 0,3 à plusieurs mm", intro: "Ce que la rivière a déposé en perdant de la force : galets roulés dans le lit, sables et limons plus fins là où le courant ralentit." }),
    colluvions: detritique({ nom: "détritique de versant", champ: 10, taille: [0.1, 3], arrondi: false, jointif: [0.55, 0.8], serre: 0.9,
      grains: [["quartz", 0.3, { sansMarque: true, role: "fragments anguleux" }], { cle: "calcite", ab: "Cal", nom: "Fragments de calcaire", fond: "#ece4d2", part: 0.05, role: "beiges" }],
      liant: { nom: "Terre fine", fond: "#9b8062", taches: ["#b8742f", "#6f5a42", "#ddd6bb", "#a8a08a"], role: "argiles, oxydes de fer et paillettes de mica" },
      grain: "fragments peu usés de 0,1 à 3 mm dans une terre fine", intro: "Matériaux arrachés au haut d'une pente par le ruissellement et le gel, descendus lentement et accumulés en bas du versant : fragments peu usés noyés dans une terre fine." }),
    eboulis: detritique({ nom: "détritique grossière (éboulis)", champ: 100, taille: [8, 40], arrondi: false, jointif: [0.86, 0.97], serre: 0.9,
      titreGrains: "Blocs détachés de la paroi",
      grains: [{ cle: "calcite", ab: "Cal", nom: "Blocs de calcaire", fond: "#ece4d2", taches: "#cfc2a6", part: 0.74, role: "anguleux, de toutes tailles" }],
      liant: { nom: "Terre fine", fond: "#b8a58a", taches: ["#b8742f", "#9c8f7b", "#b9bebc"], role: "argile, sable de quartz et oxyde de fer entre les blocs" },
      grain: "blocs anguleux de 1 à 5 cm et plus", intro: "Blocs détachés d'une paroi par le gel (l'eau qui gèle dans les fissures augmente de 9 % de volume) et accumulés au pied, sans transport : ils restent anguleux et de toutes tailles." }),
    alterite: detritique({ nom: "altérée en place (arène)", champ: 20, taille: [1, 5], arrondi: false, jointif: [0.86, 0.96],
      titreGrains: "Grains hérités du granite",
      grains: [["quartz", 0.45, { sansMarque: true, role: "grains intacts, inaltérables" }], ["orthose", 0.1, { taches: "#e9e2d2", role: "feldspath blanchi, en cours d'altération" }], ["muscovite", 0.05, { role: "paillettes, peu altérées" }]],
      liant: { nom: "Argiles d'altération", fond: "#e2d7c1", taches: ["#b8742f", "#c9b48f", "#9c8f7b"], role: "kaolinite et illite nées des feldspaths, oxydes de fer" },
      grain: "grains de 1 à 5 mm dans une argile claire", intro: "Le granite pourri sur place : l'eau a changé feldspaths et micas noirs en argiles (kaolinite) tandis que le quartz, presque inaltérable, reste en grains intacts ; la roche garde sa structure mais s'effrite sous les doigts." }),
    dunes: detritique({ nom: "détritique éolienne", champ: 3, taille: [0.15, 0.4], arrondi: true, jointif: [0.98, 1.04],
      titreGrains: "Grains repris par le vent",
      grains: [["quartz", 0.88, { sansMarque: true, role: "grains arrondis, à surface dépolie" }], { cle: "calcite", ab: "Cal", nom: "Débris de coquilles", fond: "#f1ece0", part: 0.05, role: "blancs" }, ["orthose", 0.02, { role: "rares grains roses" }]],
      liant: { nom: "Vides", fond: "#f4f1ea", taches: ["#b8742f", "#141414"], role: "espaces vides, quelques grains d'oxyde" },
      grain: "grains de 0,15 à 0,4 mm, très bien triés", intro: "Du sable de plage repris par le vent : les grains, tous à peu près de la même taille et arrondis, ont une surface dépolie par les chocs." }),
    cataclasite: detritique({ nom: "cataclastique", champ: 10, taille: [0.2, 4], arrondi: false, jointif: [0.68, 0.9], serre: 0.9,
      titreGrains: "Fragments de la roche broyée",
      grains: [["quartz", 0.2, { sansMarque: true, role: "éclats anguleux" }], { cle: "orthose", ab: "Gr", nom: "Fragments de granite", fond: "#d9b3a3", taches: "#f5f2ea", part: 0.15, role: "morceaux de roche non orientés" }, ["plagioclases", 0.1, { role: "éclats de feldspath" }]],
      liant: { nom: "Matrice broyée", fond: "#8c8a80", taches: ["#86a77e", "#f1ece0", "#6f6a64"], role: "poudre de roche recimentée par la chlorite et la calcite" },
      grain: "fragments anguleux de 0,2 à 4 mm, non orientés, dans une poudre de roche", intro: "Roche broyée à faible profondeur (quelques kilomètres) dans une faille, à froid et de façon cassante : fragments anguleux de toutes tailles, non orientés, dans une poudre de roche recimentée." }),
    breche_volcanique: detritique({ nom: "bréchique volcanique", champ: 40, taille: [2, 16], arrondi: false, jointif: [0.75, 0.9], serre: 0.92,
      titreGrains: "Fragments de lave",
      grains: [{ cle: "lave", ab: "L", nom: "Blocs de lave", fond: "#5a524c", taches: "#f5f2ea", part: 0.5, role: "plagioclase, pyroxène et hornblende dans un verre sombre" },
        { cle: "scorie", ab: "S", nom: "Fragments de scorie", fond: "#6a3a2e", taches: "#3a241c", part: 0.1, role: "lave bulleuse rougie" }],
      liant: { nom: "Matrice de cendre", fond: "#9a8f7c", taches: ["#7a7060", "#b9ae98", "#141414"], role: "cendre et verre en partie altérés en argile (smectite)", detail: false },
      grain: "fragments anguleux de 2 à 15 mm et plus, dans une cendre", intro: "Explosions et effondrements de dôme ont fragmenté la lave : blocs anguleux et scories, mêlés à de la cendre, se sont accumulés puis cimentés." }),
    impactite: detritique({ nom: "bréchique d'impact", champ: 30, taille: [1, 12], arrondi: false, jointif: [0.72, 0.9], serre: 0.92,
      titreGrains: "Fragments broyés et fondus par le choc",
      grains: [{ cle: "socle", ab: "S", nom: "Fragments du socle", fond: "#d9b3a3", taches: "#2f2a27", part: 0.42, role: "granite et gneiss broyés" },
        { cle: "verre", ab: "V", nom: "Verre d'impact", fond: "#3d3530", taches: "#6a5a50", part: 0.22, role: "roche fondue par le choc puis figée" }],
      liant: { nom: "Matrice broyée", fond: "#a39488", taches: ["#c7cbc9", "#e8b8a0", "#9c8f7b"], role: "poussière de quartz, de feldspath et d'argile", detail: false },
      grain: "fragments de 1 à 10 mm et plus dans une matrice broyée", intro: "Il y a environ 207 millions d'années, une météorite a frappé la région de Rochechouart : le choc a broyé et en partie fondu le socle granitique ; fragments de roche et de verre ont été ressoudés dans une matrice broyée." }),
    // ───────────── pyroclastiques, verre de friction ─────────────
    tuf_volcanique: { mode: "pyroclastique", nom: "pyroclastique (tuf)", champ: 10, vue: "Surface sciée et polie", soude: false, echardes: 220,
      grain: "échardes et cendres de moins de 0,5 mm, ponces et cristaux de 0,3 à 3 mm",
      intro: "Cendres et ponces tombées d'un panache éruptif ou d'un écoulement, puis tassées sans se souder : les échardes de verre gardent leur forme en croissant. Le verre s'altère facilement en argile (smectite).",
      ponces: { part: 0.15, taille: [0.8, 3], fond: "#e3dccb" },
      cristaux: [{ min: "plagioclases", part: 0.1, taille: [0.4, 1.4], allong: [1.5, 2.4], biseau: 0.15, essais: 3000, role: "éclats blancs striés" },
        { min: "pyroxenes", part: 0.07, taille: [0.3, 1], allong: [1, 1.4], sections: 8, essais: 3000, role: "éclats verts" },
        { min: "sanidine", part: 0.05, taille: [0.3, 1.2], allong: [1.3, 2], biseau: 0.1, essais: 3000, role: "éclats limpides" },
        { min: "magnetite", part: 0.03, taille: [0.05, 0.2], allong: [1, 1.2], sections: 8, casse: 0, essais: 3000 }],
      cendre: { fond: "#cfc3ab", taches: ["#b9ad96", "#e3dccb", "#a8a08a"], echarde: "#f4efe6" } },
    pseudotachylite: { mode: "vitreuse", nom: "vitreuse de friction", champ: 3, vue: "Vue au microscope", plis: 4, lits: [6, 20],
      teintes: ["#3a302a", "#46392f", "#2f2723"], cristallites: 260, couleurCristallites: "#d9cdb4",
      roleVerre: "liquide de fusion figé, brun sombre, rubané par son injection", roleCristallites: "petites lattes de biotite cristallisées dans le liquide",
      titreCristaux: "Débris de la roche encaissante",
      grain: "débris arrondis de 0,05 à 0,4 mm dans un verre sombre",
      intro: "Dans une faille, un glissement brutal (un séisme) a chauffé la roche par frottement au point de la fondre en quelques secondes ; le liquide, injecté en fines veines, s'est figé en verre sombre autour de débris de quartz et de feldspath.",
      cristaux: [{ min: "quartz", part: 0.12, taille: [0.06, 0.4], allong: [1, 1.4], sections: 10, role: "débris arrondis" },
        { min: "plagioclases", part: 0.08, taille: [0.06, 0.35], allong: [1, 1.5], sections: 10, sansMarque: true, role: "débris arrondis de feldspath" },
        { min: "biotite", part: 0.04, taille: [0.05, 0.2], allong: [2, 3.5] },
        { min: "magnetite", part: 0.05, taille: [0.02, 0.06], allong: [1, 1.2], sections: 8 }] },
    // ───────────── laves microlitiques ─────────────
    andesite: lave({ grain: "phénocristaux de 0,5 à 2 mm, microlites de 0,1 à 0,3 mm", fluidalite: 0.5,
      phenos: [["plagioclases", 0.13, [0.5, 1.8]], ["hornblende", 0.06, [0.5, 1.5]], ["pyroxenes", 0.05, [0.3, 1]]],
      microlites: [["plagioclases", 0.22, [0.18, 0.55], { allong: [4, 7] }]],
      pate: { type: "intermediaire", role: "verre gris et petits grains de pyroxène et de magnétite" },
      intro: "Lave des volcans de subduction, plus riche en silice et plus visqueuse que le basalte : grands plagioclases, hornblende et pyroxène dans une pâte de microlites et de verre." }),
    dacite: lave({ grain: "phénocristaux de 0,5 à 3 mm dans une pâte surtout vitreuse", fluidalite: 0.5,
      phenos: [["plagioclases", 0.13, [0.5, 2]], ["quartz", 0.07, [0.4, 1.4]], ["hornblende", 0.06, [0.5, 1.6]], ["biotite", 0.04, [0.4, 1.2]]],
      microlites: [["plagioclases", 0.12, [0.15, 0.45], { allong: [4, 7] }]],
      pate: { type: "acide", nom: "Verre et microcristaux", role: "verre clair et fins cristaux de quartz et de feldspath" },
      intro: "Lave riche en silice, si visqueuse qu'elle forme des dômes plutôt que des coulées : plagioclase, quartz, hornblende et biotite dans une pâte en grande partie vitreuse." }),
    trachyte: lave({ nom: "microlitique fluidale (trachytique)", grain: "lattes de sanidine de 0,1 à 0,5 mm alignées, quelques cristaux de 1 à 4 mm", fluidalite: 0.9, flux: 0.1,
      phenos: [["sanidine", 0.1, [1, 3]], ["amphiboles", 0.04, [0.5, 1.4]], ["biotite", 0.03, [0.4, 1]]],
      microlites: [["sanidine", 0.38, [0.15, 0.5], { allong: [4, 7] }]],
      pate: { type: "intermediaire", fond: "#8d8780", nom: "Verre et petits grains", role: "plagioclase, magnétite et un peu de verre" },
      intro: "Lave riche en potassium, comme au puy de Dôme : de fines lattes de sanidine, couchées par l'écoulement de la lave encore visqueuse, dessinent la texture « trachytique » autour de quelques grands cristaux." }),
    trachyandesite: lave({ grain: "phénocristaux de 0,5 à 2 mm, microlites de 0,1 à 0,3 mm", fluidalite: 0.55,
      phenos: [["plagioclases", 0.12, [0.5, 1.8]], ["amphiboles", 0.06, [0.5, 1.5]], ["pyroxenes", 0.06, [0.3, 1]]],
      microlites: [["plagioclases", 0.24, [0.18, 0.55], { allong: [4, 7] }]],
      pate: { type: "intermediaire", role: "sanidine, magnétite et verre" },
      intro: "Entre l'andésite et le trachyte : une lave intermédiaire un peu enrichie en sodium et potassium, où la sanidine apparaît dans la pâte." }),
    trachybasalte: lave({ grain: "phénocristaux de 0,4 à 1,5 mm, microlites de 0,1 à 0,4 mm",
      phenos: [["olivine", 0.08, [0.4, 1.3]], ["pyroxenes", 0.06, [0.4, 1.1]], ["plagioclases", 0.04, [0.5, 1.4]]],
      microlites: [["plagioclases", 0.26, [0.15, 0.45], { allong: [5, 8] }]],
      pate: { type: "basique", role: "pyroxène, magnétite, sanidine et un peu de verre" },
      intro: "Un basalte un peu plus riche en sodium et en potassium : un peu de sanidine cristallise dans la pâte. Fréquent dans le Massif central." }),
    latite: lave({ grain: "phénocristaux de 0,5 à 2 mm, microlites de 0,1 à 0,4 mm", fluidalite: 0.5,
      phenos: [["plagioclases", 0.1, [0.5, 1.8]], ["pyroxenes", 0.06, [0.4, 1.1]], ["biotite", 0.05, [0.4, 1.2]]],
      microlites: [["plagioclases", 0.16, [0.18, 0.55], { allong: [4, 7] }], ["sanidine", 0.12, [0.18, 0.5], { allong: [3, 6] }]],
      pate: { type: "intermediaire", role: "verre, magnétite et pyroxène" },
      intro: "L'équivalent volcanique de la monzonite : plagioclase et sanidine à parts voisines, avec pyroxène et biotite." }),
    phonolite: lave({ grain: "phénocristaux de 0,5 à 3 mm, lattes de sanidine alignées", fluidalite: 0.75,
      phenos: [["sanidine", 0.1, [0.8, 3]], ["nepheline", 0.06, [0.4, 1.2]], ["aegyrine", 0.04, [0.4, 1.2]], ["hauyne", 0.03, [0.3, 0.8]], ["titanite", 0.02, [0.3, 0.8]]],
      microlites: [["sanidine", 0.3, [0.12, 0.45], { allong: [4, 7] }], ["aegyrine", 0.05, [0.05, 0.2], { allong: [4, 7], biseau: 0 }]],
      pate: { type: "alcaline", role: "néphéline, verre et petits grains" },
      intro: "Lave alcaline pauvre en silice : des feldspathoïdes (néphéline, haüyne) au lieu du quartz, de fines lattes de sanidine alignées. Elle se débite en dalles qui sonnent sous le marteau, d'où son nom, comme au mont Gerbier-de-Jonc." }),
    basanite: lave({ grain: "phénocristaux de 0,4 à 2 mm, microlites de 0,1 à 0,3 mm",
      phenos: [["olivine", 0.1, [0.4, 1.8]], ["pyroxenes", 0.08, [0.4, 1.4]]],
      microlites: [["plagioclases", 0.2, [0.18, 0.5], { allong: [5, 8] }]],
      pate: { type: "basique", role: "pyroxène, néphéline, magnétite et verre" },
      intro: "Un basalte très pauvre en silice : la néphéline, en tout petits grains dans la pâte, remplace une partie du feldspath, et l'olivine abonde." }),
    picrite: lave({ grain: "olivines de 0,5 à 3 mm, abondantes", champ: 8,
      phenos: [["olivine", 0.36, [0.5, 3]], ["pyroxenes", 0.1, [0.4, 1.5]]],
      microlites: [["plagioclases", 0.08, [0.15, 0.45], { allong: [5, 8] }]],
      pate: { type: "basique", role: "pyroxène, magnétite et verre" },
      intro: "Un basalte chargé en olivine (plus de 30 %) : des cristaux accumulés au fond de la chambre magmatique ont été entraînés par la lave." }),
    spilite: lave({ nom: "microlitique altérée (spilitique)", grain: "microlites d'albite de 0,1 à 0,5 mm, bulles de 0,3 à 1 mm remplies de calcite",
      vacuoles: [{ part: 0.09, taille: [0.3, 1], aplat: [0.6, 0.95], fond: "#f1ece0", cle: "calcite", ab: "Cal", nom: "Amygdales", role: "anciennes bulles de gaz remplies de calcite" }],
      phenos: [["pyroxenes", 0.07, [0.3, 0.9], { role: "reliques du basalte d'origine" }]],
      microlites: [["albite", 0.36, [0.15, 0.5], { allong: [5, 8] }]],
      pate: { type: "basique", fond: "#6f8f64", taches: ["#86a77e", "#b8b64a", "#141414", "#5d7f57"], nom: "Chlorite et épidote", role: "le verre et l'olivine devenus chlorite, avec de l'épidote et de la magnétite" },
      intro: "Un basalte sous-marin transformé par l'eau de mer chaude qui l'a traversé : le plagioclase est devenu albite, le verre et l'olivine sont devenus chlorite, et les bulles de gaz se sont remplies de calcite." }),
    pouzzolane: lave({ nom: "scoriacée (vacuolaire)", champ: 8, grain: "bulles de 0,3 à 3 mm, cristaux de 0,3 à 1 mm",
      vacuoles: [{ part: 0.35, taille: [0.3, 2.5], aplat: [0.6, 1] }],
      phenos: [["pyroxenes", 0.08, [0.3, 1]], ["olivine", 0.07, [0.3, 1]]],
      microlites: [["plagioclases", 0.03, [0.1, 0.3], { allong: [4, 7] }]],
      pate: { type: "basique", fond: "#6a3328", taches: ["#4a241c", "#8a4a38", "#141414"], nom: "Verre oxydé", role: "verre basaltique rougi par l'oxydation du fer, grains de magnétite" },
      intro: "Une scorie basaltique : la lave, projetée en l'air et pleine de gaz, s'est figée en fragments criblés de bulles, souvent rougis par l'oxydation du fer. Elle sert de matériau léger (chaîne des Puys)." }),
    komatiite: lave({ nom: "à spinifex", champ: 30, vue: "Surface sciée et polie", domaines: 6, grain: "lames d'olivine de 1 à 10 mm entrecroisées en gerbes",
      phenos: [["chromite", 0.03, [0.2, 0.5]]],
      microlites: [["olivine", 0.42, [3, 12], { allong: [10, 18], sansMarque: true, chevauche: 0, role: "longues lames en gerbes (spinifex)" }]],
      pate: { type: "basique", fond: "#5f7152", taches: ["#7e9b63", "#8c8a5c", "#141414"], nom: "Pâte serpentinisée", role: "pyroxène et verre devenus serpentine, magnétite" },
      intro: "Lave du manteau très chaude (plus de 1 600 °C), épanchée surtout il y a plus de 2,5 milliards d'années : trempée d'un coup, l'olivine a poussé en longues lames entrecroisées, comme des touffes d'herbe (texture spinifex). L'eau l'a ensuite en partie changée en serpentine." }),
    // ───────────── porphyriques ─────────────
    rhyolite: porphyrique({ nom: "porphyrique à pâte fluidale", champ: 15, grain: "phénocristaux de 1 à 5 mm dans une pâte aux grains invisibles, rubanée par l'écoulement",
      phenos: [["sanidine", 0.12, [1.5, 5]], ["quartz", 0.09, [1, 3]], ["plagioclases", 0.05, [1, 3]], ["biotite", 0.02, [0.6, 1.5]]],
      pate: { type: "acide", lits: "#b9a79c", nom: "Pâte felsitique", role: "microcristaux de quartz et de feldspath et un peu de verre, en lits d'écoulement" },
      intro: "Lave très riche en silice, l'équivalent volcanique du granite : quartz et sanidine ont grandi dans la chambre magmatique, puis la lave, très visqueuse, s'est figée en une pâte fine rubanée par son écoulement." }),
    microdiorite: porphyrique({ champ: 20, grain: "phénocristaux de 1 à 4 mm dans une pâte fine",
      phenos: [["plagioclases", 0.2, [1, 4]], ["hornblende", 0.1, [1, 3]], ["biotite", 0.04, [0.6, 1.8]]],
      pate: { type: "intermediaire", fond: "#9a958c", nom: "Pâte microgrenue", role: "plagioclase, hornblende et quartz en grains de moins de 0,5 mm" },
      intro: "Le magma d'une diorite, monté en filon ou en petit massif près de la surface : plagioclase et hornblende avaient commencé à cristalliser en profondeur, le reste a donné une pâte fine." }),
    porphyre: porphyrique({ champ: 30, grain: "grands cristaux de 3 à 15 mm dans une pâte fine",
      phenos: [["orthose", 0.15, [5, 14]], ["quartz", 0.07, [2, 5]], ["plagioclases", 0.06, [2, 5]], ["biotite", 0.03, [1, 2.5]]],
      pate: { type: "acide", fond: "#b98c7c", taches: ["#9f7466", "#d8b5a6", "#e9e2d6", "#5a4a44"], nom: "Pâte", role: "grains microscopiques de quartz et de feldspath, un peu de verre" },
      intro: "Roche à gros cristaux noyés dans une pâte fine : le magma a commencé à cristalliser lentement en profondeur, puis est monté vite près de la surface, où le reste a figé d'un coup." }),
    lamprophyre: porphyrique({ champ: 15, grain: "paillettes de biotite et prismes d'amphibole de 1 à 5 mm dans une pâte fine",
      phenos: [["biotite", 0.24, [1, 4], { role: "paillettes brun-noir" }], ["hornblende", 0.12, [1, 4]], ["pyroxenes", 0.05, [0.6, 1.8]]],
      pate: { type: "intermediaire", fond: "#5f5a52", taches: ["#e8b8a0", "#f5f2ea", "#2f2a27", "#d9e2d6"], nom: "Pâte", role: "feldspaths, apatite et petits micas" },
      intro: "Roche de filon sombre, née d'un magma riche en eau et en potassium venu du manteau : biotite et amphibole y cristallisent en grands cristaux avant les feldspaths, qui restent dans la pâte." }),
    kimberlite: porphyrique({ nom: "porphyrique bréchique", champ: 30, grain: "olivines arrondies de 1 à 10 mm dans une pâte serpentinisée",
      phenos: [["olivine", 0.28, [1.5, 9], { sections: 10, allong: [1, 1.4], role: "grains arrondis arrachés au manteau" }], ["phlogopite", 0.06, [1, 3]], ["pyroxenes", 0.05, [1, 4], { sections: 10, allong: [1, 1.3], role: "grains arrachés au manteau" }]],
      pate: { type: "basique", fond: "#5f6b5a", taches: ["#7e9b63", "#f1ece0", "#141414", "#8a8a6a"], nom: "Pâte", role: "serpentine, calcite et magnétite" },
      intro: "Roche d'une cheminée volcanique (diatrème) montée très vite de plus de 150 km de profondeur : elle arrache au manteau des cristaux d'olivine, arrondis pendant la remontée, et parfois des diamants. Il n'y en a pas en France." }),
    // ───────────── plutoniques et filoniennes grenues ─────────────
    granodiorite: grenue({ champ: 25, e: 0.9, remplit: ["quartz", "plagioclases"],
      ordre: [["magnetite", 1], ["hornblende", 1], ["biotite", 1], ["plagioclases", 1, { frac: 0.85 }], ["orthose", 2]],
      grain: "cristaux jointifs de 1 à 6 mm",
      intro: "Comme le granite, un magma refroidi lentement en profondeur, mais plus riche en calcium, fer et magnésium : le plagioclase l'emporte sur le feldspath potassique, et la hornblende accompagne la biotite." }),
    tonalite: grenue({ champ: 25, e: 0.9, remplit: ["quartz", "plagioclases"],
      ordre: [["magnetite", 1], ["hornblende", 1], ["biotite", 1], ["plagioclases", 1, { frac: 0.85 }]],
      grain: "cristaux jointifs de 1 à 6 mm",
      intro: "Un granitoïde sans feldspath potassique : plagioclase, quartz et minéraux sombres. C'est la roche typique des grands plutons formés au-dessus des zones de subduction." }),
    trondhjemite: grenue({ champ: 25, e: 0.9, remplit: ["quartz", "plagioclases"],
      ordre: [["magnetite", 1], ["biotite", 1], ["plagioclases", 1, { frac: 0.85 }], ["muscovite", 2]],
      grain: "cristaux jointifs de 1 à 6 mm",
      intro: "Une tonalite très claire, pauvre en minéraux sombres, à plagioclase sodique (oligoclase). Elle abonde dans les vieux boucliers archéens et forme de petits massifs dans les ophiolites." }),
    diorite: grenue({ champ: 20, e: 0.8, remplit: ["plagioclases", "hornblende", "quartz"],
      ordre: [["magnetite", 1], ["pyroxenes", 1], ["plagioclases", 1, { frac: 0.8 }], ["hornblende", 2, { frac: 0.8 }], ["biotite", 2]],
      grain: "cristaux jointifs de 1 à 5 mm",
      intro: "Roche plutonique intermédiaire, mouchetée de blanc et de noir : plagioclase dominant et hornblende, très peu de quartz. Son équivalent refroidi en surface est l'andésite." }),
    monzonite: grenue({ champ: 25, e: 0.9, remplit: ["orthose", "plagioclases", "quartz"],
      ordre: [["pyroxenes", 1], ["hornblende", 1], ["biotite", 1], ["plagioclases", 1], ["orthose", 2, { frac: 0.75 }]],
      grain: "cristaux jointifs de 1 à 7 mm",
      intro: "Autant de feldspath potassique que de plagioclase, peu de quartz : l'orthose, cristallisée après le plagioclase, l'enveloppe souvent." }),
    monzodiorite: grenue({ champ: 25, e: 0.85, remplit: ["orthose", "plagioclases"],
      ordre: [["magnetite", 1], ["pyroxenes", 1], ["hornblende", 1], ["biotite", 1], ["plagioclases", 1, { frac: 0.9 }]],
      grain: "cristaux jointifs de 1 à 6 mm",
      intro: "Entre la diorite et la monzonite : plagioclase dominant, feldspath potassique cristallisé en dernier entre les autres minéraux, pas de quartz ou presque." }),
    syenite: grenue({ champ: 30, e: 1, remplit: ["orthose", "quartz"],
      ordre: [["aegyrine", 1], ["hornblende", 1], ["biotite", 1], ["plagioclases", 1], ["orthose", 2, { frac: 0.7 }]],
      grain: "tablettes de feldspath de 3 à 10 mm",
      intro: "Un magma pauvre en silice et riche en potassium a surtout cristallisé du feldspath potassique, en grandes tablettes ; le quartz manque presque entièrement." }),
    pyroxenite: grenue({ champ: 20, e: 0.9, remplit: ["pyroxenes", "hornblende"],
      ordre: [["olivine", 1], ["magnetite", 1], ["pyroxenes", 1, { frac: 0.7 }]],
      grain: "cristaux jointifs de 1 à 5 mm", roleRemplit: "prismes verts trapus, jointifs",
      intro: "Roche faite presque entièrement de pyroxène, accumulé au fond d'une chambre magmatique basique (cumulat) ou formé dans le manteau." }),
    hornblendite: grenue({ champ: 20, e: 0.9, remplit: ["hornblende", "biotite"],
      ordre: [["magnetite", 1], ["pyroxenes", 1], ["hornblende", 1, { frac: 0.7 }]],
      grain: "prismes jointifs de 1 à 6 mm", roleRemplit: "prismes vert sombre, jointifs",
      intro: "Plus de 80 % de hornblende : cette amphibole contient de l'eau (groupes OH) et ne cristallise en telle quantité que dans un magma basique riche en eau." }),
    syenite_nephelinique: grenue({ champ: 25, e: 0.9, remplit: ["orthose", "nepheline"],
      ordre: [["apatite", 1], ["titanite", 1], ["nepheline", 1, { frac: 0.8 }], ["aegyrine", 2], ["biotite", 2], ["orthose", 2, { frac: 0.6 }]],
      grain: "cristaux jointifs de 2 à 8 mm",
      intro: "Magma trop pauvre en silice pour former du quartz : à sa place cristallise la néphéline, un feldspathoïde. Quartz et néphéline ne peuvent pas coexister à l'équilibre, ils réagiraient pour donner du feldspath." }),
    foidolite: grenue({ champ: 20, e: 0.8, remplit: ["nepheline"],
      ordre: [["apatite", 1], ["titanite", 1], ["pyroxenes", 1], ["aegyrine", 1], ["biotite", 2], ["nepheline", 1, { frac: 0.6 }]],
      grain: "cristaux jointifs de 1 à 5 mm", roleRemplit: "grains gris, jointifs",
      intro: "Roche plutonique faite surtout de feldspathoïde (ici la néphéline), sans feldspath : très rare, elle naît de magmas alcalins extrêmement pauvres en silice." }),
    charnockite: grenue({ champ: 25, e: 0.9, remplit: ["quartz", "orthose", "plagioclases"],
      ordre: [["magnetite", 1], ["enstatite", 1], ["grenat", 1], ["plagioclases", 1], ["orthose", 2, { frac: 0.7 }]],
      grain: "cristaux jointifs de 1 à 6 mm",
      intro: "Un « granite » à orthopyroxène : cristallisé vers 800–900 °C dans la croûte profonde, dans un magma pauvre en eau, où l'orthopyroxène tient la place de la biotite." }),
    gabbro: grenue({ champ: 20, e: 0.9, remplit: ["pyroxenes", "plagioclases"],
      ordre: [["olivine", 1], ["magnetite", 1], ["plagioclases", 1, { frac: 0.8 }], ["pyroxenes", 2, { frac: 0.4 }]],
      grain: "cristaux jointifs de 1 à 6 mm", roleRemplit: "prismes verts moulés sur les plagioclases",
      intro: "L'équivalent profond du basalte : plagioclase et pyroxène en cristaux de quelques millimètres ; le pyroxène, en partie cristallisé après le plagioclase, moule ses tablettes." }),
    essexite: grenue({ champ: 20, e: 0.85, remplit: ["nepheline", "augite", "plagioclases"],
      ordre: [["olivine", 1], ["magnetite", 1], ["augite", 1, { frac: 0.7 }], ["plagioclases", 1, { frac: 0.8 }], ["biotite", 2]],
      grain: "cristaux jointifs de 1 à 5 mm",
      intro: "Un gabbro alcalin : à la place d'une partie du feldspath, de la néphéline, cristallisée en dernier entre les autres minéraux." }),
    carbonatite: grenue({ champ: 15, e: 0.6, remplit: ["calcite", "dolomite"],
      ordre: [["apatite", 1], ["magnetite", 1], ["pyrochlore", 1], ["biotite", 1], ["calcite", 1, { frac: 0.4 }]],
      grain: "cristaux jointifs de 0,5 à 3 mm", roleRemplit: "grains blancs à macles, jointifs",
      intro: "Roche magmatique faite surtout de carbonates : un magma carbonaté très fluide, venu du manteau, a cristallisé calcite, apatite et magnétite ; le pyrochlore y concentre le niobium." }),
    peridotite: grenue({ champ: 15, e: 0.7, remplit: ["olivine", "pyroxenes"], espacement: 2.2,
      ordre: [["magnetite", 1], ["pyroxenes", 1, { frac: 0.5 }], ["olivine", 1, { frac: 0.35 }]],
      grain: "grains jointifs de 1 à 4 mm", roleRemplit: "grains vert-jaune craquelés",
      temps: ["Cristaux aux formes nettes", "", "Grains jointifs"],
      intro: "La roche du manteau supérieur : surtout de l'olivine, avec des pyroxènes. Elle n'affleure que là où la tectonique l'a remontée, comme à l'étang de Lherz dans les Pyrénées, qui a donné son nom à la lherzolite." }),
    aplite: grenue({ champ: 5, e: 0.1, remplit: ["quartz", "orthose", "plagioclases"], espacement: 0.35, vue: "Vue au microscope",
      ordre: [["muscovite", 1, { taille: [0.2, 0.4] }], ["plagioclases", 1, { frac: 0.5, allong: [1.2, 1.6] }], ["orthose", 1, { frac: 0.5, allong: [1.1, 1.4] }]],
      grain: "grains fins et égaux de 0,2 à 1 mm (texture « en sucre »)", roleRemplit: "grains jointifs",
      temps: ["Formés en premier", "", "Grains cristallisés ensemble"],
      intro: "Le dernier liquide d'un granite, pauvre en eau, injecté en filon dans la roche déjà froide : il a cristallisé vite, en grains fins et presque tous de même taille." }),
    pegmatite: grenue({ champ: 100, e: 4, remplit: ["quartz", "orthose"], espacement: 14,
      ordre: [["tourmaline", 1, { taille: [8, 25] }], ["beryl", 1, { taille: [8, 18] }], ["muscovite", 1, { taille: [6, 14] }], ["plagioclases", 1], ["orthose", 2, { frac: 0.8 }]],
      grain: "cristaux de 1 à 10 cm",
      intro: "Le dernier liquide d'un granite, très riche en eau et en éléments rares : les atomes y circulent vite, les cristaux deviennent énormes. On y trouve tourmaline noire, béryl, grandes lames de mica." }),
    dolerite: grenue({ nom: "doléritique (ophitique)", champ: 10, e: 0.35, remplit: ["pyroxenes", "plagioclases"], espacement: 2.2, vue: "Vue au microscope",
      ordre: [["olivine", 1], ["magnetite", 1], ["plagioclases", 1, { taille: [1, 3], allong: [3.5, 5.5], frac: 0.98, chevauche: 0.12 }]],
      grain: "baguettes de plagioclase de 1 à 3 mm englobées dans des pyroxènes plus grands", roleRemplit: "grands cristaux verts qui englobent les baguettes",
      temps: ["Formés en premier : baguettes nettes", "", "Ensuite : le pyroxène grandit autour d'elles"],
      intro: "La composition d'un basalte, mais cristallisée en filon à quelques centaines de mètres de profondeur : les baguettes de plagioclase se sont formées d'abord, puis le pyroxène a grandi autour d'elles en les englobant (texture ophitique)." }),
  });
})();
